### ISSUE TITLE
Hitting tab when creating a new entry causes the create function to trigger twice

### ISSUE THREAD

**Issue by willjohnson** [selectize/selectize.js#1001]
If on a dropdown types in a new entry ("Test") and then hits Tab rather than selecting "Add Test" two new entries are created.
`

```
$('#transaction_payee_id').selectize({
    allowEmptyOption: true,
    sortField: 'text',
    selectOnTab: true,
    createOnBlur: false,
    closeAfterSelect: true, 
    placeholder: "Select payee",
    create: function(input, callback) {
        $.ajax({
            type: "POST",
            url: "/payees",
            data: { payee: { name: input } },
            success: function(data){
                console.log(data);
                return callback({ text: input, value: data.id});
            },
            error: function(){
                alert("Ajax error!");
                    return false;
            }
        });
    }
});
```

`

If I set "selectOnTab: false" the user is still able to create a new entry ("Test") even if "Test" already is an option.

**Comment by willjohnson** [comment]
It might be related to this issue: https://github.com/selectize/selectize.js/issues/350#issuecomment-174506030

**Comment by jsgoupil** [comment]
When `createOnBlur` is false, then I would expect tabbing out WOULD NOT create the item.
`selectOnTab` is contradictary with `createOnBlur`. We should at least update the documentation if this is the intended behavior.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.

**Comment by himanshutecstub** [comment]
Hello,
In this JS i fetch problem with below code

```
jQuery('#transaction_payee_id').selectize({
    selectOnTab: false,
    createOnBlur: false,
    create: function(input, callback) {
        jQuery.ajax({
            type: "POST",
            url: "/payees",
            data: { payee: { name: input } },
            success: function(data){
                console.log(data);
                return callback({ text: input, value: data.id});
            },
            error: function(){
                alert("Ajax error!");
                    return false;
            }
        });
    }
});
```


Here when i try to write anything & press tab than new filed is created while in my page tab is use for skip.
Is there any solution?
