### ISSUE TITLE
NPM package still points to old repository

### ISSUE THREAD

**Issue by godza** [selectize/selectize.js#1002]
Hello,

Selectize NPM package still points to the old repository https://www.npmjs.com/package/selectize

**Comment by joallard** [comment]
Paging @brianreavis

**Comment by brianreavis** [comment]
Good catch. This will get updated on NPM whenever we put out a new release

**Comment by dfreeman** [comment]
@brianreavis Do you have a particular set of milestones in mind for the next release? There've been a few interesting additions since the last one that I'd love to see published.

**Comment by fahmilatib** [comment]
@brianreavis I know this isn't a big deal but can you include this in README? so that people will know that you also provide npm as an option.

Thanks
