### ISSUE TITLE
input type text styling options for item

### ISSUE THREAD

**Issue by tobsn** [selectize/selectize.js#1005]
by default it looks like this with bootstrap 3:

![2016-02-15 at 3 54 pm](https://cloud.githubusercontent.com/assets/109529/13051977/817756c6-d3fc-11e5-9d4a-c08457b36ae5.png)

Is there any way to style this, possibly per selectize instance?

Best would be if I could apply a label class and then style via label-info label-success etc.

Currently I extended "setupTemplates" to rewrite the item template but that seems like a very silly workaround... 

Thanks!

EDIT:

I fixed it by adding a render option:

```
render: {
    item: function(data, escape) {
        var field_label = this.settings.labelField;
        return '<span class="label label-info">' + escape(data[field_label]) + '</span>';
    }
},
```

BUT this displays the labels super tiny, not like normal label's in bootstrap:

![2016-02-15 at 5 14 pm](https://cloud.githubusercontent.com/assets/109529/13054050/df8115e4-d407-11e5-93fc-5c95e72be952.png)

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
