### ISSUE TITLE
large items performance bad when scroll page

### ISSUE THREAD

**Issue by pigochu** [selectize/selectize.js#1006]
My table has more than 100 items

![selectize](https://cloud.githubusercontent.com/assets/1013744/13139094/ca47f00c-d665-11e5-806b-ce688384dd37.png)

When I scroll the page in chrome , it will lag a bit.

I found selectize registed scroll & resize event . when i remove all events , scroll page very fast and work fine.

```
$(window).unbind('resize');
$(window).unbind('scroll');
```

So is there any way to remove selectize's events ?

**Comment by a10j11** [comment]
+1

**Comment by qqlu83** [comment]
+1

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
