### ISSUE TITLE
Mulitple sources/flavors for tags

### ISSUE THREAD

**Issue by nine-2-five** [selectize/selectize.js#1008]
Is it possible to have selectize exclusively pipe into lets say 3 different javascript arrays, each holding a different flavor of the tag to be displayed when chosen?
By exclusively, I mean when one tag is selected from a given array, that array is excluded from the next autocomplete selectize queries?
So for example, there are 3 arrays:
[size] [color] [length]
When the color red is selected and present in the input box as a tag, even if I start typing yello..., I would like it to not return anything. But if I start typing a digit 4 it should return from both size and length arrays if they hold the dimension with digit 4.
I have data that differentiates all attributes so size for example would be just integer, while length would be a number with metric unit appended.
I would disable custom input in the input box.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
