### ISSUE TITLE
try to set value during 'initialize' event doesn't seem to work

### ISSUE THREAD

**Issue by louking** [selectize/selectize.js#1009]
I am using dataTables.Editor, which can be configured to use selectize.

I am trying to set a value in a field based on the selectize value in a different field, when the Editor form is created.

When I try to catch the 'initialize' event of the selectize field to set a value in another field, somehow the set doesn't work. See http://codepen.io/louking/pen/wMbYPJ

If I use 'focus' the value is set correctly. See http://codepen.io/louking/pen/VeOGyE

In either case, click the checkbox on one of the rows and click Edit button. In initialize case field col1 is not updated. In focus case, it is updated correctly.

Note `editor.set()` simply calls `selectize.setValue()`. See https://editor.datatables.net/plug-ins/field-type/editor.selectize

I would prefer to use initialize to focus because I don't want to keep changing the value of the separate field every time the user touches the selectize field.

Is this a bug or a feature I'm not understanding?

thanks

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
