### ISSUE TITLE
After selecting/clearing and coming back to the select, the window is placed randomly

### ISSUE THREAD

**Issue by pblanchardie** [selectize/selectize.js#1011]
Looks like it's a regression in 4.0.1 and 4.0.2, downgrading to 4.0.0 fixes the bug.

Easy to reproduce, especially with remote loading, and the bug occurs also on the examples page.
- click on the select and begin typing "ex".
- the window will open, and depending on the placement and number of results, it will show above the select.
  ![image](https://cloud.githubusercontent.com/assets/676407/13290470/fd5fa266-db13-11e5-9cff-2982f0514148.png)
- Select an item.
- Click again on the select, and the window opens well above the select, very far from the component... :'(
  ![image](https://cloud.githubusercontent.com/assets/676407/13290529/4504740c-db14-11e5-8120-a95509f3bfbd.png)

Thanks in advance for fixing, it's critical!

**Comment by pblanchardie** [comment]
Looks like it's a regression, downgrading to 4.0.0 fixes the bug.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
