### ISSUE TITLE
`drag_drop` plugin causes `.selectize-dropdown` to open at undesirable times

### ISSUE THREAD

**Issue by lpender** [selectize/selectize.js#1012]
_Steps to Reproduce:_
1. Initialize a multi-select box with code below.
2. Drag and drop to re-order the content.
3. Drag and drop the content again.

_Expected Result:_

`.selectize-dropdown` should stay hidden.

_Actual Result:_

`.selectize-dropdown` appears as in the screenshot.

Here is my code:

```
  $("#myDiv select").selectize({
    plugins: ['drag_drop']
    closeAfterSelect: true
  });
```

And here is the issue:

![image](https://cloud.githubusercontent.com/assets/1406554/13413301/7ad56058-df17-11e5-901e-98391fb89ee3.png)

**Comment by lpender** [comment]
Note that this is reproducible at the [plugin example page](http://selectize.github.io/selectize.js/)

**Comment by joallard** [comment]
Thank you for this report.

**Comment by joallard** [comment]
I've tried to reproduce at the plugin page with the STR, to no avail. Any pointers?

**Comment by Cashewz** [comment]
The problem still appears (also on the plugin example page). To reproduce this, you have to remove one item with backspace on the example page before the drag/drop.

**Comment by frame** [comment]
The 'reproduction failed' label should be removed from the issue.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
