### ISSUE TITLE
load options on focus

### ISSUE THREAD

**Issue by alex-muntean** [selectize/selectize.js#1013]
Hi,

I am using angularjs and I am loading options on focus but when the ajax call si back and i get the results, the dropdown closes, so i have to click again to see the results. 

How can i make something like click -> loading icon -> open dropdown ?

Thanks

**Comment by mjjones0** [comment]
If you're not loading options within load(query, callback) then you will need to make sure to call refreshOptions after you have manually added your items. refreshOptions takes an optional parameter boolean to specify whether or not you want to open the dropdown.
