### ISSUE TITLE
Publish release 0.12.2

### ISSUE THREAD

**Issue by yankeeinlondon** [selectize/selectize.js#1014]
Can we get a new publish of the latest commits? Particularly keen to incorporate 593a2f2bb3626f3c0da52d01a091e4f5a491ffb9 but they all look worth having. Here's to version `12.2`.

**Comment by joallard** [comment]
Duly noted, thanks for the ping, I'll try to have a release out as soon as possible. Meanwhile, I'll close this to remove this from the issue list.

**Comment by joallard** [comment]
Emailed @brianreavis about access to npm, any news Brian?

**Comment by brianreavis** [comment]
@joallard Sorry for the delay! Added you – you should be good to go. `make release version=0.12.2` whenever you're ready.

**Comment by joallard** [comment]
Thanks @brianreavis! I'll also need your help with some maint stuff, I'll be in touch.
