### ISSUE TITLE
Not compatible with jQuery 1.12.1?

### ISSUE THREAD

**Issue by alranel** [selectize/selectize.js#1016]
I just tried selectize v0.12.1 with jQuery 1.12.1 and it doesn't seem to be working. The basic example (i.e. `selectize({})`) does not populate the drowdown with the existing options. Reverting to jQuery 1.7.2 makes it happy again.

Is this a duplicate maybe?

(Thank you for selectize, I like it very much.)

**Comment by joallard** [comment]
A quick search reveals no one else has reported this, maybe someone else can pitch in? Else, are you able to show a demo and find a cause for this?

**Comment by alranel** [comment]
Demo is quite easy: https://codepen.io/anon/pen/KzXQJB

**Comment by joallard** [comment]
Thanks, it helps a lot. From what I can tell, the dropdown is not getting populated, sifter returns no results, but there needs to be more investigation as to what this has to do with jQuery 1.12.x

**Comment by alranel** [comment]
I confirm #1045 fixes the issue for me. Thank you!

**Comment by joallard** [comment]
Thanks for confirming @alexrj
