### ISSUE TITLE
reinitialize with dynamic content from ajax

### ISSUE THREAD

**Issue by Redani** [selectize/selectize.js#1017]
Hi, and thanks for this lovely plugin ;)

I'm wondering if there is a better way to use selectize on new "select" elements created using Ajax. i currenty do this:

```
$.ajax({
    url: "/fine.php",
    success: function(result) {
        $("#container").html('<p>' + result + '</p>');
        $("#container select.selectize").selectize();
    }
});
```

Thanks

**Comment by pigochu** [comment]
I think u can use jquery.load() , it can execute your script  .
So  u can put "$("#container select.selectize").selectize(); " in your ajax page.

see http://api.jquery.com/load/

**Comment by Redani** [comment]
Thanks pigochu for your reply.
I already use `$("#container select.selectize").selectize();` so i was wondering if there is a better way to reinitialise selectize

**Comment by pigochu** [comment]
maybe you can use "not selector"

```
$("#container select.selectize").not('.selectized').selectize()
```

**Comment by joallard** [comment]
I will close this as this doesn't seem to be exactly an issue with Selectize, but feel free to update as to the solution to your problem.

**Comment by Redani** [comment]
Hi Joallard,

Well, i'm still looking for a great solution to my need... :D
At the same time, I'd also love to know how i can tell if a "select" element is selectized, do you know how to?

**Comment by joallard** [comment]
@Redani What happened with @pigochu's solution, did it work?

**Comment by Redani** [comment]
I already use his solution, but I was wondering if there is an option to simply or reinitialize the specific select element!
