### ISSUE TITLE
IE11 splitOn with \n or \r doesn't work when pasting in new content (i.e. from excel)

### ISSUE THREAD

**Issue by tonydifranco** [selectize/selectize.js#1019]
this works in chrome but not in IE11 when pasting in from excel with the remove_button plugin
splitOn: /[,\r\n\s]+/,
only the first split is retained... perhaps increasing the timeout from 0ms to a small positve in the paste event handler could help.

**Comment by zinkkrysty** [comment]
hi @tonydifranco did you manage to solve this? I am having the same issues, basically I can't get this to paste and transform into items:

```
a, b, c,
d, e, f,
g, h, i
```

only the first line of items is pasted in IE 11: 

![image](https://user-images.githubusercontent.com/570771/37209898-1175d74c-23a7-11e8-9c9e-570e06ef997b.png)

While on Chrome and Edge, it works:

![image](https://user-images.githubusercontent.com/570771/37210135-ea03678c-23a7-11e8-8a0b-a5ccd8550fa3.png)

**Comment by tonydifranco** [comment]
hi @zinkkrysty , it's been awhile but I don't believe I ever did solve this for IE11... sorry,

**Comment by zinkkrysty** [comment]
I found out what it was. It's the fact that Selectize uses an `<input>` tag for getting the text when pasting. Pasting new lines into an input works in other browsers, except IE11, which cuts down the text to just the first line. Hence, Selectize is never getting the full string. I'll try to find a workaround, using a `<textarea>` instead.
