### ISSUE TITLE
Listen to original select changes

### ISSUE THREAD

**Issue by heruan** [selectize/selectize.js#102]
Selectize should be listening on original `<select>` change events and update accordingly, so if the original value is changed by other plugins Selectize would reflect the change.

P.S. Selectize is awesome! I replaced chosen with selectize using the Bootstrap 3 theme and it looks amazing.

**Comment by petemolinero** [comment]
It honestly amazes me that this feature hasn't been added yet; it seems pretty core. In the mean time, though, I've created a simple jQuery method that will update the selectize form based on the original `select` element.

```
$.fn.updateSelectize = function() {

   // Convert the HTML options into a usable array/object for selectize
    var options = [];
    this.find('option').each( function( index ) {
      var option = {
        text:$(  this ).text(),
        value: $( this ).val()
      }
      options.push( option );
    } );

    // Get the Selectize instance
    selectize = this[0].selectize;
    selectize.clearOptions();
    selectize.load(function(callback){
      callback(options);
    });

    // Select the first option
    $.each( selectize.options, function( index, prop ) {
      first_option = index;
      return false;
    });
    selectize.addItem(first_option);

    // Return the jQuery object for chaining
    return this;
};
```

With a little bit more work that could be built into a change listener. Hopefully that'll help someone!

**Comment by Alex-Sokolov** [comment]
+1

**Comment by jmas** [comment]
+1

**Comment by jmas** [comment]
Hey guys, Selectize updating very slow. Can you give Selectize fork that maintained more quickly?

**Comment by joallard** [comment]
Selectize is a large project that is maintained by volunteers, and the number of issues that aren't always qualified and often without tests, and having to support many browser quirks make it hard among others to make the project advance. Nevertheless I'll put forward a plan to ease the advancement, but I'd ask you to be considerate of the fact that this project is organized by volunteers and offered free of charge to projects that are often for-profit.

**Comment by jmas** [comment]
@joallard Np, but if someone add PR to current reposetory - it have all chances to be ignored because project maintained very slowly. For example, I need to add support of native `change` event on native `select` element. So I did fork and want to discuss and merge changes with main-project to share changes.

BTW my fork is https://github.com/BrightLocal/selectize.js

And this feature is very important because it will be more easy to replace `chosen` with `selectize` plugin or add `selectize` to exists project (you do not need to rewrite javascript `addEventListener` logic with `selectize` "events").

**Comment by smohadjer** [comment]
This should be marked as a bug, not an enhancement. Adding selectize to a select element should not break the existing functionality written around that element. It's acceptable to expect developers to change their code to support new functionalities offered by selectize, but it's not ok to expect them to refactor their code just to keep the existing functionality.

**Comment by uaoleg** [comment]
+
