### ISSUE TITLE
Data values arrangements

### ISSUE THREAD

**Issue by bashaappiness** [selectize/selectize.js#1022]
I have a problem in arranging the data values. The problem is when the user selects any item from the drop-down list that should come at a first position of the data values, but its happening in a reverse way. How can I fix this issue? Please help

**Comment by joallard** [comment]
Can you show us a demo?

**Comment by yonicd** [comment]
this is an example of the problem when the library is used within a R shiny application. https://stackoverflow.com/questions/56797061/with-shiny-selectize-avoid-sorting-of-search-results/56797563?noredirect=1#comment100172216_56797563
