### ISSUE TITLE
How to add remove button to dropdown selectize menu?

### ISSUE THREAD

**Issue by carlotrimarchi** [selectize/selectize.js#1023]
Hello,
I'm using the Selectize plugin for a single select menu where I can select a country.
I wanted to add a "x" icon when I select a country, so that I can clear the selection and looking around I found the remove_button plugin.

I installed following the instructions but nothing is happening. It's installed correctly, as I see the right class added to the element in the html code, but no icon or anything is addedo. Is it possible that it works only with multiselect and not with the dropdown?

How can I make it working?

**Comment by animaux** [comment]
There is a fix for this in the code but not in the latest release. —> https://github.com/selectize/selectize.js/pull/799

**Comment by joallard** [comment]
#848 has been merged but not released yet. I'll look to have a new release as soon as I can.

**Comment by joallard** [comment]
Ps. thanks @animaux for pointing the way forward!
