### ISSUE TITLE
Callback does not currently support dynamically loaded option groups?

### ISSUE THREAD

**Issue by mjjones0** [selectize/selectize.js#1025]
I'm looking through the source code at the load event and it does not seem that the callback function passed to load supports loading option groups from the server. Is there plans to implement this in the future? 

I'm looking around line 1767 for the load function in selectize.js.

**Comment by jfishbein** [comment]
This is definitely supported as I've just implemented it in a project. There are two ways to do this:

1) You can pass in a "load" option to the selectize initializer that is a function that takes a callback function as it's only argument to pass the items back to selectize. That load function can then do an Ajax call (or anything else you want to grab data) complete with it's own callbacks. Once you have your options you then need to call the given selectize callback so it can properly build the list. Your load function will be called whenever selectize determines it needs to load options based on the setting.

2) You can call load directly on a selectize which takes one parameter that is the exact same load function as described above (that function does your load and takes one callback parameter to pass the options back to selectize.)

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
