### ISSUE TITLE
loadingClass applying to wrong element?

### ISSUE THREAD

**Issue by mjjones0** [selectize/selectize.js#1026]
I am tasked with reimplementing a loadingSpinner within my selectize integration (we are migrating from Select2 potentially) and I came across the loadingClass parameter to the configuration objects. I notice, however, that this applies to the wrapper element. Shouldn't this be applying to the control's input element instead, or am I doing something totally wrong here? Here's my hack to get the loading spinner working for me:

css:
`.loadinggif {
   background:
     url('http://www.hsi.com.hk/HSI-Net/pages/images/en/share/ajax-loader.gif')
     no-repeat
     right center
     !important;
}`

javascript:
`input = config.selectize.$control;
input.addClass('loadinggif');`

 // $Http call

`function(response) {`
 // do stuff with response
 `input.removeClass('loadinggif');
  }`

**Comment by joallard** [comment]
I don't totally understand the issue here, is there something you expected that didn't happen right? Not sure whether to triage this as enhancement or bug.

**Comment by guyclairbois** [comment]
I have the same issue. If I e.g. add a spinner background image to the 'loading' styleclass, the background image is added to the (non-visible) wrapper element ('selectize-control') at the back and not to the actual input ('selectize-input') in which you're typing the search text. That way the spinner is not visible for the end user.

**Comment by joallard** [comment]
Can someone make a clear STR-actual-expected with demo? Thanks

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
