### ISSUE TITLE
CSS issue when selectize is within a div with style attribute overflow:auto

### ISSUE THREAD

**Issue by nagkumar** [selectize/selectize.js#1027]
We are seeing ember-selectize dropdown is clipped (dropdown is hidden) if ember-selectize is used within another container div, with style="overflow: auto". Same works fine if the continer div style is set to style="overflow: visible"

Same is not the case with normal html , irrespective of container height, select dropdown is overlayed outside the container.

This seem to be a issue with some style attributes of selectize component. Any known CSS fixes to selectize.

[Link to Emberjs forum](http://discuss.emberjs.com/t/ember-selectize-dropdown-is-clipped-when-continer-div-has-overflow-attribute-auto/10245)

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
