### ISSUE TITLE
Why does the ng-model only store the id field?

### ISSUE THREAD

**Issue by mjjones0** [selectize/selectize.js#1028]
Select2's models store the entire object, so if you were to set the default selected items in your select box it would be able to render the label field and store the id field. Since the id field and value field are different in my objects, the model needs to know about both in order to be persisted... otherwise I have to add external caching for all of my select boxes. Is there a built-in way to do this or plans to implement this? 

Here's what I'm talking about:

save $scope.model when the user leaves the page with selectize

<select ...  selectize="config" ng-model="model" />

comes back to page, $scope.model gets loaded, and I want it to be set as a default
item:

config = {
    onInitialize: function () { 
        this.addOption($scope.model);
        this.setValue( ???? , true); 
    }
    onLoad: function(query, callback) { ... }
};

The options loaded from the server are of the form { id: 'a', text: 'b' }, but $scope.model is of the form 'a'. Yet in order for me to set the default items when returning to the page with the select box, I need both 'a' a 'b' for it to be correct...

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
