### ISSUE TITLE
Automatically select of highlighted option

### ISSUE THREAD

**Issue by heruan** [selectize/selectize.js#103]
It would useful the have an option to make have the highlighted option automatically selected. Use case:
1. compiling a form using the keyboard;
2. switching between controls with the `TAB` key;
3. on focusing a selectized `<select>`, the dropdown appears;
4. scrolling with the `DOWN` key highlights the options;
   OR
5. typing the first letter highlights the first result option;
6. the highlighted option is selected without having to press the `ENTER` key, but just the `TAB` key.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
