### ISSUE TITLE
registerOption undefined values

### ISSUE THREAD

**Issue by Wyzix33** [selectize/selectize.js#1031]
Hi, I have a situation where my array has some missing keys.
Javascript will always "fill in" gaps in the list of array keys. If you miss some out, Javascript will fill in the blanks with undefined, so if my array looks like this :
var a = []; // empty array
a[1] = {"id":1,"name":"Something"}; // don't set a[0]
console.log(a.length); // gives 2
and if i try to initialize selectize with my a array like this

```
$('#myselect').selectize({
maxOptions : 20,
valueField: 'id',
labelField: 'name',
searchField: ['name'],
options: a,
create: false
});
```

i get TypeError: a is undefined 

on

registerOption:function(a){var b=z(a[this.settings.valueField]);return!... 

is there a way to allow me to use my array like this? I need to keep my id as array key too for some future updates.

Thank you and great job with selectize!!!

**Comment by Alex-Sokolov** [comment]
Maybe you just need filter array from undefined elements before?

``` js
var arr = [1,2,,3,,3,null,,0,,undefined,4,,4,,5,,6,,,,];
arr = arr.filter(function(n){ return n != undefined });
// arr = [1, 2, 3, 3, 0, 4, 4, 5, 6]
```
