### ISSUE TITLE
Cascading Droplist not working

### ISSUE THREAD

**Issue by snallamu** [selectize/selectize.js#1032]
Cascading Droplist not working in chrome as well as in
the hosted example under Selectize.js

**Comment by joallard** [comment]
I don't understand the issue. Can you show us a demo on jsfiddle/codepen, explain us the steps to reproduce, what you expected and what happened? Thanks

**Comment by snallamu** [comment]
Hey Joallard,

Thanks for your reply

Hit the below url
http://selectize.github.io/selectize.js/

Please try the City/State Selection Scenario
After Selecting State
City Droplist is not loading .

**Comment by joallard** [comment]
It says:

> Note: The API for fetching cities is a little spotty, so if it fails to list cities, that's what's going on (try another state).

Are you able to demonstrate another scenario with another API?

**Comment by snallamu** [comment]
Hey Jollard,

you were right the city is wrong my api works well.
No issue with cascading

Below are findings

1.URL and value is not working on the lookup

 url: 'https://jsonp.afeld.me/?url=http://api.sba.gov/geodata/primary_city_links_for_state_of/' + *_value *_\+ '.json',

Soln: Please replace the url as below it will work

url: 'http://api.sba.gov/geodata/primary_city_links_for_state_of/' +  $("#controlid").val()+ '.json',

2.For somereason the above url is not working in the droplist binding

Soln: Please try this url
http://jsonplaceholder.typicode.com/users?id=1

Thanks
Saravanan Nallamuthu

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
