### ISSUE TITLE
Uncaught TypeError: Cannot read property 'mixin' of undefined

### ISSUE THREAD

**Issue by ems2141** [selectize/selectize.js#1034]
I saw this issue pop up for somebody else about a month ago but there was not a clear resolution posted. I have pulled the stand alone js files and all of the css files under the "dist" directory (don't know which css is required at this point). They are being required and I see all the js and css files coming across the network but I am getting two errors:

selectize.min.js?body=1:3 Uncaught TypeError: Cannot read property 'mixin' of undefined

and

edit:4500 Uncaught TypeError: $(...).selectize is not a function

Can somebody please assist? I have used selectize before in another project and so I'm not sure what is going wrong this time.

Thank you!!

**Comment by joallard** [comment]
Sounds like #701

**Comment by snallamu** [comment]
Try loading the selectize.min.js on the top of the content under header section

**Comment by ems2141** [comment]
Thank you!  It is working now!
