### ISSUE TITLE
Safari Mac and iPhone filtering bugs

### ISSUE THREAD

**Issue by briemarie** [selectize/selectize.js#1039]
With Safari while on a Mac (multiple computers have been used to test so operating system and type is irrelevant), only a single letter can be entered into the input field to filter the options. Another side effect of this is that create does not work unless the user only wants to enter a single letter which doesn't work in our case. Furthermore, the ability to enter text for filtering is only working if the input filed is tabbed into. If the field is clicked into, filtering is unavailable. 

While on iPhones with Safari, filtering is the same behavior as above, except the ability to enter a single letter only comes after selecting an option from the dropdown and then deleting it.

Here is how I set the options:

$('#industry-select').selectize({
  create: true,
  sortField: 'text',
  closeAfterSelect: true,
  selectOnTab: true,
  render: {
    option_create: function(data, escape) {
      return "<div class='create'>Looks like we don't have this industry yet — let's talk!</div>";
    }
  },
});

I tried to remove the selectOnTab : true part to see if that would at least fix the bug where the field only allows filtering when it is entered via the tab, but not when it is clicked. This changed nothing.

Here is a quicktime video to show the behavior on Mac.
https://youtu.be/7GMa9I-1vi4

**Comment by briemarie** [comment]
I'm so sorry, the bug was found to be a conflicting style on the input element.
  -webkit-user-select: none;
  -moz-user-select: none;

**Comment by app-gps** [comment]
Safari renders things differently and uses a UI overlay for dropdowns. You can't just hide them, but you can refresh the options match from array each time. Here I use jQuery to clear a select options each time and create new options:

`<input type="text" id="inputPatro" onchange="myFunction()" placeholder="Filtre per nom.." title="Escriu un patró per filtrar les opcionw del desplegable">
<select id="selectArticles">
</select>

<script>
myFunction();

function myFunction() {

  //alert("dins");

	var select = document.getElementById("selectArticles");
  var options = ["NouCreus", "Pic de l'Àliga", "Puigmal", "Finestrelles", "NouFonts", "Núria Estació"];
  
	var i, L = select.options.length - 1;
  for(i = L; i >= 0; i--) {
     select.remove(i);
  }

	var input, filter, ul, li, a, i, txtValue;
	input = document.getElementById("inputPatro");
	filter = input.value.toUpperCase();
  
  var el = document.createElement("option");
      el.textContent = "Vall de Núria";
      el.value = "-1";
      select.appendChild(el);

  for(var i = 0; i < options.length; i++) {
  	var opt = options[i];
    if (opt.toUpperCase().indexOf(filter) > -1) {
      var el = document.createElement("option");
      el.textContent = opt;
      el.value = opt;
      select.appendChild(el);
    }
  }
}
</script>`
