### ISSUE TITLE
Cannot delete selected item on BB10

### ISSUE THREAD

**Issue by Endeer** [selectize/selectize.js#1040]
Hello,

when using quite basic Selectize, I found that on BlackBerry Classic (and most certainly all OS10 devices with hardware keyboard), you cannot use backspace after a selection is made.

```
            $('select#place_id').selectize({
                sortField: {
                    field: 'text',
                    direction: 'asc'
                },
                dropdownParent: 'body'
            });
```

This is because BB10 sends KEY_DELETE when the input field is empty, not KEY_BACKSPACE. I fixed this for myself by also alllowing KEY_DELETE to be used in deleteSelection(), I can do it conditionally based on BB10 string in user agent, but it does not seem very clean.

However if it was acceptable, I can create a pull request.

**Comment by m4r14n** [comment]
Try this:
` $(document).on('click', 'div.selectize-input div.item', function(e) {
        var select = $('#services').selectize();
        var selectSizeControl = select[0].selectize;
        // 1. Get the value
        var selectedValue = $(this).attr("data-value");
        // 2. Remove the option 
        select[0].selectize.removeItem(selectedValue);
        select[0].selectize.refreshItems();
        select[0].selectize.refreshOptions();
    });`

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
