### ISSUE TITLE
Bootstrap Disabled Style Not Applied When Selectize is Disabled

### ISSUE THREAD

**Issue by jblacker** [selectize/selectize.js#1042]
Normally when using the Bootstrap (3) theme when an input element is disabled it is grayed out and there's a not-allowed cursor when hovering over the element.  When a Selectize'd element is disabled by calling `.disable()` it does not honor the disabled styling of Bootstrap causing it to not look the same as other disabled elements as seen below where the Name field is Selectize'd:

![image](https://cloud.githubusercontent.com/assets/726152/14611989/f2106c78-0562-11e6-9ef8-634201f557a8.png)

It is successfully disabled and all of the correct behavior is exhibited by the disabled Selectize'd element, but the styling does not conform to the rest of the inputs.

**Comment by whelaro** [comment]
I believe modifying this will get you what you're after on the cursor side (I can't confirm the other part as I'm actually leveraging Material Bootstrap which replaces the Serialize css), but I did have to copy this code over from selectize.css to the CSS file imported and then adjust to not-allowed:

`.selectize-input.disabled,
.selectize-input.disabled * {
  cursor: not-allowed !important;
}`

**Comment by goraSi** [comment]
Use bellow CSS:

`.ui-select-toggle[disabled], .ui-select-toggle[disabled]:hover {
  color: #555;
  background-color: #eee;
  opacity: 1;
}`
