### ISSUE TITLE
Include optgroup label in the search filter

### ISSUE THREAD

**Issue by docmattman** [selectize/selectize.js#1043]
I have a selectize box that contains a list of cities as options grouped by their states as optgroups.  Is there a way to have the optgroup labels  included in the search?

For example, currently if I type "Richmond", it will filter and show:

```
- California
    Richmond
- Virginia
    Richmond
```

If I type "Virginia", I'd like it to see that "Virginia" is an optgroup and filter to show something like:

```
- Nevada
    Virginia City
- Virginia
    Alexandria
    Arlington
    Fairfax
    .... the rest of the cities in Virginia
```

In the above example, it knows there is a city in Nevada matching "Virginia", and it knows there is an optgroup named "Virginia" so it displays all of them.

Can this be done with Selectize?

**Comment by maxi032** [comment]
+1

**Comment by fTelliez** [comment]
Hi,
You can do this by this code:
`<option data-state="Virginia" data-city="Alexandria">Alexandria</option>`
and with selectize:
`$("#myselect").selectize() {
    searchField: ['state','city'],
    ...
`

Hope it helps

**Comment by ghost** [comment]
I'm sorry, I tried the solution above and it didn't work for me. @fTelliez 
I had the same select HTML, something like:
`<select name="test" id="test-select">
    <optgroup label="stores">
        <option data-type="stores" value="1">First store</option>
        ...
    </optgroup>
</select>`
And then:
`$('select#test-select').selectize( { searchField: [ 'text', 'type' ] } ) ;`

But it doesn't search for optgroup labels (or, in this case, the data-type attribute). Is there something I can do?

Thank you in advance

**Comment by fTelliez** [comment]
Sorry, I forgot the initialization part in the selectize constructor. The complete code is:

`$('select#test-select').selectize({
  searchField: ['text', 'type'],
  onInitialize: function() {
    var s = this,
      children = this.revertSettings.$children;
    if (children.first().is('optgroup')) {
      children = children.find('option');
    }
    children.each(function() {
      $.extend(s.options[this.value], $(this).data());
    });
  }
});`

Here is a fiddle to test it: https://jsfiddle.net/hb8ydhs9/24/

**Comment by christoomey** [comment]
Not sure if this is from a more recent change, but it looks as though the text of the `optgroup` tag is included in the options, so it seems that you can use `searchField: ['text', 'optgroup']` without needing any extra code.

``` html
<select name="test" id="test-select">
  <option value="">Select an item...</option>
  <optgroup label="stores">
    <option value="1">First item</option>
    <option value="2">Second item</option>
  </optgroup>
  <optgroup label="warehouse">
    <option value="3">First item</option>
    <option value="4">Second item</option>
  </optgroup>
</select>
```

``` js
$('select#test-select').selectize({
  searchField: ['text', 'optgroup'],
});
```

Sample fiddle: https://jsfiddle.net/christoomey/4rkuvgxo/4/

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
