### ISSUE TITLE
input field is shifted to center while fetching data from third-party

### ISSUE THREAD

**Issue by irfan-yusanif** [selectize/selectize.js#1046]
http://newtemp.apphb.com/ 
above is the link for live demo. When i type something in input field it is shifted to center. and when the ajax success portion is run its shifted back to its original postion.
Why its being shifted to center while fetching data?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
