### ISSUE TITLE
option_create and pasting data

### ISSUE THREAD

**Issue by madej** [selectize/selectize.js#1048]
In version 12 regression is introduced, that if option_create is defined and you paste anything it will be invoked immediately.

**Comment by hfelici** [comment]
I am having the same problem in chrome Version 52.0.2743.116 unknown (64-bit) and firefox 48. When I press ctrl+v to paste, the create function is fired

**Comment by joallard** [comment]
@hfelici Does this still happen in 0.12.3? There was a fix with `onPaste`

**Comment by romanlex** [comment]
I can cofirm. Chrome. The create function is fired.
0.12.4

When I change delimeter and set splitOn options to null creat function not fired.
I think what trouble in this code

``` javascript
// if splitOn was not passed in, construct it from the delimiter to allow pasting universally
if (!self.settings.splitOn && self.settings.delimiter) {
    var delimiterEscaped = self.settings.delimiter.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
    self.settings.splitOn = new RegExp('\\s*' + delimiterEscaped + '+\\s*');
}
```

Because when fired onPaste event `if (self.settings.splitOn) {` splitOn always determined

**Comment by joallard** [comment]
Okay, can someone put together an STR with demo?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
