### ISSUE TITLE
Possible to have more than one delimiter?

### ISSUE THREAD

**Issue by originalfoo** [selectize/selectize.js#1049]
Loving selectize.js, but there's one thing I really miss from Select2 - that's the ability to have an array of delimiters, most commonly `[',', ' ']`

I was wondering if this feature could be added to selectize.js and started poking around in the code but am not sure of best place to make the change.

Essentially I was thinking that it could do something like this to facilitate backwards compatibility:

``` javascript
if $.isArray(settings.delimiter) {
  // cycle through elements of array to see if they appear in the value and split accordingly
} else {
  values = value.split(settings.delimiter);
}
```

The first delimiter in the array would be used when calling `getValue()`:

``` javascript
  getValue: function() {
    if (this.tagType === TAG_SELECT && this.$input.attr('multiple')) {
      return this.items;
    } else {
      var delimiter = this.settings.delimiter;
      return this.items.join($.isArray(delimiter) ? delimiter[0] : delimiter);
    }
  },
```

Am I thinking along the right lines and would changes be needed in other locations where delimiter is mentioned (and also in the numerous other files in the repo)?

**Comment by craig-jennings** [comment]
There is an option, `splitOn`, that accepts a regex to match as a delimiter. You can use that to have multiple delimiters. In one instance, I set it to `/[,;]/` to split on either a `,` or a `;`. Although looking at the code it only applies to pasted text :/

**Comment by originalfoo** [comment]
Ah, I was wondering why there was a separate `splitOn` property. I'm still trying to wrap my head around the code...

**Comment by joallard** [comment]
I don't really get the `splitOn` separate either. But the delimiter question is interesting, as the delimiter is both (a) the input character that tells S. on input to break it down, and (b) the character used to separate values when serializing the "tags" into the input value in the form. I'm guessing this is an enhancement request regarding (a) but not (b)?

**Comment by chrisidakwo** [comment]
Any plan or progress on this?

**Comment by petrosmm** [comment]
I noticed `splitOn` was not in the documentation, was this done on purpose?
