### ISSUE TITLE
Bootstrap 3 theme container height

### ISSUE THREAD

**Issue by heruan** [selectize/selectize.js#105]
Using the Bootstrap 3 theme applies `height: auto` on `.form-control.selectize-control` which mysteriously gets a height of 39px, where the default Bootstrap `.form-control` has an height of 34px. Having for example two forms side by side this 5px difference is  a sensitive issue.

**Comment by FabianKoestring** [comment]
`vertical-align:top;` on `selectize-input` works like a charm!

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
