### ISSUE TITLE
groups optgroupField object

### ISSUE THREAD

**Issue by lafriks** [selectize/selectize.js#1050]
Currently there is no way to use optgroups if group property is object.

Example:

``` js
options: [
    {id: 1, name: "Name 1", group: { id: 5, name: "Group 1" }},
    {id: 2, name: "Name 2", group: { id: 5, name: "Group 1" }},
    {id: 3, name: "Name 3", group: { id: 6, name: "Group 2" }},
    ....
]
```

Would be perfect if groups could be automatically populated from such objects with selectize options:

``` js
optgroupValueField: "id",
optgroupLabelField: "name",
optgroupField: "group"
```

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.

**Comment by lafriks** [comment]
this is still actual and imho is not still supported

**Comment by databyte** [comment]
What version are you on?

Check out the Option Groups section of the [Demos page](http://selectize.github.io/selectize.js/).

**Comment by lafriks** [comment]
I know this but option groups are only supported for string type ex:
```
options: [
    {id: 1, name: "Name 1", group: "Group 1" },
    {id: 2, name: "Name 2", group: "Group 1 },
    {id: 3, name: "Name 3", group: "Group 2" },
    ....
]
```
What would be nice to have to support when group field is object with its own value and name properties

**Comment by databyte** [comment]
Optgroup ultimately ends up as a string `label="Group 1"`. There's no complex types supported in the HTML standard itself for option groups.

To say it another way, the group IDs from your original example would simply be lost in translation as its rendered to HTML and selected by the user.

If the goal you want is to get the IDs back, they won't be in HTML anymore. Storing extra `data-` fields on the HTML tags just to pull them back out is beyond the scope of selectize simply making existing HTML markup more interactive. For the data storage and retrieval, it'd be simpler for you to have the value/onClick to run through a small lookup function on your side to grab the ID of the selected item's group.

If its more about passing in an object you already have, I too think a small function to pluck out the name as the group value would work too.

```javascript
var pluckName = function(groupObj) {
  return groupObj.name;
}

const options = [
  { id: 1, name: "Name 1", group: pluckName({ id: 5, name: "Group 1" }) },
  { id: 2, name: "Name 2", group: pluckName({ id: 5, name: "Group 1" }) },
  { id: 3, name: "Name 3", group: pluckName({ id: 6, name: "Group 2" }) }
]

console.log(options)
```

or passing in the full object to render out options

```javascript
var renderOptions = function(group) {
  return group.map(item => { return { id: item.id,
                                      name: item.name,
                                      group: item.group.name }; });
}

console.log(renderOptions([
  { id: 1, name: "Name 1", group: { id: 5, name: "Group 1" } },
  { id: 2, name: "Name 2", group: { id: 5, name: "Group 1" } },
  { id: 3, name: "Name 3", group: { id: 6, name: "Group 2" } }
]))
```

https://jsitor.com/aaHzG23iw
