### ISSUE TITLE
Not all values displayed in multi-select mode

### ISSUE THREAD

**Issue by Alex-Sokolov** [selectize/selectize.js#1052]
Using selectize.js over text-field. Not all values showed as selected

Use custom delimiter '|'
In value `Оптоволоконные линии связи|Беспроводные сети|3` — 3 values
Showed `3` — 1 value

JSFiddle: https://jsfiddle.net/rsdqz0bb/4/

**Comment by Alex-Sokolov** [comment]
up

**Comment by joallard** [comment]
Are you able to debug and find the cause?

**Comment by Alex-Sokolov** [comment]
The problem in `addItem` function.

I have a multi-select.
Dropdown-list items stored in `self.settings.options`. For example:
- ЛВС организации
- Оптоволоконные линии связи

Selected items in `self.settings.items`. For example:
- Проверка
- 4534534
- Оптоволоконные линии связи

Selected `1 item` from dropdown-list and `3 items` created by user
Creating items allowed, in create-option there is function:

``` js
create: function (input) { return { value: input, text: input }; }
```

What in `addItem` function:

``` js
addItem: function(value, silent) {
    var events = silent ? [] : ['change'];

    debounce_events(this, events, function() {
        var $item, $option, $options;
        var self = this;
        var inputMode = self.settings.mode;
        var i, active, value_next, wasFull;
        value = hash_key(value);

        if (self.items.indexOf(value) !== -1) {
            if (inputMode === 'single') self.close();
            return;
        }

        if (!self.options.hasOwnProperty(value)) return;
        // ^^ that checking drop items which is not in dropdown-list
        // line 2493 in https://github.com/selectize/selectize.js/blob/master/dist/js/standalone/selectize.js#L2493
        // ...
```

**Comment by Alex-Sokolov** [comment]
Found a possible fix — adding created items in options.
Tweaking `addItem` function seems to be more complicated, because format of items and options in my case not the same.

That need tweak `build options table` (https://github.com/selectize/selectize.js/blob/master/dist/js/standalone/selectize.js#L1112)

Before need move higher block with initializing `self.settings.mode`, because this option already need to this fix

``` js

// option-dependent defaults
self.settings.mode = self.settings.mode || (self.settings.maxItems === 1 ? 'single' : 'multi');
if (typeof self.settings.hideSelected !== 'boolean')
{
    self.settings.hideSelected = self.settings.mode === 'multi';
}

// build options table
if (self.settings.options)
{
    // ######################################################
    // Add user-created items in options
    if (self.settings.mode === 'multi' && self.settings.create !== false)
    {
        var created = [];
        for (var m = 0, length = self.settings.items.length; m < length; m++)
        {
            created.push(self.settings.create(self.settings.items[m]));
        }

        self.settings.options = self.settings.options.concat(created);
    }
    // ######################################################

    for (i = 0, n = self.settings.options.length; i < n; i++) {
        self.registerOption(self.settings.options[i]);
    }
    delete self.settings.options;
}
```

**Comment by joallard** [comment]
Okay thanks. I'll try to review that

**Comment by Alex-Sokolov** [comment]
Any news?

**Comment by joallard** [comment]
Found it. It's the same demand as #693.
