### ISSUE TITLE
Search remote data - not removing items from search result

### ISSUE THREAD

**Issue by netbka** [selectize/selectize.js#1053]
Hello,
I am using selectize to query my Database.
I am trying to use selectize.js as search box to retrieve JSON data from my DB.
It is almost working as I want, but I old result are still showing in the dropdown + the search in looking for values in irrelevant field. I want it to look only on "ProductName" (as specified), but I see highlights also on "ProductShortDesc"
My controller code is:

```
   [HttpPost]
    public JsonResult SearchProductSelectize(string keyword)
    {
        IEnumerable<Product> products= db.Product.Include(p=>p.Tegs).Where(p => p.ProductName.Contains(keyword)).ToList();
        List<SearchResult> result = new List<SearchResult>();
        foreach (Product p in products)
        {
            result.Add(new SearchResult()
            {
                Id = p.Id,
                ProductName = p.ProductName,
                ProductShortDesc = p.ProductShortDesc,
                Tegs = p.Tegs.Select(c => c.TegName).ToList()
            });

        }
```

and the script is:

```
  $('#globalsearch').selectize({
    persist: false,
    valueField: 'Id',
    labelField: 'ProductName',
    searchField: ['ProductName'],
    create: false,
    render: {
        option: function (item, escape) {
            return '<div><span class="productname">' + escape(item.ProductName) + '</span><br />' +
                '<span class="productshortdesc">' + escape(item.ProductShortDesc) + '</span></div>';
        }
    },
    score: function (search) {
        var score = this.getScoreFunction(search);
        return function (item) {
            return 1;
        };
    },

    load: function (query, callback) {
        if (!query.length) return callback();
        $.ajax({
            url: '/Products/SearchProduct/',
            type: 'POST',
            dataType: 'json',
            data: {
                keyword: query,
            },
            error: function () {
                callback();
            },
            success: function (res) {
                console.log(res);
                callback(res);
            }
        });
    },


});

 });
```

Do you have any idea what I am doing wrong?
Thank you!

**Comment by nicklecoder** [comment]
I am experiencing the same problem. In addition, the dropdown doesn't appear for me until after I take the focus away from the field and bring it back.

**Comment by coneybeare** [comment]
+1

**Comment by coneybeare** [comment]
Note, `create: false` is also ignored.

**Comment by joallard** [comment]
The format of the issue is far from clear to understand and take action, anyone want to file a separate issue with a clear description of the problem, steps to reproduce and expected results?

**Comment by unstoppablecarl** [comment]
I made a fiddle. 

https://jsfiddle.net/gpsLvkga/1/

Add a value not in the list. Then change to a different value. Then see that it is still in the list.

**Comment by unstoppablecarl** [comment]
It does seem to behave as expected when `maxItems > 1`

This seemed to work ok for me:

``` js
$el.selectize({
            create:      function(input) {
                return false;
            }
        });
```

In this case I am using sync data though.

**Comment by joallard** [comment]
1. Visit https://jsfiddle.net/gpsLvkga/1/ (Given `persist:false`)
2. Click the select, type 'buzz', press Enter
3. Select 'foo'
4. 'buzz' is not gone from the list

@netbka, is that the issue you are reporting?

**Comment by ulriklystbaek** [comment]
The reason why you experience this, is because of selectize way of handeling load. Selectize actually saves all items loaded through all loads, and will use its score function to determine which to shown. So you need to update the score function to reflect how you select item on your remote datasource. I have made a better support for remote datasources, I will spend time creatin a pull request as soon as see my other pull requests being handeled. I have added loadOption attribute, that can be changed from default local:
- local:           Normal behavior, all loaded items are stored in container. Score function is used to choose which items are shown. Load function is only called with new queries.
- remote:          Remote data source. Every time query changes, list will be cleared and the list is populated with new loaded items when they are ready.
- remote_score:    Remote data source. Will reload items each time query changes. It will not clear container before items for new query is ready. This may give a more smooth transition between queries. Score function will be used to choose which items to be shown from old dataset in container until new loaded. (Score function will also affect new dataset, so it need to be reflect remote selection).

**Comment by JakeAlmer** [comment]
@ulriklystbaek that sounds like a great way to handle it! I have some hacks in the score and load params but a formal way to handle this would be great.

**Comment by therealbrandon** [comment]
For the highlighting, Selectize will highlight anything that matches in the render function.  For extra description in the render function I would add a no-highlight class to the area you don't want highlighted.

```
render: {
        option: function (item, escape) {
            return '<div><span class="productname">' + escape(item.ProductName) + '</span><br />' +
                '<span class="productshortdesc no-highlight">' + escape(item.ProductShortDesc) + '</span></div>';
        }
    },
```

Then use CSS to prevent highlighting:

```
.no-highlight .highlight {
  background: initial !important;
}
```

**Comment by timbleck** [comment]
@JakeAlmer can you please share your workaround as we're dealing with the same issue and i've tried various hacks in `score` and `load` as well but did not got it right as its mostly clearing the selected options as well when using `clear()` or `clearOptions()` or `this.options = this.sifter.items = {}`.

**Comment by JakeAlmer** [comment]
setting the score function to a static value and clearing the previous options on each request is what ended up working for me

something like:
```javascript
domElement
	.selectize({						
		score: function() { return function() { return 1; }; }, // only filtering is done server side
		load: function(query, callback) {
			var self = this;
			$.ajax({
				success: function(res) {
					self.clearOptions(); // don't want to display previously cached options
					callback(res);
				}
			});
		}
	})[0].selectize;
```

**Comment by timbleck** [comment]
@JakeAlmer thanks, this works (clearing the search results) but it also clears all previous selected options which is not what i want (i want to keep all selected options). I tried to use just parts of the implementation of `clearOptions()` like `this.options = this.sifter.items = {}` and this resets only the search result but this then causes an error when selecting results on the 2nd search result list while selecting on the 1st search result list works just fine.

```
Uncaught TypeError: Cannot read property 'title' of undefined
    at Selectize.updateOriginalInput (selectize-0.12.4.self-7e677d3….js?body=1:2815)
    at Selectize.<anonymous> (selectize-0.12.4.self-7e677d3….js?body=1:2621)
    at debounce_events (selectize-0.12.4.self-7e677d3….js?body=1:923)
    at Selectize.addItem (selectize-0.12.4.self-7e677d3….js?body=1:2575)
    at Selectize.onOptionSelect (selectize-0.12.4.self-7e677d3….js?body=1:1823)
```

**Edit**

I just figured out this issue only occurs when using a `<select>` field, if using a `<input>` everything works as expected.

**Comment by ulriklystbaek** [comment]
I have changed a lot to get it working properly, the simple hacks had different issues with the other functionality... I do not have the changes by itself anymore, but I can link you to the js file.

**Comment by timbleck** [comment]
@ulriklystbaek i'd appreciate that, thanks

**Comment by ulriklystbaek** [comment]
I am using it on my site http://payup.dk, but it is not available yet, so I will try to send you some direct links here:

Custom selectize: http://payup.dk/scripts/selectize.0.12.4.js
Script where I initialize (in my case): http://payup.dk/scripts/site.account.email.lookup.js

Hope it will help you out.

**Comment by ulriklystbaek** [comment]
Did you get it working?

**Comment by timbleck** [comment]
Yes, finally. Clearing the options using `this.options = this.sifter.items = {}` within the `load` worked fine for both cases (`select` and `input`) but when using with an `select` field the `updateOriginalInput` throws an error because the `options` hash is empty and this hash is used to determine the label for the `option` tag (`label = self.options[self.items[i]][self.settings.labelField] || '';`. I've fixed this by overriding this method in my initialization script to simply fallback to an empty label.

```
Selectize.prototype.updateOriginalInput = (opts = {}) ->
  if this.tagType == 1
    options = []
    for item in @.items
      label = this.options[item]?[this.settings.labelField] || ""
      options.push("<option value=\"#{item}\" selected=\"selected\">#{label}</option>")
    if !options.length && !this.$input.attr('multiple')
      options.push('<option value="" selected="selected"></option>')
    this.$input.html(options.join(''))
  else
    @.$input.val(this.getValue())
    @.$input.attr('value',this.$input.val())

  if (this.isSetup)
    if (!opts.silent)
      this.trigger('change', this.$input.val());
```

**Comment by deltoss** [comment]
@ulriklystbaek 
I was wondering why load isn't being called when I type on selectize... 
It'd be nice to those options to be in there.

> Load function is only called with new queries.

After stumbling across this post too late, I ended up ditching the **load** event, and used the **onType** event to meet my requirements similar to the OP:

```
function clearUnselectedOptions(selectize) {
	for (var option in selectize.options) {
		if ($.inArray(option, selectize.items) === -1) {
			selectize.removeOption(option);
		}
	}
}

$('#tagSelectServerSideFiltering').selectize({
	persist: true,
	createOnBlur: true,
	create: true,
	valueField: 'ID',
	labelField: 'Name',
	searchField: 'Name',
	score: function () { return function () { return 1; }; },
	openOnFocus: false,
	closeAfterSelect: true,
	onItemAdd: function (value, $item) {
		clearUnselectedOptions(this); // Prevents options (potentially irrelevant) previously brought up from showing again
	},
	onItemRemove: function (value) {
		clearUnselectedOptions(this); // Prevents options (potentially irrelevant) previously brought up from showing again
	},
	// Note: 
	// Selectize brings up previous irrelevant suggestions user has brought up before
	// Thus, onType was used instead of Load to have more flexibility and control over this behaviour
	onType: function (str) {
		if (!this.lastQuery.length)
		{
			// Manually prevent dropdown from opening when there is no search term
			// especially when you hit backspace and clear your search term
			this.close();
			// Clear out the unselected options
			clearUnselectedOptions(this);
		}
		var self = this;
		// Load from ajax, if the typed query is not empty, and 
		// typed length is over a certain number of characters
		// You should change the minimum length as required
		var refreshData = function() {
			if (str.length && str.length > 0)
			{
				self.load(function (callback) {
					$.ajax({
						url: "URL",
						type: 'GET',
						dataType: 'json',
						data: {
							searchQuery: str,
							},
						error: function () {
							callback();
						},
						success: function (res) {
							clearUnselectedOptions(self);
							callback(res);
							self.refreshOptions(true);
						}
					});
				});
			}
		}

		// Only trigger the data refreshing if stopped typing a specified amount (in milliseconds)
		// This feature is inbuilt to Selectize as part of the property "loadThrottle", but only 
		// if you use the load event, which causes other issues
		if (self.typingTimer)
			clearTimeout(self.typingTimer);
		self.typingTimer = setTimeout(function () { refreshData(); clearTimeout(self.typingTimer); }, 300);
	},
});
```

**Comment by darius00klokj** [comment]
change:
`searchField: ['ProductName'], `
to 
`searchField: 'ProductName',`

add on first line to load function :
```
load: function (query, callback) {
  this.clearOptions();
```

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
