### ISSUE TITLE
Turkish characters not working(like "İ" or "ı")

### ISSUE THREAD

**Issue by rajaz-tr** [selectize/selectize.js#1057]
In Turkish we have "ı" character in additon to "i". And in uppercase "ı" becomes "I" and "i" becomes "İ".

For example if have "İstanbul" in my list and if i type "İ" nothing happens. I guess it happens because this plugin uses Javascript keyCode function to detect what is typed and keyCode does not support non ASCII characters? Is there a way to fix this issue?

**Comment by Ca-aC** [comment]
Any update on this? Capital i ("İ") does not register. "Ç" and "Ş" do, though.

**Comment by joallard** [comment]
The updates are what we see. The status is currently `cause unknown`, so someone needs to go in debugger and find out the cause.

**Comment by kadir950** [comment]
@grinninglich   change 'i': '[iÌÍÎÏìíîïĪī]'  To    'i': '[iÌÍÎÏìíîïĪīİ]'  in selectize.js  (add upper i (İ) in the string). I solved problem with this way.

**Comment by brianreavis** [comment]
@grinninglich @Ca-aC @kadir950 This should be fixed by sifter 0.5.1: https://github.com/brianreavis/sifter.js/commit/46a8b557266f20aaab49e601751a85563c845a01
