### ISSUE TITLE
onInitialize fires after templates are used

### ISSUE THREAD

**Issue by dakuzen** [selectize/selectize.js#1058]
onInitialize fires after templates are rendered and cached.  Attempts to augment / retain data from original options and have that data applied to custom templates is not possible on first load.

Current solution is to trigger `setValue()` at the end of `onInitialize`, but it would be ideal if the initialize event was triggered before anything rendered and cached.
## Scenario
- Modified Item Template to render custom value
- Custom attribute present on original <option> tag
- Custom attribute not retained by selectize, so revertSettings is modified in onInitlialize (as discussed in issue #239)
- Because setValue is fired before onInitialize, the custom attributes are unavailable
## Ideal Solutions
- Store reference to original object in options array, so custom templates can lookup item if needed 
- Move onIntiialize before any rendering takes place
## Quick Solutions
- Lookup the item from the self.revertSettings.$children array available within the template

```
  jQuery(el).selectize({
    'render': {
      'item': function(data, escape) {
        if (typeof data['class'] == 'undefined') {
          data['class'] = jQuery(this.revertSettings.$children[ data.$order - 1 ]).attr('class');
        }
        return '<div class="item '+data['class']+'"><i></i>' + escape(data['text']) + '</div>';
      }
    }
  });
```
- Flush cache and run self.setValue( self.getValue() ) at the end of onInitialize

```
  jQuery(el).selectize({
    'render': {
      'item': function(data, escape) {
        return '<div class="item '+data['class']+'"><i></i>' + escape(data['text']) + '</div>';
      }
    },
    'onInitialize': function () {
      var self = this;
      self.revertSettings.$children.each(function () {
        jQuery(this).data('class', jQuery(this).attr('class'));
        jQuery.extend(self.options[this.value], jQuery(this).data());
      });
      self.renderCache = [];
      self.setValue(self.getValue(), true);
    }
  });
```

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
