### ISSUE TITLE
Problem with jQuery object not validating correctly

### ISSUE THREAD

**Issue by IAmJulianAcosta** [selectize/selectize.js#1062]
Hi! I'm using selectize with ember-selectize, and I'm adding ember `models` to selectize.

When removeItem is called, and checking if `value`is an object:

```
removeItem: function(value, silent) {
        var self = this;
        var $item, i, idx;

        $item = (typeof value === 'object') ? value : self.getItem(value);
        value = hash_key($item.attr('data-value'));
```

(https://github.com/selectize/selectize.js/blob/253e1dd936796d95487cbced32d4a05f2f3781c6/src/selectize.js#L1490)

$item value will be an instance of `DS.model` that doesn't have the `attr` method, so an error is thrown.

I guess that the evaluation `$item = (typeof value === 'object')  ...` should be `$item = (value instanceof jQuery) ? ...` in order to assure that value is a jQuery object and `$item.attr ()` exists. 

Related issue on ember-cli-selectize: https://github.com/miguelcobain/ember-cli-selectize/issues/123

**Comment by joallard** [comment]
Thanks. Closing in favor of the descriptively-titled #1063
