### ISSUE TITLE
Setting a default value from database with remote source

### ISSUE THREAD

**Issue by grafikkaos** [selectize/selectize.js#1064]
I currently have selectize loading a list of books from an ajax remote source.  Once a value is selected, it is saved to a database base.  The problem I have with selectize now is that when i want to edit input box, it is not pre-populated with the item name, only with the id.

Is there a way I can resolve this issue?  Any help would be appreciated.  My code is shown below.

```
var bookSelect = $('#select-book').selectize({
        valueField: 'id',
        labelField: 'value',
        searchField: 'value',
        maxItems: 15,
        options: [],
        create: false,
        render: {
            option: function (item, escape) {
                return '<div>' +
                    '<span class="title">' +
                    '<span class="name"><i class="fa fa-book fa-fw"></i>' + escape(item.value) + ' &pound;' + parseFloat(item.unit_price).toFixed(2) + '</span>' +
                    '</span>' +
                    '</div>';
            }
        },
        load: function (query, callback) {
            if (!query.length)
                return callback();
            $.ajax({
                url: SITE_URL + '/store/get_books',
                type: 'POST',
                dataType: 'json',
                data: {
                    q: query
                },
                error: function () {
                    callback();
                },
                success: function (res) {
                    //console.log(res);
                    callback(res);
                }
            });
        },
        onItemAdd: function (item) {
            //console.log(item);
            var itemDetails = {
                'id': item,
                'value': $('.item').text()
            };
            var selectize = prescriptionSelect[0].selectize;
            selectize.clear();
            return false;
        }
    });
```

**Comment by adriandmitroca** [comment]
I found the same issue. Have you figured out how to populate your value? I believe that `addOption` and `setValue` methods from API could be a good workaround to solve this issue.

**Comment by joallard** [comment]
Can you try to reduce your example to a minimal example of the library not working right and show that in a Fiddle?

**Comment by CodingPeak** [comment]
@adriandmitroca 
I found that using addOption and setValue do show the value as the selected value, but when submitting the form, the field is being sent as an empty value. Can't figure out why.. :/

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
