### ISSUE TITLE
"allowEmptyOption" doesn't seem to work as expected.

### ISSUE THREAD

**Issue by ADmad** [selectize/selectize.js#1067]
As per the documentation setting `allowEmptyOption` to `true` would cause an option with value `""` (empty string) to be treated as normal option. But that doesn't seem to be the case.

The 3rd examples in `basic.html` has option `None` with value `""` and has  `allowEmptyOption` set to `true` yet `None` is not shown in the options list.

**Comment by joallard** [comment]
I'll have to give you a little tap on the fingers here:
https://github.com/selectize/selectize.js/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+allowemptyoption

**Comment by ADmad** [comment]
@joallard So this is a known bug since quite some time, waiting for someone to submit a fix?

How about updating the documentation in the meanwhile stating that the feature doesn't actually work as documented? That way people don't waste their time.

**Comment by joallard** [comment]
Correct, though it's one of the priority ones. But that sounds reasonable.
