### ISSUE TITLE
onItemRemove is not called on change if an other element was selected before

### ISSUE THREAD

**Issue by ghost** [selectize/selectize.js#1069]
Wouldn't it be consistently that also an onItemRemove event would be carried out, in addition to the onChange event, if an other element was selected before?

In the current state, it is not possible to get the previous selected value from a select box if needed.

Or anybody has a hint for me how I can get it?

**Comment by joallard** [comment]
I'm not sure I follow, can you indicate steps to reproduce?

**Comment by ghost** [comment]
Here is a small code example:
https://jsfiddle.net/rabe69/wezkd5xu/4/

The onItemRemove event is not triggered, if you change the select box from "Foo" to "Bar".
The onItemAdd event on the other hand is triggered correctly.

In my opinion "change" (mostly) means to "remove" one item and "add" another one.

In my case I need the _previous_ selected value on changes as well, to do something with it.

**Comment by jackmarchant** [comment]
@rabe69 I would say this is not a bug but is due to the select element only having change event. 

To get the remove you could potentially listen to the focus event, get the value and use that as the previous value when the change event occurs.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
