### ISSUE TITLE
Customize "create" action when clicked

### ISSUE THREAD

**Issue by coneybeare** [selectize/selectize.js#1074]
I know I can change the appearance of the "Add foobar..." option via `option_create` in `render`, but my use case calls for me to hijack that button for something else outside of selectize.

Basically, I have nested forms which allow the user to select from multiple existing items, but adding requires more data than the input term. Thus, when the user types a term and it is not found via the ajax call, I want the "Add" option to **not** add the term to the list, rather let me call another function or link.

Is this possible?

**Comment by joallard** [comment]
Have you tried looking in the source how the add function works and try to replace the call?

**Comment by coneybeare** [comment]
Of course, but `createItem` is called in a million places, many of which I don't know how to override.

**Comment by joallard** [comment]
Okay. So what you're asking is an enhancement to include a callback or event trigger on item creation, correct?

**Comment by joallard** [comment]
Have you looked at the `item_add` event? -- Edit: `onItemAdd` *

**Comment by coneybeare** [comment]
I wanted to see if there was something I was missing that could help me accomplish what I seek first, but I think you just confirmed there isn't so yes, please file this under feature request.

Ideally, I could pass my own function into selectize or a function name that gets called, with the option of allowing the value to still add to the select, or stop it from happening.

**Comment by coneybeare** [comment]
If I listened to `item_add`, how can I tell the value is the `Add XXX` one vs from the select? Can I still stop selectize from adding the element to the list?

**Comment by joallard** [comment]
Yeah looks like we don't have a stock way to do that right now. Let us know what's the simplest way to do it

**Comment by coneybeare** [comment]
haha well simplest way is for me to place an "Add XXX" button outside of selectize, so I may just go with that.

**Comment by jackmarchant** [comment]
Have you tried using the `create` option?https://github.com/selectize/selectize.js/blob/master/docs/usage.md#options

I believe you can choose to not return the new value object if you'd like to stop that from happening.

**Comment by paulm17** [comment]
This one was pretty easy IMO.

add a setting like:

    elem.selectize({
        ...
        insert: false,
        ...
    });

Find the function 
    
    addItem: function(value, silent) {

Then set whether you want the item to be inserted or not. 

	debounce_events(this, events, function() {
		var $item, $option, $options;
		var self = this;
		var inputMode = self.settings.mode;
		var i, active, value_next, wasFull;
		value = hash_key(value);

		if (self.settings.insert) {	
			if (self.items.indexOf(value) !== -1) {
				if (inputMode === 'single') self.close();
				return;
			}

			if (!self.options.hasOwnProperty(value)) return;
			if (inputMode === 'single') self.clear(silent);
			if (inputMode === 'multi' && self.isFull()) return;

			$item = $(self.render('item', self.options[value]));
			wasFull = self.isFull();
			self.items.splice(self.caretPos, 0, value);
			self.insertAtCaret($item);
			if (!self.isPending || (!wasFull && self.isFull())) {
				self.refreshState();
			}

			if (self.isSetup) {
				$options = self.$dropdown_content.find('[data-selectable]');

				// update menu / remove the option (if this is not one item being added as part of series)
				if (!self.isPending) {
					$option = self.getOption(value);
					value_next = self.getAdjacentOption($option, 1).attr('data-value');
					self.refreshOptions(self.isFocused && inputMode !== 'single');
					if (value_next) {
						self.setActiveOption(self.getOption(value_next));
					}
				}

				// hide the menu if the maximum number of items have been selected or no options are left
				if (!$options.length || self.isFull()) {
					self.close();
				} else {
					self.positionDropdown();
				}

				self.updatePlaceholder();
				self.trigger('item_add', value, $item);
				self.updateOriginalInput({silent: silent});
			}
		}
		else {
			$item = $(self.render('item', self.options[value]));					

			self.updatePlaceholder();
			self.trigger('item_add', value, $item);
			self.updateOriginalInput({silent: silent});
		}
	});

For me, it was a case of just setting $item when I didn't want an insert and using onItemAdd callback to do the logic from then on in.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
