### ISSUE TITLE
It's not possible to perform actions before selectize's events

### ISSUE THREAD

**Issue by Phlegz** [selectize/selectize.js#1082]
I'm trying to perform some actions when user presses Ctrl+Enter but since the Enter key tries to select the selected option, the action would be compromised.

The solution would be to first let other events run rather than calling the default event declared in Selectize. I'd submit a PR regarding this issue.

**Comment by mpourismaiel** [comment]
@physgeekoder I submitted pull request #1083 to fix this issue.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
