### ISSUE TITLE
Freeze on newest version of Chrome with large data set

### ISSUE THREAD

**Issue by anam-hossain** [selectize/selectize.js#1084]
Google Chrome for Mac
Version 51.0.2704.84 (64-bit)

First try demo in Firefox or Safari, it will load faster but Chrome will be unresponsive for long time.

Demo:
http://codepen.io/anon/pen/VjjzNe

Update:
Some of our customers reported that their Samsung mobile browser also freezes.

**Comment by claytoncarmo** [comment]
I'm having the same issue. To solve, instead of create the html options, I fetched all options in javascript (ajax in my case), instantiate selectize in the empty select and insert again using addOption.

**Comment by lucaswiman** [comment]
This [JIT bug in V8](https://www.reddit.com/r/javascript/comments/4oxtgk/javascript_developers_be_warned_about_this_crazy/) may be related. The version numbers approximately line up. I could see this sort of bug causing an infinite loop for some code.

**Comment by lucaswiman** [comment]
FWIW, the demo example seems to be working correctly on the latest Chrome Canary

**Comment by anam-hossain** [comment]
@lucaswiman Chrome Canary is for the developers. Hopefully the next stable release will fix the issue.

**Comment by joallard** [comment]
Did you find out if: (1) something is broken in Selectize we need to fix?, (2) a performance tweak can be made to Selectize?

**Comment by anam-hossain** [comment]
@joallard I am not sure what caused this. It may be something changes in Chrome V8 engine. However, I have tested same example with <a href="https://select2.github.io/">Select2</a>, its loading faster.

http://codepen.io/anon/pen/zBoJRp

In addition to that, Select2 running much faster in Firefox and Safari compared to Selectize.js.

**Comment by joallard** [comment]
Related to #1105, I opened branch `pr-1105` with a new example to test performance. @anam-hossain, can you tell me (1) if you experience the bug at commit `pr-1105^1`, (2) at `pr-1105`, and (3) if you see anything interesting towards performance? Thanks

**Comment by temistokles** [comment]
Unfortunatelly this still happens with 0.12.4

**Comment by temistokles** [comment]
@joallard The patch pr-1105 indeed does seem to help a lot during the first page load (first load of the list in Chrome, on Windows). But as soon as I hit refresh, the effect is gone and HTML parsing takes forever once again (this therefore seems to be related to JIT).

Without the patch, even the first load takes forever.

The loaded list contains 140k items.

**Comment by temistokles** [comment]
I also found out, the slowness is related to preselecting the item that is far away in the list (if I choose the last item in 140k list to be preselected, the page load will not finish in 10 minutes, if I chose 1st, it usually took 4-10s).

**Comment by joallard** [comment]
Thanks for investigating. I'd be looking forward to a PR with some before-after benchmarks if you can pull it off.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
