### ISSUE TITLE
Handler react to multiple events

### ISSUE THREAD

**Issue by bogdancss** [selectize/selectize.js#1086]
Ability to have multiple events run the same handler:

`selectize.on('event_name1 event_name2', handler);`

**Comment by joallard** [comment]
@b0gd4n Thanks for the report. Can you make a minimal example of what you'd like to do?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
