### ISSUE TITLE
Selectize not playing nicely with components it overlaps e.g. Tablesorter

### ISSUE THREAD

**Issue by paulweb2** [selectize/selectize.js#1087]
If a user selects an item and that item that is ovelapping another component like Tablesorter which is also  listening for a click event then the Selectize click event also fires the click event on the overlapped component.

Is there a way to force Selectize to select items on click rather than mouse down as this seems to stop the issue?

**Comment by joallard** [comment]
Thank you @paulweb2. Can you make a minimal example?

**Comment by paulweb2** [comment]
Run this basic (sorry it's a mess) jsfiddle https://jsfiddle.net/ysqkureL/#&togetherjs=g9P9qqojcx .

Select a an option that overlaps the heading row of the table (tablesorter.js) below. Selecting will also fire a table sort.

I've added a test div (the red thing in between the select and table) that console logs mousedown mouseup and click events. If you select a country that overlaps it, you'll see the issue (I think) is that a mouseup event leaks out from Selectize. Which is only an issue really if something underneath is listening for that event alone (dubious idea think and not standard) but it seems tablesorter is doing it so... or it might just be a bug with that component. But then again maybe if Selectize is using mousedown it too might need to make sure mouseup gets handled like click i.e. it doesn't fire elements underneath?

Thanks

P.

**Comment by paulweb2** [comment]
Closed it by mistake.

**Comment by paulweb2** [comment]
I realise now that this is actually a bug (now fixed in latest version) with TableSorter.js. There's now way for Selectize to stop a mouseup firing once it's closed. Tablesorter was sorting on a mouseup event alone rather than checking for a prior mousedown too.

Thanks.

P.

**Comment by joallard** [comment]
Okay, thanks for documenting! At least if someone else searches for it it'll all be here

**Comment by paulweb2** [comment]
Thanks for the quick support.

P.
