### ISSUE TITLE
selectize.min.js:2 Uncaught TypeError: Cannot read property 'mixin' of undefined

### ISSUE THREAD

**Issue by Rob-Syndic** [selectize/selectize.js#1088]
Chrome throwing this error up on the console. Could be I've done something wrong, but I'm clearly not changing anything as I pull the script from cdnjs.cloudflare.com.

Suggestions?

**Comment by atakangktepe** [comment]
It's problem not repeating when using standalone version. Can you use this https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.1/js/standalone/selectize.js

**Comment by joallard** [comment]
Ahem. Please use the search before filing an issue, this is an easy one. #701
