### ISSUE TITLE
Need to support right to left

### ISSUE THREAD

**Issue by AhmedMozaly** [selectize/selectize.js#109]
a 'direction' option is needed, which should affect the ui elements rendering
I made it work as 'rtl' by just 2 minor changes

1- in the selectize.js file, hideInput method should position the input at (1000) positive value, instead of the current (-1000) negative value 

2- in the selectize.default.css file, inside the css selector (.selectize-control.single .selectize-input:after) you need to change (right: 15px;) to (left: 15px;)

**Comment by joallard** [comment]
I believe that has been fixed? I will close because it's been inactive for more than 2 years. If there is still a problem, please re-open.
