### ISSUE TITLE
0.12.2 is not on bower

### ISSUE THREAD

**Issue by artem-v-shamsutdinov** [selectize/selectize.js#1091]
Just want to make sure you still support the bower disto, which is still pointing to 0.12.1

We are nearing a QA release for our app and IE 11 support is a must.  And we are using bower for dependency management.  Getting the fixed tabbing issue would be a huge win for us. :+1:

**Comment by joallard** [comment]
Thanks for the report. I think it's a matter of moving the pointer on the Bower package to the new repo. What do you think @brianreavis?

**Comment by artem-v-shamsutdinov** [comment]
I think so too.  Are you guys considering doing so in the next two weeks (that's our code-freeze date for production release)?

**Comment by joallard** [comment]
I'd do it right away if I could, but only @brianreavis has the rights to edit the bower package. Pinging again. Otherwise as a workaround I'd suggest using NPM to manage dependencies, our npm pack is up to date.

**Comment by artem-v-shamsutdinov** [comment]
Got it, thank you. I doubt we can pull of moving to npm this close to the release date, so worse come to worst I might fork selectize and publish it to bower under a temporary name :(

**Comment by artem-v-shamsutdinov** [comment]
Guys, FYI, I created a bower package under the name "selectize-0-12-2" with the latest source as of now.

**Comment by dfabreguette** [comment]
+1

**Comment by brianreavis** [comment]
Sorry for the delay everyone. Just unregistered/re-registered selectize. It should work now!

**Comment by joallard** [comment]
Thanks @brianreavis !

**Comment by artem-v-shamsutdinov** [comment]
Thank you! :)
