### ISSUE TITLE
Directly Modifying Options Not Reflected Upon Refresh

### ISSUE THREAD

**Issue by jblacker** [selectize/selectize.js#1095]
I haven't gone deep enough through the codebase to determine if this is intended behavior or a bug.  If you directly modify values of an object stored in the internal options array (not adding/removing), and then call `.refreshOptions()` and/or `.refreshItems()` the displayed value will not change in the dropdown or selected text box part of the control.

This can be reproduced either by modifying a member of an object or replacing the object completely in the options array and then calling a refresh method:

```
//Assume that options objects contain name (display) and id (value) members
var updatedName = $('#updated-name-field).val();
var updatedId = $('#updated-id-field).val();
var selectize = $('#selectized)[0].selectize;
selectize.options[updatedId].name = updatedName;

/* Same behavior is seen doing this as well
 * var updatedOption = selectize.options[updatedId]
 * updatedOption.name = updatedName;
 * selectize.options[updatedId] = updatedOption; */

//The below does not change this behavior either
//selectize.clear(true);
//selectize.addItem(updatedId, true);

selectize.refreshOptions(false);
selectize.refreshItems();
```

I expected this to update the dropdown (and text box if the item(s) is/were selected), however it uses the original value stored in that display field.  This was surprising since I figured it would have re-rendered from the available options.

This is pretty low priority since there's an easy workaround to this, but wanted to add it to the tracker in case it is actually a bug.

Workaround:

```
var selectize = $('#selectized)[0].selectize;
var updatedOption = selectize.options[updatedId];
selectize.removeItem(updatedId, true); //need to do this first to make sure it's done silently
selectize.removeOption(updatedId);
//change members of option as necessary
selectize.addOption([updatedOption]);
selectize.refreshOptions(false);
selectize.addItem(updatedId, true);
//selectize.refreshItems() //does not appear to be necessary
```

**Comment by joallard** [comment]
Good report @jblacker, good point. From memory, this might be due to the item/options rendering being cached. I remember coming across a switch that checks whether the item has a render in cache. Ring a bell?

**Comment by jblacker** [comment]
Last time I was digging through things I recall that the render function definitely checked to see if the item was cached first, so most likely this is the case.

However, I was just looking through the codebase a bit again this morning and noticed a function called [`updateOption()`](https://github.com/selectize/selectize.js/blob/master/src/selectize.js#L1252).  ~~This isn't documented anywhere, and never appears to be called by any other functions internally~~.  It appears that this actually has functionality to invalidate the cache for the specific item that's being updated.  I'm going to do some testing and find out if this performs the behavior that I was originally expecting when directly updating an object in options array.  If that's the case I'll just submit a pull request updating the API documentation, otherwise the refresh functions may need updating.

**EDIT**:  I'm an idiot.  This is certainly in the documentation, but apparently I don't know how to read.  I'm not sure if this should be considered a bug a this point since it appears that @brianreavis never intended for users to directly manipulate the internal options array.

**Comment by jblacker** [comment]
Ok, I did a bunch of testing of the `updateOption()` function and it looks like it's behavior is exactly what my workaround does, but in a more efficient manner.  It appears that @brianreavis never intended for users to directly manipulate the internal options array due to the caching mechanisms, which makes sense.  

I'll submit a pull request updating the API documentation later today or tomorrow.

**Comment by joallard** [comment]
Hahaha stuff like that happens. Looks like the API could be snuffed up a little on that side. I will close this, and if you want to open another ticket about refactoring/adding methods to the API, you'd be most welcome to.
