### ISSUE TITLE
Allow refreshItems to be performed silently

### ISSUE THREAD

**Issue by jblacker** [selectize/selectize.js#1096]
**Enhancement request**  

It appears that calling `refreshItems()` causes a change event to be fired as I've learned while debugging.  If would be great if this could be performed silently similar to the other api functions that manipulate the selected items.  This would be nice to have when updating underlying options.  (Originally found when performing debugging that lead to issue #1095)

**Comment by joallard** [comment]
I agree that firing `change` is unexpected. Thanks for the report.

**Comment by egracens** [comment]
Temporary we can use next snippet if we want to rerender items without fire `change` event.
```
var items = selectize.items;
selectize.clear(true); //silently clear
selectize.addItems(items, true); //silently add items
```

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
