### ISSUE TITLE
Reload dynamically added options

### ISSUE THREAD

**Issue by emilkarl** [selectize/selectize.js#1097]
Welcome to the Selectize bug tracker. Thank you for taking the time to
make Selectize a better library!

Please keep in mind this repository has an important issue backlog and
that maintainers have limited time to fix issues, triage, and understand
them.

If you've never done so, please read the
[guide to reporting issues](https://github.com/selectize/selectize.js/wiki/Reporting-issues-guide)
in the Wiki to help us better understand your issue. Here's the gist:
- Search for if your issue has already been submitted
- Make sure you're reporting something precise that needs to be fixed
- Give your issue a descriptive and concise title
- Create a _minimal_ working example
- Indicate the steps to reproduce and result
- Use proper formatting, especially for code
- Help it be solved by finding the cause and proposing fixes

Thank you for reading this! You can now erase everything up to the
following dashes, and then complete what's after.

---

[replace me with a short description of issue]

Steps to reproduce:

1.
2.
3.

Expected result:

Actual result:

[you can add explanations here of the context/what you were trying to
do, and if you have findings about what the cause might be]

**Comment by lazaronixon** [comment]
Same problem here.
select with create: true, after submit is not selected
