### ISSUE TITLE
Highlight only works for the first typed letter

### ISSUE THREAD

**Issue by skimi** [selectize/selectize.js#1098]
The highlight only highlights the first or first and second letterz (if you are fast) of the input text.
Afterward anything you type is ignored.

Also, if you copy paste a string in the input it will be highlighted completely but will ignore anything you type after that string.
This must be related to some kind of timing issue.

![highlight](https://cloud.githubusercontent.com/assets/10855180/16522751/e26e3260-3f9f-11e6-8f47-b2a655a85971.png)

**Steps to reproduce:**
1. On http://selectize.github.io/selectize.js/ Email Contacts example
2. Type "brian"
3. Only "b" or "br" is highlighted

**Expected result:**
Brian should be highlighted in both the email and the name

**Actual result:**
Only "b" or "br" is highlighted

**Might be related:**
The highlight `<span class="highlight">` gets wrapped inside other `<span class="highlight">` at each new highlight instead of resetting the string.

**Comment by skimi** [comment]
Ok, I've debugged a bit more.

The bug is due to the way the highlight function splits the string to insert the `<span class="highlight">`. After the split, every letter is on its own line and is considered a full word by the function.

In [newer version of the highlight function](http://johannburkard.de/blog/programming/javascript/highlight-javascript-text-higlighting-jquery-plugin.html) they have added a removeHighlight() function that solves the problem by reverting all highlighted strings to their original state.

I would simply update the highlight script to the last version but the last version has changed it's matching system and it does not pass the js strict mode so it can't be commited as is into selectize repo.

Anyway I've made a minimal commit where I've just updated selectize version to include their removeHighlight() and edited it to pass strict mode.

**Comment by 0xbaigorria** [comment]
Hey guys!

I bet this is already fixed since Jonathan closed it, but I wanted to add to what Skimi pointed out, that a second issue is that since highlights don't get cleared, you end up with multiple `<span>`s wrapping the same or different highlighted letters. Check screenshot.

![selectizehighlightbug](https://cloud.githubusercontent.com/assets/4060852/17036556/26fe78e0-4f63-11e6-89b3-7557cb436bf3.png)

_I'm using Safari Version 9.1.2 (11601.7.7) on OS X 10.11.6 (15G31)._

**Comment by skimi** [comment]
Yep it'll be fixed in 0.12.3. Previous highlights will always get cleared before new ones are added.

**Comment by Larivact** [comment]
When will 0.12.3 be released? It's annoying to download the latest release only to figure out that the highlighting is completely broken. And now so for over a month, despite a fix existing for 26 days.

**Comment by joallard** [comment]
@Larivact If you need master bugfixes, then use master. Else the new release will come soon.

**Comment by imolorhe** [comment]
@joallard would I get the fix if I download the code in the master branch?

**Comment by joallard** [comment]
@imolorhe correct!

**Comment by imolorhe** [comment]
Yeah I figured it out later. I had to build it to get the changes. The
changes aren't already built into the dist folder in the master branch.

**Comment by Wardrop** [comment]
@skimi  This ought to be re-opened. I've just built from master and the highlighting is still buggy. If you type something, and then backspace it, the highlighting for the first letter remains until you type something else.

**Comment by skimi** [comment]
@Wardrop Yep, you are correct. When clearing the input the last highlight remains present.
Though, for the sake of clarity, could you create a new issue?

**Comment by joallard** [comment]
+1 @skimi @Wardrop Open a new issue and we'll try to get it sorted before 0.12.3
