### ISSUE TITLE
Disable text input on a vanilla select

### ISSUE THREAD

**Issue by arathael** [selectize/selectize.js#110]
Is there any configuration option to explicitly disable text input on the control?

I mean, not to disable the dropdown, but just disable keyboard input (and the caret blinking), something like the readonly attr for the generated text input maybe?

**Comment by tltowles** [comment]
@styledev Thank you!

**Comment by tltowles** [comment]
@efreibe Thank you!

**Comment by djchar89** [comment]
You can disable pointer for the "selectize-control" div. 

example:
$('.selectize-control').css('pointer-events', 'none');

**Comment by harpreetsb** [comment]
Incase this helps

``` javascript
/**
 * triggerSelect
 * @param className
 */

function triggerSelect(className, sort, search, addnew) {
    if (typeof(addnew) == "undefined") {
        addnew = false;
    }

    if (typeof(search) == "undefined") {
        search = false;
    }

    if (sort == true) {
        $(className).selectize({
            create: addnew,
            sortField:'text',
            closeAfterSelect: true
        });
    }
    else{ // get rid of alphabetic ordering
        $(className).selectize({
            create: addnew,
            closeAfterSelect: true
        });
    }

    if (search == false) { // remove input if required
        $(className).siblings('.selectize-control').children('.selectize-input').children('input').attr('disabled', true);
    }
}
```

**Comment by AndreaCatania** [comment]
Have you found a solution? as "styledev" said the input is very very bad on mobile phone.... it's a good library and add 1 option to disable inputbox is very useful for all...

If you add option readOnly where if true the system add the attribute readonly to input element "'<input type="text" autocomplete="off" />'" at line https://github.com/brianreavis/selectize.js/blob/master/src/selectize.js#L124 it's easy.

---

## EDIT 1

### Fast implementation fix

To fast add this features i've changed this line of code:

`$control_input    = $('<input type="text" autocomplete="off" />').appendTo($control).attr('tabindex', $input.is(':disabled') ? '-1' : self.tabIndex);`

WITH

`$control_input    = $('<input type="text" autocomplete="off" />').appendTo($control).attr('readonly',typeof q.attr("data-selectize-readonly")!=='undefined'?true:false).attr('tabindex', $input.is(':disabled') ? '-1' : self.tabIndex);`

now by setting "**data-selectize-readonly**" on the input you will have the input in readonly state.

---

## EDIT 2

~~https://github.com/brianreavis/selectize.js/pull/803~~ #803

**Comment by zeeberry** [comment]
Hopefully your PR gets accepted @AndreaCatania. In the mean time I'm using this:

``` javascript
$('select').selectize({
    onFocus: function() {
        var input = 'selectize-input input',
              wrapper = 'selectize-input';
        $('.' + input).attr('readonly', true);
        $('.' + input + ', .' + wrapper).css('cursor', 'pointer');
     }
  });
```

**Comment by PawelGIX** [comment]
+1

**Comment by yavuzm** [comment]
@efreibe Helal lan sana , Thanks :)

**Comment by saysource** [comment]
My solution was to write a simple plugin:

``` javascript
Selectize.define('hidden_textfield', function(options) {
        var self = this;
        this.showInput = function() {
             this.$control.css({cursor: 'pointer'});
             this.$control_input.css({opacity: 0, position: 'relative', left: self.rtl ? 10000 : -10000 });
             this.isInputHidden = false;
         };

         this.setup_original = this.setup;

         this.setup = function() {
              self.setup_original();
              this.$control_input.prop("disabled","disabled");
         }
});
```

Then use it this way:

``` javascript
$('select').selectize({
            plugins: ['hidden_textfield']
        });
```

**Comment by joallard** [comment]
This looks like this is within scope for the project, and should be feasible. I'll look all of this over.

**Comment by ghost** [comment]
Didn't read every comment, but here's how I did it.

JS to disable the text input:

```
$('.selectize-control.single .selectize-input, .selectize-control.single .selectize-input input').attr('disabled', 'disabled');
```

CSS to keep mouse pointer at every part of the selectize:

```
.selectize-control * {
        cursor: pointer;
    }
```

**Comment by cyphix333** [comment]
Urgh........ been using select2 but then found my way over to selectize because it does something I need that select2 doesn't and now I find out selectize doesn't even offer a vanilla dropdown option...... soooo annoying!

**Comment by ghost** [comment]
@cyphix333 it does, my app is full of these, you just need to configure it to behave like that.

**Comment by cyphix333** [comment]
@aledmb It seems you have to implement your own hacky solution to achieve this, this concerns me as I worry it will not behave the way it is supposed to.

**Comment by ghost** [comment]
what are you worried about? maybe we can help you.

if you just need to disable the input, it's a simple jQuery `attr()` call. ;)

**Comment by cyphix333** [comment]
I worry that a hacky solution can lead to unpredictable things happening under certain situations. ;)

**Comment by joallard** [comment]
@cyphix333  Yep, this can be kinda annoying, but I'm afraid we'll be stuck with it for some time as development is going at snail's pace. If you'd like to sponsor the development, not expecting this but on the off-chance, let me know. (I'm out of work right now so most of my time is spent trying to find work, and not towards Selectize development, unfortunately)

**Comment by cyphix333** [comment]
@joallard No worries. At this point not in a massive need for it, but would like to get it out of the way; if I don't find another reliable solution then I can look at this possibility further. :)

**Comment by stSaHiB** [comment]
disabling the input is a poor solution. It prevents the select from getting focus. also you can't select a value out of the dropdown, with keyboard.
As many users mentioned before, i really dont understand, why such a basic option like a simple vanilla dropdown is missing. Using some other decorator script is really no good option. It means having 

- more code
- more issues
- having to style 2 scripts, so that the dropdowns all look the same
- learning 2 api...
- updating 2 scripts in your projects

@brianreavis: no it's not out of scope of this project. you can already do so many things with selectize, so why not add this basic feature?

**Comment by joallard** [comment]
> As many users mentioned before, i really dont understand, why such a basic option like a simple vanilla dropdown is missing.

Because no one implemented it.

> no it's not out of scope of this project. you can already do so many things with selectize, so why not add this basic feature?

That's not your call to make. But also, I made that decision when I re-opened the issue.

You want it to be implemented? Make a high-quality pull request for it. But please watch your tone, it's namely comments like this that make maintainers like me abandon the project and it ending up going at a snail's pace.

**Comment by pelenthium** [comment]
Guys, there is can help you to use selectize.js as select : 
First of all: hidden_textfield - nice plugin but has some issues when input was disabled (as example for required fields, it does not work), but you can set easy styles to hide blinking cursor
this.$control_input.css({color: 'transparent', cursor:'pointer'});
and now you don't have any reason to disable input

**Comment by depeele** [comment]
Tagging off @zeeberry , I hooked `onInitialize` instead of `onFocus`:
```javascript
$('select').selectize({
    onInitialize: function() {
        this.$control_input.attr('readonly', true);
     }
  });

**Comment by pelenthium** [comment]
@depeele 
but you have a problem when select field is required - the browser will send this field without validation

be careful

**Comment by whattafack** [comment]
@joallard please see PR https://github.com/selectize/selectize.js/pull/1419
I made an enhancement PR to solve this.

Thanks!

**Comment by rodrigoguariento** [comment]
> Is there any configuration option to explicitly disable text input on the control?
> 
> I mean, not to disable the dropdown, but just disable keyboard input (and the caret blinking), something like the readonly attr for the generated text input maybe?

Readonly in selectize is a call to "lock" method. Eg.:

`$('#yourElement')[0].selectize.lock();`

Dynamically is possible to unlock too:

`$('#yourElement')[0].selectize.unlock();`

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.

**Comment by eduardo-mior** [comment]
With a little bit of CSS and a little bit of JS we can create this. And it looks perfect.

```javascript
var select = $("#my-select-input");
$(select).next().find("div.selectize-input").addClass("no-searchable"); // Adding style to the div
$(select).next().find("div.selectize-input > input").addClass("no-searchable"); // Adding style to the input
$(select).next().find("div.selectize-input > input").prop("readonly", true); // Setting the input to read-only
$(select).next().find("div.selectize-input > input").prop("inputmode", "none"); // Ensuring that the keyboard will not open on mobile
$(select).next().find("div.selectize-input > input").focus(function () { // Hack for when the search input gets the focus it will automatically blur.
    $(this).blur();
});
```
```css
.no-searchable {
    cursor: pointer !important;
    background-color: #FFFFFF !important;
}
.has-items input.no-searchable {
    width: 1px !important;
}
```
