### ISSUE TITLE
Should we fire focus on right-click?

### ISSUE THREAD

**Issue by joallard** [selectize/selectize.js#1100]
Been doing some development recently, needing to inspect stuff by right-clicking and selecting 'Inspect element'. Then, surprise surprise, Selectize opens even if it's right-clicked to be inspected. 

I went to the Selectize source, expecting in `onMouseDown` to see something like

``` js
if (!(e.button !== 0) return;
```

but nope. I then ran a short search for 'right-click' in the issue list, there's nothing titled so. Strange things.

Does it bother anyone else than me?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
