### ISSUE TITLE
Message for remote data with no result

### ISSUE THREAD

**Issue by jayrosen1576** [selectize/selectize.js#1101]
When sourcing data from a remote source, and no results are returned, there does not seem to be a way to elegantly display that there were no matches to the user. Am I missing something or is this not a current feature? If not, then it would be greatly appreciated if a customizable message indicating no matches could be generated. This is for drop downs that do not allow a user to add options if not found.

**Comment by joallard** [comment]
https://github.com/selectize/selectize.js/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20no%20found

Closing for #470
