### ISSUE TITLE
multiClose function closes parent modal

### ISSUE THREAD

**Issue by sspread** [selectize/selectize.js#1102]
I'm using selectize for a 'tagging' feature within a Foundation Reveal modal. When I click the the close button on the 'tag', the modal closes. The issue has something to do with event propagation, and can be fixed by adding `return false;` to the click handler callback within the multiClose setup function.

This is a duplicate of issue https://github.com/selectize/selectize.js/issues/870

**Comment by joallard** [comment]
Okay... since it is a duplicate, we should therefore close it?

**Comment by sspread** [comment]
It would make sense to close one of them. I figured it  was forgotten, and
likely a quick-ish fix, so I wanted to reraise it.

**Comment by joallard** [comment]
Okay, well, that's not exactly useful. What would be useful would be suggesting a well-thought out solution/changes to the code. You can do that on the original issue.
