### ISSUE TITLE
Restore after backspace + escape

### ISSUE THREAD

**Issue by achapela** [selectize/selectize.js#1103]
Hello, 
Great tool. How could I restore to previous selected value when canBeEmpty=false and you backspace the selected one. 

Steps to reproduce:

1.Click on control.
2.Backspace all the way
3.Leave control.

Expected result:
If allowEmptyValue = false the value should return to previously selected value.

Actual result:
The control is empty/.

Thanks for the help.

**Comment by Swennet** [comment]
Same issue. Has this since been fixed?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
