### ISSUE TITLE
Replace values in single-item selection

### ISSUE THREAD

**Issue by nuno-agostinho** [selectize/selectize.js#1104]
Selectize.js is great even for single-item selection. The problem is that after the user has selected the item, s/he needs to delete the selected item and start typing to search from the beginning. I think it would be more intuitive if the "deletion" step wasn't needed.

Steps to reproduce:
1. Click selectize input box
2. Type a few letters

Expected result: Delete the selected item and search the available items.

Actual result: Nothing happens, since step 2 is actually "delete selected item" and only step 3 is "type a few letters"

**Comment by joallard** [comment]
Related to #110

**Comment by JacobEvelyn** [comment]
Note that [Select2](https://select2.github.io/examples.html) behaves this way, to see a concrete example.

**Comment by bettysteger** [comment]
Also related to https://github.com/selectize/selectize.js/issues/996

**Comment by javvkenn** [comment]
This solution might be late but it might be of help to someone. This will reopen the textbox for edit and select all the text when the use focuses on the element.

`var select = $('select[name=\"$name\"]').selectize({});
var selectizeControl = select[0].selectize
    selectizeControl.on('focus', function() {
            var value = selectizeControl.getItem(selectizeControl.getValue()).text();
            selectizeControl.clear(); //remove selected item
            selectizeControl.setTextboxValue(value); //re-populate search input
            $('input[type=select-one]').select();
      });`
