### ISSUE TITLE
Text overflow when long text string option is selected

### ISSUE THREAD

**Issue by 0xbaigorria** [selectize/selectize.js#1113]
Hi. I'm having trouble fixing this edge-case with a CSS only approach. Unfortunately I'm not a JavaScript developer, and I can't come up with an interesting JS solution either.

To reproduce the issue, grab any demo and add a very long text string option and then select it. This should happen when the option is selected and when you attempt to select another option after selecting the long option:

![selectize 1](https://cloud.githubusercontent.com/assets/4060852/17037283/7cf3b9e2-4f66-11e6-8ac8-c221b98443a9.png)

![selectize 2](https://cloud.githubusercontent.com/assets/4060852/17037284/7d2991f2-4f66-11e6-8b2b-2b7c3fa3a060.png)

I tried fixing it with CSS by using:

```
.selectize-input {
  .item {
    display: block;
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
  }

  &.focus {
    .item {
      display: -moz-inline-stack;
      display: inline-block;
    }
  }
}
```

But of course, this didn't work, because when using `display: block;` and attempting to reselect an option, the select breaks (check screenshots), as it needs to be inline-block.

![selectize 3](https://cloud.githubusercontent.com/assets/4060852/17037394/28ac83f4-4f67-11e6-930b-a29c7242d190.png)

![selectize 4](https://cloud.githubusercontent.com/assets/4060852/17037395/28e1a354-4f67-11e6-8f94-0a051d34900d.png)

I think a nice temporary solution for this, would be, that when you expect to get overflowing content, add an option to remove selected option on re-select. Maybe not the best UX, but definitely avoids this breaking issue, which is even worst.

Hope this helps, and let me know if I can be of any further help.

_I'm using Safari Version 9.1.2 (11601.7.7) on OS X 10.11.6 (15G31)._

**Comment by xewl** [comment]
And what if you make the element `max-width: 99%`?

**Comment by CGB0** [comment]
Here is a fix.   max-width did not work for me but it did solve another problem...  

This could be done as a plug in but I am not jquery expert and so I need to just steal some code from the selectize.js file.  

Put this code somewhere in your code base.   I was unable to directly call these functions in the selectize.  This is due to my lack of knowledge.

```

var measureString = function (str, $parent)
    {
        if (!str)
        {
            return 0;
        }

        var $test = $('<test>').css({
            position: 'absolute',
            top: -99999,
            left: -99999,
            width: 'auto',
            padding: 0,
            whiteSpace: 'pre'
        }).text(str).appendTo('body');

        transferStyles($parent, $test, [
			'letterSpacing',
			'fontSize',
			'fontFamily',
			'fontWeight',
			'textTransform'
        ]);

        var width = $test.width();
        $test.remove();

        return width;
};

var transferStyles = function ($from, $to, properties)
{
    var i, n, styles = {};
    if (properties)
    {
        for (i = 0, n = properties.length; i < n; i++)
        {
            styles[properties[i]] = $from.css(properties[i]);
        }
    } else
    {
        styles = $from.css();
    }
    $to.css(styles);
};
```
Now you can measure the graphical size of the control and the graphical size of the string and if the string is too long, you can shorten it. 
Here is code to do this.   I have it in render section. 
```

 render: {
     option: function (item, escape)
     {            
        // this code stacks the data one over the other so that the user can see
        //  as much of the name as possible
        return '<div class="option">' +   '<div class="text">' +
            '<span class="name">' + escape(item.CostCode) + '</span>' +                     
             '<p class="description">' + item.Description + '</p>' + 
             '</div>' +   '</div>';
      },
      item: function (_item, _escape)
      {
          // once the user has selected the item I want to concatenate them 
          // but if they are too large they are painted through the dropdown arrow
          // and shifted left...   
          // trick is to shorten them and add an ellipsis to show it is shortened.  
          var _desired_percent = .75;
             //  get the desired string.
          var _label_string  = _item.CostCode + ' : ' + _item.Description;
          var _label_length = _label_string.length;
          var _$outer = this.$control.find('.item-wrap-outer');
          var _$inner = _$outer.find('.item-wrap-inner');
          var  _labelWidth = measureString( _label_string, _$inner);  // get the graphical length
          var _controlWidth = this.$control.width();          // get the graphical length
           // what is the relative percentage length of the  string with regards to the control
           var _percent = _labelWidth / _controlWidth  ;   
                        
           // decide if we need to do anyting
           if (_percent > _desired_percent)
           {
               // gives you a number like .75 or .80 or somehing
               //  depends on the value of  _desired_percent 
               var newpercent = 1 - (_percent - _desired_percent); 
               var _newlength = Math.floor(_label_length * newpercent);  // gives you a char count. 
               // shorten the string
               _label_string = _label_string.substring(0, _newlength);

                 //  add the dots so the user knows this is shortended
                _label_string = _label_string + ' ...';
             }
             return '<div>'  + _label_string   + '</div>';
       }
 }
```

Hopefully someone finds this useful.

Cheers 

Colin

**Comment by kalavhan** [comment]
In case someone is having the same problem i fixed it with some minor changes on the css and js, this may not be the greatest fix but at least it worked for me.
in the js file on line 1263:
`$control          = $('<div>').addClass(settings.inputClass).addClass('items').appendTo($wrapper);`
i changed it to:
`$control          = $('<div>').addClass(settings.inputClass).addClass('items').addClass('textOverflowSP').appendTo($wrapper);`
and i added this two css classes:
.item{
  text-overflow: ellipsis;
  white-space: nowrap;
  overflow: hidden;
}

.textOverflowSP{
  overflow: hidden !important;
}
is not the best approaching but it helped me.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
