### ISSUE TITLE
Lower border of the input tags sometimes disappears

### ISSUE THREAD

**Issue by nbro** [selectize/selectize.js#1118]
I've asked this question first on SO, so you can simply read it from there:

> http://stackoverflow.com/questions/38629843/why-does-part-of-the-lower-border-of-the-input-tags-sometimes-disappears

**Comment by joallard** [comment]
Are you able to remake an example of it happening, even if only sometimes?

**Comment by nbro** [comment]
@joallard No, I still didn't understand in which circumstances it's happening...

**Comment by joallard** [comment]
I get that this is an intermittent bug. Still, try to come up with the most minimal example of it happening, starting from your case and removing as much stuff as you can. My approach is, given I'm in Git, to start deleting stuff, reloading a few times to see if it still does it, and deleting until you're left with nothing but the input and the code that goes with it. Assuming you've already tried breaking out the inspector and trying to figure out what's wrong directly, that is. (Toggling CSS rules might be a good pointer here)

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
