### ISSUE TITLE
Prevent the selector to be empty

### ISSUE THREAD

**Issue by danielesalvatore** [selectize/selectize.js#1120]
Good morning,

I would like to prevent the selector to be empty. I would like the selector to behave like an HTML select that have a default value. If i render a selectize with a default value is always possible to remove it and show the placeholder message.

I checked the documentation and i cannot find the proper configuration. 

Thank you very much for your support.

**Comment by joallard** [comment]
Please follow the issue guide when reporting issues, as said in the placeholder text when you created this issue.
