### ISSUE TITLE
Trigger change being called twice

### ISSUE THREAD

**Issue by xxRockOnxx** [selectize/selectize.js#1123]
So, I have a select that is required. Upon removing the selected option which is by pressing backspace on the input, seems like the onChange or whatever that event that handles it calls the trigger change on the original select element.

Next, when you click anywhere which can trigger an onBlur event, the error class (of Bootstrap) will be removed.

If I added a trigger change on the onBlur event, the effect is kinda crazy. Just try these steps:
- Make a required select element.
- Select an option
- Press backspace to clear the input
- Supposed to be form-group should have an has-error class.
- Click anywhere outside that will blur the input.
- has-error class is now removed and no more red text.

Add trigger('change') on the select element upon onBlur and the result will be:
- Make a required select element.
- Select an option
- Press backspace to clear the input
- Supposed to be form-group should have an has-error class.
- Click anywhere outside that will blur the input.
- has-error class is now removed and no more red text.
- onBlur will be triggered. the $(selector).trigger('change') will be triggered
- has-error class again.

How do I fix this? Am I missing something, making something wrong, or it's the plugin itself?

I am expecting it to retain its state even after clicking outside.

I think something like this would fix it:

On any event that can trigger a change on the input, there is a variable that holds the state if the input has error or not.

Upon onBlur check if there is an error and then retain the state? I dunno. Rough guess. My mind's crowded right now as the docs is a bit unclear.

And for the meantime:

How do I get the input of a select produced by selectized? Any method that can return it?  I guess, I'll just add it to the validator I am using (1000hz)

---

I did:
- [x] Search for if your issue has already been submitted
- [X] Make sure you're reporting something precise that needs to be fixed
- [X] Give your issue a descriptive and concise title

**Comment by xxRockOnxx** [comment]
For the meantime, I currently do this:

$(selector).closest('div').find('.selectize-input input').first().prop('required', true).attr('data-validate', true);

Hope there's a method that would return the text input element of a select that is being "selectize" to access it easily.

This way it doesn't do the error, no error-class, error.

This is just a very rough workaround.

```
var $select = $(selector").selectize({
             placeholder: 'Select one patient (required)',
             onFocus: function (){
                  $("selector).closest('div').find('.selectize-input input').first().prop('required', true).attr('data-validate', true);
             },
             onBlur: function(){
                 $(selector).trigger('change');
                 $(selector).closest('div').find('.selectize-input input').first().prop('required', false).attr('data-validate', false);
             },
         });
```

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
