### ISSUE TITLE
Documentation Request: Nested Properties

### ISSUE THREAD

**Issue by ashireman** [selectize/selectize.js#1124]
Looking at current documentation it notes that sifter.js has the ability to filter results based on nested properties. Looking at docs for both selectize and sifter doesn't give a clear indication of how to do so. If the values you are looking for are not in the top level search fields then no results will be displayed. However, doing a blur/focus on a selectize element will display the results. 

While I have tried a few different methods I can't find any way to tell selectize which nested fields to look in. If some information can be provided on how to do so, I can help and contribute the basic docs/examples.

**Comment by joallard** [comment]
To be honest, I don't know any more than you do. The best way is probably to break out the debugger, see how it works and report back.

**Comment by ashireman** [comment]
Added PR #1126 to allow searching subfields. Take a look and see what you think. Whichever config format you prefer I can tailor the config to work that way. Once it's how you'd like it I can add either more commits or a separate PR for documentation/examples.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
