### ISSUE TITLE
Backspace not fired when cursor after item in Chrome for Android

### ISSUE THREAD

**Issue by waddlesplash** [selectize/selectize.js#113]
(@joallard edit: 0. Use Google stock keyboard)
1. Go to http://brianreavis.github.io/selectize.js/ in Chrome for Android.
2. Attempt to backspace in the first example -- it won't work. Firefox for Android works as expected with backspace.

This happens for me on:
Android 4.3, Nexus 7 (build `JWR66Y`), Chrome 29 [latest stable].

If you need any more info, please let me know.

**Comment by bratanon** [comment]
Im still having this issue.

**Comment by rasmuscnielsen** [comment]
Just updated to 6.01 on Sony Xperia, and I'm also still experiencing the issue.

**Comment by joallard** [comment]
I see the need, but that's not an easy one. Anyone has a reasonable solution?

**Comment by rasmuscnielsen** [comment]
@joallard I made this workaround on the angular-selectize directive: https://github.com/machineboy2045/angular-selectize/pull/139

It allows for an easy way to add a special 'clear option' in the dropdown itself. When selected, it will clear the input.
For the directive, the name of the option is added as an attribute, so for instance it can be 
`<input type='text' selectize options='[]' clear-option='Any'>`

I guess a possibility like this in the selectize library itself would not only solve the problem, but be a nice feature?

![skaermbillede 2016-06-09 kl 21 53 57](https://cloud.githubusercontent.com/assets/8465957/15944266/1ac48f16-2e8d-11e6-92ab-39d77fd63bd4.png)

**Comment by joallard** [comment]
Seeing [chromium#118639](https://bugs.chromium.org/p/chromium/issues/detail?id=118639) was closed as `wontfix` in Google's _infinite wisdom_...

@rasmuscnielsen I'm sorry, I'll have to disagree with the UX here. What I could see as viable workarounds however, is that one use the RemoveButton plugin, or have a `X` on the right side of the field.

**Comment by joallard** [comment]
I've fooled around on https://w3c.github.io/uievents/tools/key-event-viewer.html a bit to see what we could do for an ugly workaround.

Here's the event log of what happened:

```
# 1. Click field, type X

- keydown 229, value ''
- input, 'X'
- keyup 229, 'X'

# 2. Type 'Y'

- keydown 229, 'X'
- input, 'XY'
- keyup 229, 'XY'

# 3. Backspace Y

- input, 'X'
- keydown 229 'X'
- keyup 229 'X'

# 4. Backspace X

- input, ''
- keydown 229 ''
- keyup 229 ''

# 5. Backspace when empty (*)

- keydown 229 ''
- keyup 229 ''
```

Seems that the one backspace we want is the one that has no input event, and keyup and keydown.

We could work around that, say that if you're on Chrome Android, and the input value was empty, you down 229 and it is still empty, that's a backspace. We could also wait until they release compositionstart and work with that.

**Comment by doydoydoy** [comment]
I'm currently having this issue using Google Keyboard and Huawei Sywpe Keyboard.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.

**Comment by joshuabach** [comment]
This issue is still occuring on Firefox for Android 106.1.0 (Android 10).

My workaround (insipred by @andreapavon) is

```js
onType: function(text) {
    if (text.length <= 1) {
         this.clear();
    }
}
```

Which simply clears the control once the user starts typing. Works well enough for me.
