### ISSUE TITLE
Can't enter 'ą' character in tags mode

### ISSUE THREAD

**Issue by PawelGIX** [selectize/selectize.js#1132]
Try input word that contains "ą" letter.
Keyboard Shortcut: Alt + A

![ktokmt61eq](https://cloud.githubusercontent.com/assets/391153/17599200/3b97b266-5ffe-11e6-9b90-3c483b18ae15.gif)

http://selectize.github.io/selectize.js/#demo-tagging

Solution: http://stackoverflow.com/a/18570096
Disable "Select All" on  Alt Gr key

```
if (event.ctrlKey && event.altKey) {
    // Appears to be Alt Gr
}
```

**Comment by joallard** [comment]
@PawelGIX always provide an STR, even though gifs are nice! The checklist is not a decoration.

### ~~STR~~
1. Using latest master `0316d24`, in local mode go to `examples/basic.html`[^1], Tagging demo
2. Enter 'a'
3. Copy `ą` character (u+0105: latin small letter a with ogonek)
4. ~~Paste char into input right after 'a', leaving 'aą'~~
5. Type 'a' again
6. => Text input disappears, inconsistent state

Expected: input shows 'aąa' with prompt, consistent state.

[^1]: Alternatively, 0.12.2 demo page can be used, but we won't be able to paste the u+105 character since it's not available on English keyboard.

**Comment by joallard** [comment]
Crap, the fact that I'm pasting triggers the case in my STR.

**Comment by joallard** [comment]
@PawelGIX what is your STR, is it different? Here's what I'm doing:
1. Using Tagging demo online
2. Click input, type 'rząd' (using Polish keyboard layout on OSX)
3. Press 'Enter'
4. => Tag 'rząd' is added to input, as expected.

**Comment by PawelGIX** [comment]
On my setup (Win 10 + Latest Chrome)
the keyboard shortcut "ą" "RIGHT ALT + A" triggers [self.selectAll();](https://github.com/selectize/selectize.js/blob/master/src/selectize.js#L469)
[All because the KeyboardEvent e.ctrlKey && e.altKey both are true](http://stackoverflow.com/a/18570096).

This simple change solved the problem for me:

```
switch (e.keyCode) {
KEY_ case:
if (self.isCmdDown && !e.altKey) {
self.selectAll ();
return;
}
break;
```

**Comment by joallard** [comment]
Ah! We were missing the Windows part. I get it now.

**Comment by joallard** [comment]
Interesting related bug per my STR above, is that the `isCmdDown` flag isn't cleared by the time I type the second stroke `a`, and triggers pretty much the same behavior. I'll see what's up.

**Comment by joallard** [comment]
@PawelGIX, could you do me a solid, go to https://w3c.github.io/uievents/tools/key-event-viewer.html, focus the input, tap each of <kbd>AltGr</kbd> <kbd>Left Alt</kbd> <kbd>Ctrl</kbd> once and screen me the result? I'm trying to understand the whole Cmd-Alt-Ctrl-AltGr model

_Edit_ For posterity, here are the results on Mac, <kbd>Cmd</kbd> being mapped to `Meta`
![Modifiers and keyboard codes on Mac](https://cloud.githubusercontent.com/assets/949482/17602006/bc7b6038-5fd8-11e6-98ba-a56ca5f55918.png)
(keydowns 9 and 10 is me taking a screenshot, _pris en flagrant délit_)

**Comment by PawelGIX** [comment]
# **RightAlt + A**

![keyboard event viewer](https://cloud.githubusercontent.com/assets/391153/17603772/fcca458e-6012-11e6-85f6-606e85c36648.png)

# **RightAlt**

![right_alt](https://cloud.githubusercontent.com/assets/391153/17603773/fcd01676-6012-11e6-812f-4a4972361346.png)

**Comment by joallard** [comment]
Thanks, interesting. In that second case you were holding `AltGr`?

**Comment by PawelGIX** [comment]
Exactly. It seems that in non-US keyboards  RightAlt/AltGr corresponds to Alt+Ctrl in US keyboards.
https://en.wikipedia.org/wiki/AltGr_key#Control_.2B_Alt_as_a_substitute

**Comment by joallard** [comment]
Interesting. I'll check it out.

**Comment by drmad** [comment]
Hi. FYI the '@' character in (afaik) latinamerican and spanish keyboards uses the AltGr key, so this bug prevents to write email addresses in this otherwise excelent software.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
