### ISSUE TITLE
Sorting manually

### ISSUE THREAD

**Issue by sylido** [selectize/selectize.js#1140]
How can one trigger a re-sort of the options after you programmatically replace all options with `addOption()`. It does add the new option(s) but it doesn't re-sort, it keep the new option at the bottom of the list, searching for something and then clearing it doesn't trigger the sort as well. Doesn't seem to be in the documentation as well, from what I could find online, it seems like most people are trying to do the opposite and disable automatic sorting.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
