### ISSUE TITLE
Highlight deletes characters on match double-up

### ISSUE THREAD

**Issue by Wardrop** [selectize/selectize.js#1142]
Another highlighting related issue in the master branch. This is best explained with an example, included below. With the blow example, if you type "Isabel", everything is good, but when you start typing the "S" for street (i.e. "Isabel S"), the second "S" rematches the with the "s" in "Isabel". If you continue typing the "t" (i.e. "Isabel St"), the "sabel" is deleted. The whole issue seems to be caused by the fact that highlighting is being applied to already matched words, causing this kind of weirdness.

See related issues #1141 and #1098.

``` html
<select id="select-test">
    <option value="">Select a country...</option>
    <option value="AL">Isabel Street</option>
</select>
```

``` javascript
$('#select-test').selectize();
```

**Comment by Wardrop** [comment]
For the moment, for anyone else looking for a work-around, I'm using [mark.js](https://markjs.io/).

``` javascript
$('#selector').selectize({
  // ...
  highlight: false,
  onType: function (value) {
    $(".selectize-dropdown-content").unmark().mark(value, {exclude: ['.exclude']});
  }
  // ...
})
```

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
