### ISSUE TITLE
jQuery is not defined regression in 0.12.3

### ISSUE THREAD

**Issue by Stevebel** [selectize/selectize.js#1144]
After updating from 0.12.2 to 0.12.3, my Angular application started throwing a "jQuery is undefined" error. I tracked it down to the new addition of the jQuery removeHighlight plugin. Most likely an issue for me because the application uses Browserify imports instead of traditionally loading jQuery. I've made a pull request(#1143) to resolve the issue and recommend reverting 0.12.2 for anyone else experiencing this issue.

**Comment by jacobsvante** [comment]
Same here. Thanks for the PR, it worked great.

I can recommend setting up some mocha tests like this to protect you from this type of problem in the future:

``` javascript
assert = require('assert')


describe('Package versions', ->
  describe('jQuery', ->
    # We've previously had problems where jQuery plugins change and don't
    # require jQuery properly anymore. Catch those problems here.
    it('jQuery.fn.zoom should exist after jquery-zoom import', ->
      jQuery = require('jquery')
      require('jquery-zoom')
      assert.notEqual(jQuery.fn.zoom, undefined)
    )
    it('jQuery.fn.selectize should exist after selectize import', ->
      jQuery = require('jquery')
      require('selectize')
      assert.notEqual(jQuery.fn.selectize, undefined)
    )
  )
)
```

**Comment by danielesalvatore** [comment]
+1

**Comment by danielesalvatore** [comment]
Would it be possible to update the `npm` version too?
