### ISSUE TITLE
Change event not always firing on item click

### ISSUE THREAD

**Issue by JacobEvelyn** [selectize/selectize.js#1145]
I did:
- [X] Search for if my issue has already been submitted
- [X] Make sure I'm reporting something precise that needs to be fixed
- [X] Give my issue a descriptive and concise title
- [ ] **[still working on this]** Create a _minimal_ working example on JsFiddle or Codepen
  (or gave a link to a demo on the Selectize docs)
- [ ] **[still working on this]** Indicate _precise_ steps to reproduce in _numbers_ and the result,
    like below

I've tried to create a minimal reproduction case in Codepen but so far haven't been able to reproduce the issue. The problem (see gifs below) is that some Selectize options don't get "selected" when I click on them; no "change" event fires. Note that this happens sporadically and appears to be based on where I click on them. Here's a particularly bad example:

![selectize-onchange](https://cloud.githubusercontent.com/assets/1114569/18139605/3637a114-6f80-11e6-9aea-b85878614ca7.gif)

I suspect it might be related to our use of a custom font and the option spanning multiple lines. See the cursor flickering between `pointer` and `default` here; when it's `default` is when the change event fires as expected:

![selectize-onchange-cursor](https://cloud.githubusercontent.com/assets/1114569/18141128/436d8bea-6f86-11e6-8d38-494bd50a4c5b.gif)

I'll continue working on a minimal reproduction in Codepen but I thought in the meantime it would be good to see if this Issue strikes a chord with either anyone familiar with this codebase (I couldn't even find where the `change` event is called but am happy to dive in with some guidance) or anyone who's seen this before.

Thanks!

**Comment by JacobEvelyn** [comment]
Ah, I figured it out. I had a hover state on a parent DOM node that was setting the opacity to `0.8`, which interferes with click events (http://stackoverflow.com/questions/13846807/why-does-opacity-negate-pointer-events). Maybe this issue will help someone else in the future!

**Comment by joallard** [comment]
Oh wow. Thanks for the report @JacobEvelyn!
