### ISSUE TITLE
How to Communicate between two dropdowns using selectize.js with ReactJS

### ISSUE THREAD

**Issue by surendraGaddam99** [selectize/selectize.js#1146]
Hi ,

As shown in below diagram i have two dropdowns available.

First dropdown : List of schemas
second dropdown : List of tables .

Scenario : 
1)User selects any one schema from the list on first dropdown.
2)list of tables should be displayed in second dropdown based on selected schema from first dropdown.

i.e second dropdown values should be changed based on first dropdown selection.
so if user selects AA360ST1 schema then list of tables to be displayed in second dropdown for this schema.

I am using  React JS with selectize plugin for this scenario.

```
File : TableSearch.jsx

<label htmlFor="tables-input">Schemas</label>       
     <SearchSchemaField id='test' options={options} value='b' labelField='description'
         valueField='code' onChange={dropDownOnChange} placeholder="Select a schema"
  />  

      <label htmlFor="tables-input">Tables</label>
      <SearchInputField
        ref="tableSelectize"
        placeholder="Select a table"
        selectizeOptions={this.tableSelectizeOptions} />
```

tableSelectizeOptions() {  
    return _.extend({}, commonSelectizeOptions, {  
      preload: true,
      render: {
        option: this._renderTableOptions
      },

```
  valueField: 'fqn',
  labelField: 'fqn',

  sortField: [{
    field: 'usages',
    direction: 'desc'
  }],

  searchField: ['fqn', 'tableName', 'schema'],

  plugins: {
    'remove_button': {},

    'header': {
      headers: ['Table', 'Usages']
    }
  },

  load(query, callback) {
      $.ajax({
      url: './api/table',
      type: 'GET',
      error() { callback(); },

      success(res) {
        callback(res);

      }
    });
  },
```

_renderTableOptions(item, escape) {

```
  console.log("***********inside _renderTableOptions() :escape(item.fqn)="+escape(item.fqn)); 
return (   
  '<div class="row">' +
    '<div class="col-sm-11 col-name"><span>' + escape(item.fqn) + '</span></div>' +
    '<div class="col-sm-1"><span>' + escape(item.usages) + '</span></div>' +
  '</div>'
);
```

  },

let dropDownOnChange = function(change) {

```
              $.ajax({
            url: './api/table?selectedSchema='+change.newValue,
            type: 'GET',                
            error() { callback(); },      
            success(res) {
              callbacknew(res);
            }
      });

};
```

SearchInputField.jsx
![image](https://cloud.githubusercontent.com/assets/19906954/18170970/ea2541ce-707d-11e6-8fe8-740d0200d712.png)

SearchSchemaField.jsx
![image](https://cloud.githubusercontent.com/assets/19906954/18171034/23336356-707e-11e6-9b2b-27fe839d9807.png)

My Issue is : 
I am getting proper json response after onchange of first dropdown but how to set this response to second dropdown to refresh table list data.

Please help me with code on how to  populate/refresh the second dropdown table list data  based on json response received from first dropdown selection.

![image](https://cloud.githubusercontent.com/assets/19906954/18169826/7d2caff2-7079-11e6-858e-a803eaeeb872.png)

![image](https://cloud.githubusercontent.com/assets/19906954/18169909/d7e27936-7079-11e6-9482-6bdc973f02e7.png)

![image](https://cloud.githubusercontent.com/assets/19906954/18169949/fc1a2fec-7079-11e6-8e5c-0c7ef229e63a.png)

![image](https://cloud.githubusercontent.com/assets/19906954/18170597/71aeb762-707c-11e6-9c65-422cc342a570.png)

Thanks
Surendra

**Comment by joallard** [comment]
On first read, this doesn't seem like a minimal example of something to fix with Selectize. As said in the issue template, we don't have time to answer open-ended questions.
