### ISSUE TITLE
Required Inputs broken with new release

### ISSUE THREAD

**Issue by jeffblake** [selectize/selectize.js#1148]
It looks like in: https://github.com/selectize/selectize.js/commit/abc8a560a8335a017790c2a799925cc123670bfc

in the function `refreshValidityState`
`this.$input.prop('required', !invalid);`
Removes the required attribute from my input. Shouldn't the bang be removed? if its invalid, then the input should be required?

This breaks my validation library, Parsley, which depends on the `required` attribute being set on the input. 

Can we leave the `required` attribute alone? 

I can get it to work again using the Parsley specific data attribute `data-parsley-required` but I really don't want to go edit all my inputs, and using the html5 required attribute is better/cleaner.

I'm using the latest version of everything: selectize, parsley, jquery 3

**Comment by joallard** [comment]
Hmm. The target commit is actually 629f7e64. It fixed an error where Chrome would complain there's a `required` attribute on a hidden field (we hide the original input, `this.$input`).

I don't know your library, but if you have a solution, I'm all ears.

**Comment by canastasiou** [comment]
Also affects jQuery Validation Plugin, which now detects required selectize inputs as not required. The js code that initializes the plugin is called after js code to build selectize fields is called.

**Comment by kishorekumarnethala** [comment]
I noticed that required validator is not working if underlying data is changed , the required validation is not showing up even if nothing is selected .. is there a work around . please advice..
