### ISSUE TITLE
Can not display completely  in a bootstrap modal

### ISSUE THREAD

**Issue by yesmeck** [selectize/selectize.js#115]
The dropdown box can display completely.
http://jsfiddle.net/yesmeck/yaBPm/1/

**Comment by carbonell** [comment]
this solution seems to be no longer working. I checked the fiddle. Any new workaround available?

**Comment by chavolla** [comment]
some bootstrap classes force the select to have a position relative attribute instead of absolute. Add to the style section :
    .selectize-dropdown { z-index: 99999 !important; position:absolute !important;}

**Comment by evertramos** [comment]
I could not make it work inside a modal even with all these options...

**Comment by HB9HIL** [comment]
This worked for me
Bootstrap 5.3

```javascript
onInitialize: function() {
    $('.selectize-control').parents().each(function() {
        $(this).css('overflow', 'visible');
    });
}
```
