### ISSUE TITLE
Remote dropdown dependent on input type not showing

### ISSUE THREAD

**Issue by andrewpros** [selectize/selectize.js#1153]
https://github.com/selectize/selectize.js/issues/1116

It is me again, still not fixed?

Or it is even not supported, i don't know.

Oh, and i can't report the issue with your template cuz it is useless...

It asks "Make sure I'm reporting something precise that needs to be fixed"

AND i don't even now if using one OR another param is supported or not, so how can i know if it needs fixes??? Again, worthless.

If i detect text or id and return values dropdown won't show, the data structure is the same, it is product id or name, but won't show, if it is only id or only name then it shows???

But i can't report it, i can't answer "Make sure I'm reporting something precise that needs to be fixed" cuz i don't know.. silly...

But the funny thing is, it has nothing to do with usig OR params, it even stops working on your own simple examples from github.

**Comment by joallard** [comment]
... 

duplicate #1116.
