### ISSUE TITLE
Cache issue on options - Class "Selected" being copied over / referenced to cache

### ISSUE THREAD

**Issue by BradyNadeau** [selectize/selectize.js#1154]
There is an issue since since 0.12.2 that made any option that has been selected to keep the class "Selected" in the cache. 

This seems like a reference issue knowing the cache doesn't get updated ever again after the option has initially been put in the cache.

I made a quick fix on my fork of the repo here:
https://github.com/BradyLiles/selectize.js/commit/9d953d765cb4c89428929245afea17e7a8f259d5?diff=split#commitcomment-19115571

Simply test by selecting and then deselecting an option and look at the option class afterwords.

`// pull markup from cache if it exists
        if (cache) {
            if (!isset(self.renderCache[templateName])) {
                self.renderCache[templateName] = {};
            }
            if (self.renderCache[templateName].hasOwnProperty(value)) {
                var cachedValue = self.renderCache[templateName][value];
                if(templateName == 'option')
                {
                    $(cachedValue).removeClass("selected");
                }
                return cachedValue;
            }
        }`

**Comment by joallard** [comment]
As asked in the template, can you make a numbered STR and designate a demo page?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
