### ISSUE TITLE
does not go off default sorting of selected items

### ISSUE THREAD

**Issue by pdomkar** [selectize/selectize.js#1155]
Hi I create selectize(multiple) by jquery from select filled by server side. And set selected items. Selectize sorting items by alphabet.
Existing any way how this turn off? So items will be sorted by order of Select element ( how it gets from server). I looked on this: https://github.com/selectize/selectize.js/issues/218, but that solution doesnt work.

Thanks

**Comment by joallard** [comment]
Issue template was erased, this is not a place for questions.
