### ISSUE TITLE
single selectize control can't capture Chinese input string from virtual keypad on mobile device(IOS & Android)

### ISSUE THREAD

**Issue by thlo7777** [selectize/selectize.js#1156]
Steps to reproduce:
1. Change language to Chinese in iPhone or Android mobile 
2. Open a custom html page with select element, invoke selectize() options with create is true  in js file
3. Input Chinese characters to search or add new option

Expected result:
Same like English character, if options contains input character, then score and display, if not then show Add xxx .... 

Actual result:
Nothing happened, can't capture single Chinese character. 

[But I found when you input multiple Chinese characters, then use virtual keypad delete key, then the these characters will be captured. ]

Platform:  
iPhone 6 and Android + browser (webkit view)  + h5/js/css + bootstrap3.3.7 + selectize 0.12.3

I create a select 

`                    <div class="form-group">
                        <label for="cb-first-category" class="col-lg-2 control-label">cb商品一级分类</label>

```
                    <div class="col-lg-10">
                        <select class="form-control" id="cb-first-category" placeholder="选择/输入分类">
                            <option></option>
                            <option value="PA">Pennsylvania</option>
                              <option value="CT">Connecticut</option>
                              <option value="NY">New York</option>
                              <option value="MD">Maryland</option>
                              <option value="VA">Virginia</option>
                        </select>
                    </div>
                </div>
```

`  

When I input Chinese characters on mobile device (use standard iPhone virtual keypad and Chinese input method), the $control_input's  onKeyUp function can not capture it, but onKeyUp can get all English characters. 

I referenced the select2.js code (version 4.0.3)   [https://github.com/select2/select2]. They reminded a workaround to solve this issue.  (select.js  4.0.3  line 3918)
1. unbind keyup event from $control_input
2. bind ('keyup input') for $control_input.

Here are my codes, I tested and it works now.

`       var $select = $('#cb-first-category').selectize({
            create: true,
            sortField: 'text'
        });

```
    var selectize = $select[0].selectize;
    $('#cb-first-category-selectized').on('input', function(event) {
        $(this).off('keyup');
    });

    $('#cb-first-category-selectized').on('keyup input', function(event) {

        var self = selectize;

        if (self.isLocked) return e && e.preventDefault();
        var value = self.$control_input.val() || '';
        if (self.lastValue !== value) {
            self.lastValue = value;
            self.onSearchChange(value);
            self.refreshOptions();
            self.trigger('type', value);
        }
    });
```

`
Because I can't get instance $control_input of  selectize  when selectize initialize phase. So I use
 $('#cb-first-category-selectized') directly to verify my solution.  
After unbind keyup event,   the $control_input's onKeyUp event will not trigger anymore, all keyup event will captured by my custom 'keyup input' event. 

I don't know if this workaround is complete or not, hope some one can give me clearly explanation.

Thanks

**Comment by gotounix** [comment]
@thlo7777 Did you solved this problem? I have the same problem.

**Comment by YanKawaYu** [comment]
+1
