### ISSUE TITLE
Check for the existence of stop() or animate() in setActiveOption()

### ISSUE THREAD

**Issue by albell** [selectize/selectize.js#1157]
jQuery slim builds, mainstream these days, don't include animation support. That triggers hard fails in `setActiveOption()`, because `stop` is not a method.

The one animation there is superfluous in many cases. It might be nice to put in a check for those methods, in the interest of increased compatibility with the slim build.

Thanks for a maintaining this!

**Comment by joallard** [comment]
Yep. Would you PR in a check, along with a comment mentoning the slim build?

**Comment by albell** [comment]
Sure, I won't be able to do it for a week or so though...

**Comment by joallard** [comment]
No worries

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
