### ISSUE TITLE
Dropdown menu re-opens after external system call

### ISSUE THREAD

**Issue by buttonsense** [selectize/selectize.js#1158]
- [x] Search for if my issue has already been submitted
- [x] Make sure I'm reporting something precise that needs to be fixed
- [x] Give my issue a descriptive and concise title
- [ ] Create a _minimal_ working example on JsFiddle or Codepen
  (or gave a link to a demo on the Selectize docs)
- [x] Indicate _precise_ steps to reproduce in _numbers_ and the result,
    like below

[Inside onChange function, I'm calling C++ addon using Node.js to trigger external system call that will run other program in the background. I do have closeAfterSelect as true, but after the call has finished selectize re-opens the dropdown menu.]

Steps to reproduce:
1. Initialize selectize with options and onChange function
2. For every selection, the function will call Node.js C++ addon to run .exe file in the background
3. Select one of the options to trigger onChange function and wait for the system call to finish and you'll see the dropdown re-opening

Expected result:
Dropdown menu should be closed after selection
Actual result:
Dropdown menu re-opens

JavaScript

```
    $theLocalBus= $('#local').selectize({
       options: items,
       closeAfterSelect: true,
       labelField: "item",
       valueField: "loc",
       searchField: ['item'],
       // onchange function used so value is automatically updated on selection
       onChange: function(value) {
            localBusChosen = $theLocalBus[0].selectize.getItem(value).html();
            localBusChosenLoc = value;
            if(value !== "" && value !== undefined && value !== null){
    //node.js C++ addon
                var remote_bus_options = addon.remote_bus(localBusChosenLoc);
                console.log(remote_bus_options);
                if($theRemoteBus !== undefined){
                    $theRemoteBus[0].selectize.clearOptions();
                    $theRemoteBus[0].selectize.addOption(remote_bus_options);
                }
                $theRemoteBus = $('#remote').selectize({
                    options: remote_bus_options,
                    closeAfterSelect: true,
                    labelField: "bus_name",
                    valueField: "bus_index",
                    searchField: ['bus_name'],
                    // onchange function used so value is automatically updated on selection
                    onChange: function(value) {
                        remoteBusChosen = $theRemoteBus[0].selectize.getItem(value).html();
                        remoteBusChosenLoc = value;
                        if(localBusChosen&&remoteBusChosen){
                            simulate();
                        }
                    }
                }).show();
            }
            $theLocalBus[0].selectize.close();
       }
    }).show();
```

**Comment by joallard** [comment]
Thanks. Can you make a demo we can try the steps on and debug? Also, can you try to cut down on the code to demonstrate the issue better?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
