### ISSUE TITLE
Selectize does not work with npm - jQuery is not defined

### ISSUE THREAD

**Issue by naBausch** [selectize/selectize.js#1161]
Hi,

we are using selectize with npm (common js).

Unfortunately there is a bug where you use `jQuery` instead of `$`.
This causes "jQuery is not defined".

The bug is already solved in the [src/contrib/highlight.js line 45](https://github.com/selectize/selectize.js/blob/702761d60ea236985989589830ab16f4c1117dbd/src/contrib/highlight.js#L45).

However in the dist folder it is still set to jQuery:

https://github.com/selectize/selectize.js/blob/702761d60ea236985989589830ab16f4c1117dbd//dist/js/selectize.js#L67

Could you please build the plugin with the newest sources and release a bug fix?

Thanks

**Comment by joallard** [comment]
So, there's nothing to fix, you just want to add some pressure to make a new release.

**Comment by naBausch** [comment]
I don't understand what you mean - the current npm version is broken.
Is there anything I can do to help on this?

**Comment by jantimon** [comment]
Same issue here - when do you plan to release the fix?

**Comment by radojesrb** [comment]
Hi joallard, thanks for selectize. I am experiencing the same issue. My team dislike workarounds :( is there a chance to do it on the level of selectcize? Thanks in advance.

**Comment by jantimon** [comment]
Thanks we tried it and now it works! 👍
