### ISSUE TITLE
Found way to re-render selected item

### ISSUE THREAD

**Issue by emilsgulbis** [selectize/selectize.js#1162]
Hi!

Found out that **selectize.refreshItems()** doesn't re-render selected item, but this does.
`selectize.clearCache()
selectize.updateOption(selectize.getValue(), selectize.options[selectize.getValue()])`

**Comment by joallard** [comment]
Is #1095 relevant?

**Comment by vphantom** [comment]
Very interesting find.  Note that for my purposes, `selectize.clearCache()` wasn't required.  Furthermore, the above only works for a single-value select, not a multiple, which is something to keep in mind.

(If the author is curious, I'm allowing users to create arbitrary e-mail addresses in a select multiple, and I ask extra information in a modal form in that case, then re-render the item with the newfound name for the person.  I trigger my modal form using `onOptionAdd()` and from there, when that form is closed I update `data['name']` and invoke `selectize.updateOption(value, selectize.options[value])` to reformat the tag as if the contact had always existed.)

**Comment by winzig** [comment]
Thanks @emilsgulbis, I read the docs multiple times and could not figure out how to refresh a previously chosen item. It seems like `refreshItems()` should be improved to do what your code above does, specifically, you should be able to specify the identifier of the item to be updated, as well as whether or not it should be re-rendered.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
