### ISSUE TITLE
option without label has height smaller as an option with label

### ISSUE THREAD

**Issue by sturchyn** [selectize/selectize.js#1165]
Hi,

Thank you very much for the feature allowEmptyOption in the version 0.12.3.

We have a select box like this:

```
<select id="select">
  <option value=""></option>
  <option value="A">A</option>
  <option value="B">B</option>
  <option value="C">C</option>
</select>
```

This is an optional input field, so the first option has neither value nor label.
But an option without label has height smaller as an option with label.

Currently we use this workaround:

```
<select id="select">
  <option value="">--</option>
  ...  
</select>
```

The example to reproduce it:
https://jsfiddle.net/sturchyn/z8wt3zdd/

Many thanks in advance :-)

Best regards
Stanislav

**Comment by joallard** [comment]
Given a selectized select with a first option with empty text (as above)

STR:
1. Click on select element

Actual: Height of empty element is abnormally small.

**Comment by voodookoop** [comment]
Not the best solution, but this can help in your own css until it is fixed :

`.selectize-dropdown [data-selectable], .selectize-dropdown .optgroup-header {
	min-height: 20px;
}`

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
