### ISSUE TITLE
Safari (MAC OS) Alignment Issue

### ISSUE THREAD

**Issue by goclixy-core** [selectize/selectize.js#1171]
Thank you for this great UI control, this simlified my dropdown tasks.

I am facing issues with Safari browser, especially on Mac Devices.

I tried to use line-height attribute, it solved the alignment issue, but created problems with the placeholder text.

It would be helpful, if you could let me know what I am doing wrong.
CSS
`.selectize-input {
    border-radius: 0;
    font-family: inherit;
    max-height: 40px;
    min-width: 150px;
    overflow: hidden;
    width: 100%;
    padding: 11px 12px;
}

/\* Safari 6.1+ (10.0 is the latest version of Safari at this time) */
@media screen and (min-color-index:0) and(-webkit-min-device-pixel-ratio:0) 
{ @media {
    .selectize-input {
        height: 40px !important;
        line-height: 40px !important;
        padding: 14px 12px !important;
    }
    .selectize-input:after {
        top: 75% !important;
        margin-top: 0px !important;
    }
}}`

HTML
`<form class="form navsearch" role="search" method="get" id="search-form" action="<?php echo base_url('stickers');?>" name="search-form">
            <div class="input-group has-feedback-right searchbar">
                <select id="select-module" name="c" class="span6 hidden-xs home-stickers-selectize selectize-first-child">
                    <option value="0"><?php echo lang('header_select_category');?></option>
                    <?php if(!empty($header_categories)):?>
                    <?php foreach($header_categories as $category): ?>
                    <option value="<?php echo $category->id;?>" <?php echo (isset($searchCategory) && ($searchCategory == $category->id)) ? 'selected': ''; ?>><?php echo $category->name;?></option>
                    <?php endforeach; ?>
                    <?php endif;?>
                </select>                   
                <span class="input-group-addon padding-5"> </span>
                <input class="form-control search-input search-field-width" name="q" <?php echo settings_item('site.direction') == 1 ? 'dir="rtl"' : '';?> id="sticker-search" autocomplete="off" type="text" value="<?php echo isset($searchKeyword) ? $searchKeyword : '';?>" placeholder="<?php echo lang('header_search_term');?>">
                <span class="input-group-addon"> </span>
                <span class="input-group-btn">
                    <button class="btn btn-modero search-btn" type="submit" id="searchSubmit" name="searchSubmit">
                    <span class="glyphicon glyphicon-search"></span>
                    </button>
                </span>
            </div>
        </form>`
![selectize-issue](https://cloud.githubusercontent.com/assets/15327282/19407967/cce44358-92ce-11e6-82bb-3b2e870b9947.png)

**Comment by joallard** [comment]
Closed for erasing the template.
