### ISSUE TITLE
eCommerce use?

### ISSUE THREAD

**Issue by ghost** [selectize/selectize.js#1173]
Hi! Can I use the plugin together with a my paid eCommerce module? 
In its original form without changes.

**Comment by ghost** [comment]
Too bad!
Thank you! I need MIT, maybe then change it MIT?

**Comment by joallard** [comment]
Well first off, I'm not the author of this library, Brian Reavis is. But even then, it's a little over the top to ask for a project to change its license just to fit your own case that is commercial at that. Just my two cents.

Now just maintaining the package needs a lot of work, I can't imagine writing _and_ maintaining it for two years, what Brian has done. If you find the Apache license doesn't suit your use, maybe you can arrange something with him directly, maybe pitch in some money. I have no idea how he'd like this to go, but I do know he's very busy. Best of luck.

**Comment by brianreavis** [comment]
Apache is perfectly friendly to commercial use:
http://choosealicense.com/licenses/apache-2.0/

Apache's basically MIT with more words (ish). Feel free to use it as you wish @Tuning-Soft

**Comment by ghost** [comment]
@brianreavis @joallard 
Thank you very much guys, yes, I think to try it, I wish you success!
