### ISSUE TITLE
Allow manual copying of tags by user

### ISSUE THREAD

**Issue by calumgunn** [selectize/selectize.js#1177]
I did:
- [x] Search for if my issue has already been submitted
- [x] Make sure I'm reporting something precise that needs to be fixed
- [x] Give my issue a descriptive and concise title
- [x] Create a _minimal_ working example on JsFiddle or Codepen
  (or gave a link to a demo on the Selectize docs)
- [x] Indicate _precise_ steps to reproduce in _numbers_ and the result,
    like below
## 

I've been trying to work out how to get this working all day, so this is my final port of call. Hope you don't mind.

We're using Selectize for user-inputted tags in our app. I'd like to be able to select the resulting tags, copy them (with a right-click > copy, or ctrl+v), and paste them into another selectized field to populate it with the copied tags.

Steps to reproduce:
1. Create Selectized tag box and input some tags
2. Select tags in box and copy
3. Paste tags into another Selectized tag box

Expected result:
Second tag box is populated with copied tags.

Actual result:
Nothing.

If this has been solved in some way, or is not a desired feature, let me know!

Thanks

**Comment by joallard** [comment]
Thanks for the report. Do you know what's being copied?

**Comment by calumgunn** [comment]
Currently, nothing is being copied - text within the tag is unselectable. Whatever's in your clipboard previously is pasted after attempting to copy the tags.

Ideally, it would be possible to copy a delimited list of tags, I guess, to make pasting into another tags field work nicely.

**Comment by joallard** [comment]
I agree.

**Comment by dadvir** [comment]
Is there any update on this issue?

**Comment by Eight-Ball** [comment]
+1

**Comment by rylwin** [comment]
I know this is an old issue, but I landed here looking for a solution. Hopefully this can help someone else. 

I ended up doing the following, which seems to work fine for me when I select one or more items and press `Ctrl-C`. A few notes/caveats:

* I've only tested on Chrome, FF
* This only implements copy. Cut won't do anything with this snippet
* I haven't used this in production yet

```js
document.addEventListener("copy", (event) => {
  const anchorNode = document.getSelection().anchorNode
  if (anchorNode instanceof HTMLElement &&
    anchorNode.classList.contains("selectize-input")) {
    const items = Array.from(anchorNode.getElementsByClassName("item active"))
    const string = items.map(i => i.innerText).join(", ")
    event.clipboardData.setData("text/plain", string)
    event.preventDefault()
  }
})
```
