### ISSUE TITLE
Emit global events using jQuery namespacing format

### ISSUE THREAD

**Issue by pauleustice** [selectize/selectize.js#1180]
I did:
- [x] Search for if my issue has already been submitted
- [x] Make sure I'm reporting something precise that needs to be fixed
- [x] Give my issue a descriptive and concise title
- [x] Create a _minimal_ working example on JsFiddle or Codepen
  (or gave a link to a demo on the Selectize docs)
- [x] Indicate _precise_ steps to reproduce in _numbers_ and the result,
    like below

As a new user to selectize (porting over from Select2), I noticed a lack of global events. It seems the only way to listen is to either assign callbacks when instantiating selectize, or using instance.on('eventtype').

As the library has a jQuery dependency, it seems unusual that events are not emitted globally (from what I can tell, having looked in the documentation at https://github.com/selectize/selectize.js/blob/master/docs/events.md).

Ideally it would be possible to do something like this:

```
$('body').on('selectize:dropdownclose', function () {
  // event handling code here
});
```

My codebase is modular and the responsibility for handling the event (in my case, field validation) is dealt with - and needs to remain contained - within a validation module, and not where the plugin instantiation code is.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
