### ISSUE TITLE
Cannot listen to click event on child node of an option

### ISSUE THREAD

**Issue by nebulousGirl** [selectize/selectize.js#1181]
I am looking into a way to click on a small delete icon on the side of each option which would allow me to delete from server.

I did:
- [X] Search for if my issue has already been submitted
- [X] Make sure I'm reporting something precise that needs to be fixed
- [X] Give my issue a descriptive and concise title
- [ ] Create a _minimal_ working example on JsFiddle or Codepen
  (or gave a link to a demo on the Selectize docs)
- [ ] Indicate _precise_ steps to reproduce in _numbers_ and the result,
    like below

First, I tried to do this : 

```
 $('select', this.$el.find('.adv-search-save')).selectize({
                allowEmptyOption: true, 
                render: {
                    item: function(item, escape) {
                        return '<span class="adv-search-save-selected">' +
                             escape(item.text) +
                        '</span>';
                    },
                    option: function(item, escape) {
                        return '<div class="adv-search-save-item">' +
                             escape(item.text) +
                        '<span class="icon-cancel-circle"></span></div>';
                    }
                },
                sortField: 'text'
            });
```

But, the click was not being triggered at all.

I found this workaround in 0.12.1 and allowed me to delete and reload the page when the icon-cancel-circle was clicked:

```
 $('select', this.$el.find('.adv-search-save')).selectize({
                allowEmptyOption: true, 
                render: {
                    item: function(item, escape) {
                        return '<span class="adv-search-save-selected">' +
                             escape(item.text) +
                        '</span>';
                    },
                    option: function(item, escape) {
                        return '<div class="adv-search-save-item">' +
                             escape(item.text) +
                        '</div>'+
                            '<span class="icon-cancel-circle"></span>';
                    }
                },
                sortField: 'text'
            });
```

But for some reason, it is not working in more recent versions. Any idea why?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
