### ISSUE TITLE
How to always show create option

### ISSUE THREAD

**Issue by hakimihamdan88** [selectize/selectize.js#1182]
Hi, im wondering is it possible to always show without need to search first?

**Comment by h-morales** [comment]
This option is good for user experience. When there are no records yet to show, the user would not know that he/she needs to type something in the textbox. When the users see that there's an Add button, they know already how to add new record from the list.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
