### ISSUE TITLE
Error after destroy(): Cannot read property 'blur' of undefined

### ISSUE THREAD

**Issue by markvital** [selectize/selectize.js#1184]
After I destroy Selectize instance using destroy() method, Chrome gives me an error
**`selectize.js:732 Uncaught TypeError: Cannot read property 'blur' of undefined`**

It looks like **blur** event is not destroyed properly. I'm trying to delete blur event manually, but it doesn't help.

Here is my full code:

```
    $('.tags-editable > textarea').click(function (){
        var parent = $(this);
        var previousTagsValue = parent.val();
        $(this).selectize({
            plugins: ['drag_drop', 'remove_button'],
            delimiter: ',',
            persist: false,
            create: function(input) {
                return {
                    value: input,
                    text: input
                }
            },
            onInitialize: function() {
                parent.selectize()[0].selectize.focus();
            },
            onDestroy: function() {
                parent.selectize()[0].selectize.off('blur');
            },
            onBlur: function() {
                //check if tags changed
                var theTags = parent.selectize()[0].selectize.getValue();
                if (theTags != previousTagsValue){
                  $.ajax({
                    url: '/updateTags',
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        id: parent.data('id'),
                        tags: theTags
                    },
                    error: function() {
                        parent.selectize()[0].selectize.destroy();
                    },
                    success: function(res) {
                        parent.selectize()[0].selectize.destroy();
                    }
                  });
                } else {
                    var component = parent.selectize()[0].selectize;
                    component.off('blur');
                    component.destroy();
                }
            }
        });
    });
```

PS: I'm using standalone version of selectize 0.12.4 from [cdnjs](https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.4/js/standalone/selectize.js).

**Comment by jblacker** [comment]
I believe that you're referencing the incorrect selectize object.  Currently you have:

```
parent.selectize()[0].selectize.off('blur');
```

It should be

```
this.off('blur');
```

What you were probably attempting is `parent[0].selectize.off('blur')`, since the variable `parent` is a jQuery object, however since we're already within the context of the selectize object you can just use the `this` keyword instead.  

Remember if you're using the jQuery extension `$(..).selectize()` then you're instantiating a new instance of selectize.  To reach the API you need to only need access the selectize property of the ELEMENT (hence the usage of the indexer to access the underlying element of the jQuery object)

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
