### ISSUE TITLE
Display input box Before selected items

### ISSUE THREAD

**Issue by saeed-parsaee** [selectize/selectize.js#1185]
Is there any option to display the input box as the first element, always the first one?
I mean: by selecting options,  the item list rendered after the input box. like this picture.
![s](https://cloud.githubusercontent.com/assets/3070844/19685690/afc28b82-9aca-11e6-906f-2779c32d8d32.PNG)
By having this option and adding some style to input box like `width:100%`,
I want to display selected tags below input box which also is a solution to issue #833 
This would be great if having some control option on selectize-input like: render_position/width/height/show_hide

**Comment by saeed-parsaee** [comment]
From selectize.JS it seems that i should prepend **$control_input** to **$control** or reorder them. But is there any other way to do this without changing the source code?

```
$.extend(Selectize.prototype, {
  setup: function() {
    /*
     * => some parts deleted, for more readability
     */
    inputMode         = self.settings.mode;
    classes           = $input.attr('class') || '';

    $wrapper          = $('<div>').addClass(settings.wrapperClass).addClass(classes).addClass(inputMode);

/*=>*/  $control          = $('<div>').addClass(settings.inputClass).addClass('items').appendTo($wrapper);
/*=>*/  $control_input    = $('<input type="text" autocomplete="off" ').appendTo($control).attr('tabindex', $input.is(':disabled') ? '-1' : self.tabIndex);

    $dropdown_parent  = $(settings.dropdownParent || $wrapper);
    $dropdown         = $('<div>').addClass(settings.dropdownClass).addClass(inputMode).hide().appendTo($dropdown_parent);
    $dropdown_content = $('<div>').addClass(settings.dropdownContentClass).appendTo($dropdown);

```

**Comment by Genkilabs** [comment]
Ideally, the items could end up in their own container, then it would be easier to do something like re-order them or apply other code and styles, without having to account for their 'input' sibling.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
