### ISSUE TITLE
Selectize bug with groups, group content is empty

### ISSUE THREAD

**Issue by LorisZ** [selectize/selectize.js#1188]
I did:
- [x] Search for if my issue has already been submitted
- [x] Make sure I'm reporting something precise that needs to be fixed
- [x] Give my issue a descriptive and concise title
- [ ] Create a _minimal_ working example on JsFiddle or Codepen
  (or gave a link to a demo on the Selectize docs)
- [ ] Indicate _precise_ steps to reproduce in _numbers_ and the result,
    like below

We use selectize together with a normal, multiple select which activates option groups in the selectize-select, by rendering optgroups as "" when the group is not selected. This works without problems using the version 0.12.1, but from 0.12.2 to 0.12.4 (currently newest version) it does not work anymore.

Sometimes there is the following error message `"Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.` at `selectize.js:2181"`

The optiongroups are shown, but its options are gone. (Only group-captions visible, not the options themselfes).

I tried creating a jsfiddle for this situation, but was having some different problems. If there is need for it, i'll retry another day, really have to go now.

**Comment by joallard** [comment]
Thanks for the report, I appreciate that it's hard to put a reproduction case together. 

Maybe you could somehow bisect into the repo if it's a regression?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
