### ISSUE TITLE
usage.md: Default for option sortField unclear

### ISSUE THREAD

**Issue by Chealer** [selectize/selectize.js#1189]
[docs/usage.mdx](https://github.com/selectize/selectize.js/blob/master/docs/docs/usage.mdx) says the default value for option sortField is "$order". I fail to understand what this refers to.

**Comment by joallard** [comment]
I think it's in Sifter, there's a link.

**Comment by Chealer** [comment]
joallard, there is no link on the default value. If you are referring to the link to sifter documentation, it does not discuss $order.

**Comment by joallard** [comment]
Okay, well I'll accept some clarification

**Comment by Chealer** [comment]
With the current contents of the cell in the Description column, it seems like the link is only about overriding "the `$score` function". I would recommend to start by giving the last sentence its own paragraph.

**Comment by joallard** [comment]
I'll accept a PR on the matter

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.

**Comment by Chealer** [comment]
Sorry @risadams but please elaborate, the only information I have is that you closed this on 2020-11-12.
What kind of examples do you think this "issue" must include?

**Comment by risadams** [comment]
@Chealer that was a general message that we are using to close most issues that have open longer than a year.  I am going to reopen this and take it into consideration when we update the documentation (which is happening next on my list)

**Comment by Chealer** [comment]
Why is this ticket closed?

**Comment by Chealer** [comment]
@github-actions, was something done to resolve this?

**Comment by Chealer** [comment]
@github-actions, thanks for reopening this ticket

**Comment by risadams** [comment]
Hello @Chealer,  This issue is going to stay closed.
If there are any specific changes you wish to see, please file a PR; we would be more than happy to incorporate any clarifications that you have.
Thanks.

**Comment by Chealer** [comment]
@risadams you would want a _bug report_ to be filed? Is that ticket not one already? In any case, no, the changes I wish to see are not _specific_ in my mind - I know it's unclear, but I do _not_ know what the authors meant.

**Comment by Chealer** [comment]
Thanks for reopening this ticket

By the way, a space is also missing in the _Description_.
