### ISSUE TITLE
Limit optGroup selection

### ISSUE THREAD

**Issue by rickysullivan** [selectize/selectize.js#1190]
Is there a way to only allow 1 item to be selected from each optGroup?'

If not, should I build a plugin?

**Comment by joallard** [comment]
I don't think there is one, no. If you end up making it a plugin, I'd be interested in testing plugins in their own repos  (#976), let me know.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
