### ISSUE TITLE
Cannot support responsive

### ISSUE THREAD

**Issue by rebelholic** [selectize/selectize.js#1196]
Hello,

I already added selectize.js to search input on my website but when resize less than 768px cannot support responsive like screenshot below:

![responsive](https://cloud.githubusercontent.com/assets/6254876/20132325/00d74230-a695-11e6-85f9-67ee85450e7f.jpg)

After typed it would be responsive if resize less than 768px like screenshot below:
![responsive2](https://cloud.githubusercontent.com/assets/6254876/20132624/697df90e-a696-11e6-943a-20f70b651257.jpg)

So my problem how I can make 
``` <div class="selectize-dropdown multi inputsearch plugin-remove_button" style="display: none; width: 331px; top: 36px; left: 0px; visibility: visible;"><div class="selectize-dropdown-content"></div></div> ``` 
become responsive if resize less than 768px?

**Comment by rebelholic** [comment]
@joallard why you closed this bug?

**Comment by joallard** [comment]
Cause you erased the issue reporting template and haven't followed the criteria. It's quite clear:

> ISSUES THAT EITHER:
> - IGNORE THE ISSUE GUIDELINES
> - ERASE THE FOLLOWING TEMPLATE
> - DON'T FOLLOW THE PROPER NUMBERED FORMAT FOR STEPS TO REPRODUCE
> 
> COULD BE CLOSED.
