### ISSUE TITLE
Can't test for submission on enter using Syn.js

### ISSUE THREAD

**Issue by floretan** [selectize/selectize.js#120]
We started using Syn.js for testing interactions (similar to what is done in test/interactions.js), but had trouble with testing actions that require pressing the return key. It turns out there's two issues:

Syn.js automatically submits forms when the enter key is pressed, we had to add  $form.submit(function(e) {e.preventDefault();}) to prevent a page reload. This might only be necessary if the selectize widget is used within a form.

Syn.js has its keycodes saved as strings and selectize.js uses integers, which causes mismatches in switch() statements. Overriding Syn.keycodes to contain integers would make it possible to test the complete workflow of a selectize widget using the keyboard.

**Comment by joallard** [comment]
Thanks for reporting this issue. I am closing this since we have a lot of issues and this issue has been inactive for more than 2 years. If there is still a problem, please re-open.
