### ISSUE TITLE
Selectize doesn't preserve `title` attribute

### ISSUE THREAD

**Issue by osya** [selectize/selectize.js#1200]
If I use <select> tag with `title` attribute then tooltip appears at this <select>. If I use such <select> with `title` attribute with Selectize then tooltip for `title` attribute disappeared. See example [https://jsfiddle.net/osya/627q4m7v/](url)
![tooltip](https://cloud.githubusercontent.com/assets/998657/20249132/e6a486f8-aa03-11e6-85f4-3e4a5ba69944.png). Chosen works with `title` attribute properly. Thats because generated <div> tag in Selectize has `display:inline-block`, but in Chosen generated <div> tag has `display:block`. Please make `title` attribute working with Selectize

**Comment by rcaf** [comment]
I have the same problem

**Comment by BigOHenry** [comment]
Same here :(

**Comment by master455** [comment]
The problem continues

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
