### ISSUE TITLE
onDropdownClose triggered twice

### ISSUE THREAD

**Issue by Miteshivgroup** [selectize/selectize.js#1203]
onDropdownClose event is triggered twice when I select option with enter key

**Comment by wTheRockb** [comment]
Any follow up on this? I can reproduce this quite easily by adding a `console.log` into the `onDropDownClose` field of an options object passed to the `selectize` function. Could anyone else confirm or deny this?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
