### ISSUE TITLE
Selectize deletes data attributes from select options

### ISSUE THREAD

**Issue by kodeo** [selectize/selectize.js#1204]
When selectize is applied to a select, its options' data attributes are removed.

```
<select id="s">
  <option value="foo" data-bar="baz" selected>Foo</option>
</select>
```

```
var $s = $("#s");
alert($s.find("option:selected").data("bar"));
$(s).selectize();
alert($s.find("option:selected").data("bar"));
```

https://jsfiddle.net/u6qobn24/

**Comment by kodeo** [comment]
Have fixed this in PR #1206, although I now see this fails a test. Think the test may need rewriting. Maybe someone else can assist.

**Comment by hajikelist** [comment]
this is fairly important, any movement on this?

**Comment by ghost** [comment]
+1 to this. I think all data-attributes on select and options should be preserved.

**Comment by planotransmedia** [comment]
+1 to this. as well

**Comment by Oxicode** [comment]
+1

**Comment by dokle** [comment]
+1

**Comment by Oxicode** [comment]
@joallard @brianreavis please merge

**Comment by CristianSitov** [comment]
+1

**Comment by joallard** [comment]
@Oxicode This is an issue, it's not mergeable

**Comment by vivekapex** [comment]
+1

**Comment by dantheother** [comment]
+1

**Comment by tonksullan** [comment]
+1

**Comment by paulzi** [comment]
+1

**Comment by ptlergo** [comment]
+1

**Comment by coughsyrupgit** [comment]
+1

**Comment by ansien** [comment]
+1

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.

**Comment by Oxicode** [comment]
Everything you should not do.

> closing stale issues older than one year.
> If this issue was closed in error please message the maintainers.
> All issues must include a proper title, description, and examples.
