### ISSUE TITLE
Input width is not calculated correctly in Safari 10 when autofill / autocomplete is enabled

### ISSUE THREAD

**Issue by StevenVerbiest** [selectize/selectize.js#1209]
As the title says.

Autofill is enabled when some conditions are met: 
http://stackoverflow.com/a/1348601

Most, if not all, browsers also ignore the autocomplete tag, so there is no way to disable it.

First example:
https://www.belisol.nl/actiedagen

![example1](https://cloud.githubusercontent.com/assets/2128348/20531510/4e2c2842-b0d7-11e6-86de-8f11c62d47d2.png)

Second example, from the selectize site:

<img width="562" alt="example2" src="https://cloud.githubusercontent.com/assets/2128348/20531569/6dfba8d2-b0d7-11e6-8332-dbec4cfd72c2.png">

The input above is 'Nikola Tesla', but only 'la Tesla' is showing.

And here is a jsfiddle where you can test it for yourself:

https://jsfiddle.net/z8t315rb/4/

Everything works fine when autofill is not enabled.

**Comment by brendt** [comment]
I'm having the same issue.

**Comment by jillro** [comment]
We have the same issue.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
