### ISSUE TITLE
Firefox Warning: Mutation-events

### ISSUE THREAD

**Issue by NashBridgesAT** [selectize/selectize.js#1210]
I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [ ] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [ ] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

I tried to integrate selectize.js to my web project. I get a FF browser warning, that mutation-events should not be used anymore. (Mutations-Ereignisse sollten nicht mehr verwendet werden. Verwenden Sie MutationObserver stattdessen.)

Steps to reproduce:

1. Use Firefox 50.0
2. Use selectize.js (standalone) and selectize.defaults.css
3. Use jquery 3.1.0

Expected result:
Working input field

Actual result:
Working input field.
**Browser warning that mutation events should not be used anymore. MutationObserver should be used instead.**

**Comment by joallard** [comment]
Thanks for the report. Are you able to provide a demo? I'm using the official demo that runs on an older jQuery.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
