### ISSUE TITLE
Clicking 'x' on an item to delete it from input

### ISSUE THREAD

**Issue by pmichna** [selectize/selectize.js#1211]
I did:

* [x] Search for if my issue has already been submitted
* [ ] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [ ] Create a *minimal* working example on JsFiddle or Codepen (or gave a link to a demo on the Selectize docs)
* [ ] Indicate *precise* steps to reproduce in *numbers* and the result, like below

Is there a way to add an 'x' button on each of the tags that get selected? I would like to have something like below. Clicking 'x' would delete the clicked item from the list.

![x](https://cloud.githubusercontent.com/assets/3777006/20599651/86a8f410-b24f-11e6-9a80-cc2a5dc54836.png)

**Comment by priyank87** [comment]
There is a pluging 'remove_button' that comes for this. Also, you can override the item render method to add this.

**Comment by joallard** [comment]
Correct! Thanks @priyank87
