### ISSUE TITLE
Search term highlighting cuts the ends of words off

### ISSUE THREAD

**Issue by kodeo** [selectize/selectize.js#1214]
When searching using a phrase, where the second word begins with a letter in the first word, the first word is truncated at that letter in the search results, e.g.

```
<select>
  <option></option>
  <option>Blue Moon</option>
  <option>Blue Lagoon</option>
  <option>Blue Umbrella</option>
  <option>Blue Eyes</option>
</select>
```

`$("select").selectize();`

As you start typing 'blue la' you get:

![selectize_error](https://cloud.githubusercontent.com/assets/996340/20798134/b364ac66-b7d5-11e6-8143-9580fc7a0b4a.png)

The truncation then seems to stick, so you'll need to reload to see the same with other letters e.g. 'blue um'.

https://jsfiddle.net/fffnbo1x/

**Comment by shashankgroovy** [comment]
Might want to take a look at #1149.

**Comment by joallard** [comment]
Are you on master? A fix has been made in #1193

**Comment by x00** [comment]
I built from master and am still having issue with this, Part of the first word gets deleted.

"Mile End" becomes "Mil End" and only End is highlighted. This is not what is received from the server.

Also the way it is filtering is counter intuitive. I want a right phase search rather an 'or' search with two word. So the cache filtering don't match how the server is searching.

**Comment by trudynamica** [comment]
I have built from the master and still have the same problem. House Of Cards , turns to H Of Cards

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
