### ISSUE TITLE
How can we define lowercase characters of unicode characters?

### ISSUE THREAD

**Issue by ceremcem** [selectize/selectize.js#1217]
Hi, 

I need to define lowercase characters for some unicode characters, such as `ç` for `Ç`, `ö` for `Ö` etc... How can I do that?

**Comment by joallard** [comment]
That's an excellent question, I believe there exists some material on this already. As for our repo, maybe phrasing this as something concrete to improve on the plugin would make this a viable issue.

Oh. 

> TEST CASE: Words "ÇALIŞ ÖĞÜN" can be searched with "çalış öğün".

By memory, Sifter would be responsible of that. Can you investigate?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
