### ISSUE TITLE
npm package should not have "dependencies", just "devDependencies"

### ISSUE THREAD

**Issue by vivainio** [selectize/selectize.js#1218]
We want to install the 'selectize' npm package just to get access to dist/selectize.js - i.e. we want to use the package similarly to the way you use it from bower (without browserify/webpack).

Currently package.json contains:
```
  "dependencies": {
    "jquery": "^1.7.0",
    "microplugin": "0.0.3",
    "sifter": "^0.5.1"
  }
```

We don't want to install any of these, and sifter is a problematic dependency because of the transient C++ dependency.

It would be useful to either have this changed, or publish a new npm package without production dependencies.

**Comment by joallard** [comment]
In my understanding, dependencies are packages you need to run the library, devDependencies being packages you need to work on improving the library. Hence, we're saying Selectize cannot be ran without packages Jquery, Microplugin and Sifter.

Can you walk me through your logic?

**Comment by vivainio** [comment]
Dependencies are the packages you actually require() in node sense, not packages you need to have loaded up by <script>. Selectize doesn't require() anything when included through selectize.js

For comparison, see e.g. https://github.com/angular-ui/bootstrap/blob/master/package.json - it has devDependencies to angular & others, but no actual "dependencies". Dependencies for frontend package don't make much sense unless you only support browserify or webpack workflows.

**Comment by brianreavis** [comment]
When I set this up a long time ago, I included dist files for people manually downloading files into their project. That workflow has changed a lot by now. That said, I think including a package via a `<script>` tag loaded with NPM is not that common. (I could be proven wrong.) Most people are loading selectize via npm using it with a bundler like webpack or browserify. 

I don't forsee supporting separate packages for the myriad of build setups out there. It's up to @joallard though, as he's been the one graciously maintaining the project.

**Comment by joallard** [comment]
Thanks for the input @brianreavis. This is not an unsignificant change, and I'm not well-versed enough in the different build environments out there to make that change. I'd be looking forward to hearing more perspectives about this though.

**Comment by vivainio** [comment]
@brianreavis There has been an exodus of Bower users to NPM, and what they expect to do is just loading up their packages from node_modules instead of bower_components - still expecting a similar dependency-clean dist.js.

We have a good bunch of Angular frontend packages (fetched from npm) in our app, and none of them pulled runtime dependencies on installation.

**Comment by heldchen** [comment]
ran into exactly the same issue today. coming from Bower. I was surprised by the 16 dependencies pulled in due to the `sifter` and `microplugin` dependencies - as we're including just the standalone dist files from selectize directly in a `<script>` tag.

**Comment by barry-johnson** [comment]
Just adding my thoughts that a correct package.json without the unneeded dependencies would be nice. I am not sure why the change is significant as it will just be removing the dependencies section from  package.json. None of the listed items are dependencies in the typical NPM sense, as @vivainio explained.

**Comment by brianreavis** [comment]
> @vivainio: Dependencies are the packages you actually require() in node sense, not packages you need to have loaded up by <script>. Selectize doesn't require() anything when included through selectize.js

> @barry-johnson: None of the listed items are dependencies in the typical NPM sense, as @vivainio explained.

That's not true. See https://github.com/selectize/selectize.js/blob/master/dist/js/selectize.js#L24 (what "main" in package.json points too). If we rip out `sifter` and `microplugin`, it will break for people using bundlers (which I'd guess is the majority of people).

**Comment by powerbuoy** [comment]
Perhaps this deserves its own thread but are there any plans on ditching the jQuery dependency?

**Comment by mikemaccana** [comment]
Selectize *should* require jquery, rather than expecting a jQuery global.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
