### ISSUE TITLE
sometimes search option hints are malformatted

### ISSUE THREAD

**Issue by Xuefeng-Zhu** [selectize/selectize.js#1219]
I had some weird search option hints for some specific cases

fiddle example
https://jsfiddle.net/kk6kezo7/

Steps to reproduce:

1.type `@a --> @a` into the input field

Expected result: option `@a --> @a --> @a --> @a --> @a --> @a --> @a --> @a --> @a` will be highlighted 

Actual result: 
![image](https://cloud.githubusercontent.com/assets/5875315/21063250/38159246-be1a-11e6-858c-55f587e1059b.png)

**Comment by joallard** [comment]
Thanks for the report, I'm just not able to confirm because of a bug on the page.

**Comment by Xuefeng-Zhu** [comment]
@joallard Are you referring to bugs on jsfiddle page? How about this one https://jsfiddle.net/hdbu9581/

**Comment by joallard** [comment]
Correct! Weird indeed.

**Comment by bs-thomas** [comment]
I'm facing the same issue here.  I forked the jsfiddle with my scenario "St. Tropez"

https://jsfiddle.net/4nf1wvh4/

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
