### ISSUE TITLE
Pasting items with splitOn and create asnyc callback does not keep order

### ISSUE THREAD

**Issue by zinkkrysty** [selectize/selectize.js#1220]
I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [x] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [x] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

When I paste delimited items into the selectize control which has a `create` callback (async), the items created are in random order (depending on the order of the async callback). 

See [demo on JSFiddle](https://jsfiddle.net/zinkkrysty/3ekcqth7/)

Steps to reproduce:

1. Initialize a selectize control with `splitOn: ', '` and `create: function...` properties
2. Paste in a list of comma separated values e.g. `1, 2, 3, 4, 5, 6, 7, 8`

Expected result:
The items would be in the original order: `1, 2, 3, 4, 5, 6, 7, 8`. 

Actual result:
Items are in random order. Also the cursor gets set after the first item, instead of the last one.

![image](https://cloud.githubusercontent.com/assets/570771/21187152/498efde0-c217-11e6-9bcc-cfce4865f255.png)

**Comment by zinkkrysty** [comment]
I'm trying to create a test that will fail and try to fix the issue myself but I got stuck here:

```js
describe('pasting comma separated items with a async create function', function() {
    it('should create items in the right order', function(done) {
        var textarea =
            $('<textarea>1, 2, 3, 4, 5, 6, 7, 8</textarea>').appendTo('form');
        var test = setup_test('<select multiple="multiple">' +
            '<option></option>' +
            '</select>', {
                splitOn: ', ',
                delimiter: false,
                create: function(input, callback) {
                    // Simulate AJAX asynchronicity
                    setTimeout(function() {
                        callback({
                            value: input,
                            text: input
                        });
                    }, Math.random() * 10);
                }
            });


        syn.type(textarea, '[ctrl][a]', function() {
            syn.type(textarea, '[ctrl][c]', function() {
                click(test.selectize.$control, function() {
                    syn
                        .type(test.selectize.$control_input, '[ctrl][v]')
                        // Given that we have 8 elements and "ajax" delay for each is
                        // max 10 ms the total delay cannot be above 100ms
                        .delay(200, function() {
                            expect(test.selectize.items).to.be.equal(['1', '2', '3', '4', '5', '6', '7', '8']);
                        });
                })
            });
        });

    });
});
```

basically it works to paste the text but after the delay the items are not yet created. It's also very hard to use karma because I can't really run a single test and stop it in the browser to debug it.

**Comment by joallard** [comment]
Thanks @zinkkrysty, great report. I'll schedule this for next bugfix to draw attention to it, though I don't have the time for now to dive in directly myself.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
