### ISSUE TITLE
Use of selectOnTab in Firefox results in the full list being displayed

### ISSUE THREAD

**Issue by kodeo** [selectize/selectize.js#1221]
After filtering a list and selecting an option using Tab, the chosen item is selected but the entire list is redisplayed below. Fails in Firefox, works in Chrome and IE. 

https://jsfiddle.net/n4xLk8az/

Before:
![tab_bug_before](https://cloud.githubusercontent.com/assets/996340/21203372/187551c2-c24a-11e6-8ff0-4e38f32937b4.png)

After:
![tab_bug_after](https://cloud.githubusercontent.com/assets/996340/21203378/1c4772da-c24a-11e6-83a3-5efa3fc4a314.png)

**Comment by joallard** [comment]
Thanks. Confirmed on Firefox Aurora

STR:

1. Type 'on'
2. Press Tab

**Comment by Fonsan** [comment]
+1

**Comment by PredragPeranovic** [comment]
Does anyone have workaround for this bug or any progress in fixing it?

**Comment by koichirose** [comment]
Can confirm this with selectize 0.12.6 and Firefox 61.0.1.
Had to revert to 0.12.2 which seems to be working on all the browsers I tested (Safari, Chrome, Firefox, Opera).

**Comment by koichirose** [comment]
Unfortunately, with 0.12.2 the remove_button plugin is not working.
Needing both remove_button (works on .6, not on .2) and selectOnTab (works on .2, not on .6), I'm currently stuck.

Intermediate versions (.3, .4, .5) all have one or the other issue.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
