### ISSUE TITLE
Selected saved value on edit form

### ISSUE THREAD

**Issue by TDK1964** [selectize/selectize.js#1224]
I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [ ] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [x] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

[Selected saved value on edit form]

Steps to reproduce:

1. Open and save form in create mode
2. Load form in edit mode
3. Previously save selected value is displaying the "id" value and not the "name" 

Expected result:
Selectize DDL should show the text and not the id

Actual result:
Shows the Id

```
    $('#RaisedById').selectize({
        persist: false,
        valueField: 'Id',
        labelField: 'Name',
        searchField: 'Name',
        options: [],
        create: false,
        preload: true,
        maxItems: 1,
        load: function(query, callback) {
            var self = this;
            $.ajax({
                url: '/SelectHelper/GetUserList',
                type: 'GET',
                dataType: 'json',
                data: { q: query },
                error: function() { callback(); },
                success: function(res) {
                    callback(res);
                }
            }).then(function() {
                console.log("then");
            }).done(function() {
                console.log("done");
                var val = parseInt(self.items[0]);
                self.setValue(val);
            });
        }
    });
```

**Comment by joallard** [comment]
Thank you. Can you post your demo?

**Comment by TDK1964** [comment]
Unfortunately not, it's all local development work. However, using the example above, RaisedById will be populated from the database with an FK integer ID. This ID is the PK from another table.

**Comment by joallard** [comment]
Okay. Can you make a small demo on which to try the STR? That would be helpful. Here's the guide: https://github.com/selectize/selectize.js/wiki/How-to-make-a-great-reproduction-case

**Comment by TDK1964** [comment]
When the form loads this input tag is generated.
I was expecting selectize to bind to the Id value and display the text but it displays the id
```
<input type="hidden" value="4" name="AssignedToId" id="AssignedToId" tabindex="-1" class="selectized" style="display: none;">
```

Id 4 should be displayed as "Item 4"
I'm guessing it's because the options are loaded from ajax and consequently are not available when selectize initialises?

**Comment by TDK1964** [comment]
I really can't understand why it's so difficult to do the simplest thing in the world i.e. display a previously saved selection on an edit form when the selectize ddl is populated via ajax!! 

It's not just me either, trawling around the net reveals lots of frustrated developers :(

**Comment by copperx** [comment]
@TDK1964 is absolutely right. selectize.js is full of features, but it can't set the value automatically on page load if the field is loaded with AJAX? If I had more time on my hands I would try to fix it and submit a patch, unfortunately, I'm behind schedule on a project and will have to switch to select2 or chosen for this basic functionality (after wasting a couple of hours trying to fix it with a hack).

**Comment by joallard** [comment]
Well, you're busy, and so is everyone. If nobody actually takes the time to implement it and make a quality PR, no one else will. After all, this is an open source project, not a corporation with loads of money.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
