### ISSUE TITLE
Make it possible to focus an input *inside* an item

### ISSUE THREAD

**Issue by jojoT84** [selectize/selectize.js#1225]
I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [x] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below
* [x] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)

**I want insert inside an input in item, but when i click it no focus**

Steps to reproduce:

I modified this example codehttps://github.com/selectize/selectize.js/blob/master/examples/customization.html with the below: 

$('#select-links').selectize({
					theme: 'links',
					maxItems: null,
					valueField: 'id',
					searchField: 'title',
					options: [
						{id: 1, title: 'DIY', url: 'https://diy.org'},
						{id: 2, title: 'Google', url: 'http://google.com'},
						{id: 3, title: 'Yahoo', url: 'http://yahoo.com'},
					],
					render: {
						option: function(data, escape) {
							return '\<div class="option"\>' +
									'\<span class="title"\>' + escape(data.title) + '\</span\>' +
									'\<span class="url"\>' + escape(data.url) + '\</span\>' +
								'\</div\>';
						},
						item: function(data, escape) {
							return '\<div class="item"\>\<input type="text" value="' + escape(data.url) + '"\> ' + escape(data.title) + '\</div\>';
						}
					},
					create: function(input) {
						return {
							id: 0,
							title: input,
							url: '#'
						};
					}
				});

Expected result:
I wish I could change the input field

Actual result:
no focus on input inside item

DEMO: https://jsfiddle.net/z8wt3zdd/12/

**Comment by joallard** [comment]
Okay thank you. A demo with some steps would be helpful. For help please see this guide: https://github.com/selectize/selectize.js/wiki/How-to-make-a-great-reproduction-case

**Comment by jojoT84** [comment]
ok, sorry
https://jsfiddle.net/z8wt3zdd/12/

example is very simple, i can't modify input value

**Comment by joallard** [comment]
Oh okay I see. That would be a little complicated, but you can maybe hack around.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
