### ISSUE TITLE
Unselect a single

### ISSUE THREAD

**Issue by jackmcdade** [selectize/selectize.js#123]
Correct me if i'm wrong, but it would seem there is no way to "unselect" your option in single mode? Is there a way to accomplish this? No rush, but would be really helpful. Thanks!

**Comment by Pictor13** [comment]
The remove-button is there on _single-select_; I fixed it's styling in #1311 .
Eventually using `alllowEmptyOption: true` will also add the dropdown empty-choice for clearing the current value (#163)
