### ISSUE TITLE
preload: 'onfocus' will call ajax twice

### ISSUE THREAD

**Issue by saeed-parsaee** [selectize/selectize.js#1230]
As a reference to issue  #301 when i use preload 'onFocus' loading options with ajax called twice!
see this issue on beta version of this site:
1- go to [this url](http://bahook.com/shelf?cat=461)
2-hover the first filter to open box.
![image](https://cloud.githubusercontent.com/assets/3070844/21631705/d466f016-d253-11e6-8197-b0dce909d194.png)
3-check for console log.
by focusing in the first 3 filter you will notice that focus in each box will load data twice.
here are my selectize options:
       
        valueField: 'id',
        labelField: 'text',
        searchField: 'text',
        autoselect: 'first',
        closeAfterSelect: true,
        disableDelete: true,
        openOnFocus: true,
        preload: 'focus',
        addPrecedence : false,
        maxOptions: 25,
        loadThrottle: 1200,
        filter: false,
        clearCache: true,
        plugins: ['remove_button', 'preserve_on_blur' ],

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
