### ISSUE TITLE
Feature request for .setMaxItems(n) method on the API

### ISSUE THREAD

**Issue by guischdi** [selectize/selectize.js#1231]
I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [ ] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [x] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

**Is it possible to provide a `.setMaxItems(n)` method on the API?**
This would be very helpful in cases, where the maximum number of items that can be selected depends on some other user inputs. When calling the method on an field with more than `n` items it might just unselect/slice the last `x-n` selected items.

Steps to reproduce:
This is a feature request. So there are no steps. If this is the wrong place for feature requsts, pls tell me where to put it.

Expected result:
`selectize.setMaxItems(3);` sets the `maxItems` property on the considered selectize input to `3` and leaves only the first 3 of the currently selected items selected.

Actual result:
None, yet.

**Comment by oller** [comment]
+1

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
