### ISSUE TITLE
Release new disable options/optgroup feature on npm

### ISSUE THREAD

**Issue by gijsroge** [selectize/selectize.js#1233]
I did:

* [x] Search for if my issue has already been submitted
* [x] Give my issue a descriptive and concise title
* [ ] Make sure I'm reporting something precise that needs to be fixed
* [ ] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [ ] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

[This feature](https://github.com/selectize/selectize.js/commit/bbdde959beb26d019bc8005de21564ae025a1458) has been written, but not yet released.

I feel that this new feature is release worthy as its not a small tweak. Disabled options is default browser behavior so a big deal to get this working in Selectize.js 😄 

Also, thanks for writing this feature!

**Comment by btesf** [comment]
This is a feature we have been waiting for for sometime. We even thought of using another plugin just for this reason.

**Comment by ahsan-ssi** [comment]
any update about the release of this feature?
much needed!

**Comment by tonejac** [comment]
Any examples on JSFiddle or Codepen yet?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
