### ISSUE TITLE
Selectize regains focus after clicking outside document and then click on document

### ISSUE THREAD

**Issue by Trevald** [selectize/selectize.js#1236]
### To reproduce:
- Visit: http://selectize.github.io/selectize.js/
- Scroll down to "Max Items"
- Click on select to activate Dropdown
- While dropdown is open, click on taskbar or if on Os X you can click the tab bar in dev tools (make sure to open dev tools before previous step). That will make the dropdown go away
- Then click anywhere inside body and the dropdown opens again. You could also click on the "Gear" select and you will get two dropdowns open at the same time.

Fix for Chrome seems to be to call blur on control input on blur. But in Explorer that doesn't work, click on the taskbar while dropdown is open will close it but then re-open when clicking on body.

This is mostly a problem when you have multiple selectize instances on the same page, since they may overlap.

**Comment by ghost** [comment]
@Trevald and what about hide and show the input on blur, to break the browser focus chain? or also try to find the active element.
```
options["onBlur"] = function() {
    var self = this;
    self.blur();
    self.$control_input.hide();
    self.$control_input.show();
    if(document.activeElement) {
        document.activeElement.blur();
    }
};
```
Set the focus to other form control?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
