### ISSUE TITLE
Having available options for text input

### ISSUE THREAD

**Issue by zeno-bg** [selectize/selectize.js#1238]
---

I did:

* [ x] Search for if my issue has already been submitted
* [ x] Make sure I'm reporting something precise that needs to be fixed
* [ x] Give my issue a descriptive and concise title
* [ ] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [ ] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

Hi, I want to make a keywords text input like this:

```
 var $tags = $("#tags").selectize({
         delimiter: ",",
         persist: false,
         create: function (input) {
             return {value: input, text: input }
         }
     });

```

It works alright, but I want to have all my keywords available for "selection" - so when I start writing, instead of "Add [keyword]..." I could just select "[keyword]". However, none of the available settings seem to allow this. I can add options for select input, but not for text input. Anyone run into such issue? Thanks!

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
