### ISSUE TITLE
After migrating from 1.12.1 to 1.12.4 the labelField option is ignored

### ISSUE THREAD

**Issue by bb1** [selectize/selectize.js#1240]
* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [x] JsFiddle https://jsfiddle.net/z1cs0420/4/
* [x] Indicate *precise* steps to reproduce in *numbers* and the result below

Steps to reproduce:

1. Set up a selectize with labelField changed
`$("#"+id).selectize({labelField : 'value', load: function(query, callback) {
  loadFunc(id, query, callback);
}});`
2. use the callback from the load-Option to fill the Box
= it fails and produces the screenshot below
3. Try again with $.map() and add a text attribute to each object
= it works

Result:
![Screenshot](https://abload.de/img/selectize_labelfield_3mset.png)

Okay I need some help here. This bug suddenly appeared after I upgraded from 1.12.1 to the newest release. But when I tried to reproduce it in a JsFiddle it worked. I used the exact same configurations minus the Ajax-Request.

I had to add an ugly work-around to make it work: I map the server response to fit the default configuration:
`success : function(res) {
	var cleaned = $.map(res, function(val, i){
		return {
			value: val.value,
			text: val.value
		};
	});
	callback(cleaned);
}`

I know this is more or less useless without steps to reproduce. Maybe it helps if I add some more information:
jQuery 1.11.2,
$.ui.version "1.11.0"
`$("#selectId")[0].selectize.settings.labelField // "text"` but should be "value"
It seems like the attribute labelField wasn't set and the default parameter was used.
Does someone else has the same problem or any idea what it may causes? I'm running out of ideas.

**Comment by CGB0** [comment]
There is something wrong with the Json coming back from the server.    I get what you are seeing  if I send something back and have built it using a custom serializer to convert the data to a json.    When I use JsonConvert.SerializeObject( mydatatable) (c# call on server)  and then return the resulting string its okay.

you might also run the data through  JSON.parse
```
var setTaskNameGuidOptions = function (callback, _jobGuid)
{
    $.ajax({
        url: '/Tasks/TaskNameGuid',
        data: { '_jobGuid': _jobGuid },
        success: function (data)
        {
            var tData = JSON.parse(data); // <<<  I need to do this as well.
            callback(tData);
            select_taskNameGuid.settings.placeholder = "Select existing or enter a new name";
            select_taskNameGuid.updatePlaceholder();
            select_taskNameGuid.enable();
        }
    });
}
```

**Comment by bb1** [comment]
Okay... it was my mistake... This is no selectize bug. Thanks for your help anyway.

Also thanks for making such a great framework! Keep on rocking!
