### ISSUE TITLE
Did dropdown table get built?

### ISSUE THREAD

**Issue by CGB0** [selectize/selectize.js#1241]
Did the dropdown_table mentioned in this thread.

https://github.com/selectize/selectize.js/issues/56

ever get built?  I have searched selectize.js and could not see it.

Thanks.

**Comment by JakeAlmer** [comment]
you might be looking for the "optgroup_columns" plugin, you can see a demo on the plugins tab at http://selectize.github.io/selectize.js/

**Comment by CGB0** [comment]
I was actually looking for a dropdown table.  Thanks for pointing me at optgroup_columns.    By lining up the data and using optgroup_colums I can actually fake it from a looks perspective but I am stuck on getting the right data to display when I click on an item.  The problem is the item.label.

The  jquery element is a select with a dropdown.  

I have data like this:
4 columns
```

 id      column1 text     column2 text      column3 text
 1         xxxxxxx           yyyyyyyy       zzzzzzzzz
 2         aaaaaaa           bbbbbbbb       ccccccccc

```
id is actually a guid in the form  {xxxx-xx...}  and is system unique.
column 1 text is not system unique

Issues.
1. No matter which column I click on I want to get _id_ back for that row.  Duplicate id's for the column data are not allowed ( _the duplicate id and data is simply dumped_).  I can live with that.  On the server I simply append an alpha on each column id.  {xxxx-xx...}a  > column1 text    {xxxx-xx...}b >column2 text  {xxxx-xx...}c  > column3 text    No matter which id I get back I can link it back by stripping off the trailing alpha.      Solved

2. This one is harder and I don't have a solution.   I  need  the _column1 text in_  the select box no matter which column is selected.     I was hoping I could hide some data as an invisible field which I could return as the valueField or as the labelField but I don't see how.     

Does anyone have any idea how I could accomplish issue number 2.   

here is a small data sample.   guid shortened for ease of viewing. 
    ```
   options: [
{ id: "{D86208E3-......}a", fieldname: "taskname", fieldvalue: "32125015 : 4 Man Days 13" },
{ id: "{D86208E3-......}b", fieldname: "trade", fieldvalue: "Heating" },
{ id: "{D86208E3-......}c", fieldname: "floor", fieldvalue: "L1" },
{ id: "{FFC0AB92-......}a", fieldname: "taskname", fieldvalue: "32125015 : 4 Man Days 2" },
{ id: "{FFC0AB92-......}b", fieldname: "trade", fieldvalue: "Heating" },
{ id: "{FFC0AB92-......}c", fieldname: "floor", fieldvalue: "L1" },
{ id: "{A0E9213B-......}a", fieldname: "taskname", fieldvalue: "32125015 : 4 Man Days 3" },
{ id: "{A0E9213B-......}b", fieldname: "trade", fieldvalue: "Heating" },
{ id: "{A0E9213B-......}c", fieldname: "floor", fieldvalue: "L1" },
{ id: "{F70477D3-......}a", fieldname: "taskname", fieldvalue: "32125015 : 4 Man Days 4" },
{ id: "{F70477D3-......}b", fieldname: "trade", fieldvalue: "Heating" },
{ id: "{F70477D3-......}c", fieldname: "floor", fieldvalue: "L1" }, ],

    optgroups: [
              { id: 'taskname', name: 'TaskName' },
              { id: 'trade', name: 'Trade' },
              { id: 'floor', name: 'Floor' }
      
        ],
        labelField: 'fieldvalue',
        valueField: 'id',
        optgroupField: 'fieldname',
        optgroupLabelField: 'name',
        optgroupValueField: 'id',
        optgroupOrder: ['taskname', 'trade', 'floor'],
        searchField: ['taskname'],
        plugins: ['optgroup_columns']
```

Any help is appreciated.  
Thanks,

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
