### ISSUE TITLE
Difference in adding options on init vs. dynamically with addOption (hideSelected problem)

### ISSUE THREAD

**Issue by vsekelj** [selectize/selectize.js#1242]
I have 2 selectize input components with the same config (basically just persist:false and hideSelected:true). The difference is that one gets its options created on initialisation, while the other one gets its options afterwards/dynamically via addOption. Other than that - same config, same data.

Even though thats the only difference between them - they behave differently: 
1. if I add a tag to the second (dynamic) one, then delete it - the option will disappear completely from the drop-down
2. if I add a tag to the first (static) one, then delete it - both options will again be available from the drop-down as desired (so here it works correctly)

I did a quick example here:
[http://codepen.io/anon/pen/dNmKyB?editors=1010](http://codepen.io/anon/pen/dNmKyB?editors=1010)

It seems like a bug to me - if not, tell me what I'm doing wrong. 

Also any ideas on a quick workaround? I'd really like it to behave properly but for my app I need to add data dynamically and I'd rather do that without destroying/creating the entire component every time my options change.

Any help is appreciated - thank you!

**Comment by samstorino** [comment]
Change `persist: false` to `persist: true`. False will remove the option from the list if the user selects an option, then hits "Delete" to remove it as a selected item.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
