### ISSUE TITLE
With selectOnTab set to true, tabbing through a select without inputting anything selects the first option

### ISSUE THREAD

**Issue by drekembe** [selectize/selectize.js#1243]
I did:

* [x ] Search for if my issue has already been submitted
* [x ] Make sure I'm reporting something precise that needs to be fixed
* [x ] Give my issue a descriptive and concise title
* [x ] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [x ] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

Steps to reproduce:
1. open the fiddle: https://jsfiddle.net/zc0bjqkx/
2. focus on the first field
3. keep pressing tab

Expected result:
Reaching the end of the fields without any options being selected.

Actual result:
The first option is always selected. In the last select, which is a multiple select, all of the options get selected.

Hey! I'm not 100% sure that this is a bug, but it is behavior I think should be fixed. The problem is if you have selectOnTab set to true, and you tab through a bunch of selects, the first option will be selected when I don't fill anything in and press tab. If I don't input anything and press tab, it should just move on to the next input without selecting anything. My use case is that I have clients that have big forms with lots of fields, but most of them are optional. They want to be able to quickly tab through the form, filling in only the inputs that they want.
![selectize](https://cloud.githubusercontent.com/assets/997022/22561804/2633c5d0-e97a-11e6-842c-b23a06e13f23.gif)
https://jsfiddle.net/zc0bjqkx/

**Comment by rskaarup** [comment]
Easy fix:

selectize.js v0.12.2 (which currently is the only version with tab-functions that work - see #1164 and #1464). Change line 1593 in standalone version and line 957 in src version from:

`                                      if (self.settings.selectOnTab && self.isOpen && self.$activeOption) {
`

To: 
`                                        if (self.settings.selectOnTab && self.isOpen && self.$activeOption && (self.lastValue !== '')) {
` 

It's the line just below:
`                                case KEY_TAB:
`

Then you can tab through new and already filled out selectizes without messing them up.

(in v0.12.6 code is the same, but line numbers are 1022 and 1658 for src and standalone version respectively.)

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
