### ISSUE TITLE
Firefox BUG - Scrolls Left in Scrollable Divs (x-direction) on subsequent clicks

### ISSUE THREAD

**Issue by jermahs** [selectize/selectize.js#1244]
I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [x] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [x] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

In Firefox if you selectize is in a div that scrolls in the x direction subsequent clicks (not the first) causes the div to scroll back to the far left edge of the div.

Steps to reproduce:

OS & VERSION: **Mozilla Firefox** (I was on 50.0.2 at the time of testing)

1. Got to the codepen: http://codepen.io/anon/pen/YNLXey
2. scroll to the right till you find the selectize input (also make sure you have actually scrolled to the right)
3. change the value to '2'
4. click the selectize input a second time. 
5. notice the div scrolls back to the far left edge every time you click it after the first initial click.

Expected result:
It shouldn't scroll to the left on subsequent clicks.

Actual result:
It does scroll to the left on subsequent clicks.

We have a horizontal form that overflows in the x-direction. When our users click on the selectize input subsequent times (not the first) it's causing the horizontal form to jump back to the start.

**Comment by kirchner** [comment]
@jpgilchrist I'm having the exact same issue on Chrome (Version 58.0.3029.110).  Did you possibly already happen to find a solution?

**Comment by jermahs** [comment]
@kirchner nope we moved over to using [select2](https://github.com/select2/select2)

**Comment by dmytro-y-dev** [comment]
```
/**
		 * Gives the control focus.
		 */
		focus: function() {
			var self = this;
			if (self.isDisabled) return;
	
			self.ignoreFocus = true;
                self.$control_input[0].focus();
			window.setTimeout(function() {
				self.ignoreFocus = false;
				self.onFocus();
			}, 0);
		},
```

should be

```
/**
		 * Gives the control focus.
		 */
		focus: function() {
			var self = this;
			if (self.isDisabled) return;
	
			self.ignoreFocus = true;
			window.setTimeout(function() {
				self.ignoreFocus = false;
				self.onFocus();
                self.$control_input[0].focus();
			}, 0);
		},
```

Then the issue is gone. In first case, $control_input has `position: absolute; left: -10000px` which causes browser to scroll left. In second case, $control_input `position: relative; left: 0px` at the moment of focus, which causes normal behavior during the focus.

**Comment by dmytro-y-dev** [comment]
Another solution would be to use `fixed` instead of `absolute` in

```
/**
		 * Hides the input element out of view, while
		 * retaining its focus.
		 */
		hideInput: function() {
			var self = this;
	
			self.setTextboxValue('');
			self.$control_input.css({opacity: 0, position: 'absolute', left: self.rtl ? 10000 : -10000});
			self.isInputHidden = true;
		},
```

**Comment by kylejordan** [comment]
Both solutions provided by @metamaker would still have some issues when I used the tab key to change fields. Sometimes it would still scroll left and other times it wouldn't properly scroll to the input field so the dropdowns would appear outside of the container. I'm using the the "dropdownParent" : "body" option as well to deal with overflow-y: auto issues as well which might be the reason those solutions didn't fully work.

What did work for me was removing the position and left entirely from hideInput and showInput and relying only on the opacity. Is the position change necessary for anything? 

Here's the code change so this:



        /**
         * Hides the input element out of view, while
         * retaining its focus.
         */
        hideInput: function() {
            var self = this;

            self.setTextboxValue('');
            self.$control_input.css({opacity: 0, position: 'absolute', left: self.rtl ? 10000 : -10000});
            self.isInputHidden = true;
        },

        /**
         * Restores input visibility.
         */
        showInput: function() {
            this.$control_input.css({opacity: 1, position: 'relative', left: 0});
            this.isInputHidden = false;
        },
became this:



        /**
         * Hides the input element out of view, while
         * retaining its focus.
         */
        hideInput: function() {
            var self = this;

            self.setTextboxValue('');
            self.$control_input.css({opacity: 0});
            self.isInputHidden = true;
        },

        /**
         * Restores input visibility.
         */
        showInput: function() {
            this.$control_input.css({opacity: 1});
            this.isInputHidden = false;
        },

**Comment by deeksha-07** [comment]
I am facing the same problem in chrome as well as in Firefox. And none of the above solutions works for me, if anyone is having any other solution kindly post it.

**Comment by deeksha-07** [comment]
I am facing the same issue for chrome and firefox and none of the above solutions works for me.

**Comment by matinwd** [comment]
> 
> 
> I am facing the same problem in chrome as well as in Firefox. And none of the above solutions works for me, if anyone is having any other solution kindly post it.

have same problem and nothing worked. move to Select2

**Comment by LimmaPaulus** [comment]
Seems that this issue still exists. I found solution from here https://github.com/reidransom/selectize.js/pull/2 (thanks @theSage21). 

I "injected" the fix to upstream package in this way:

```
Selectize.prototype.focus = function() {
    const self = this;
    if (self.isDisabled) return self;

    self.ignoreFocus = true;
    setTimeout(function () {
        self.ignoreFocus = false;
        self.onFocus();
        self.$control_input[0].focus();
    }, 0);
    return self;
};
```
