### ISSUE TITLE
Select height is smaller than button large height

### ISSUE THREAD

**Issue by oghenez** [selectize/selectize.js#1246]
---
**I did:**
Created a form with the code in this report

**Steps to reproduce:**
1.  Create a html form
2. load bootstrap 3 css and selectize bootstrap css
3. open the form in the browser.

```
<form class="form-horizontal" role="form" style="padding-bottom:45px;" id="search-form">
				<div class="form-group">
					<div class="input-group">
						<select class="form-control input-lg" id="city_id" name="city_id" required >
					</select>
						<span class="input-group-btn">
						  <button type="submit" class="btn btn-success btn-lg">Find Now</button>
					  </span>
					</div><!-- /input-group -->
				</div><!-- /input-group -->
			</form>
```

**Expected result:**
Select input should have same height as button

**Actual result:**
Select height is smaller than button height
![selectize_input](https://cloud.githubusercontent.com/assets/3947396/22881960/3a8259f8-f1e9-11e6-86b1-c2619ea52c8d.jpg)

**Comment by clinkadink** [comment]
I found that when you comment out  **overflow: hidden;** in `selectize.bootstrap3.css` (or whichever version of the css you use), the issue goes way.

```
.selectize-input {
  border: 1px solid #cccccc;
  padding: 6px 12px;
  display: inline-block;
  width: 100%;
  /* overflow: hidden; */
  position: relative;
  z-index: 1;
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  -webkit-box-shadow: none;
  box-shadow: none;
  -webkit-border-radius: 4px;
  -moz-border-radius: 4px;
  border-radius: 4px;
}
```
My html for the selectize then looks like this:

```
<div class="input-group input-group-lg mb-2" >    
     <div class="input-group-prepend">
          <span class="input-group-text"><i class="fas fa-database"></i></span>
     </div>
     <select class="form-control" id="username" name="username" placeholder="Select name"></select>
</div>
```

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
