### ISSUE TITLE
how to set an option of a dropdownlist to disabled

### ISSUE THREAD

**Issue by alperensaylar** [selectize/selectize.js#1248]
I use selectize.js for dropdownlists in my project. I have 3 dropdownlists related to each other. When I click an option from first dropdownlist, some elements from second and third dropdownlists should be disabled. When I click an option from second dropdownlist, some elements from third dropdownlist should be disabled.

When I try some basic jquery or javascript methods to disable an option from dropdownlists, they don't affect. However, when I delete selectize.js classes from dropdownlists, they immediately affect, disable options that I want.

How can I set an option of a dropdownlist?

**Comment by gijsroge** [comment]
Duplicate of #1233

**Comment by jackton1** [comment]
This removes the options from the other inputs distinguish by the name attribute. 

```javascript
var filterOptions = function () {
            var selectize = this.selectize;
            var $wrapper = $(selectize.$wrapper);
            var currentName = $wrapper.parent().find('> select').attr("name");
            var selectedValue = selectize.getValue();
            var otherSelectOptions = $('.test-select select'
            ).filter(function(i, e){ return $(e).attr("name") !== currentName});
            otherSelectOptions.each(function (i, element) {
                $(element).selectize()[0].selectize.removeOption(selectedValue);
            });
        };
 $('.test-select select').selectize().each(function () {
            $(this).on('change', filterOptions);
        })
```

**Comment by ninja1ndia** [comment]
var selectize = $('.selectsize')[0].selectize;

var selectedValue = $('.selectsize').find('option')[0].value;

selectize.removeOption(selectedValue);

selectize.clear();

**Comment by sun-ks** [comment]
I used that plugin for disabling https://github.com/mondorobot/selectize-disable-options

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.

**Comment by n-ubo** [comment]
for people not willing to plugin, i found this work around.
```
 function updateOptions(selectizeInstance) {
     Object.values(selectizeInstance.options).forEach(function (option) {
         if (option.is_disabled) { // or whatever your flag is
             let element = document.querySelector("[data-value='" + option.value + "']");
             if (element) {
                 element.removeAttribute("data-selectable");
             }
         }
     });
 }
```

this **disables** the option, it doesnt remove it. this was perfect for one of my use cases so just leaving this there.
