### ISSUE TITLE
Options in DOM for multiple selectizes

### ISSUE THREAD

**Issue by leqwasd** [selectize/selectize.js#1249]
More of a question:
So in my web, I had a situation, where I had to add multiple selectize inputs, but all of them are the same. I had to let user choose a species - list of couple of thousadns. And for some 50 inputs, the web was struggling to load. For each input, it added new dom element for options.

Question - is it possible, to make it add options to dom just a single time for all of the inputs and use the same for all of the selectize inputs? I think that would increase the performance.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
