### ISSUE TITLE
Selectize and Knockout

### ISSUE THREAD

**Issue by heruan** [selectize/selectize.js#125]
I'm trying to selectize a `select` element populated with Knockout.js.
Take this http://jsfiddle.net/uxfgc/ for example: Three `select`s, binded to each other so that when I change the selected option on one of them the others reflect the change. I also debug on console the `change` event on all of them. When I apply Selectize, strange things happen: when I change the option on one of the first two `select`s, a `change` event is fired on the third, but the selected option doesn't change. Then, if I change the third `select`, the others don't update.
There must be some interaction between Selectize and Knockout which I'm missing!

**Comment by adam-lynch** [comment]
+1!

**Comment by adam-lynch** [comment]
Actually, nevermind... native selects are the way to go (at least for us); https://twitter.com/lynchy010/status/588441175880634369. Works easily & transparently with knockout and there are loads of other benefits. Although to be fair I wasn't looking to do anything advanced like have multiple values, etc.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
