### ISSUE TITLE
How i can hide a opt-group ???

### ISSUE THREAD

**Issue by PaykomanVll** [selectize/selectize.js#1253]
Hello,

i need a way to show/hide opt gorups.
I have 2 dropdownmenus...

#1 has list of platform
#2 there items are be grouped by platforms

if menu #1 changed i will hide all groups without the seleted.

i see selectize add div`s with class .optgroup this contains the selectable items as childs.
But i can not acces to the content of .selectize-dropdown-content if i use $('.optgroup') will not work or other test will not work...

I hope anybody can help to acces the div with class '.optgroup'

**Comment by PaykomanVll** [comment]
okay also the first problem is, the div.selectize-dropdown-content is empty, It can be filled by simple line onLoad.

```
selectize.setValue('default');
```

Fine now, is not empty and we can acces to content. But now comes next problem, selectize render the menu again and again when opening the dropdown :(

I can`t set classes, or new attributes, all will be deleted if dropdown open =(

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
