### ISSUE TITLE
Show All Dropdown Options Without Scrolling

### ISSUE THREAD

**Issue by dchenk** [selectize/selectize.js#1255]
When there are more than a few options in a Selectize dropdown, some of them are hidden and you need to scroll inside the dropdown menu to select them. I need to make it so that _all_ of the options are shown when a user clicks to select an option.

I couldn't find a way to initialize a dropdown with that option. Is there a way to still do it with JavaScript or CSS?

Thanks!

**Comment by yehudahkay** [comment]
https://github.com/selectize/selectize.js/issues/191

**Comment by yehudahkay** [comment]
#191

**Comment by yehudahkay** [comment]
See #191

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
