### ISSUE TITLE
selectize.destroy does not seem to reset everything correctly

### ISSUE THREAD

**Issue by prtome** [selectize/selectize.js#1257]
I did:

* [x ] Search for if my issue has already been submitted --->  it might be similar to #827
* [ x] Make sure I'm reporting something precise that needs to be fixed
* [x ] Give my issue a descriptive and concise title
* [x ] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [x ] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

The problem is shown in the following jsfiddle: https://jsfiddle.net/prtome/0cv893cr/10/

Steps to reproduce:

1. click on the single button, select an option then click on cancel then  read the value in the result area  (it is what is expected: example "5")
2. click on the list button, select an option then click on cancel then read the value in the result area (its is what is expected example ["5"] )
3. click again on the single button, select an option then click on cancel then  read the value in the result area  (it is NOT what is expected: example ["5"] like with the list version)

I would have expected that after calling cancel, and thus destroying, and recreating the selectize, I would have again the same result with single. It seems like if destroy is not resetting completely the options. 
Tests have run on safari and Chrome 
Thank you

**Comment by dmytro-y-dev** [comment]
I also verified, selectize's event listeners are not being properly detached from jQuery.

When you run `$._data(window, 'events')` in browser's console, you can find that after going through several pages in our SPA where selectize is embedded, `resize` events count is rapidly growing.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.

**Comment by CyrilleHantz** [comment]
Issue is still Here in version 0.15.2. Not completed at all.

I found the reason in the code:
Events are linked to "Selectize.count++", instead of an eventual "Selectize.uid++"
But destroy do "--Selectize.count", no need to explain the result on event uid.

You can change the destroy or the setup function as you wish.

Workaround:

```js
require([
    'jquery',
        'selectize'
    ], function ($, selectize) {
        ...
        input_jquery[0].selectize.destroy();
        selectize.count++;
        ...
})
```
