### ISSUE TITLE
Secect by frequency is not working

### ISSUE THREAD

**Issue by brain2xml** [selectize/selectize.js#1258]
Hi, nice plugin but I have trobels with sorting

Plugin config is 
`jQuery('#material-tagnames').selectize(
	{"plugins":["remove_button","restore_on_backspace"],
	"valueField":"label",
	"labelField":"label",
	"searchField":["label"],
	"sortField":[{field:'frequency',direction:'desc'}],
	"create":true,
	"render":{option:function(item, escape) { return '<div><strong>' + item.label + '</strong> - ' + item.frequency + '</div>'; }, 
	item:function(item, escape) { return '<div>' + item.label + '</div>'; }},
	"load":function (query, callback) { 
		if (!query.length) return callback();
		$.getJSON('/tag/list', { query: query }, function (data) { callback(data); }).fail(function () { callback(); }); 
}});`

my json is 
`[{"id":55625,"label":"SOCAR","frequency":1329},{"id":61994,"label":"ГНКАР/SOCAR","frequency":663},{"id":137576,"label":"Госнефтекомпания Азербайджана (SOCAR)","frequency":6},{"id":93060,"label":"SOCAR Energy Georgia","frequency":4},{"id":78834,"label":"SOCAR Georgia Gas","frequency":4},{"id":67583,"label":"SOCAR Turkey","frequency":2},{"id":55504,"label":"SOCAR Turkey Energy","frequency":2},{"id":142560,"label":"SOCAR OGPC","frequency":1},{"id":93588,"label":"SOCAR Trading","frequency":1},{"id":156569,"label":"SOCAR Turkey Enerji","frequency":1}]`

and its sotred by frequency field

when I start typing word 'socar' by letters tags will appear alpabeticly not by frequency even if I use sortField 
"sortField":[{field:'frequency',direction:'desc'}],

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
