### ISSUE TITLE
Clicking inside the select box won't close the dropdown

### ISSUE THREAD

**Issue by russeljo** [selectize/selectize.js#1261]
(sorry, for my bad english, hope you'll understand my problem)
I need to close dropdown when click in .selectize-input, 
like when you click outside .selectize-input.
I try something like this(code below), but it work only first time clicking (dropdown is closed),
 after that dropdown not dropp, because .selectize-input is still focused(all classes - focus & .input-active is still exist).
I have to click outside .selectize-input to unFocus, then foucus is off and dropdown is drop again when i click on .selectize-input.

  ```
 jQuery('.selectize-input').on('mousedown',function(e){
      if(jQuery(this).parent('.selectize-control.multi').hasClass('multi')){
         var $select = jQuery(this).parent('.selectize-control.multi').siblings('.selectized');
         var selectize = $select[0].selectize;

         if (selectize.isFocused){
            selectize.close();  //dropdown close, but control stil is focused 

            console.log('blur on click inside', e.target.nodeName);
         }else{
            console.log('out of focus');
         }
      }
   });
```

**Comment by fernanDOTdo** [comment]
Hello!
This this:

`$('.selectize-input').on('mousedown',function(e){
                    if($(this).parent('.selectize-control.multi').hasClass('multi')){
                        var $select = $(this).parent('.selectize-control.multi').siblings('.selectized');
                        var selectize = $select[0].selectize;
                        if (selectize.isOpen){
                            selectize.close();
                        }else{
                            selectize.open();
                        }
                    }
                });`

**Comment by corescan** [comment]
I experience similar behavior, if i understand the OP correctly. I cannot "toggle" the dropdown by clicking the input area, which would be the expected behavior coming from a native select control.
When i click the input while dropdown is open, dropdown quickly flashes closed then open again. It seems as though there are too many event listeners registered to closing/opening the dropdown, making this behavior annoying clunky.

**Comment by Erbenos** [comment]
Experiencing the same issue.

**Comment by mdaguerre** [comment]
I'm having the same issue here. When i click on the arrow icon to close it doesn't work, this is only happening when is a multiple select. Any ideas?

**Comment by dominicgan** [comment]
Experiencing the same issue as @corescan. I found it to be caused by this line (hotfix for removing focus on ios on-screen keyboard): 

https://github.com/selectize/selectize.js/blob/master/src/selectize.js#L1776 

Commenting this line out fixes the bug for me, at the expense of having to manually close the on screen keyboard on ios. Tried looking through the onBlur function but I couldn't figure out what was specifically causing the dropdown to re-open after closing.

**Comment by yandodov** [comment]
I had the same issue but I noticed the following:

- When the input is not focused and you click, first fires the `onFocus` event and then a `click` event on `this.$control`
- When you click on the input _while_ it is focused and the dropdown is shown, it's the opposite - first fires `onBlur`, then `click` and finally `onFocus`

Basically, you don't want to have the dropdown open immediately after `this.$control` has received a `click`, as in the second scenario. Here's how I made it work:

```js
$(".foo").selectize({
    openOnFocus: false,

    onInitialize: function () {
        var that = this;

        this.$control.on("click", function () {
            that.ignoreFocusOpen = true;
            setTimeout(function () {
                that.ignoreFocusOpen = false;
            }, 50);
        });
    },

    onFocus: function () {
        if (!this.ignoreFocusOpen) {
            this.open();
        }
    }
});
```
You get the same functionality as with `openOnFocus` set to `true`, except you don't get this strange unable-to-close behavior.
The `setTimeout` might scare you, but it's legit. The actual time difference between the `click` and `onFocus` is not controlled by the user and is usually about 2-5 milliseconds. Waiting for `50` is more than enough to prevent unexpected behavior.

Tested on all major browsers + IE11. Works perfectly.

**Comment by ghost** [comment]
@hdodov that's great and it works, but i wonder if this will eventually break my app at some point when a new update comes out... i guess we just have to keep an eye on it, right?

thanks for sharing it!

**Comment by amackaurea** [comment]
The fix does not seem to work for multiselect, any ideas?

**Comment by erikkubica** [comment]
Noone noticed that this "solution" messes up the icon? It´s closed but it indicates that it´s open. On mobile you need to click/tap twice on dropdown to open it...

**Comment by kfir91** [comment]
Any solution to solve ?
its not toggling its only open and if i click again its do nothing...

**Comment by SnowDiamond** [comment]
I solved this issue by unbinding all events from `$control`, and all click events from `input`. You may write any events by yourself.

```js
class SelectWidget {
  constructor(el) {
    this.select = el.selectize(this.options())[0].selectize
    this.focus = false
    this.bindEvents()
  }

  bindEvents() {
    this.select.$control.unbind()
    this.select.$control.find('input').off('click', '**')
    this.handleOpenClose()
  }

  handleOpenClose() {
    this.select.$control.click(() => {
      if (this.focus) {
        this.select.close()
        this.toggleFocus(false)
      } else {
        this.select.open()
        this.toggleFocus(true)
      }
    })
  }

  toggleFocus(focus) {
    this.focus = focus
  }

  options() {
    return {
      openOnFocus: false
    }
  }
}

new SelectWidget($('.some-select'))

```

**Comment by russeljo** [comment]
After years of searching :) I found the root of this problem and open new issue (but in real i just decide use selectize one more time and after years have same problem)
https://github.com/selectize/selectize.js/issues/1605
The problem is simple to resolve - we need add separate button in selectize-input(like arraow in select) which will do one thig: open/close dropdown.
I think that developers just missed this thing.

**Comment by nikitagrygoriev** [comment]
> I solved this issue by unbinding all events from `$control`, and all click events from `input`. You may write any events by yourself.

This requires double click to activate on mobile devices. Unfortunately, the problem still persists.

**Comment by nikitagrygoriev** [comment]
@brianreavis @joallard could you reopen this issue?

**Comment by joallard** [comment]
@nikitagrygoriev Of course.

If I understand correctly:

1. Given the dropdown is open, on a mobile device
2. Click once inside the box
3. Actual: Dropdown does not close (Expected: Dropdown closes)

Is that correct?

**Comment by eduardo-mior** [comment]
As I understand the problem is this:
- If I have the Select open and click on the input field it should close the select. It doesn't close today. 
  
That is the problem? I, as a user, do not click again on the field waiting for it to close. Is this correct? I'm wondering if anyone would expect it to close, when you click on an input it's because you want to type in it, who would click waiting for it to close?

**Comment by slackingway** [comment]
Speaking as a desktop user, default HTML \<select\> elements close when clicked anywhere, so the behaviour is expected, at least when Selectize is used as a simple dropdown with no input. For another example, open any dropdown on this very page and click again on whatever element opened the dropdown. The dropdown closes.

**Comment by joallard** [comment]
@eduardo-mior You're stating the case correctly, yes.

What I can see from Selectize demos is that clicking the input box again "flashes" the opened dropdown. So I'd say that behavior seems undefined. Anecdotically, if I hold my click (mousedown) on the input, it stays closed, and as soon as :mouseup, it opens back up. It feels like it should either be one or the other.

UX-wise, I've tried a few examples, I'm not sure which is the right call (click closes vs click does nothing), which is a question to answer/decision to make before attempting a fix. Unless there's a specific "promise" or expectation that Selectize close, I would close this bug report.

I will open up a discussion with "Should the dropdown close when the input control is clicked?" (#1696). Seems like an interesting issue. I could personally see it either way, I'd be interested to hear different perspectives.

**Comment by Dashawn-passthru606** [comment]
> The fix does not seem to work for multiselect, any ideas?





https://stylesheets.space/questions/hiding-the-search-box-by-clicking-away-from-it
