### ISSUE TITLE
Broken table markup in usage doc

### ISSUE THREAD

**Issue by RuSPanzer** [selectize/selectize.js#1263]
https://github.com/selectize/selectize.js/blob/master/docs/usage.md

and API doc 

https://github.com/selectize/selectize.js/blob/master/docs/api.md

**Comment by rumangerst** [comment]
I noticed that, too. But I think the documentation itself is not broken, but Github seems to have changed something again. If I paste the RAW into Atom and let it render the Markdown file, it works fine ...

**Comment by siegy22** [comment]
see #1265

**Comment by RuSPanzer** [comment]
https://github.com/selectize/selectize.js/blob/master/docs/api.md
API doc also broken
