### ISSUE TITLE
Select Multiple items without reseting the searchfilter (using Shortcuts or by clicking)

### ISSUE THREAD

**Issue by olileo1** [selectize/selectize.js#1267]
It would be great if there was an option where one can enable to select multiple items from the dropdown menu without deleting the keywords from the searchbar. 
For example using the Windows commands "Ctrl + A" or "Shift + Cursor". 

E.g. In the "Max Items"-Demo on https://selectize.github.io/selectize.js/ i would like to select "Kansas" and "Arkansas" at once, if I type "sas" into the textbox. 
If you enter "sas" now and select "Arkansas" you have to scroll through the dropdown menu again to select "Kansas" or enter "sas" again.

Especially if the list of choices is very long the possibility to select multiple entries without reseting the keywords in the searchbar could help to save a lot of time

**Comment by olileo1** [comment]
Does anyone have the same problem or has the feeling that issue needs to be tackled?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
