### ISSUE TITLE
How to set default selected value inzil page loasd?

### ISSUE THREAD

**Issue by shanmugakumar-s** [selectize/selectize.js#1273]
Hi 
How to set selected  multiple values inzialal page loaded itsel. 
```

<select id="select-state"  multiple class="demo-default" name="material[]" >
  <option seleted="true" value="1">one</option> 
  <option seleted="true" value="2">two</option> 
  <option seleted="true" value="3">Three</option> 
  <option seleted="true" value="4">Four</option> 
</select>
        <script>
        $('#select-state').selectize({
          maxItems: 500
          
        });
        </script>
```

**Comment by dattz** [comment]
You can simply add "selected" attribute to the <option> tags, just as you normally would.
I see you have tried to add the selected attributes but you have made a typo.
It's "selected", not "seleted". (missing letter **c**).

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
