### ISSUE TITLE
Clicking out in MS Edge takes focus to body

### ISSUE THREAD

**Issue by priyank87** [selectize/selectize.js#1275]
I am facing a weird issue with MS Edge. When you click out of a selectize field into any other text input, the activeElement changes to body.

Steps (In MS Edge) -
1. Focus selectize input
2. Click on any other text input (Lets call it text2)

Results - 
1. document.ActiveElement is body instead of the other text2. Weirdly enough, cursor is still at the other text input (text2).
2. It takes 2 tab key presses to move cursor out of text2.

This only happens if you click text2 which selectize field is focused. Tabbing to text2 works fine.

To reproduce -
Use http://jsfiddle.net/t0npsj12/4/ in MS Edge.

**Comment by priyank87** [comment]
I think the issue is in the blur(dest) function, it should call blur() on the control after onBlur has been invoked. That is -

`blur: function(dest) {
	this.$control_input[0].blur();
	this.onBlur(null, dest);
}`

to

`blur: function(dest) {
	this.onBlur(null, dest);
	this.$control_input[0].blur();
}`

Right now, second call to onBlur that has the dest param always returns at the top since isFocused has been set to false by `$control_input[0].blur()`.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
