### ISSUE TITLE
jQuery 3 Support

### ISSUE THREAD

**Issue by jblacker** [selectize/selectize.js#1277]
This is more of a discussion/information request.  Has anyone tested selectize.js against jQuery 3?  I'm getting ready to upgrade a project from jQuery 2.2.2 to jQuery 3 and this is the only library that I'm not sure about its compatibility.  I plan on doing some testing on my own at some point, but figured I'd create a post here to see what anyone else's findings were and see if we can make selectize.js's jQuery 3 support "offical."

**Comment by shaneog** [comment]
Did you manage to test this @jblacker? I'm in the same position now that you were in.

**Comment by avranu** [comment]
I've tried running selectize on both jquery 1 and 3, and have seen no differences between the two. YMMV.

**Comment by RaquelPlaza** [comment]
I have upgraded to jQuery 3.2.1 recently and when I run my karma tests I get a selectize error: TypeError: undefined is not an object (evaluating 'a.extend') at bower_components/selectize/dist/js/standalone/selectize.min.js:2

Selectize version is v0.12.1

Has anyone else experienced this problem?

**Comment by vcajes** [comment]
with jQuery 3.2.1 and selectiza 0.12.1 I got this error while following the basic example:

`Uncaught TypeError: Sifter is not a constructor`

**Comment by dansleboby** [comment]
Same error on 2.2.3

**Comment by DenisLabrecque** [comment]
I'm upgrading to jQuery 3.5.1 and get the following deprecations: 

- [ ] `JQMIGRATE: jQuery.isArray is deprecated; use Array.isArray`. Looks like calls to `Array.isArray` have been interspersed with `$.isArray` in selectize standalone 0.12.6
- [ ] `JQMIGRATE: Use of number-typed values is deprecated in jQuery.fn.css`
- [ ] `JQMIGRATE: jQuery.trim is deprecated; use String.prototype.trim`

**Comment by erropix** [comment]
@brianreavis @joallard

Can you confirm if this issue is taken into consideration since WordPress 5.6 has been released with jQuery 3 and I see various migration warnings?

With WordPress 5.7, they will completely remove jQuery Migrate and this will break the Selectize library in WP sites.

**Comment by risadams** [comment]
@ERROPiX there should be no issues,  we are using jquery 3.5.1 for local testing and all tests, demos, and examples are working as expected.

**Comment by erropix** [comment]
@risadams I just tried, it's working, these are just deprecated warnings, but as shown in this comment https://github.com/selectize/selectize.js/issues/1277#issuecomment-647696823 these functions are deprecated and need be changed which is easy to fix

**Comment by abhij89** [comment]
This is still an issue. I am using selectize v0.13.3 with WordPress 5.7..and there is a deprecation warning:
`selectize.min.js: jQuery.isArray is deprecated; use Array.isArray`


Any thoughts on how can I solve this, I don't want to switch to another library?
