### ISSUE TITLE
on select?

### ISSUE THREAD

**Issue by seabasss** [selectize/selectize.js#1278]
Hey

I've played with the on change, on item_add and on blur, but I would need an on select. Is that possible? I want to trigger an action even if the already selected item is clicked on.

For some reason this doesn't work either.

```

$('.selectize-dropdown').on('click', function(e) {
//...
});
```

Any ideas?

Thanks!

Edit // I actually got it to work the way I want with a combo of change, blur, item_add and item_remove hehe. Problem solved. But if there is way to do on select please let me know. Thanks!

**Comment by rwcorbett** [comment]
probably relates to https://github.com/selectize/selectize.js/issues/256

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
