### ISSUE TITLE
Move items selected (in multiple select) after the input[select]

### ISSUE THREAD

**Issue by kafisher9** [selectize/selectize.js#1284]
Hi,

Ive been working with your code, many thanks for releasing. I was wondering how I might get selected items in the "multiple" demo to sit after the input[select]?

Presently as default they are placed before the input[select]

Open the examples "customization.html"
Steps to reproduce: click on one of the items in the list box

I'd like the selected item to appear in the html page *after* the input:select not before.
Has anyone managed to do this?

This is not a bug, but a question.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
