### ISSUE TITLE
Error with selectize losing focus in Internet Explorer

### ISSUE THREAD

**Issue by sethkyle** [selectize/selectize.js#1285]
I am using the latest version of Selectize on a form. When filling out the form and navigating using the tab, if I make a selection within a Selectize then my form loses focus and the tabbing is back at the beginning of my form. This only occurs in Internet Explorer. You can recreate it by tabbing through the [Selectize home page](http://selectize.github.io/selectize.js/) on Internet Explorer.

**Comment by roblevintennis** [comment]
We're noticing this too for the single select and state examples (anything that doesn't put focus back on the input like multi selects/tags).

It's affecting one of our customers, I'm trying to see if my company will give me time to try to submit a patch but have to wait to find out if that's possible. In any event, I thought I'd provide the attached example which is ie11 in vbox, and confirms @sethkyle reporting of this bug.

![selectize-focus-issue](https://user-images.githubusercontent.com/142403/28096045-d79e1d90-665a-11e7-91c5-e83fb54d9f3d.gif)

**Comment by sethkyle** [comment]
Thanks

Seth Kyle

**Comment by roblevintennis** [comment]
I was having a look at the `selectize.js/examples/basic.html` example, and I notice that for the `select-beast` example, in my IE env, it looks to remove any control div and uses the `<select>` element:
![image](https://user-images.githubusercontent.com/142403/28194634-6ae1b6d4-67fa-11e7-9b78-22276e72e27b.png)

vs. in Chrome where it hides that `<select>` and uses the selectize-control div instead:
![image](https://user-images.githubusercontent.com/142403/28194641-7b922176-67fa-11e7-935e-b3af11c11d3a.png)

This would be nice to utilize as a fallback option as using the raw <select> would seem to preserve focus / tab capabilities in IE (I think). It IS different from what we're seeing on the  Selectize demo page on Internet Explorer as already mentioned which doesn't do this dance of removing the control div and unhiding and using the `<select>`

I'm trying to look at the code to decipher why/how that decision is being made. Perhaps this may be a simple configuration or setup issue? I'll keep digging, but no success figuring this out so far. Any clues from the maintainers would be appreciated 😋

**Comment by mhascak** [comment]
Hi, my sloution is: 
Commented: ` self.$control_input.blur(); `
```
        /**
		 * Closes the autocomplete dropdown menu.
		 */
        close: function () {
            var self = this;
            var trigger = self.isOpen;

            if (self.settings.mode === 'single' && self.items.length) {
                self.hideInput();
                // self.$control_input.blur(); // close keyboard on iOS -- this line caused problem, jus delete or comment it
            }

            self.isOpen = false;
            self.$dropdown.hide();
            self.setActiveOption(null);
            self.refreshState();

            if (trigger) self.trigger('dropdown_close', self.$dropdown);
        },
```

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
