### ISSUE TITLE
Small detail missing for your plugin demo (maxItems)

### ISSUE THREAD

**Issue by WillGoldstein** [selectize/selectize.js#1288]
Hey all,

Just wanted to point out a small detail missing in your "show code" for all your [plugins here](http://selectize.github.io/selectize.js/).

The show code on remove_button, for example, looks like:

$('#input-tags3').selectize({
    plugins: ['remove_button'],
    delimiter: ',',
    persist: false,
    create: function(input) {
        return {
            value: input,
            text: input
        }
    }
});

But when I mimic it, I can't replicate. That's because maxItems, of course, defaults to 1, so you have to say maxItems: 100 or whatever number makes sense greater than 1. Without that, you can't use these great plugins. This is probably something that is super obvious to the developers, but to make it clearer for someone who maybe isn't familiar with selectize, I'd suggest putting it in.

Keep up the great work and thanks!

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
