### ISSUE TITLE
Allow HTML in placeholder

### ISSUE THREAD

**Issue by azhararmar** [selectize/selectize.js#1290]
I want to include font-awesome Icon in the placeholder, I used the following syntax

`<select class="selectize" placeholder='<i class="fa fa-location-arrow"></i>Zipcode'</select>`

The issue is, the HTML is escaped in here, is there a way retain the HTML markup so I can include the icon? I tried with unicode but the problem is, the font "FontAwesome" gets applied to the placeholder text as well which I don't want. Find below the reference on how it renders.

![screen shot 2017-05-26 at 9 23 23 pm](https://cloud.githubusercontent.com/assets/10097624/26502238/a45842f0-4259-11e7-8b56-6583f0e56807.png)

I could easily do this using select2 with following markup.

```
$('.select2').select2({
    escapeMarkup : function(markup) {
        return markup;
    }
});
```
The escapeMarkup retains all the HTML markup, how do I do the same using selectize?

I am trying to achieve the similar result using selectize as in the screenshot below, currently I did it using select2, but now I want to switch to selectize.

![screen shot 2017-05-26 at 9 29 01 pm](https://cloud.githubusercontent.com/assets/10097624/26502511/a84c4126-425a-11e7-8e14-2b2765d0f36c.png)

**Comment by azhararmar** [comment]
I noticed that selectize uses input element whereas select2 uses other markup, and to what I know, HTML specs says that placeholder can only contain string or unicode characters, this kind of explains the limitation.

It would still be nice to know if there is any possible workaround.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
