### ISSUE TITLE
the drop-down list button

### ISSUE THREAD

**Issue by shsh12345** [selectize/selectize.js#1291]
1、Test the environment Google Chrome
2、in the v0.12.3 and v0.12.4
3、In the examples
4、cities.html
5、Click the drop-down list button,choose one option，
6、then Click the drop-down list button 
7、Do not select anything，
8、then you can not close the drop-down list，，，，the  reason  is  your   selectize.js   in    Action   named    close    【self.$control_input.blur(); // close keyboard on iOS】

if   you   Comment  out this sentence[self.$control_input.blur(); // close keyboard on iOS],,,,the   bug   is 
1、in the v0.12.2，，，，，in the v0.12.3 and v0.12.4  also   has   the    bug
3、In the examples
4、cities.html
5、Click the drop-down list button,choose one option，
6、    when   you    Switch the window， the drop-down list is open

my  email    is    1281021077@qq.com

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
