### ISSUE TITLE
searchField to include custom values?

### ISSUE THREAD

**Issue by seabasss** [selectize/selectize.js#1292]
Is it possible to set the searchField to something else than the valueField and labelField?

I'd love if it could search for both of those and also a data-attribute that I set in the option tag or something similar. Is this possible?

Thanks!

**Comment by nickmerwin** [comment]
@seabasss you can achieve this by adding JSON data to your `<option>`, adding the `dataAttr` , and adding the property name to the `searchField` array.

```html
<option value="foo" data-extra-search="{'other':'bar'}">baz</option>
```

```javascript
$(...).selectize({
    dataAttr: 'data-extra',
    searchField: ['value','text','other']
});
```

Now searching "foo", "bar", or "baz" should yield that option.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
