### ISSUE TITLE
Sort tags alphabetically?

### ISSUE THREAD

**Issue by seabasss** [selectize/selectize.js#1293]
Is there a way to automatically sort the tags alphabetically when they're added?

**Comment by arcil** [comment]
` $('.selectize').selectize({
      sortField: 'text'
  });`

should do the trick

**Comment by urmamb** [comment]
Use `sortField` and you should see the sort `sortField: [{field: 'name', direction: 'asc'}]` forexample

```
var select = $('.js_client_search').selectize({
			maxItems	: 1,
			valueField	: 'name',
			labelField	: 'name',
			searchField	: ['name', 'message'],
			options		: [],
			maxOptions	: 30,
			loadThrottle: 0,
			sortField	: [{field: 'name', direction: 'asc'}],
```

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
