### ISSUE TITLE
Don't show the add button if it already exists, case-insensitive

### ISSUE THREAD

**Issue by seabasss** [selectize/selectize.js#1294]
I found a line of code on here to not add a tag if it already exists, but my problem is that it doesn't look for both the label and the value.

`createFilter: function (value)
		{
		    for (var optValue in this.options)
		    {
		        if (optValue.toLowerCase() === value.toLowerCase() && optValue !== value)
		        {
		            return false;
		        }
		    }
		    return true;
		}`

How can I make so this will not show the add button if a tag label is the same as what you enter, no matter what the select value is?

Right now I have some pre-defined tags with numercal option values. If I type the exact same tag name that is pre-defined the add button shows up because it looks for the values, not for the label names.

Thanks for help!

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
