### ISSUE TITLE
Make Persist: false work for programmatically set input value contents

### ISSUE THREAD

**Issue by rosematsa** [selectize/selectize.js#1298]
I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [x] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [x] Indicate *precise* steps to reproduce in *numbers* and the result

Selectize option `persist:false`, which prevents user-entered items from showing up in the dropdown as auto-suggested values, does not work for programmatically set input value contents, as demonstrated in the first Demo titled "Tagging" on the [Selectize page](http://selectize.github.io/selectize.js/). **I need a way to make `persist:false` work for this case as well.**

Steps to reproduce:

1. Set Selectize options
```javascript
var options = {
    plugins: ['remove_button'],
    delimiter: ',',
    persist: false,
    create: function(input) {
      return {
        value: input.replace(/\"/g, ""),
        text: input.replace(/\"/g, "")
      }
    },
    onItemAdd: function(input) {
      var input = input.replace(/\"/g, "");
      anchors.push(input);
      add_anchor(input);
      console.log(anchors);
      console.log("Item added: " + input);
    },
    onDelete: function(value) {
      // convert *value* object to string
      // in order to find it in the anchors array
      anchors.splice(anchors.indexOf( value.toString() ), 1);
      remove_anchor(value);
      console.log(anchors);
      console.log("Item removed: " + value);
    },
    onClear: function() {
      clear_canvas();
    }
  }
```

2. Selectize setup in this function

```javascript
function initSelectize() {
    // parse anchors array to string before passing to search field element
    var searchField = anchors.toString();
    $( ".search-field" ).val(searchField);

    // init selectize
    var $search_bar = $('.search-field').selectize(options);
    // fetch the instance
    var query = $search_bar[0].selectize;
    console.log("Selectize has been initialized.");

    if ( $(".selectize-input").hasClass("has-items") ) {

      $(query.items).each( function(i, item) {
        add_anchor(item);
      });
    }
  }
```

2. The `initSelectize()` function is called once via a click event.
3. If input field has a value prior to initialization, value is parsed into Selectize items.
4. After removing original input field value items, they persist in suggestions dropdown.

Expected result:
`Persist: false` to apply for both programmatically-set and user-entered items.

Actual result:
`Persist: false` only applies for user-entered items.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
