### ISSUE TITLE
Unexpected control blur on item selection

### ISSUE THREAD

**Issue by codinome** [selectize/selectize.js#1301]
I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [x] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [x] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

This issue can be observed in the basic demo on the docs.
Choosing a option on a single select box makes the control lose focus.

Steps to reproduce:

1. Open the dropdown with click, arrow down or auto open;
2. Select an option with click or return key;
3. Observe that the control loses focus. This can be observed on the control, which loses the class "focus". The control also fires the blur event, if one is attached to it.

**Expected result:**
The control should keep focus until the user tabs away or uses another method to trigger the blur event.

**Actual result:**
The control loses focus and the blur event is fired.

This issue is caused by a instruction in the _close_ method that blurs the $control_input. The line reads as:
`self.$control_input.blur(); // close keyboard on iOS`

Simply commenting the line or overriding the method using a plugin solves the issue.
While closing the keyboard is useful on iOS, the instruction causes usability issues on desktop versions of browsers and an unexpected blur event trigger being fired.

A solution could involve enclosing the instruction in a simple check to ensure it only fires on iOS devices. Something like this may suffice (I do not own any iOS device to test this properly):

`if (navigator.userAgent.match(/(iPod|iPhone|iPad)/)) {
    self.$control_input.blur();
}`

_(english is not my native language, sorry for any grammar mistakes)_

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
