### ISSUE TITLE
Continue search without needing to delete already selected item first

### ISSUE THREAD

**Issue by fabiangehring** [selectize/selectize.js#1302]
When an element was selected (i.e. "AB") and the dropdown is clicked again, a curser shows up at the end of the selected item, indicating you can continue to write.
But adding new letters at the end does not work. To search for the item "ABC" the first selected item needs to be deleted and the search text to be entered from the beginning.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
