### ISSUE TITLE
Add minLength option

### ISSUE THREAD

**Issue by JoniJnm** [selectize/selectize.js#1306]
A `minLength` option could be great. I'm using selectize as typeahead (server search) + inputtags. I need a `minLength` option because when the `$control_input` is empty selectize.js shows options and it's uggly.

> minLength: The minimum character length needed before triggering autocomplete suggestions. You can set it to 0 so suggestion are shown even when there is no text when lookup function is called.

I did it by subscribing 'dropdown_open' and `$control_input.on('input')` and hiding the dropdown when  `$control_input.val().length < 3`.

```ts
const minLength = 3;
let selectize = $this.get(0).selectize;
let checkMinLength = () => {
	if ((<any>selectize).$control_input.val().length < minLength) {
		selectize.close();
	}
};

selectize.on('dropdown_open', checkMinLength);
(<any>selectize).$control_input.on('input', checkMinLength);
```

**Comment by rickardd** [comment]
I agree. I need this feature as well.

**Comment by 123maher** [comment]
I agree as well, seems like a basic feature, now i'm forced to handle this on server side

**Comment by mppfiles** [comment]
There is a working example in [the docs](http://selectize.github.io/selectize.js/). See the "Remote Source — Rotten Tomatoes" example. I adapted to something like this:

````javascript
  load: function(query, callback) {
      if (!query || query.length < 3) return callback();  // <- this line
      $.ajax({ 
         // ajax options...

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
