### ISSUE TITLE
jquery-3.2.1.SLIM.min.js  TypeError: self.$dropdown_content.stop is not a function

### ISSUE THREAD

**Issue by delcon** [selectize/selectize.js#1308]
Use jquery-3.2.1.**SLIM**.min.js

use `selectize.default.css `-> everything ok
use `selectize.bootstrap3.css` -> throws error 'TypeError: self.$dropdown_content.stop is not a function' on any change of dropdown

Solution: change to jquery-3.2.1.min.js 

that my save someone hours...
this might be worth adding to requirements

**Comment by gowthamgts** [comment]
Thank you sir.

**Comment by mijowi** [comment]
I ran into the same problem. In case it wasn't obvious above, use the regular **min** version of jQuery, not the **slim** version. Working for me with jQuery 3.3.1 min.js with selectize 0.12.6.

**Comment by dlcmh** [comment]
Yup, the important point is NOT to use the slim version of jQuery - combining selective 0.12.6 with https://code.jquery.com/jquery-3.4.1.min.js from https://code.jquery.com/jquery/ works for me.
