### ISSUE TITLE
Uncaught TypeError: Cannot read property 'jQuery' of undefined

### ISSUE THREAD

**Issue by WebTravel** [selectize/selectize.js#1309]
`<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>`
`<script src="assets/js/selectize.min.js"></script>`

This version 0.12.4

Console mistake "Uncaught TypeError: Cannot read property 'jQuery' of undefined" selectize.min.js:2

**Comment by Pictor13** [comment]
Me:
* created an empty *test.html* file
* created *assets/js/* folder
* added *selectize.min.js* from *dist/js/standalone/selectize.min.js*

and had no error.

If I use the non-standalone, I get:
> Make sure you either: (1) are using the "standalone" version of Selectize, or (2) require MicroPlugin before you load Selectize.

Did you check in *Developer Tools -> Network* that jQuery is getting loaded correctly?

Doesn't look like a *selectize* issue.

**Comment by Pictor13** [comment]
Did you solve the problem?

**Comment by rvnath** [comment]
Having same problem here.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
