### ISSUE TITLE
"create" function override with optgroup_column plugin produces error when using callback

### ISSUE THREAD

**Issue by adam-buckley** [selectize/selectize.js#1310]
I did:

* [x] Search for if my issue has already been submitted
    * I found a similar issue [here](https://github.com/selectize/selectize.js/issues/729) but was closed and details the error occurring on delete, for me it's happening on create
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [x] [Create a *minimal* working example on JsFiddle or Codepen](https://jsfiddle.net/wz08bLk7/2/)
	(or gave a link to a demo on the Selectize docs)
* [x] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

 I'm using the "optgroup_column" and "remove_button" plugins, I'm trying to override the "create" function so I can persist the newly created option to a backend. But I get an error when invoking the callback (so that the create override runs asynchronously):

> selectize.js:2218 Uncaught TypeError: Cannot read property '$order' of undefined

Steps to reproduce:

1. Use the optgroup_column plugin
2. Override the create function
3. Invoke callback

Expected result: item "add" events should fire

Actual result: no events fire after error occurs, resulting in the appearance that everything has worked when it actually hasn't

Note about potential causes:
* The sorting of the optgroups seems to occur twice, failing the second time
* I've tried to see what might cause this precisely but I'm new to selectize and unfamiliar with the 3000+ line codebase, so I apologise for not being able to provide extra info.

Regards,
Adam

EDIT: The options specified in my fiddle may influence the behaviour, so if you cannot recreate the issue with my steps provided, that may be why.

**Comment by AnzeKovac** [comment]
Any news about this issue ?

**Comment by Driiver** [comment]
Still not working

**Comment by jjinkxy** [comment]
A bit late to the game, but in the example `optgroupField: 'tag_type'`, which is also used in the preset options array, so instead of `type`, it also needs to be named `tag_type` in the overwritten create function's option variable:
```js
create: function (input, callback){
       var _this = this;
       // Ajax call to persist changes
      // Issue occurs in the sorting of optgroups triggered by callback below
      // (not anymore after changing type to tag_type)
      var option = {id: (fake_id++), tag: input, tag_type: 'Task'}; 
      callback(option);
```

**Comment by adam-buckley** [comment]
@jjinkxy that works perfectly! I've long since found another way to do what I was trying to achieve, but I can close this off now since it's not an issue with selectize.

Thank you very much for the help!
