### ISSUE TITLE
I want to process according to the elections.

### ISSUE THREAD

**Issue by oguzhansari** [selectize/selectize.js#1312]
Hello,

I have a problem.

Cities are listed.
And with the cities there is the "All" option.

Options;
> All
> City 1
> City 2
> City 3
> City 4
> City 5
> ...
> City 100

That's what I want.
If "All" is selected, the other selections will be canceled.
If "City" is selected, "All" option will be canceled.

How can I do it.
I tried, but it did not.

	var $selectregisterCities = $('[name="registerCities"]').selectize({
		onBlur: function (event) {
			console.log(event);
		},
		onChange: function (event) {
		}, onOptionAdd: function (value, data) {
		}, onOptionRemove: function (value, data) {
		}, onItemAdd: function (value, $item) {
			if (value != "-1") {
				$selectregisterCities[0].selectize.removeOption("-1", true);
				$selectregisterCities[0].selectize.addOption({ value: "-1", text: "Tümü" });
				$selectregisterCities[0].selectize.refreshOptions();
			} else {
				$selectregisterCities[0].selectize.destroy();
				$selectregisterCities = $selectregisterCities;
			}
		}, onItemRemove: function (value) {
		}
	});

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
