### ISSUE TITLE
Reinitialize Select

### ISSUE THREAD

**Issue by fusion2013** [selectize/selectize.js#1313]
Hi,

I am using selectize, and on basis of some condition I need to add multiple item, but also need to add remove_button plugin. 

Anyone have idea how I can do it.

Thanks

**Comment by Pictor13** [comment]
I would initialize the plugin with the selectize.
Then would work more on creating (or render) items with a CSS-class or data-attribute that tells wether to show the remove-button or not. And based on your conditions add/remove that class.
Something like
```
...,
onItemAdd: function(value, $item) {
        isRemovable(value) ? $item.removeClass('not-removable') : $item.addClass('not-removable');
    }
```
```
.not-removable .remove { display: none; }
```

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
