### ISSUE TITLE
Changing the dropdown element to <ul>?

### ISSUE THREAD

**Issue by Swennet** [selectize/selectize.js#1316]
I would like to edit the dropdown element of my selectize field so that it's a `<ul>` element with a specific class. Is this possible using the render option?

EDIT: Alternatively, just being able to wrap all the items with a custom element would be great too.

 I'm using this code right now:

```
$('#my-input').selectize({				
	render: {
		option: function(item, escape) {
			return '<li><span class="tag-item selectize-tag">' + escape(item.name) + '</span></li>';
		}
	},

	create: function(input) {
		return {
			value: input,
			text: input
		}
	}
});
```

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
