### ISSUE TITLE
'Load' property breaking css

### ISSUE THREAD

**Issue by Pateyl** [selectize/selectize.js#1317]
Hi,
My solution is based on "Email Contacts".
When a user writes the first letter then the input is moving into the middle.

Picture before enter value:
![before](https://user-images.githubusercontent.com/29894362/29280167-6fce9bba-811a-11e7-8e63-77d78f7187af.png)

Picture after enter value:
![after](https://user-images.githubusercontent.com/29894362/29280166-6fc6e956-811a-11e7-94d8-4f73a7529daf.png)

I find out that reason, why is moving, is 'load' property (even when is empty) but I don't know why. After removing property It's work fine.

Please, can you help me?

Best regards
Jan

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
