### ISSUE TITLE
Using selectize.js with a predefined selected values at init

### ISSUE THREAD

**Issue by amagnier** [selectize/selectize.js#132]
Here is my HTML part :

```
             <select onchange="refreshIvr();" id="ivrselect" class="vhc" />
```

I use this JS

```
mySelectize = $('#ivrselect').selectize(
    {
        preload: true,
        valueField: 'path',
        labelField: 'name',
        searchField: 'name',
        create: false,
        sortField: 'name',
        load: function(query, callback) {

                                   .... query implementation ...

                        callback( result );
                    }
                }
            );
        }
    }
);
```

This is fine but i want now to  define a presecled value  at init of my page when this is available :

I tried this :

```
                   <select onchange="refreshIvr();" id="ivrselect" class="vhc" style="width:180px;">
                                      <option selected="true" data-data="{ path:'aaaa' , name:'bbb'}">bbbbb</option> 
           </select>
```

But when JS initialize the component i ve some JS error :

Uncaught SyntaxError: Unexpected token p selectize.js:2709
readData selectize.js:2709
addOption selectize.js:2720
init_select selectize.js:2752
(anonymous function) selectize.js:2769
e.extend.each jquery-1.7.2.min.js:2
e.fn.e.each jquery-1.7.2.min.js:2
$.fn.selectize selectize.js:2757
(anonymous function)

Any idea pls ?

**Comment by tjperovich** [comment]
@notflip `$(xxxx).data('data')` will return the data-data attribute. Check the [docs](http://api.jquery.com/data/).

**Comment by notflip** [comment]
Waw one year later now. What a stupid question :) thanks!

**Comment by tjperovich** [comment]
ha I didn't even notice the year! whoops!

**Comment by notflip** [comment]
It's weird to see the things you didn't know one year ago. Improvements! [/offtopic]
