### ISSUE TITLE
Updating tags and using autocomplete at the same time

### ISSUE THREAD

**Issue by alinr2** [selectize/selectize.js#1322]
Hi,

What I try to do:
I have recipes with related tags.
In my edit form I want to:

- Display the already associated tags with the recipe
- Add new tags. Here I want to use autocomplete by asking the database for already existing tags.

This is my script:

`var $select = $('#tags').selectize({
                valueField: 'id',
                labelField: 'value',
                searchField: 'value',
                options: [
                    @foreach ($recipe->tagged as $tag)
                    {id: {{ $tag->id }}, value: '{{ $tag->tag_slug }}'},
                    @endforeach
                    ],
                create:true,
                render: {
                    option: function(item, escape) {

                        return '<div>' +
                                '<span class="name">' + escape(item.value) + '</span>' +
                                '</div>';
                    }

                },
                load: function(query, callback) {
                    if (!query.length) return callback();
                    $.ajax({
                        url: '/search/tag_autocomplete',
                        type: 'GET',
                        data: {
                            term: query
                        },
                        error: function() {
                            console.log('error');
                            callback();
                        },
                        success: function(res) {
                            //console.log(res[0].value);
                            callback(res);
                        }
                    });
                }

            });

            var selectize = $select[0].selectize;
            @foreach ($recipe->tagged as $tag)
            selectize.addItem({{ $tag->id }});
            @endforeach`

I am not sure if this is really an issue. If not, sorry for the inconvenience. Issue can be then closed.

By using this the autocomplete only shows the already used tags. If I use: options: [] then the autocomplete will show all tags available, but I miss the already used tags.

How can I use both:

1. Displaying the attached tags AND
2. Using autocomplete for ALL existing tags

**Comment by flakerimi** [comment]
1. Just do loop on select.
```    
<?php foreach ($tags as  $value) {
        echo '<option value="'.$value->id.'" selected>'.$value->name.'</option>';
    } ?>
```
2. create tags 

```
create:function (input, callback){
        
              $.ajax({
                    url: '/api/v1/tags/'+ input,
                    type: 'post',
                    data: {input},
                    success: function (result) {
                        if (result) {
                            addItem()
                           return callback({ id: result.id, name: result.name });
                        }
                    }
                });
           },    
```
Extra: Full script

```
    $('#Form-field-Post-tags').selectize({

    create:function (input, callback){
        
              $.ajax({
                    url: '/api/v1/tags/'+ input,
                    type: 'post',
                    data: {input},
                    success: function (result) {
                        if (result) {
                            addItem()
                           return callback({ id: result.id, name: result.name });
                        }
                    }
                });
           },    
    sortField: 'name',
    valueField: 'id',
    labelField: 'name',
    searchField: 'name',
 
    load: function(query, callback) {
        if (!query.length) return callback();
        $.ajax({
            url: '/api/v1/tags/search/' + encodeURIComponent(query),
            type: 'GET',
            error: function() {
                callback();
            },
            success: function(res) {
                console.log(res);
                  callback(res);

            }
        });
    } 

});

```

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
