### ISSUE TITLE
How to not open the dropdown when an item is removed or added

### ISSUE THREAD

**Issue by parthladani** [selectize/selectize.js#1323]
I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [ ] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [x] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

I want to close the drop-down every time an item is removed. but as soon as I remove the item. the drop-down remains open. I have tried to fix this by following many of the old issues reported and answered here but didn't got any success. 

Steps to reproduce:

1. add the item to the field by selecting any of the options from the drop-down.
2. add one more item by repeating step 1. 
3. now remove an item from the field.

Expected result: the drop down should remain closed until I type something for next item.

Actual result: the drop down remains open with all the available options.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
