### ISSUE TITLE
How to get previously selected items of the active dropdown?

### ISSUE THREAD

**Issue by abdussami-tayyab** [selectize/selectize.js#1326]
I am allowing the addition of items and initialising the selectize element like this:

```
var selectize = $('.selectize-multiple').selectize({
            persist: false,
            placeholder: 'Choose options or add your own',
            create: function (input, callback) {
                callback({
                    value: input,
                    text: input
                });
            }
        });
```

So, when I add an element, it is added to the list like this:
```
<div data-value="1" class="item">Android</div>
<div data-value="2" class="item">HTML5</div>
<div data-value="www" class="item">www</div>
```

What I want is to get the next ID in data-value and not the value like shown above:
```
<div data-value="1" class="item">Android</div>
<div data-value="2" class="item">HTML5</div>
<div data-value="3" class="item">www</div>
```

I have researched how to solve this but failed, if I can know where these list elements stored in the _[Selectize]_ object, I can do what I want to do perhaps.

**Comment by cdevroe** [comment]
@abdussami-tayyab In your anonymous create function you can use `this.items` to determine the length of items to set the value to that number.

Here is your code with changes:
`var selectize = $('.selectize-multiple').selectize({
            persist: false,
            placeholder: 'Choose options or add your own',
            create: function (input, callback) {
                callback({
                    value: this.items.length,
                    text: input
                });
            }
        });`

I gave it a try and it seems to work.
