### ISSUE TITLE
Selectize js submitting only last selected item

### ISSUE THREAD

**Issue by bigweld86** [selectize/selectize.js#1328]
Hello,

I'm currently using Selectize.js with a 'select' item and multiple options. My html is something like:

```
<div class="form-group">
                    <label for="record-genre">Genre(s):</label>
                    <select name="record_genre" id="record-genre" class="form-control multi-selectize" multiple="multiple" placeholder="Enter genre(s)">
                        <?php foreach ($record_genre_opts as $key => $val): ?>
                            <option value="<?php echo $key; ?>" <?php echo (in_array($key, $record_genre)) ? "selected" : ''; ?>
                                <?php echo set_select('record_genre', $val); ?>
                            >
                                <?php echo $val; ?>
                            </option>
                        <?php endforeach;?>
                    </select>
                </div>


```
So far so good. The items are being loaded correctly and until this point everything works great. The issue is that when the form is submitted only the last value selected is the one that is available, so if I selected multiple items I'm getting just one:

> ["record_genre"]=> string(1) "1"

Here's my JS setup:
```

$('.multi-selectize').each(function(){
            //console.log($(this))
            $(this).selectize({})

        })
```

Where is it failing?

Thanks.

**Comment by Pictor13** [comment]
Yes, (for others having the same issue) that's because of using PHP on the server side to [process the submitted array of values](http://php.net/manual/en/faq.html.php#faq.html.arrays).

@bigweld86 You should be able to close the ticket yourself. Unfortunately there is nobody here taking care of closing tickets, and they are accumulating there 😕

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
