### ISSUE TITLE
Text jumps when any language with non-English letters used

### ISSUE THREAD

**Issue by m1lk1way** [selectize/selectize.js#1336]
When i use any language with non-Engilsh letters, for example Russian, inside selectize - text jumps (horizontally) when i'm typing.
Its caused by use of **event.keyCode()** and result of it inside **String.fromCharCode()** to detect text width in measureString function.
But if you use Russian and trying to type 'Ф', for example, event.keyCode() result will be 65 and String.fromCharCode() will be English 'A' so its width will be definitely wrong.

**Comment by yurikburko** [comment]
Faced with the same problem. Fix works for me now.

**Comment by valeriya9292** [comment]
I have the same issue, thanks for fix

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
