### ISSUE TITLE
Cannot set property 'Sifter' of undefined after using babel

### ISSUE THREAD

**Issue by carlotrimarchi** [selectize/selectize.js#1341]
I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [x] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [x] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

I'm experiencing a weird issue with Selectize. When I load a page where I'm loading the plugin, in the console I get the error "Cannot set property 'Sifter' of undefined" and the plugin just doesn't work.

Before today, I've been using it for a while. What apparently caused the issue was that I added a console.log() to the Selectize source code for a quick test and this caused to put the code through my gulp workflow, which since recently includes also the babel compiler. The preset I'm using is simply "es2015".

The whole gulp task for js is this:

```
gulp.task('js', function () {
    return gulp.src('./resources/assets/js/**/*.js')
        .pipe(changed('./public/js'))
        .pipe(sourcemaps.init())

        .pipe(babel({
            presets: ['es2015']
        }))

        .pipe(print())
        .pipe(uglify())
        .pipe(sourcemaps.write('./maps'))
        .pipe(gulp.dest('./public/js'));
});

```

Simply removing babel from it makes it to work again.
I created two pens, using the code after it's gone through the gulp task (minus the uglify, so it's readable).

This is the one using babel: https://codepen.io/qarlo/pen/oGRBeN
If you open the console, you can see the error.

This is without babel, and it works: https://codepen.io/qarlo/pen/VMOzLP

**Comment by dhamaniasad** [comment]
Thanks for this issue! It helped me track down an issue after hours of fruitless debugging. If you or anyone else knows _why_ this happens, it would be great insight.

**Comment by mdahlke** [comment]
Do we know why this is happening? Anything that can be done to fix the error?

**Comment by kostt** [comment]
presets: ['es2015'], compact: true, ignore: ['selectize.min.js']

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.

**Comment by Cryfear** [comment]
how to fix it?
