### ISSUE TITLE
Dropdown scroll not working on IE

### ISSUE THREAD

**Issue by kousenlsn** [selectize/selectize.js#1343]
When trying to scroll from the scrollbar a dropdown of any selectize instance, the dropdown loses focus.
Only on IE, and lastest version.

**Repro example:**
1. Try open on IE: (version 11.1770.14393.0)
   http://selectize.github.io/selectize.js/
2. Go to any selectize where as the dropdown has many options creating scroll
3. Click on the scroll (bar or arrows), the dropdown will close.

Opening a new issue as all the other old Issues posts are deprecated and none fix have worked for this new version here.

**Comment by refringe** [comment]
I can reproduce this.

**Comment by mrosenberger67** [comment]
Fix from @sivakumarganga is working for me.

**Edit**: selectize doesn't close on document click now :(

**Comment by iamnimnul** [comment]
I can reproduce this bug on IE 11.0.9600.18816.

- Download [IE11 on Win7 (x86) VM](http://selectize.github.io/selectize.js/)
- Install [KB4040685](http://download.windowsupdate.com/d/msdownload/update/software/secu/2017/09/ie11-windows6.1-kb4040685-x86_086c709a4041399c2f47d6d7c8ac08b3656d0136.msu) update 
- Open selectize [demo](http://selectize.github.io/selectize.js/) website
- Scroll to `Option Groups`, open `Gear` selectize, click on scrollbar.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
