### ISSUE TITLE
truncated word in drop down

### ISSUE THREAD

**Issue by trudynamica** [selectize/selectize.js#1345]
I did:

* [ x] Search for if my issue has already been submitted
* [ x] Make sure I'm reporting something precise that needs to be fixed
* [x ] Give my issue a descriptive and concise title
* [ x] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [ ] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

[replace me with a short description of issue]

Steps to reproduce:

1. Create a drop down list with multiple items starting with word house.
2. Make sure some of them have long  names
3.In the Select box as You start typing House , the list changes House to H. For example House Of Cards will change to H Of Cards

Expected result: House Of Cards

Actual result: H Of Cards

**Comment by jag2136** [comment]
I believe this unreleased (but working) pull request addresses this issue as well:
#1193 

Didn't try your exact test case, but I tested a very similar one I was having, and the fix resolved it.

**Comment by mcavalletto** [comment]
I agree with jag2136 that this issue has been fixed in master but not yet released.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
