### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by sflang1** [selectize/selectize.js#1348]
Hi!

This is a question more than an issue. Is it possible to make a selectized control to perform its Javascript content without altering the previous CSS behavior of my template?

Thanks a lot!

**Comment by TakesTheBiscuit** [comment]
How would you tackle adding the css styles needed to make this work?

Selectize works by hiding the original select box and creating a dummy select box using css and html with a sprinkling of JS for the injection and driving the setting of the original select box value.

So you see i don't really know how you could use selectize in any other way?
Perhaps just write some over-riding (cascaded) styles to alter how selectize appears for you?

```
		<style type="text/css">
		.selectize-control .option .title {
			display: block;
		}
		.selectize-control .option .url {
			font-size: 12px;
			display: block;
			color: #a0a0a0;
		}
		.selectize-control .item a {
			color: #006ef5;
		}
		.selectize-control .item.active a {
			color: #303030;
		}
		</style>
```
see more here:
https://github.com/selectize/selectize.js/blob/master/examples/customization.html
