### ISSUE TITLE
Provided Selected Items Not displayed in box

### ISSUE THREAD

**Issue by rbeckACQ** [selectize/selectize.js#1350]
I did:

* [X ] Search for if my issue has already been submitted
* [ X] Make sure I'm reporting something precise that needs to be fixed
* [ X] Give my issue a descriptive and concise title
* [ ] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [ X] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

I have a select box that retrieves a list of items from an AJAX query. I want to be able to preselect items in that box when the page loads.

The items are not preselected.

Steps to reproduce:

1. Enter a list of items such as items: ['value1','value2']
2.Refresh page
3.

Expected result:

Items value1.text and value2.text are visible in the select box.

Actual result:

Select box is empty.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
