### ISSUE TITLE
Regex fails

### ISSUE THREAD

**Issue by Dinesh-Wasnik** [selectize/selectize.js#1351]
@brianreavis 
Email contact accepting value like this 'a@go'.

How to replicate

Type email address in input upto @ sign(like xxx@xxx) and wait for hinting box .i.e 'Add text'
and then hit enter.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
