### ISSUE TITLE
7kb? min is 39kb and standalone is 45kb, let alone css files

### ISSUE THREAD

**Issue by voltuer** [selectize/selectize.js#1352]
Just wanted to know what do you mean by 7kb on the description.

<3

**Comment by MicahBrown** [comment]
The description mentions 7KB when it's **gzipped**. Gzipping is different from minification. 

https://css-tricks.com/the-difference-between-minification-and-gzipping/

**Comment by databyte** [comment]
Yep, that's it.

**Comment by voltuer** [comment]
thanks for replying and closing 3 years later, lol

**Comment by databyte** [comment]
Yep, nothing like spring cleaning in Nov!
