### ISSUE TITLE
Results is loaded in the browser but didn't appear in the Dropdown menu

### ISSUE THREAD

**Issue by TahseenAlaa** [selectize/selectize.js#1362]
Hi, i got issue when typing in search field, I just got 10 results (the results are loaded in the browser but didn't appear in the  #Dropdown menu of Selectize), where is the problem ?

![a](https://user-images.githubusercontent.com/10079531/34724054-9722d39a-f55d-11e7-917d-7fff19fc56ad.jpg)

![aa](https://user-images.githubusercontent.com/10079531/34724055-975687f8-f55d-11e7-84fb-efa6c8a41fd5.jpg)

![aaa](https://user-images.githubusercontent.com/10079531/34724131-d54bdbc6-f55d-11e7-973b-ba494962539d.jpg)

Note // the Selectize in modal of DataTables and the back end is laravel. Here is the Code

___________________________________________________________________________________

`

        $(document).on('mouseover', '#selectize', function (e) {

        });

        //Editor Script
        var url = window.location.origin;
        var editor;  // use a global for the submit and return data rendering in the examples
        $(document).ready(function () {
                editor = new $.fn.dataTable.Editor({
                    ajax: {
                        url: url + '/cart_getter',
                        type: 'POST',
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    },
                    table: "#table_id",
                    idSrc: "id",
                    fields: [{
                        label: "@lang('orders.search'){{ ':' }}",
                        name: "search",
                        id: 'selectize',
                        className: '{{ App::isLocale('ar')? 'font-ar' : '' }}'
                    }, {
                        label: "RowId:",
                        name: "rowId",
                        id: 'rowId',
                        type: 'hidden'
                    }, {
                        label: "@lang('orders.product_name'){{ ':' }}",
                        name: "name",
                        type: "readonly",
                        id: 'product_name',
                        className: '{{ App::isLocale('ar')? 'font-ar' : '' }}'
                    }, {
                        label: "@lang('products.buy_price'){{ ':' }}",
                        name: "options.buy_price",
                        type: "readonly",
                        id: 'buy_price',
                        className: '{{ App::isLocale('ar')? 'font-ar' : '' }}'
                    }, {
                        label: "@lang('orders.currency'){{ ':' }}",
                        name: "buy_currency",
                        type: 'select',
                        id: 'buy_currency',
                        options: [{label: "@lang('orders.dinar')", value: "1"}, {label: "@lang('orders.dollar')", value: "0"}],
                        className: '{{ App::isLocale('ar')? 'font-ar' : '' }}'
                    }, {
                        label: "@lang('orders.sell_price'){{ ':' }}",
                        name: "price",
                        id: 'sell_price',
                        className: '{{ App::isLocale('ar')? 'font-ar' : '' }}'
                    }, {
                        label: "@lang('orders.currency'){{ ':' }}",
                        name: "options.sell_currency",
                        type: 'select',
                        id: 'sell_currency',
                        options: [{label: "@lang('orders.dinar')", value: "1"}, {label: "@lang('orders.dollar')", value: "0"}],
                        className: '{{ App::isLocale('ar')? 'font-ar' : '' }}'
                    }, {
                        label: "@lang('orders.quantity'){{ ':' }}",
                        name: "qty",
                        id: 'quantity',
                        className: '{{ App::isLocale('ar')? 'font-ar' : '' }}'
                    }
//                    {
//                    label: "Discount ( % ):",
//                    name: "options.discount",
//                    id: 'discount',
//                },

                    ]
                }).on('open', function (e, type) {
                    var lists = [];
                    $('#buy_currency').attr('disabled', 'true');
                    $('#selectize').selectize({
                        placeholder: '@lang('orders.search_for_products')',
                        valueField: 'id',
                        labelField: 'product_name',
                        searchField: 'product_name',
                        create: false,
                        maxItems: 1,
                        onItemAdd(value, $item) {
                            let result = lists.find((item) => {
                                if (item.id == value) {
                                    return item
                                }
                            });

                            //START Client Side Validation
                            editor.on( 'preSubmit', function ( e, o, action ) {
                                if ( action !== 'remove' ) {

                                    var qty   = this.field( 'qty' );
                                    if ( qty.val() === '0'  ) {
                                        qty.error( '@lang('validation.not_zero')' );
                                    }
                                }
                                // ... additional validation rules
                                // If any error was reported, cancel the submission so it can be corrected
                                if ( this.inError() ) {
                                    return false;
                                }
                            } );
                            //END Client Side Validation

                            $('#product_name').val(result.product_name);
                            $('#buy_price').val(result.buy_price);
                            $('#sell_price').val(result.sell_price);
                            $('#buy_currency').val(result.buy_currency);
                            $('#sell_currency').val(result.sell_currency);
                            $('#quantity').val("1");
//                        $('#discount').val("0");
                        },
                        onOptionAdd(value, data) {
                            lists.push(data);
                        },
                        onFocus() {
                            this.clearOptions();
                        },

                        load: function (query, callback) {
                            var csrf_token = $('meta[name="csrf-token"]').attr('content');
                            if (!query.length) return callback();
                            $.ajax({
                                url: 'search',
                                type: 'POST',
                                data: {'query': query, "_token": csrf_token},
                                error: function () {
                                    callback();
                                },
                                success: function (res) {
                                    callback(res.slice(0, 10));
                                }
                            });
                        }
                    });

`

**Comment by IQ-Coder** [comment]
@brianreavis  @joallard  could you check it please ?

**Comment by TahseenAlaa** [comment]
I solved it by changed the search query in the back end.
