### ISSUE TITLE
Empty space above dropdown with jQuery 3.2.1 and Chrome

### ISSUE THREAD

**Issue by irfanullahjan** [selectize/selectize.js#1365]
When using jQuery 3.2.1, I get UI glitch in Chrome. There is empty space between input and dropdown as shown in the screenshot. Going back to jQuery 2.x fixes this issue.

This happens in chrome Version 63.0.3239.132 but not in Edge.

![screenshot 4](https://user-images.githubusercontent.com/7108679/34942054-0709a79c-fa18-11e7-8994-8366e3078398.png)

I verified this by using only the code from your demos and upgrading only jQuery to make sure my CSS is not causing this.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
