### ISSUE TITLE
Documentation does not list dependency on JQuery UI

### ISSUE THREAD

**Issue by developher-net** [selectize/selectize.js#1366]
Selectize has an undocumented dependency on JQuery UI:
https://github.com/selectize/selectize.js/blob/47e048662d865c4f1ea3b2337de5e06e92fd9530/dist/js/selectize.js#L2877

This is not listed anywhere in the documentation or dependency lists:

1. https://github.com/selectize/selectize.js#dependencies
2. https://github.com/selectize/selectize.js/blob/master/package.json
3. https://github.com/selectize/selectize.js/blob/master/yarn.lock

This came as a surprise when our platform was removing JQuery UI dependencies. Luckily we're not dependent on the drag-and-drop feature, but it took a while to trace down that Selectize expected JQuery UI.

**Comment by risadams** [comment]
fixed in #1556
