### ISSUE TITLE
Remove disgusting style attributes

### ISSUE THREAD

**Issue by Knudian** [selectize/selectize.js#1368]
I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [x] Create a *minimal* working example on JsFiddle or Codepen (see below)
* [x] Indicate *precise* steps to reproduce in *numbers* and the result,

Extract from an existing implementation of Selectize in one project :
- original :
```html
<div class="col-xs-3">
    <p id="clientNameHelp" class="help-block hidden" data-i18n="field.client.helper"></p>
    <select class="form-control input-sm" id="clientId" name="client"></select>
</div>
```
- output : 
```html
<div class="col-xs-3">
    <p id="clientNameHelp" class="help-block hidden" data-i18n="field.client.helper"></p>
    <select class="form-control input-sm selectized" id="clientId" name="client" tabindex="-1" style="display: none;">
        <option value="" selected="selected"></option>
    </select>
    <div class="selectize-control form-control input-sm single">
        <div class="selectize-input items not-full">
             <input type="select-one" maxlength="null" autocomplete="off" tabindex="" id="clientId-selectized" style="width: 4px; opacity: 1; position: relative; left: 0px;">
        </div>
        <div class="selectize-dropdown single form-control input-sm" style="display: none; visibility: visible; width: 359px; top: 34px; left: 0px;">
        <div class="selectize-dropdown-content"></div>
     </div>
</div>
```

Steps to reproduce:
Initiate Selectize on any input

Expected result:
A clean non-modified HTML markup.

Actual result:
A dirtied HTML markup full of "style" attributes.

---
In reality, even if as the example suggests it, I am using Bootstrap, the added styling messes all the styling, not only mine, but also Bootstrap.

If someone knows of a workaround to override this behavior of Selectize (ie : only the added _style_ attributes), please tell me. I don't want to create a fork of the library just for that puny little thing.

**Comment by NashBridgesAT** [comment]
+1

**Comment by NashBridgesAT** [comment]
Hi
I was facing a similar problem yesterday. I realized that the style attributes are not caused by selectize, but by bootstrap itself. Reformatting my html solved the problem. In my case it happened using an inline form, where you have to define the width specifically for the input fields. I have solved this problem replacing the inline form with a `form-horizontal`. You can easily find it in the [bootstrap docs](https://getbootstrap.com/docs/3.3/css/#forms-horizontal).
