### ISSUE TITLE
Keep options selected order

### ISSUE THREAD

**Issue by luixal** [selectize/selectize.js#1369]
**DISCLAIMER**: this is a question about something I couldn't find in the docs and could be a feature request, not an issue.

Hi,

I've searching around the docs, older issues and google, but couldn't find a solution for what I'm looking for. The closest issue seems to be #641 .

Excepted behaviour: having a multiple selector, click on several options, having as a result and array keeping the order in which the options were selected.

This is: if I have a selector with options `['A', 'B', 'C']` and I click on B, C and A, the resulting array should be `['B', 'C', 'A']` instead of `['A', 'B','C']`.

Any idea on how to get this behaviour with selectize.js?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
