### ISSUE TITLE
Moving search box inside the dropdown

### ISSUE THREAD

**Issue by FinPayTech** [selectize/selectize.js#1372]
is it possible for move the search box inside the dropdown menu ?

**Comment by mcavalletto** [comment]
This is possible but would require custom programming. Good luck!

**Comment by jazzvanz** [comment]
Looking into doing this myself. Will post my solution if it is reasonable.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
