### ISSUE TITLE
Possible to add classes to set configurations?

### ISSUE THREAD

**Issue by piercemcgeough** [selectize/selectize.js#1373]
I am wondering if there is a way to set additional configuration settings without doing it from the init?

Im looking to see if i could add a class selectize_no_create to stop the create method from being called.

I have defaults set as below and create specific classes for certain type of people. I have come across 1 situation where I don't want the create function. As you can see below I use `selectize__buyer_no_create` and the appropriate options are set.

```
$('.selectize').selectize($.extend(true, {}, selectizeDefaults));
$('.selectize__buyer').selectize($.extend(true, {}, selectizeDefaults, buyerOptions));
$('.selectize__buyer_no_create').selectize($.extend(true, {}, selectizeDefaults, buyerOptionsNoCreate));
$('.selectize__owner').selectize($.extend(true, {}, selectizeDefaults, ownerOptions));
$('.selectize__tenant').selectize($.extend(true, {}, selectizeDefaults, tenantOptions));
```

Is there a way to make it work that I would do the following where I just add a selectize_no_create to the select box?

```
<select id="buyer_id" name="buyer_id" class="form-control selectize__buyer selectize_no_create pull-left" placeholder="Select a buyer..." data-rule-required="true">
   <option value="">Select a buyer...</option>
   {foreach $buyers as $buyer}
        <option value="{$buyer.id}"
                {if $buyer.id eq $form_data.buyer_id}selected="selected"{/if}
                data-data="{htmlspecialchars($buyer|@json_encode, ENT_QUOTES, 'UTF-8')}">
            {$buyer.name_alpha_order}
        </option>
   {/foreach}
</select>
```

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
