### ISSUE TITLE
Refresh tags list after updating input field

### ISSUE THREAD

**Issue by BackInBiz** [selectize/selectize.js#1374]
Sorry if my question has been already ask but is there already a function to update serialize tag list after updating my empty input field in AJAX.

I'm loading the serialize input with basic code.
`				 	
	     $('.meta').selectize({
			plugins: ['remove_button'],
			delimiter: ', ',
			persist: false,
			create: function(input) {
				return {
					value: input,
					text: input
				}
			}
		});`

But after i'm refreshing the input field in ajax and i want to split word added to a tag list.

Value is empty, i'm refreshing with "A lit, of different, tags" and i want to have my 3 tags shown.

Thanks

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
