### ISSUE TITLE
CSS class not updated after removing selected option

### ISSUE THREAD

**Issue by hkericb** [selectize/selectize.js#1375]
The class "selected" not removed after deleting the selected value from the input field.

Steps to reproduce:

1. Open demo page (http://selectize.github.io/selectize.js/)
2. Scroll to the section "Single Item Select"
3. Select the option "Chuck Testa" in the dropdown menu
4. Remove the selected option in the input field by backspace.

Expected result: The option "Chuck Testa" should not contain the "selected" CSS class.

Actual result: The option "Chuck Testa" still contains the "selected" CSS class.

![screen shot 2018-02-22 at 8 08 11 pm](https://user-images.githubusercontent.com/7336352/36537816-3204e486-180c-11e8-9620-ed5810d9f939.png)
![screen shot 2018-02-22 at 8 08 31 pm](https://user-images.githubusercontent.com/7336352/36537817-323630e0-180c-11e8-9b65-2efd6260b143.png)

**Comment by mcavalletto** [comment]
I was able to reproduce this as described above.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.

**Comment by hkericb** [comment]
@risadams issue still exists
