### ISSUE TITLE
Clicking Outside of Drop down Triggers on Change

### ISSUE THREAD

**Issue by ameshkin** [selectize/selectize.js#1376]
We are having a strange issue where clicking outside of a select box is triggering an on change.

I have tried openOnFocus: false

This kind of fixes the problem but then the user is forced to click on the arrow, and the input box is no longer clickable.

Has anyone had this issue?  Or do we have other css or js that could be interfering?

**Comment by mcavalletto** [comment]
There's not enough detail here to solve your problem. Create a minimal example on CodePen or JSFiddle that has just enough code to demonstrate the issue.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
