### ISSUE TITLE
Dropdown box not closing with an item already selected

### ISSUE THREAD

**Issue by hkericb** [selectize/selectize.js#1377]
Cannot close the dropdown if there is an item already selected.

Steps to reproduce:

1. Open demo page (http://selectize.github.io/selectize.js/)
2. Scroll to the section "Single Item Select"
3. Select the option "Chuck Testa" in the dropdown menu
4. Expand the dropdown box again by clicking on the arrow down icon.
5. Click on the arrow up icon.

Expected result: The dropdown box will collapse.

Actual result: The dropdown box will collapse and expand again.

**Comment by mcavalletto** [comment]
I am able to reproduce this as described above.

**Comment by ghost** [comment]
there's a fix for this, in case you still need it... https://github.com/selectize/selectize.js/issues/1261#issuecomment-340445999

**Comment by ErnestBrandi** [comment]
I'd like an official fix for that !

**Comment by mlncn** [comment]
Would also very much like a fix in Selectize for this bug or at least an option to have this behavior, and the wider behavior sought in #1261 (pressing an open dropdown in a place that doesn't make a selection or de-selection should close the dropdown).
