### ISSUE TITLE
Clicking optgroup closes dropdown

### ISSUE THREAD

**Issue by samesfahani** [selectize/selectize.js#1382]
I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [x] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [x] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

Example: http://www.iainheng.com/assets/fo/scripts/selectize0/examples/optgroups.html

If you open up any of the dropdowns on the demo with an optgroup, clicking the optgroup will close the entire dropdown even with `closeAfterSelect` set to false. This behavior is not standard with native optgroups.

**Comment by samesfahani** [comment]
Possible culprit: https://github.com/selectize/selectize.js/blob/master/src/selectize.js#L226

Seems like this logic doesn't handle the case where `e.target` was the `div` that represents the optgroup. Adding something like a `|| $.contains(self.$dropdown[0], e.target)` to the condition set (to short circuit) might fix the issue... Can't speak to how performant that is though.

**Comment by MeesterDev** [comment]
I think https://github.com/selectize/selectize.js/pull/762 should fix this.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
