### ISSUE TITLE
Selectizejs isn't loading the options correctly

### ISSUE THREAD

**Issue by elieobeid7** [selectize/selectize.js#1383]
I'm using ajax, creating a dependent category and subcategory, everything works, my html is valid, I'm using selectizejs on both category and sub category. the category is working fine, the subcategory isn't. If I don't use selectize, everything works perfectly

     $(".category").change(function () {
         var id = $(this).val();
         var dataString = 'id=' + id;
    
         $.ajax
             ({
                 type: "POST",
                 url: "subcat.php",
                 data: dataString,
                 cache: false,
                 success: function (html) {
                     $(".subcat").html(html);
                 }
             });
     });
    $('#subcat').selectize({
        plugins: ['remove_button'],
        persist: false,
    });

`index.php`

    <label class="control-label col-md-3 col-3">Sub Category <span class="required">*</span>
    <select name="post[subcategory]" class="subcat" id="subcat">
    <option selected="selected" value="">Select Sub Category</option>
    </select> </label>

`subcat.php`

    foreach ($children as $child) {?>
    <option value="<?php echo $child->id; ?>"><?php echo $child->name ?></option>
    <? } ?>

[![enter image description here][1]][1]

No errors in console. Again, if I remove selectize, I get a perfectly normal dropdown. 

  [1]: https://i.stack.imgur.com/ivbfM.png

**Comment by TahseenAlaa** [comment]
Hi, I would help but don't spot your issue ...
however SelectizeJS had many issues not yet fixed.

**Comment by elieobeid7** [comment]
@TahseenAlaa forget about it, I had the following two issues

https://stackoverflow.com/questions/49162665/selectizejs-dynamically-generated-select-elements

https://stackoverflow.com/questions/49158849/selectizejs-isnt-loading-the-options-correctly

I just switched to chosenJS and everything is working fine now,

**Comment by TahseenAlaa** [comment]
@elieobeid7 Thats Amazing, I will switch my project too, thanks
