### ISSUE TITLE
On focus scrolls the HTML Table

### ISSUE THREAD

**Issue by vikaskallidantheyil** [selectize/selectize.js#1386]
Hello,
 I am using selectize drop down in an html table, where in last few columns of the table has drop down.

when i try to edit the value in the drop down it automatically brings the control to beginning of the table. i.e when i click on a particular row on selectize drop down it takes me all the way back to the starting column of the table. 

my table has 30+ columns and not able to edit the values because of this issue.

While adding values to the empty field its working fine. problem is only when i try to edit the existing value.

**Comment by fzyukio** [comment]
Same issue here.

**Comment by fzyukio** [comment]
Looks like the problem comes from `onMouseDown`. I'm not sure why it's needed. Overwriting that function seems to work for me:

```js
var control = $select.selectize({/* options */});
control[0].selectize.onMouseDown = function (e) {
    e.preventDefault();
    e.stopPropagation();
};
```

I'm pretty sure there is a better solution for this. But for now it works for me.

**Comment by Nurpeyis** [comment]
Not working for, still scrolls to begin of the line

**Comment by workgena** [comment]
Same issue as well (master branch).

**Comment by workgena** [comment]
Demonstration of a bug: https://jsfiddle.net/aq9Laaew/165854/

Steps to reproduce:
1. The TABLE(or page) should be scrollable(not fit in one screen by X-axis)
2. Scroll page to the right
3. Select any option from drop-down
4. Try to select once more
Error: The drop-down does not show, instead it scrolls the page to the 0,0 position

Browsers: latest Firefox and Chrome

Expected result: Open/Close drop down many times

Actual result: Only "first click" allows to select option. Then the drop down no shows, and scrolls page to 0,0 position.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.

**Comment by prathamesh1997** [comment]
After looking around found this. selectize input has input field which has position absolute and left -10000.

`.select-dropdown-auto{
    position: relative;
    .selectize-input{
        input{
            position: relative !important;
            left: 0px !important;
        }
    }
}`

**Comment by rodrigo1990** [comment]
Removing this part of the code at line 2047 should fix the problem:

// ensure control has focus
self.hideInput();
if (!this.isFocused) {
  self.focus();
}

**Comment by rodrigo1990** [comment]
Removing self.focus(); will fix the problem
```
setActiveItem: function($item, e) {
			...
			// ensure control has focus
			self.hideInput();
			if (!this.isFocused) {
				 self.focus();
			}
		},
```
