### ISSUE TITLE
Option to hide "Add new_typed_option..." option when create and createOnBlur option is set to true.

### ISSUE THREAD

**Issue by iatsi** [selectize/selectize.js#1387]
---

I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [x] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [x] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

[Cant hide "add new_option_name ...", when create parameter is set to true]

Steps to reproduce:

1. While initialization of selectize, set create field to be true.
2. Now, when we start typing in the field, by default "add new_option_name..." option comes into visibility.
3. On clicking on add it adds it to the field, but that is also achievable if we set createOnBlur field set to true.

Expected result: There should be something that must allow us to enable or disable this feature.

Actual result: "Add new_option_name..." shows by default.

![ico](https://user-images.githubusercontent.com/29480740/37383352-3f0daff2-276e-11e8-8318-07bf110b44c3.png)

**Comment by saif003** [comment]
@ashutosh21414 , for a temporary fix you can hide this option via scss or css, if you want to.
```
.selectize-dropdown {
  .selectize-dropdown-content {
    .create {
      display: none;
    }
  }
}
```

**Comment by iatsi** [comment]
Thanks for the help, Saif. To have a workaround I stored the selectize's javascript locally and modified the function that used to add this html of  **ADD..** as required.

**Comment by moussa-b** [comment]
@ashutosh21414 : selectize has a powerfull plugin mechanism, I fixed some bugs buy adding plugins instead of modifying selectize lib source code. It is especially usefull when you use library injection tool like bower, gulp, etc... See the [documentation](https://github.com/selectize/selectize.js/blob/master/docs/plugins.md).

**Comment by mustapha-ghlissi** [comment]
Normally adding **showAddOptionOnCreate** does the job 

Your code should looks like : 
```

 $(selector).selectize({
      delimiter: ",",
      showAddOptionOnCreate: false,
      create: function (input) {
          return {
              value: input,
              text: input,
          };
      },
  });
```
