### ISSUE TITLE
Using selectize with  jquery  3.3.1 on safari

### ISSUE THREAD

**Issue by matthewjj** [selectize/selectize.js#1388]
When trying to use selectize on safari with jquery 3.3.1, i get this error:

TypeError: 'undefined' is not a function (evaluating 'e.getAttribute("type")')

code example
$('.input').selectize({});

However, it works fine on chrome.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
