### ISSUE TITLE
@selectize-arrow-offset: @selectize-padding-x + 5px; does not work in Chrome

### ISSUE THREAD

**Issue by artknight** [selectize/selectize.js#1389]
Hi,
math ops like these `12px + 3px` do not get recognized in the latest Browsre versions

ex. `@selectize-arrow-offset: @selectize-padding-x + 5px;`

**Comment by mcavalletto** [comment]
Those declarations appear in .less source files which are compiled to .css files for use in browsers. 

You should not be loading .less files in a browser.

**Comment by artknight** [comment]
@mcavalletto no one is loading the .less files in a browser. The less compiler does not process additions in this way any longer. you need to use `calc()`

**Comment by mcavalletto** [comment]
You are right — all of the math in the .less files I was looking at was being applied, but a few cases in the bootstrap files are not.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
