### ISSUE TITLE
installation question

### ISSUE THREAD

**Issue by ghost** [selectize/selectize.js#1390]
Nice package from what I have seen in the examples! 
I'm trying to get it incorporated into my shiny App, but I get an error when trying to install it. 
Warning in install.packages :
  package ‘selectize.js’ is not available (for R version 3.4.3)

is there a git dev install command? I tried: 
devtools::install_github("selectize/selectize.js") but that didn't work. 

thanks for any help and for the work on this package!

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
