### ISSUE TITLE
How to retrieve custom attributes?

### ISSUE THREAD

**Issue by samstickland** [selectize/selectize.js#1392]
How can I retrieve the custom data attributes outside of the render functions?

I can set them successfully, and I can access them inside of the render functions, but how can I access these values in other areas, like a change event?

I only tested that I can see this information in the render function - is it discarded afterwards? That is, is it up to me to render it as appropriate, into my own div attributes, so that it can be retrieved later?

I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [ ] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [ ] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
