### ISSUE TITLE
List of DateRanges... Selectizejs and Daterangepicker - its possible?

### ISSUE THREAD

**Issue by Cauen** [selectize/selectize.js#1393]
Hey Guys, i'm creating a system, and i will need to create a list of dateranges...
I'm using selectize in others pieces of the system...
I can create a list of text like 01/01/2018...04/04/2018, but i want to add a date range picker for more UX... That is possible?
http://prntscr.com/j2kpaj

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
