### ISSUE TITLE
on option_create ?

### ISSUE THREAD

**Issue by dnsBlah** [selectize/selectize.js#1394]
Hi all,

I'm looking for a way to get another trigger on "option_create"
Which is responsible to add new 'options' within the select box right?

I'd like to bring up a popup to provide some 'description' on the 'created' item.
If somebody could provide an example, only for like.. do a console.log when a new option has been created I would be happy!

Thanks in advance!

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
