### ISSUE TITLE
Selectize not positioning dropdown correct

### ISSUE THREAD

**Issue by jamilalisgandarov** [selectize/selectize.js#1395]
I did:

* [X] Search for if my issue has already been submitted
* [ ] Make sure I'm reporting something precise that needs to be fixed
* [ ] Give my issue a descriptive and concise title
* [ ] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [ ] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

Steps to reproduce:

1. Just initialized selectize on fixed element's bottom side
2. Dropdown is not visible

Expected result:
Dropdown should be positioned up
Actual result:
Dropdown is positioned at the bottom

Imgs:
https://imgur.com/mFUa93r
https://imgur.com/HyOYcZY

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
