### ISSUE TITLE
Item belongs to multiple optgroups. How can selectize sort it?

### ISSUE THREAD

**Issue by MenadeL** [selectize/selectize.js#1396]
I am using an API that accepts the Item ‘name’ as the search parameter. It returns me items with a ‘type’ property.

I want to use “type” as the optgroup option on selectize. The problem is that each item can belong to more than one optgroup. So the “type” property is an array of types.

How can I implement it using selectize?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
