### ISSUE TITLE
Make dropdown auto select typing value

### ISSUE THREAD

**Issue by 1212087** [selectize/selectize.js#1402]
Hi, i have a problem with selectize dropdown.
As normal, when you type something, the dropdown show, when you hit enter, selectize auto select a previous option that match typing value. But i what to select typing value when i press enter, not any option else.
Example, when i type "Tran", the dropdown show some suggestion like "Tran Van A", "Tran Thi B", when i press enter, it selects "Tran Thi B", but i what the selected option is what i'm typing: "Tran".
Can i do that, and how i do that?
Sorry for my bad english! Please help!
Thanks!

**Comment by hugeps** [comment]
Copy that.
Have to explain users to select everything before typing - little use.
Would be simple to auto select contents of the input on focus.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
