### ISSUE TITLE
Searching with space modifies visible options dropdown values

### ISSUE THREAD

**Issue by markusos** [selectize/selectize.js#1405]
When searching in a selectize input and the search text contains a space, in some cases, it causes the visible options to be updated to a substring of the original value.

### Steps to reproduce:

1. Go to https://selectize.github.io/selectize.js/
2. Scroll to the Tagging example.
3. Clear the example and type "neat asd" in the tags input.
4. Remove the "asd" part of the search.
5. Observe that the options now contains "ne" instead of "neat"

**Expected result:** Options dropdown should still contain the "neat" option

**Actual result:** Options dropdown has renamed the option to "ne"

### Recoding of how to reproduce:

Tagging example:
![2018-05-18 10 56 05](https://user-images.githubusercontent.com/669536/40242246-187df27a-5a8b-11e8-892b-f6ba2975a71d.gif)

Country Selector example:
![2018-05-18 10 49 50](https://user-images.githubusercontent.com/669536/40242543-ed03db86-5a8b-11e8-9603-0c67ac02168a.gif)

I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [x] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [x] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

**Comment by jczstudios** [comment]
This is a problem for me to using a remote source. With names, they are getting dropped so it is quite confusing.

**Comment by mcavalletto** [comment]
This appears to be fixed in master.

**Comment by jczstudios** [comment]
It's still present. Just updated to the master branch.

**Comment by mcavalletto** [comment]
Did you rebuild from source, or are you using the old dist/ files?

I was no longer able to reproduce this problem after building a clean version of the library from source.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
