### ISSUE TITLE
Unable to copy selected values as plain text

### ISSUE THREAD

**Issue by saif003** [selectize/selectize.js#1406]
I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [ ] Create a *minimal* working example on JsFiddle or Codepen
* [x] Indicate *precise* steps to reproduce in *numbers* and the result

User can't copy the selected values inside the selectize control, by holding and dragging mouse over the intended text to be copied or even by pressing ctrl + A while focus is inside the control.

Pressing ctrl + A does highlight all the selected values, but pressing ctrl + c does nothing, also there is no option to copy text in the right click menu as well.

The actions which can be performed on the highlighted selected values seems to be very limited, so far only advantage I see of having the ctrl + A feature is that you can clear all values in bulk by pressing the backspace after selecting all values.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
