### ISSUE TITLE
Being able to run a single test (Karma)

### ISSUE THREAD

**Issue by joallard** [selectize/selectize.js#1408]
```
I need to be able to run a single test
In order for running tests to be fast and isolated
In order for running tests to be painless 
In order to fix the tests
In order for the library to work
```

Right now, `npx karma start` runs all tests. How do I run a single test?

**Comment by joallard** [comment]
`npx karma start --single-run=false` prevents runner from shutting down after runs.

**Comment by joallard** [comment]
Changing an `it` by `it.only` makes it run only this test. However this is not ideal, as it is triggered by editing and saving the test rather than a command line option.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
