### ISSUE TITLE
'invalid' event still attached to the input after destroying plugin

### ISSUE THREAD

**Issue by ccpu** [selectize/selectize.js#1411]
Just wondering if there is a reason for keeping the 'invalid' event attached to the input after destroying the plugin.

The event has been attached to the input in serialze.js file line 257:

                       // feature detect for the validation API
			if (SUPPORTS_VALIDITY_API) {
                        $input.on('invalid' + eventNS, function(e) {
					e.preventDefault();
					self.isInvalid = true;
					self.refreshState();
				});
			}

Thanks,

**Comment by joallard** [comment]
As we have more than 500 issues, the issue tracker is not a place for questions like this. If there is an issue with the library, please open another issue following the template and issue guide. Thanks.
