### ISSUE TITLE
Placeholder not showing in IE 11.  IE 11 does support place holders in input fields.

### ISSUE THREAD

**Issue by howardb3115** [selectize/selectize.js#1416]
I did:

* [X] Search for if my issue has already been submitted
* [X] Make sure I'm reporting something precise that needs to be fixed
* [X] Give my issue a descriptive and concise title
* [X] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [X] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

[This problem was reported in IE 9, where the cause was that input tags didn't support the placeholder attribute, but the issue still occurs in IE 10, where the input tag does support the attribute.]

Steps to reproduce:

1. Open the Codepen at https://codepen.io/howardb1/pen/QxNYaW
2. There are two columns of steps describing issue.  The first one relates to this reporting.
3. In short, open the drop-down list by clicking on the down-arrow of the minimized drop-down-list.
4. In IE 11 the input area is empty.  If the Codepen is open in Chrome, Firefox, or Mircosoft Edge,
   the input area properly displays the placeholder message.

Expected result:
  The placeholder message should be displayed.

Actual result:
  In IE 11 the placeholder message doesn't show.
  
[Using the latest versions of Chrome, IE, Edge, and Firefox, running in Windows 10.]

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
