### ISSUE TITLE
The remove_button plug-in button doesn't always remove the selected option.

### ISSUE THREAD

**Issue by howardb3115** [selectize/selectize.js#1417]
I did:

* [X] Search for if my issue has already been submitted
* [X] Make sure I'm reporting something precise that needs to be fixed
* [X] Give my issue a descriptive and concise title
* [X] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [X] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

[I have to click on the remove button a second time in order to remove an item from the selected options list.

This is different than #987 because focusing on the input area doesn't help AND my list only has 9 items in it.

The first attempt to remove a selected option this occurs every time, but after removing most of the selected items, the selected option sometimes does get removed the first time it's remove button is clicked.]

Steps to reproduce:

1. Open the Codepen at https://codepen.io/howardb1/pen/QxNYaW
2. There are two columns of steps describing issue.  The second one relates to this reporting.
3. In short, open the drop-down list by clicking on the down-arrow of the minimized drop-down-list.
4. Click on the remove button of the sixth selected option and notice that the option isn't removed until the remove button of that option is clicked a second time.

Expected result:
  The selected option should be removed the first time that it's remove button is clicked.

Actual result:
  The selected option is not removed the first time that it's remove button is clicked..
  
[Using the latest versions of Chrome, IE, Edge, and Firefox, running in Windows 10.]

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.

**Comment by sadovsf** [comment]
I can confirm issues still exists. Seems that main problem is that remove button is registering click event but for that to happen user have to do mouse down and up on cross element. If page for whatever reason moves (select menu causes scrollbar to appear) click does not happen. 

Remove bottom should react already on mouse down which should solve the issue.

**Comment by DannSVK** [comment]
The bug seems to be related with displaying the input after focusing the whole selectize block. After forcing it to be displayed all the time (like in the css snippet), the button works on the first click.  The autofocusing still remains though.
 
`.selectize-input > input {
    position: static !important;
}`
