### ISSUE TITLE
Selectize create to show / hide inputs

### ISSUE THREAD

**Issue by Hydro8** [selectize/selectize.js#1422]
Hi

I want to use selectize to show inputs if new option is create or to hide inputs if default option is select.

Here my html code for my selectize :

`<select id="select-type" name="type" class="form-control" placeholder="Sélectionnez ou ajoutez un type de fraction" required>																																																		<option value="">Sans</option>																									@foreach($types as $type)																																																			<option value="{{$type['nom']}}">{{$type['nom']}}</option>																											@endforeach																									</select>`

And my js code :
`$select_type = $('#select-type').selectize({
    highlight: false,
    readonly: true,
    create: true,
    persist: false,
	render: {
        option_create: function(data, escape) {
            return '<div class="create">Ajouter le bâtiment <strong>' + escape(data.input) + '</strong>&hellip;</div>';
        }
    },
    onOptionAdd: function(value) {
        $('.new_fraction').show();
            }
});`

First problem :  persist option doesn't seem to work. When I create an option, then select back a default option, my created option is selectable. 

Second problem : when I add an option, inputs are shown. But how to know that I select back a default options ?

Thank for your help !

**Comment by Hydro8** [comment]
It work with input set to multiple and by adding maxItems : 1

**Comment by Hydro8** [comment]
It works only if we press backspace to remove current created select. If we choose another option, created option isn't remove.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
