### ISSUE TITLE
Placeholder not working

### ISSUE THREAD

**Issue by Kazuto** [selectize/selectize.js#1425]
I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [ ] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [ ] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

The placeholder attribute is not showing up.
Console is not throwing any errors, Selectize.js works, except this.
Code used: `$('select').selectize({});`
`<select name="search_status" id="search_status" placeholder="which status is">`

Expected result:
The placeholder is used.

Actual result:
An option is selected Instead of the placeholder.

**Comment by crashh** [comment]
Can be resolved by calling clear() on the selectize element.

    var $select =$('.classname').selectize({
        allowEmptyOption: true,
        items: [],
        placeholder: "PLACEHOLDER TEXT."
    });
    $select.each(function() {
        $(this)[0].selectize.clear(true);
    });

**Comment by TakesTheBiscuit** [comment]
This seems broken after `https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.1/js/standalone/selectize.min.js`

I.E `0.12.2 -> 0.12.4` that i've checked are all broken
