### ISSUE TITLE
How to set my input box value blank

### ISSUE THREAD

**Issue by jezzmeto** [selectize/selectize.js#1436]
Hello,
I'm using selectize.js. 
**I wonder how to set my input box value blank.**
Because with the html ### code:
<input type="text" id="input-tags" class="demo-default" value="awesome,neat,cafe,latte,cup" >
Although it creates option to select, it also creats default values in the input box.
Thank you guys !

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
