### ISSUE TITLE
Retain All Items options in dropdown

### ISSUE THREAD

**Issue by neilgee** [selectize/selectize.js#1440]
My original 'All Items' option is removed when I use selectize.js (in the screen pics its called "All Industry Categories") - how can I maintain that when using selectise.

![screen shot 2018-08-14 at 4 23 07 pm](https://user-images.githubusercontent.com/2056045/44075094-bf33c5d4-9fde-11e8-9c08-fbf4a7ceffa4.png)
<img width="560" alt="screen shot 2018-08-14 at 4 22 55 pm" src="https://user-images.githubusercontent.com/2056045/44075095-bf81e214-9fde-11e8-93be-cc7564b0b5a3.png">

**Comment by tsaltena** [comment]
There's an option for this, I believe it is called Persist. Check the Usage API docs for it.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
