### ISSUE TITLE
Callback inside create: method doesn't work

### ISSUE THREAD

**Issue by leemour** [selectize/selectize.js#1441]
I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [x] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [x] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

Steps to reproduce:

1. Demo - https://jsfiddle.net/rm9awop7/7/
This behavior occurs when using callback inside `create:` method
```
$('.selectize').selectize({
  create: function(input, callback) {
    return $.ajax({
      url: "https://api.myjson.com/bins/uz8bs",
      data: {
        tag: {
          name: input
        }
      },
      dataType: 'JSON',
      method: 'GET',
      success: function(data, textStatus, xhr) {
        return callback({
          value: data.id.toString(),
          text: input
        });
      }
    });
  }
});
```

Expected result:
The new item is rendered and added to items.

Actual result:
New items isn't rendered, not added to items. 
When I removed `once(..)` wrapper around `create` inside `createItem` method, it started working as expected. Callback function was called before I called it in my ajax `success` method. And `once` was stopping it from being called twice. So removing `once` enabled me to call `callback()` in my success method.

**Comment by BryanColle** [comment]
It works if you remove return in front of your Ajax call. 
Since you’re returning something, it doesn’t wait for the callback to be called.

**Comment by leemour** [comment]
Wow, silly me. Thank you!
