### ISSUE TITLE
Serialize won't display design once it's been destroyed

### ISSUE THREAD

**Issue by compact722** [selectize/selectize.js#1442]
`$('.selectized').selectize();
        $('.selectized').each(function(){ // do this for every select with the 'combobox' class
            if ($(this)[0].selectize) { // requires [0] to select the proper object
                var value = $(this).val(); // store the current value of the select/input
                $(this)[0].selectize.destroy(); // destroys selectize()
                $(this).val(value);  // set back the value of the select/input
            }
        });

        $('.selectized').selectize();`

First selectize initiate works but nothing on the 2nd one?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
