### ISSUE TITLE
Horizontal scrollbar on RTL pages in IE/Edge

### ISSUE THREAD

**Issue by michael-maltsev** [selectize/selectize.js#1444]
I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [x] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [x] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

Steps to reproduce:

1. Visit https://selectize.github.io/selectize.js/ in IE/Edge.
2. Use inspector to set `dir='rtl'` for the `html` tag.
3. Observe the horizontal scrollbar which goes very far.

This happens because of the `measureString` utility, which creates a control which meant to be hidden far in the left:
https://github.com/selectize/selectize.js/blob/8c76832f95bae664fb1b533c41df414fc6192ebd/src/utils.js#L233-L260

**Comment by Litecoinlord** [comment]
Good
