### ISSUE TITLE
selectize load option not working on change of selectbox

### ISSUE THREAD

**Issue by Hiranmayee24** [selectize/selectize.js#1446]
I have 2 select box,Select Box 1 and Select Box 2
Based on select Box 1 , select Box 2 option should change
Select Box 1 (Options : High/Low)
Select Box 2 (Options : Users from user database table) -When selected High in Select Box 1 ,it should display only some users and for Low it should display all users

Design -
HTML-
<select id="severity" ng-model="newSev" ng-change="displayUser(newSev)"></select>
<select id="commManager" class="form-control" ng-model="newCommManager"></select>
Client side-
				displayCommMgr = function(sev){
														
	$selectCommManager = $('#commManager').selectize({
		valueField: 'id',
		labelField: 'title',
		searchField: 'title',
		placeholder: 'Please select User',
	        options: $scope.data.users,
		create: false,
		sortField: {
		        field: 'title',
	        	direction: 'asc'
		},
		onInitialize: function() {
			var val = $scope.data.userID;
		   this.setValue(val);
		},
		});
		selectizeControlCommManager = $selectCommManager[0].selectize;
		if(sev == 'High'){
															if(($scope.data.commManager == undefined) || ($scope.data.commManager == '')){
selectizeControlCommManager.clearOptions();
selectizeControlCommManager.load(function(callback) {
callback($scope.data.limited_users);
});
}
else{
selectizeControlCommManager.setValue('');
selectizeControlCommManager.load(function(callback) {
callback($scope.data.limited_users);
});																
}
}
else{
if(($scope.data.commManager == undefined) || ($scope.data.commManager == 'undefined') || ($scope.data.commManager == '') ||($scope.data.commManager == 'null') || ($scope.data.commManager == null)){
selectizeControlCommManager.clearOptions();
selectizeControlCommManager.load(function(callback) {
callback($scope.data.users);
});
}
};
}
									

Issue -
It works for new record and existing records which has Select Box 2 option as empty.
But doesn't work if select box 2 has a value and we change the select box 1 to HIgh , it doesn't load limited users instead it displays all users.

Please reply if you have faced this issue and have a solution for this.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
