### ISSUE TITLE
Selectize not loading in IE11: "Invalid argument" at $input.attr("autocapitalize")

### ISSUE THREAD

**Issue by jhill-dci** [selectize/selectize.js#1451]
I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [x] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [x] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

IE11 throws an "invalid argument" error on line 663 of `selectize.js`:

```javascript
662   if ($input.attr('autocapitalize')) {
663       $control_input.attr('autocapitalize', $input.attr('autocapitalize'));
664   }
```
Demo: http://jsfiddle.net/sbor2w6u/ ( http://jsfiddle.net/sbor2w6u/embedded/result,css,html,js to view in IE11 )

Expected result: Search bar loads

Actual result: Search bar does not load due to js error

**Comment by Teemu** [comment]
No, the problem is on this line:
````
$control_input[0].type = $input[0].type;
````

<img width="812" alt="screen shot 2018-10-24 at 12 28 55" src="https://user-images.githubusercontent.com/53298/47421044-6a13b280-d788-11e8-9c6a-cdc87a5bf25f.png">

**Comment by jhill-dci** [comment]
Nailed it, Frozenball - that fix worked for me.  Added bonus, now I know that the IE 11 bug reporter identifies the line before the issue, instead of the issue itself. 😄 

Thank you!
