### ISSUE TITLE
Dropdown invisible while browser does not have focus

### ISSUE THREAD

**Issue by hofmandl1** [selectize/selectize.js#1457]
I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [x] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [x] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

[replace me with a short description of issue]

Steps to reproduce:

1. Make your browser window non-maximized (so you can later click outside)
2. Go to http://selectize.github.io/selectize.js/
3. Click into the second exampe (Email contacts) (so the dropdown appears)
4. Click outside the browser window, e.g. your desktop background (the dropdown disappears)
5. Click right below the input (where the dropdown has been visible until recently)

Actual result:
An item is selected as if the dropdown had been visible

Expected result:
IMHO it would be best if the dropdown would not disappear at all, but it would probably also be acceptable if the dropdown would really close itself (instead of going invisible)

I have tried Firefox (windows/linux) and google-chrome (linux) all with the same problem. Having a button below the selectize that is covered by the dropdown can really confuse users. While they think they click the button what they actually do is select something in another widget.

This is less problematic for people using "focus-follows-mouse" (because then the dropdown reappears upon reentering the browser with the mouse) but I guess at least 99% of people don't.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
