### ISSUE TITLE
Searching without being able to choose multiple options or creating options.

### ISSUE THREAD

**Issue by GrumpyCrouton** [selectize/selectize.js#1458]
I've been playing around with selective, and love the feature where you can click the drop-down and start typing in what you are looking for, however, it seems this option only works when allowing users to create new entries or allowing users to select multiple entries.

Is there any way to enable the search feature without allowing multiple choices/creating new entries?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
