### ISSUE TITLE
Duplicate fields appears on browser back button

### ISSUE THREAD

**Issue by kumarkekse** [selectize/selectize.js#1463]
steps: Press browser back and then forward button after each other

Actual:
On browser back button:
1. Duplicate fields appears
2. Options and selected values gets disappear
![screenshot_2018-12-06 48486907-66be9480-e825-11e8-87d1-25f0c25bcf21 png png image 891 x 1014 pixels - scaled 66](https://user-images.githubusercontent.com/18588686/49585806-6aa58880-f985-11e8-9630-1e2c998096ef.png)

Expected:
 Option fields should remain singular
![screenshot_2018-12-06 settings](https://user-images.githubusercontent.com/18588686/49585896-a6405280-f985-11e8-8d1b-9cb291e88c0d.png)

**Comment by kumarkekse** [comment]
code: 
```  
$(".selectdata").selectize({ 
    delimiter: ',',
    plugins: ['remove_button', 'stop_backspace_delete']
  });
```

**Comment by nhaglind** [comment]
Experiencing the same behavior as well and can replicate. Happens to all fields. Seems to only happen when the back button is pressed. Refresh fixes it but not ideal.

**Comment by ghost** [comment]
any fix regarding this ?

**Comment by itssasanka** [comment]
Try `destroy`ing the control before the user navigates away from the page:
```
var $selectize = $(some element).selectize({ 
  options: [{text: 'blah', value: 1}, {text: 'blaaaa', value: 3} ....]
  maxItems: 3
  .....
  ....
});
```

On browser back/forward:
```
$(window).on('popstate', function(event) {
 $selectize[0].selectize.destroy();
});
```

I am using Turbolinks, so I did the second part in a different way.

**Comment by nhaglind** [comment]
Turbolinks was the issue here. This worked well for me.

```
<% if yield(:no_cache) %>
    <meta name="turbolinks-cache-control" content="no-cache">
<% end %>
```

https://github.com/turbolinks/turbolinks#opting-out-of-caching
