### ISSUE TITLE
Tab still won't change to next field - reference to #1164

### ISSUE THREAD

**Issue by rskaarup** [selectize/selectize.js#1464]
I did:

* [X] Search for if my issue has already been submitted
* [X] Make sure I'm reporting something precise that needs to be fixed
* [X] Give my issue a descriptive and concise title
* [X] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [X] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

Issue #1164 is still not fixed in 0.12.6, despite issue has been closed. I'm unable to change fields with tab i 0.12.6 - but 0.12.2 works fine. Tested in Safari and Firefox.

Fiddle with 0.12.2 (borrowed from author of #1164 ):

https://jsfiddle.net/sturchyn/b961qfjk/

Fiddle with 0.12.6:

 https://jsfiddle.net/btxjvoy6/1/

Steps to reproduce:

1. Click on fiddle link
2. Choose option B in selectize field
3. Hit Tab-key on your keyboard

Expected result:

Works with both Selectize 0.12.2 and 0.12.6

Actual result:

Works only with 0.12.2

**Comment by friendscottn** [comment]
It looks like this issue may be caused by the following line:
```
self.$control_input.blur(); // close keyboard on iOS
```
Removing the line resolved the issue for me.

Using a diff between the versions mentioned by @rskaarup I was able to isolate the line.
