### ISSUE TITLE
Documentation do not describe all dependencies for quick start

### ISSUE THREAD

**Issue by KES777** [selectize/selectize.js#1465]
* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [x] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [x] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

[JS fiddle](https://jsfiddle.net/KES777/tbo1hLcm/)

```javascript
<script type="text/javascript" src="/js/jquery-3.3.1.js"></script>
<script type="text/javascript" src="/js/selectize.js"></script>
<link rel="stylesheet" type="text/css" href="/css/selectize.css" />
<script>
$(function() {
	$('select').selectize([]);
});
</script>
```

Steps to reproduce:
1. Just run JS fiddle

Expected result:
working selectize

Actual result:
errors in console:
```
Selectize: Dependency MicroPlugin is missing selectize.min.js:3:6100
<anonymous>
https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/js/selectize.min.js:3:6100
<anonymous>
https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/js/selectize.min.js:3:6076
<anonymous>
https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/js/selectize.min.js:3:212
<anonymous>
https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/js/selectize.min.js:3:2
```

[Documentation](https://github.com/selectize/selectize.js/blob/master/docs/usage.md) should describe what is `MicroPlugin` is

**Comment by BryanColle** [comment]
It does here : 
https://github.com/selectize/selectize.js#dependencies

And the following section points you to the standalone version of selectize, for which you don’t need to worry about MicroPlugin :)

**Comment by maisonsouza** [comment]
Ao clicar nas dependências do projeto mais precisamente na seção Installation and files sou informado que preciso do arquivo selectize.js no entanto ao tentar salvar o arquivo sou direcionado para:
https://github.com/selectize/selectize.js/blob/master/dist/js/standalone/selectize.js
se eu salvar esse arquivo clicando em Salvar como obterei um arquivo HTML.
O Link correto na minha opinião seria:
https://raw.githubusercontent.com/selectize/selectize.js/master/dist/js/standalone/selectize.js
Existe algum problema com os links das dependências ou estou fazendo algo errado. Desde já agradeço.

**Comment by KES777** [comment]
@maisonsouza Попробуйте прямую [ссылку](https://raw.githubusercontent.com/selectize/selectize.js/master/dist/js/standalone/selectize.js)

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
