### ISSUE TITLE
Reopen issue/bug #729: Cannot read property '$order' of undefined

### ISSUE THREAD

**Issue by vppetrov** [selectize/selectize.js#1466]
This problem still exists today (version 0.12.6) when an object (option) is added that has no valid group value. The code that fails is:

```
// sort optgroups
if (this.settings.lockOptgroupOrder) {
	groups_order.sort(function(a, b) {
		var a_order = self.optgroups[a].$order || 0;
		var b_order = self.optgroups[b].$order || 0;
		return a_order - b_order;
	});
}
```

The error is that b is "" (because no valid group value was supplied) and the line var b_order = self.optgroups[b].$order || 0; fails.

The solution is quite easy:

```
// sort optgroups
if (this.settings.lockOptgroupOrder) {
	groups_order.sort(function(a, b) {
		var a_order = (self.optgroups[a] ? self.optgroups[a].$order : 0) || 0;
		var b_order = (self.optgroups[b] ? self.optgroups[b].$order : 0) || 0;
		return a_order - b_order;
	});
}
```

**Comment by mattgodbolt** [comment]
Also seeing this in 0.12.6. Does not happen in 0.12.4. (See mattgodbolt/compiler-explorer#1367).

**Comment by mattgodbolt** [comment]
I'm not sure this has been fixed...

**Comment by databyte** [comment]
Can someone open up a PR with a test? Otherwise this will be something we'll have to get back around to. As a volunteer, there's only so much time to recreate the issue then work on it. It sounds like you both have examples to work with. A broken test that's fixed by any changes would be perfect.

**Comment by mattgodbolt** [comment]
Understood 100% @databyte :) I admin enough projects to know how annoying that is. I'll see what I can do to repro, and open a new issue if I can repro specifically. I am excited to hear selectize is making forward progress again; with 82 outstanding PRs is a lot to deal with! thanks.
