### ISSUE TITLE
Unconverted characters in input are hidden

### ISSUE THREAD

**Issue by dito** [selectize/selectize.js#1468]
https://selectize.github.io/selectize.js/

![2019-01-11 14-29-27 2019-01-11 14_33_38](https://user-images.githubusercontent.com/4264269/51015578-1eff8380-15b0-11e9-905f-8ebd0bde0375.gif)

I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [x] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [x] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

[replace me with a short description of issue]

Steps to reproduce:

0. use Firefox
1.  https://selectize.github.io/selectize.js/
2. Enter in japanese

Expected result:

display all unconverted characters in input

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
