### ISSUE TITLE
Keep and Check selected items in the list of options

### ISSUE THREAD

**Issue by ferreiranoel** [selectize/selectize.js#1470]
Keep the selected options in the dropdown marked as checked (for example highlighted or with a check icon after element).
For example if you have a tree display in the dropdown it is annoying to have the values hidden. It would be better if they stay in the list of values marked as already choosen.

Can't do this with existing callback functions.
I can get the list of selected values with the onChange function but if i remove or loose focus the list of values is refreshed and all HTML.

We could add a option 'check_selected' used with autoHide to false. This can add a class to the dropdown option if it was selected. Or maybe span the option with check icon.

-- Input items selected  --
_______________________________________________________________
CATEGORY 1; SUBCATEGORY 1.2; SUBCATEGORY 2.1; SUBCATEGORY 3.3
_______________________________________________________________

-- List of Options --

**CATEGORY 1  v**
    SUBCATEGORY 1.1
    SUBCATEGORY 1.2  v
**CATEGORY 2**
    SUBCATEGORY 2.1  v
**CATEGORY 3**
    SUBCATEGORY 3.1
    SUBCATEGORY 3.2
    SUBCATEGORY 3.3  v

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
