### ISSUE TITLE
Item not in dropdown if outside of maxOptions 

### ISSUE THREAD

**Issue by AGFApan** [selectize/selectize.js#1471]
---

I did:

* [X ] Search for if my issue has already been submitted
* [X ] Make sure I'm reporting something precise that needs to be fixed
* [ X] Give my issue a descriptive and concise title
* [ ] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [X ] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

Item not in dropdown if outside of maxOptions 

Steps to reproduce:

1. Create selectize.js dropdown of with 1,000 or more items 
2. Set maxOptions to 100, and sort list alphabetically ascending. 
3. Select item near the end of the alphabet. e.g. STBC 978860 24x60 Baffle
4. When the dropdown is opened again the item is not only not selected in the results, but is not visible in the dropdown at all. The user is required to retype "STBC" to see the item.

Expected result:

The selected item is displayed in the dropdown, in the center of the maxOptions range, for example items starting with "A-F" would be hidden but all the S's would be visible. 

Actual result:

Selected items are not displayed in the dropdown, which is confusing users. Also once this data is saved I use the setValue function to set the value on page load. If the value is outside of the maxOptions range the same issue occurs. 

The main issue is we have thousands of inventory items. While setting maxOptions equal to the number of items produces the desired result, the dropdown becomes horribly slow (about a good five second delay after typing a letter in the search box). Also if "STBC 978860 24x60 Baffle" is the currently selected item, most likely the user is looking to simple change it to "STBC 97364 16'' Baffle" and not and not a completely different product.

So far I have not found anyway of resolving this, aside from toggling maxOptions between 100 and the full list length. 

Any suggestions on how to resolve this would be greatly appreciated.

Thank you.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
