### ISSUE TITLE
I want to hide the add new option if the option is already exist for create=true

### ISSUE THREAD

**Issue by msyadav88** [selectize/selectize.js#1472]
I want to hide the add new option if the option is already exist for create=true

**Comment by Pictor13** [comment]
Something like making a check while typing:
```
onType: function(str) {
    for (var i=0; i < this.options.length; i++) {
        if (this.options[i][this.settings.labelField] === str) {
            this.$wrapper.addClass('create_option_already_present');
        } else {
            this.$wrapper.addClass('create_option_already_present');
        }
    }
}
```
with simple styling:

```
.create_option_already_present .selectize-dropdown .create {
    display: none;
}
```

would work for you?

I didn't try the code but I think that the idea should work.
Of course looping on all the options each time that a single character is typed is not ideal performance-wise, but as a starting idea should work.
