### ISSUE TITLE
selected tags by user when i edit user profil

### ISSUE THREAD

**Issue by MSBIZ** [selectize/selectize.js#1477]
Hi,

i want show tags in my input when i edit the user profil.

each user profil have one or more alias.

This is my code

```
var Alias = new Array();
for (j in data.alias) {
 Alias.push(data.alias[j].alias);
}
$("#selectize-tags2").val(Alias).trigger('change');
```

But when i click on button edit, i not see the alias in my input, BUT when i refresh the page i see the last alias in my input. I need each time refresh 2 times page for see value in my input.

my initialisation 

```
$('#selectize-tags2').selectize({
    plugins: ['remove_button'],
    delimiter: ',',
    placeholder: '',
    maxItems: 3,
    persist: false,
    create: function(input) {
        return {
            value: input,
            text: input
        }
    }
});

```
Can you have solution for my problem ?

Thanks

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
