### ISSUE TITLE
clicking input field after clicking selectize-input div-item, no dropdown menu triggered

### ISSUE THREAD

**Issue by dnsBlah** [selectize/selectize.js#1483]
Hi all,

I'm using selectize with a lot of pleasure! It's a great well worked out script :)

I'm using this mainly for multi-dropdown fields and added some functions to my pages using `$(document).on('click', 'div.selectize-input div.item', function (e) {` to be able to add some comments for the selected item (single item) and more stuff.

Using the standalone version I have a problem when I'm NOT focussed on the input field and clicking on one of the 'already selected' item and then back into the field, this is not triggering the dropdown menu to show.

Does anyone else feel this?

**Comment by TrishaPatel** [comment]
hi 
I want to implement same functionality.
Have you found any solution?

**Comment by dnsBlah** [comment]
Hi @TrishaPatel ,

The only thing for now would be to detect mouseup on the field. And trigger the dropdown programatically if it's not open yet.
Did not have time yet to work on it.

--- Just tried something out:
Below a quick and dirty one, but I dismiss the dropdowns when I've made a selection, also on multi dropdown. Which doesn't work now on next clicked item.. Might need some more work on it :)
```
$(document).on('mouseup', '.selectize-input', function(e) {
    if(!$(e.target).is('.item')){
        var tDropdown = $(this).parent().find('.selectize-dropdown');
        if(tDropdown.css('display') !== 'block') { tDropdown.css('display','block'); }
    }
});
```
