### ISSUE TITLE
Input type should be honored (e.g. email, url, tel)

### ISSUE THREAD

**Issue by ericboehs** [selectize/selectize.js#149]
When setting an input type to `email`, for example, it should pass through to the input that selectize creates.

This is handy for mobile devices as the type is how they determine what keyboard to display.

Other fields such as `url` and `tel` should also work.

**Comment by ulriklystbaek** [comment]
Input type email support is another issue. Only types suporting selection can be used (https://html.spec.whatwg.org/multipage/forms.html#do-not-apply). So issue would be that get selectize to work withiout using selection functions.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
