### ISSUE TITLE
Can't display easily json attributes within an AJAX request 

### ISSUE THREAD

**Issue by v2lrf** [selectize/selectize.js#1491]
😎 Hi Everyone
Hi would like to diplay some specific informations  inside the dropdown. But can't display more than name or id . Don't know why yet. 

I'm only Abble to display the labelField (dashboard_display_name) and the id 💀
I would like to display some other attributes like :
```md
  id
  fork
  name
  username
  description
  language
  watchers
  forks 
```

Trying day after day to display that render without any success.
```javascript
render: {
		option: function(item, escape) {
			return '<div>' +
				'<span class="title">' +
					'<span class="by">' + escape(item.dashboard_display_name) + '</span>' +
				'</span>' +
				'<span class="description">' +  escape(item.nom) + '</span>' +
				'<ul class="meta">' +
					(item.score ? '<li class="language">' + escape(item.score) + '</li>' : '') +
					'<li class="watchers"><span>' + escape(item.watchers) + '</span> watchers</li>' +
					'<li class="forks"><span>' + escape(item.score) + '</span> forks</li>' +
				'</ul>' +
			'</div>';
		}
	}
```
![](https://res.cloudinary.com/entrepreneur/image/upload/v1559574091/final_5cf5360ed5a13e0013dd4d19_823434_l3xmnw.gif)
#### the issue 
Hi i have working on it and i still stuck on it ... don't know why nothing is better since two days
I'm RoR dev but think that it could help all. It's a front challenge.

### build the Json properly 
```ruby
json @options do |option|
  json.id option.id
  json.fork option.fork
  json.name option.name
  json.username option.username
  json.description option.description
  json.language option.language
  json.watchers option.watchers
  json.forks option.forks
end
```
### have a look on it 
[online json ](https://localdevelopment.ams3.digitaloceanspaces.com/ON_LINE_FILE_DO_NOT_DLETE/search.json)
### little picture of result ...
![worker_app](https://res.cloudinary.com/entrepreneur/image/upload/w_600/v1559572117/Capture_d_e%CC%81cran_2019-06-03_a%CC%80_16.22.04_ijttea.jpg)

### The Ajax answer
```json
{"data":[{"id":1,"fork":true,"dashboard_display_name":"Honda","username":"Rose Bush",
"description":"Statim ancilla.","language":"Zeno","watchers":384,"forks":231},{"id":35,"fork":false,
"dashboard_display_name":"Hino Motors","username":"Otto Carr",
"description":"Corporis.","language":"Mohol","watchers":6434,"forks":3}]}
```

#### The Javascrip
```javascript
$('#select-repo').selectize({
	valueField: 'id',
	labelField: 'dashboard_display_name',
	searchField: 'dashboard_display_name',
	scoreField:  "watchers",
	options: [
	],
	create: false,
	load: function(query, callback) {
		if (!query.length) return callback();
		$.ajax({
			url: "/search" + '?query=' + encodeURIComponent(query),
			// url: 'http://localhost:3000/allOptions' + encodeURIComponent(query),
			type: 'GET',
			dataType: 'json',
			error: function() {
				callback();
			},
			// success: function(res) {
			// 	callback(res.data.slice(0, 10));
			// },
			success: function (res) {
				 callback(res.data.map(function (item) {
						 return {
					 name: item.dashboard_display_name.name,
					 label: item.dashboard_display_name.label,
					 score: item.watchers.score
				 };
				 }));
		 }
// I also have tried this action ...
				// success: function(res) {
				// 
				// 	callback(res.data.slice(0, 10));
				// 
				//   $.each(res.data, function( index, value ) {
				//     alert( index + ": " + res.data[index].description );
				//     description = res.data[index].description;
				//     callback(res,description);
				//   });
				// 
				//   // description = res[0].description;
				// }
		});
	},
	render: {
		option: function(item, escape) {
			return '<div>' +
				'<span class="title">' +
					'<span class="by">' + escape(item.dashboard_display_name) + '</span>' +
				'</span>' +
				'<span class="description">' +  escape(item.nom) + '</span>' +
				'<ul class="meta">' +
					(item.score ? '<li class="language">' + escape(item.score) + '</li>' : '') +
					'<li class="watchers"><span>' + escape(item.watchers) + '</span> watchers</li>' +
					'<li class="forks"><span>' + escape(item.score) + '</span> forks</li>' +
				'</ul>' +
			'</div>';
		}
	}


});
```

#### Best potential solution founded
[here](https://stackoverflow.com/a/46247564/7800866)
but not got the thing yet 

Some ideas ? What is going wrong ?

**Comment by HHGB12** [comment]
✅ Work Well 
## for Ajax (remote data) , Json , Rails, item dropdown , Selectize Vs Select2 ?

Finally, job done and work fine with Select2 🤷🏽‍♂️
initial post[here](https://github.com/selectize/selectize.js/issues/201#issuecomment-498651920)

![](https://res.cloudinary.com/entrepreneur/image/upload/v1559651584/final_HW_select2_ajax_JSON_zqtj7v.gif) 



if need the access repo tell me bye

**Comment by v2lrf** [comment]
✅ Work Well 
## for Ajax (remote data) , Json , Rails, item dropdown , Selectize Vs Select2 ?

Finally, job done and work fine with Select2 🤷🏽‍♂️

![](https://res.cloudinary.com/entrepreneur/image/upload/v1559651584/final_HW_select2_ajax_JSON_zqtj7v.gif) 



if need the access repo tell me bye
