### ISSUE TITLE
select field not clearing option once selected.

### ISSUE THREAD

**Issue by samuel-irungu** [selectize/selectize.js#1502]
I've got two fields: Car Model and Make, when I select a make it properly populates the models.
But if I select another Make it doesn't clear the Model selected in the other list, it remains at the top of that list.
Here's the code 

    $.get("https://vpic.nhtsa.dot.gov/api/vehicles/getallmakes?format=json", function(response) {
        items = response['Results'];
        for (var index in response['Results']) {
            item = items[index];
            $('#make').append(`<option>${item['Make_Name']}</option>`);
        }

        var xhr;
        var select_state, $select_state;
        var select_city, $select_city;

        $select_state = $('#make').selectize({
            onChange: function(value) {
                if (!value.length) return;
                select_city.disable();
                select_city.clearOptions();
                select_city.load(function(callback) {
                    xhr && xhr.abort();
                    value = encodeURIComponent(value);
                    xhr = $.ajax({
                        url: `https://vpic.nhtsa.dot.gov/api/vehicles/getmodelsformake/${value}?format=json`,
                        success: function(results) {
                            select_city.enable();
                            callback(results['Results']);
                        },
                        error: function() {
                            callback();
                        }
                    })
                });
            }
        });
        
        $select_city = $('#model').selectize({
            valueField: 'Model_Name',
            labelField: 'Model_Name',
            searchField: ['Model_Name']
        });
        
        select_city  = $select_city[0].selectize;
        select_state = $select_state[0].selectize;
        
        select_city.disable();
    });

Here's a recording of this: https://youtu.be/spdwaqRLQzg

**Comment by mertasan** [comment]
```js
onChange: function(value) {
            if (!value.length) return;
            select_city.disable();
            select_city.clear(); // add this before select_city.clearOptions()
            select_city.clearOptions();
            ...
```
