### ISSUE TITLE
Nested Autocomplete using dot (.) notation as separator 

### ISSUE THREAD

**Issue by Nickath** [selectize/selectize.js#1510]
Is it possible to use selectize plugin for `nested autocomplete`? I have also posted a similar question on SO  [here](https://stackoverflow.com/questions/58573541/nested-autocomplete-with-selectize-plugin).

Example 

`[{
    "value": "AnyRole",
    "arrayofobjs": [
	    {
            "attr1": "attr1-value"
        },
        {
            "attr2": "attr2-value"
        },
        {
            "attr3": {
                       "attr3_subattr1": "attr3_subattr1_value"
                     }
        }
    ]
},
{
    "value": "Administrator",
    "arrayofobjs": [
	    {
            "attr1": "attr1-value"
        },
        {
            "attr2": "attr2-value"
        }
    ]
}]`

I would like to perform **nested autocomplete** search using the dot notation and search for their keys etc.

For instance 
    
     a
        AnyRole
        Administrator

--------------------------------

    AnyRole.
           attr1
           attr2
           attr3

--------------------------------

    AnyRole.attr3.
                   attr3_subattr1 

Is there any way to achieve this? Thanks in advance

**Comment by paulo-maia** [comment]
I'm also interest in this... haven't found anything similar yet @Nickath , have you found a solution so far?

**Comment by Nickath** [comment]
No, I did not proceed with a custom solution for my case and preferred to create a custom backend autocompleter for this type of functionality.
