### ISSUE TITLE
selectize.removeItem(item, silent) fires "onItemRemove" function call even if silent=true

### ISSUE THREAD

**Issue by williamstelvio** [selectize/selectize.js#1512]
I did:

* [X ] Search for if my issue has already been submitted
* [X ] Make sure I'm reporting something precise that needs to be fixed
* [X ] Give my issue a descriptive and concise title
* [X ] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [ X] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

DEMO: https://jsfiddle.net/7g0no4j1/17/
If silent = true, then a call to selectize.removeItem("dog", silent) should not trigger the "onItemRemove" event handler function.
By the same token
If silent = true, then a call to selectize.addItem("dog", silent) should not trigger the "onItemAdd" event handler function.

Steps to reproduce:
1. Press the 'x' button next to "dog" OR remove "dog" by pressing backspace
2. Check console

Expected result:
onItemRemove function is triggered and "dog" is re-added with the call to selectize.addItem("dog", silent). **onItemAdd should NOT be fired** after addItem call because silent = true

Actual result:
"dog" is re-added with the call to selectize.addItem("dog", silent) **AND onItemAdd IS fired** which leads to an infinite loop of adding and removing in my example

[you can add explanations here of the context/what you were trying to
do, and if you have findings about what the cause might be]
Objective: make "dog" in our animal list a read-only field. By read-only, we mean a user cannot add it to the list nor remove it if it is already present in the list.

**Comment by jicihome** [comment]
I have the same issue with the addItem. Event is fire event if silent is true
