### ISSUE TITLE
Documentation for addOption and addItem is unclear.

### ISSUE THREAD

**Issue by blackblood** [selectize/selectize.js#1514]
In the current API documentation https://github.com/selectize/selectize.js/blob/master/docs/api.md, under the "items" section, the `addItem` function does not describe what type or format should the `value` argument be. It was only after a dug in that I realized it takes a single argument which should be equal to the value attribute of the option tag. I assumed, the type of `value` argument would be something like `{ "value": 20, "text": "Car" }`, since this is what addOption accepts.
 Also, It should be made clear that the addOption function can take an array of `{"value": value, "text": text}` and `addItem` can only take a one string argument.

**Comment by aasutossh** [comment]
Well, thank you so much.

**Comment by maximus1127** [comment]
i wish I could upvote this question simply because you provided the object format for the addOption method in your question when the documentation doesn't seem to provide that on its own.
