### ISSUE TITLE
Add item manually

### ISSUE THREAD

**Issue by SGEDA** [selectize/selectize.js#1526]
Hello community, i have a small problem.
Im currently using selectize on a project, i have a dropdown list and i want to add unexisting item,and the dropdown list show add "my new option", but i want when i create the name of this new option it will be created automatically
Thank you

**Comment by risadams** [comment]
apologies, but I'm not quite sure I understand what you are asking.  Can you please provide an example on codepen that  shows the issue and steps to recreate?

Thanks
