### ISSUE TITLE
Minimist dependency needs an update

### ISSUE THREAD

**Issue by incoming-th** [selectize/selectize.js#1538]
I did:

* [x ] Search for if my issue has already been submitted
* [x ] Make sure I'm reporting something precise that needs to be fixed
* [x ] Give my issue a descriptive and concise title
* [x ] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [ x] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

npm audit output warning about prototype polution on the minimist package.

Steps to reproduce:

1. npm audit

Expected result:

Expecting no warning

Actual result:

Got Prototype Pollution:

![image](https://user-images.githubusercontent.com/26375917/87272981-10c25880-c502-11ea-8bdb-93f0aaa0a9d6.png)

**Comment by emveeoh** [comment]
bump

**Comment by oliverkane** [comment]
It looks like this library is being maintained in some form given there's fairly recent commits.  Curious if this is on the radar, and a general inquiry as to why the npm package hasn't been updated for years.

**Comment by risadams** [comment]
minimist is not actually used this project,  it is a dependency of sifter.  An issue or PR should be in that repo not here.

There will be a new npm release soon,  development on this project was stalled for a few years, but we are now in the process of getting things cleaned up and active again.

**Comment by oliverkane** [comment]
Thanks!  Had forked both this project and minimist and was going to roll my own, and then saw that this project had recent commits and was wondering.

Glad to hear things are moving again.

For what it's worth, the source code of minimist (0.6.0) seems to work with selectize from what I tested.  They don't have a npm module out that resolves the underlying issue.

**Comment by fskarmeta** [comment]
Hi @risadams as you might now there is a new known vulnerability with this package. I was thinking of opening a new issue, but yeah, just figured out that it depends on sifter. Anyway, wanted to let you know just in case, not sure if it would make sense to open this issue again
<img width="502" alt="Screenshot 2022-03-22 at 20 31 07" src="https://user-images.githubusercontent.com/69222982/159560778-9a5d20d9-52c5-4b9d-bd3a-af4525ecc6c0.png">
.
