### ISSUE TITLE
How to set init value and label

### ISSUE THREAD

**Issue by frthjf** [selectize/selectize.js#155]
I use value declaration to initialize selectize:

``` html
<input type="text" value="awesome,neat">
```

But I don't know how to declare values with a different label, something like:

``` html
<input type="text" value="[{value:12,label:awesome},{value:137,label:neat}]">
```

so that selectize will show up with "awesome" and "neat" by post "12" and "137" on submit.

**Comment by brianreavis** [comment]
See the [0.12.0](https://github.com/brianreavis/selectize.js/releases/tag/v0.12.0) release for this. Selectize now recognizes the `dataAttr` attribute (`data-data` by default) for populating the initial values.
