### ISSUE TITLE
 clicking on scrollbar causes dropdown to close

### ISSUE THREAD

**Issue by matif827** [selectize/selectize.js#1550]
We are facing an issue with editor plugin and selectize dropdown. In Chrome and Edge browsers, clicking on dropdown scroll closes the dropdown.

We have created a scenario. https://jsfiddle.net/muhammad_atif/3xntu5we/37/

Your help will be highly appreciated.

**Comment by rushabh-wadkar** [comment]
Change your `dropdownParent: 'table'` instead of `body`. It would work.
