### ISSUE TITLE
return $item on onItemRemove callback (found the fix needed)

### ISSUE THREAD

**Issue by xddengx** [selectize/selectize.js#1558]
I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [x] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [x] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

**Issue**: The `onItemRemove` callback only returns the removed value. It would be useful if it returned the item as well (similar to `onItemAdd(value, $item)`). I looked into the source code for `removeItem:` and there is a parameter for the returned item, however it is the incorrect variable. 

**Working example**: https://codepen.io/dxd24/pen/Bazvqqv?editors=1011

**Fix**
Altered line of code in "0.12.6/js/standalone/selectize.js": 
`self.trigger('item_remove', value, $item);`
change to
`self.trigger('item_remove', value, $self);`

Altered line of code in "0.12.6/js/selectize.js": 
`g.trigger("item_remove", b, d));`
change to
`g.trigger("item_remove", b, g));`

Full code:
```
      removeItem: function (b, c) {
        var d,
          e,
          f,
          g = this;
        (d = b instanceof a ? b : g.getItem(b)),
          (b = k(d.attr("data-value"))),
          -1 !== (e = g.items.indexOf(b)) &&
            (d.remove(),
            d.hasClass("active") &&
              ((f = g.$activeItems.indexOf(d[0])), g.$activeItems.splice(f, 1)),
            g.items.splice(e, 1),
            (g.lastQuery = null),
            !g.settings.persist &&
              g.userOptions.hasOwnProperty(b) &&
              g.removeOption(b, c),
            e < g.caretPos && g.setCaret(g.caretPos - 1),
            g.refreshState(),
            g.updatePlaceholder(),
            g.updateOriginalInput({ silent: c }),
            g.positionDropdown(),
            g.trigger("item_remove", b, g));
      },

```
Thanks!

**Comment by risadams** [comment]
The current removeItem function is returning the same `$item` object that the addItem function returns.  your  change is actually returning the entire selectize object, which I don't believe is the correct approach.

If you do think that a change is needed please a look at the code in the src/ folder not the dist files and feel free to make a pull request.  you will also need to make sure that all test continue to pass

**Comment by xddengx** [comment]
Sorry, I was mistaken! I do see that $item is actually returned. 

Is it possible to get the returned $item's node values? When I try `$item.parentElement` it's null because the node has already been deleted in the DOM. The reason why I return the entire selectize object is because I have multiple selectizes on the page, and my goal is to figure out which selectize the item was being removed from.

So if i had a callback function like below, I can grab the selectize object and its control:
```
$('.mySelectize').selectize({
  onItemRemove: function (value, $item) {
       let selectizeInput = $item.$control;
  }
})
```

Perhaps not a change in the source file, but an additional parameter to return the entire selectize object, or is there a different approach to solve my problem? 

Thanks.
