### ISSUE TITLE
Mark v0.13.0 as a release

### ISSUE THREAD

**Issue by justanotheranonymoususer** [selectize/selectize.js#1564]
Here:
https://github.com/selectize/selectize.js/releases

You can see the tag, but not the proper release

**Comment by justanotheranonymoususer** [comment]
Also I think changelog can be updated
https://github.com/selectize/selectize.js/blob/master/CHANGELOG.md

**Comment by enguerrand-dilitrust** [comment]
is 0.13.0 released ?

**Comment by risadams** [comment]
0.13.0 is still in a work in progress, but is coming soon
