### ISSUE TITLE
Add Voice Commands to Selectize

### ISSUE THREAD

**Issue by SaucyOfficiale** [selectize/selectize.js#1565]
I need a way to add voice commands to selectize search. So if someone said, "videos" it would show in the search box for Selectize the search term "videos".

**Comment by databyte** [comment]
That is a feature of the web site and not this component.

You can approach this in two ways.

1. NLP would be provided by the device you use. For instance, on both Android and iOS devices, you can already do Voice-to-Text as an alternative keyboard that would allow "videos" to become typed out into a text box including one that's been enabled by selectize.

2. You can look at how to integrate [Web Speech API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API/Using_the_Web_Speech_API) separately.
