### ISSUE TITLE
Release new version on NPM

### ISSUE THREAD

**Issue by kkozlik** [selectize/selectize.js#1567]
Hello developers, thanks for this great library. But the last version on https://www.npmjs.com/package/selectize is two years old. Since than many issues has been fixed. Can we have these fixes on NPM too? Thanks in advance.

**Comment by risadams** [comment]
Absolutely!  It's not quite ready yet, but it will be updated as soon as the project is cleaned-up and stable

**Comment by espen** [comment]
Great to see the progress of this project. Could this issue be reopened so it is easy to get a notification when a new version is published on NPM?

Btw: It seems stable at the moment, good work with all the updates.
