### ISSUE TITLE
Selectize in conjunction with TinyMCE give problems

### ISSUE THREAD

**Issue by JoopStringer** [selectize/selectize.js#1569]
Selectize in conjunction with TinyMCE editor give some errors
It seems to jump into functions from TinyMCE ...
Any Idea how to fix it ?
```
Uncaught TypeError: Cannot use 'in' operator to search for 'selectionStart' in undefined
    at getSelection (selectize.js:3)
    at Selection.getSel (tinymce.min.js:21426)
    at Selection.isCollapsed (tinymce.min.js:21384)
    at getLocation (tinymce.min.js:17815)
    at BookmarkManager.getBookmark (tinymce.min.js:17872)
    at Selection.getBookmark (tinymce.min.js:21316)
    at Object.add (tinymce.min.js:25653)
    at Editor.<anonymous> (tinymce.min.js:25477)
    at Dispatcher.fire (tinymce.min.js:30842)
    at Editor.fire (tinymce.min.js:31082)

```

**Comment by risadams** [comment]
Are you able to please create a simple example on codepen that can reproduce the issue?

**Comment by JoopStringer** [comment]
Will try, lot of copy paste since it is a big system where I use it …
jQuery 3.3.1
Bootstrap 3
TinyMCE 4.6.4 
Latest Selectie

Hope you can figure it out :-)

**Comment by dannydotliu** [comment]
I also saw this issue, Selectize 0.13.0 and TinyMCE 5.6.1. Only happened when TinyMCE was set to ```inline: true```. Solved it by replacing-all ```getSelection``` in selectize.js with ```selectizeGetSelection``` so it seems to be a function naming conflict.

**Comment by cjamison** [comment]
I am seeing this exact same error as well with the Froala HTML editor. The error is in selectize version 0.13. Version 0.12.6 seems fine. You don't even have to enable selectize on a field. Just including selectize js is sufficient. Here is a jsfiddle showing the issue in chrome: https://jsfiddle.net/crestonjamison/0cr7ay6v/1/. The message is slightly different in Firefox.

**Comment by risadams** [comment]
@cjamison Thanks for the jsfiddle link,  This looks like there is in issue when the input field is undefined in the getSelection method,  I have a quick fix in place that should fix that.  Once CDNJS updates can you try again with v0.13.2? and see if that solves things.  

Thanks.

note that this will not fix the larger issue if the name of the getSelection method. I still need to review usages to make sure that it is safe to rename without breaking too many other things.

**Comment by cjamison** [comment]
@risadams I tried v0.13.2 and everything seems to work. No more errors for me. Thanks!

**Comment by JoopStringer** [comment]
Thanks guys for helping me out, I will try later in my system to see if all's well now.
