### ISSUE TITLE
Selectize and Laravel

### ISSUE THREAD

**Issue by askouev** [selectize/selectize.js#1570]
Good day!
Do you know of any problems installing selectize on a laravel? I do not receive data from the DB via ajax in selectize, but a separate ajax returns data.
What could be the problem?
Thank you!

`// ==================== HTML
<select style="width: 100%" id="specialty" name="specialty"
	class="location_select @error('specialty') is-invalid @enderror"
	required>
</select>`

`// =============================== Selectize
	$('#specialty').selectize({
		maxItems: 1,
		valueField: 'id',
		labelField: 'name',
		searchField: ['name'],
		create: false,

		load: (query, callback) => {
			if (!query.length) return callback();
			$.ajax({
				url: '/specialty',
				type: 'GET',
				dataType: 'json',
				data: {
					name: query,
				},
				error: () => callback(),
				success: (res) => callback(res),
			});
			console.log(query);
			console.log(callback());
		},
		render: {
			option: (item, escape) => {
				return `<div class="card w-100">
					<div class="card-body">
						<h6 class="card-title">${escape(item.name_specialty)}</h6>
						<div class="card-text">${escape(item.name_industry)}</div>
					</div>
				</div>`;
			}
		}
	});`

**Comment by risadams** [comment]
What is the result of the request in dev tools?  are there any console errors?
I have personally never used Laravel, but there shouldn't be any conflict

**Comment by askouev** [comment]
Good evening!
There are no errors in the console, the status is 200.
The php script requires the name of the search input, but I don't know it, I didn't find it from the documentation. Can you tell me how to refer to the search input, what is its name.
Thank you!

**Comment by askouev** [comment]
![2020-12-31_10-27-41](https://user-images.githubusercontent.com/38881271/103404160-e6696380-4b52-11eb-8d3e-cae0398fdce3.png)

**Comment by askouev** [comment]
![2020-12-31_10-34-01](https://user-images.githubusercontent.com/38881271/103404419-bec6cb00-4b53-11eb-87fe-f82add1f7167.png)

But the dropdown sheet in the page does not fall

**Comment by askouev** [comment]
In what format should selectize receive data ?

**Comment by risadams** [comment]
It should use json.  unless your original code and screenshots are from different parts of the page, it looks like you might need to   update your render function with the correct names.  (for example you are looking for "name_specialty" but that is not part of your json results.

Please take a look at github example on the demos page, and it should help you get things working

**Comment by anandphulwani** [comment]
> 
> 
> In what format should selectize receive data ?

```[{value:"AL", text:"Alabama"}, ... ,{value:"WY", text:"Wyoming"}]```
