### ISSUE TITLE
Requestion an unminified standalone distribution

### ISSUE THREAD

**Issue by ddemoss222** [selectize/selectize.js#1573]
I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [ ] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [ ] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

My issue is similar to this closed issue: https://github.com/selectize/selectize.js/issues/1465.

There are some bugs with opt group that I am seeing in the standalone, and it would be great to have an official standalone distribution that exposed the source in a non-minified way to aid in debugging and possibly extending the selectize features to suite my needs. 

Also, if there was a more comprehensive quickstart for the dist non-standalone, that could expedite a solution here as well. 

Expected result:

I expected to find a non-minified standalone dist to better aid in extending the features of selectize.js

Actual result:

There is only minified selectize.js standalone available in the official distribution channels.

**Comment by databyte** [comment]
You can point npm/yarn to a github repo to pull down the source and point to it. Or `git clone` locally and point to a local file.

https://docs.npmjs.com/cli/v6/configuring-npm/package-json#github-urls

Once you have the github repo, there is an unminified version in the `dist` folder:
https://github.com/selectize/selectize.js/blob/master/dist/js/selectize.js

Additionally you can even pull in the src folder and work directly on the source for help create your PR.
