### ISSUE TITLE
Open dropdown without focusing

### ISSUE THREAD

**Issue by jicihome** [selectize/selectize.js#1585]
Is it possible to Open dropdown only without focusing input?

I'm asking because on mobile, focus will open keyboard and reduce the view you have on option list. I would like to have a way to open the dropdown but not focus directly and wait for the user to focus when the dropdown is open.

**Comment by anandphulwani** [comment]
It is quite possible, please upload snippet to help you more on this.
 
> 
> Is it possible to Open dropdown only without focusing input?
> 
> I'm asking because on mobile, focus will open keyboard and reduce the view you have on option list. I would like to have a way to open the dropdown but not focus directly and wait for the user to focus when the dropdown is open.

**Comment by jicihome** [comment]
I was able to find a workaround. thanks ;)
