### ISSUE TITLE
Handling of existing option values with async loading of values? 

### ISSUE THREAD

**Issue by zopyx** [selectize/selectize.js#1591]
In our CMS we have the case that we generate this (note that we have no texts for the options, only their values)

```
<select name="ids"> 
    <option value="1"></option>
    <option value="2"></option>
</select>
```

and apply  `selectize()` together with a function for `load`.

Searching and loading new values from the backend works nicely.

Is there any way to lookup the existing texts for the existing options with value `1` and `2` upon initialization in order to render these existing options with the text belonging to each option?

**Comment by ghost** [comment]
``` 
load: function(query, callback) {
    const vm = this;
    loadNewOptionsFromServer().then(data => { callback(vm.options.concat(data)) }
}
```

When loading new options from server, you can use `callback` function to load new options and the current options that exist in dropdown menu.
