### ISSUE TITLE
File missing \bower_components\selectize\dist\js\standalone\selectize.min.js

### ISSUE THREAD

**Issue by afinzel** [selectize/selectize.js#1593]
Welcome to the Selectize bug tracker. Thank you for taking the time to
make Selectize a better library!

Please keep in mind this repository has an important issue backlog and
that maintainers have limited time to fix issues, triage, and understand
them.

If you've never done so, please read the
[guide to reporting issues](https://github.com/selectize/selectize.js/wiki/Reporting-issues-guide)
in the Wiki to help us better understand your issue.

Place an `x` in the checklist steps (`[ ]` becomes `[x]`) to demonstrate
you have done/verified all the steps you needed to do.

Thank you for reading this! You can now erase everything up to the
following dashes, and then complete what's after.

ISSUES THAT EITHER:

* IGNORE THE ISSUE GUIDELINES
* ERASE THE FOLLOWING TEMPLATE
* DON'T FOLLOW THE PROPER NUMBERED FORMAT FOR STEPS TO REPRODUCE

COULD BE CLOSED.

---

I did:

* [ X] Search for if my issue has already been submitted
* [ X] Make sure I'm reporting something precise that needs to be fixed
* [ X] Give my issue a descriptive and concise title
* [ ] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [ X] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

When installing using bower, the javascript file \bower_components\selectize\dist\js\standalone\selectize.min.js is referenced but since 12.6, this file is no longer present.  You also seem to be missing description and keywords from bower.js

Steps to reproduce:

1. bower install selectize

Expected result:
\bower_components\selectize\dist\js\standalone\selectize.min.js  to be present

Actual result:
\bower_components\selectize\dist\js\standalone\selectize.min.js  is not present

Bower upgraded us to the latest version and then our code was 404ing on the missing file and therefore not working.

**Comment by risadams** [comment]
The selectize.js file is itself minimized,  we could provide a copy that also has the .min.js extension to avoid confusion.

As bower is a deprecated service we no longer explicitly support it, and encourage a move to npm or yarn when feasible.
