### ISSUE TITLE
Cannot read property '$order' of undefined - Error Log

### ISSUE THREAD

**Issue by ghost** [selectize/selectize.js#1594]
https://github.com/selectize/selectize.js/blob/18ae944e92bce8576a1864503200114779569a18/src/selectize.js#L1129
https://github.com/selectize/selectize.js/blob/18ae944e92bce8576a1864503200114779569a18/src/selectize.js#L1133
When ```optgroup =''``` and then it will be pushed to ```optgroups```.
After that, the ```group_order``` sort by ```optgroups[i].$order``` which optgroups[''].$order will not exist.
https://github.com/selectize/selectize.js/blob/18ae944e92bce8576a1864503200114779569a18/src/selectize.js#L1143
Can we also check like below?
```
var a_order = self.optgroups[a] && self.optgroups[a].$order || 0;
var b_order = self.optgroups[b] && self.optgroups[b].$order || 0;
```

**Comment by risadams** [comment]
Good catch.  A fix should be available in the next release
