### ISSUE TITLE
Select text on focus

### ISSUE THREAD

**Issue by MattKetmo** [selectize/selectize.js#160]
Actually, on a "Single Item Select", when you want to select an item you have to focus (eg. click) on the input, then type backspace to clear the previous selection in order to search something else.

IMO, when focusing on the input text, the text should already be selected. So that you can start typing your search without pressing backspace first (like a normal select).

**Comment by axelvnk** [comment]
+1

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
