### ISSUE TITLE
An infinite loop may happen when searching option - Can not blur to another input!

### ISSUE THREAD

**Issue by ghost** [selectize/selectize.js#1600]
When typing an option that not in the options list. I have an issue that I can not focus on another input in Dom.
I go through the code and see that: on `Open` function calls `focus` function, and in `focus` function it calls `onFocus` function and in `onFocus` function, it calls `refreshOptions` function, finally in `refreshOptions` function, it calls `open` function.
  [`open`](https://github.com/selectize/selectize.js/blob/fc523380c77608383c78e299c8274a83d05ac0a0/src/selectize.js#L1852) --> [`focus`](https://github.com/selectize/selectize.js/blob/fc523380c77608383c78e299c8274a83d05ac0a0/src/selectize.js#L990) --> [`onFocus`](https://github.com/selectize/selectize.js/blob/fc523380c77608383c78e299c8274a83d05ac0a0/src/selectize.js#L628) --> [`refreshOptions`](https://github.com/selectize/selectize.js/blob/fc523380c77608383c78e299c8274a83d05ac0a0/src/selectize.js#L1218) --> [`open`](https://github.com/selectize/selectize.js/blob/fc523380c77608383c78e299c8274a83d05ac0a0/src/selectize.js#L1852)
If all of the conditions passes, the infinite loop will hapen.
Unfortunately, it happens in my case lead to I can not click on another input

**Comment by risadams** [comment]
We will take a look.  Thanks

**Comment by viktorsmari** [comment]
I am not able to reproduce this on Ubuntu, but I have been told this happens on new Windows machines with Firefox and Microsoft Edge browsers. Can you confirm this happens on Windows computers?

**Comment by ghost** [comment]
I am using ubuntu 18.04 with Chrome browser. The problem occurred when I try to delete some invalid options when `onDropdownOpen`  and `bllur` function has emitted, and also call `addOption` function to add a valid option.
This is because, when getting options from api to render into the dropdown, but the user does not want to choose any of them instead of click outside the input. So I need to add what user has typed to the option.
For example: User type 'Apple' but in the response data of api do not contain any text includes 'Apple', after that they click out side the input and expected 'Apple' will remain on the input.
This happened to me 2 months ago, so I solve the problem by editting selectize.js file on my side.
