### ISSUE TITLE
Sifter.prototype.search - options does not have `filter` property

### ISSUE THREAD

**Issue by ghost** [selectize/selectize.js#1601]
When calling `refreshOptions` at line 1106 [var results           = self.search(query);](https://github.com/selectize/selectize.js/blob/fc523380c77608383c78e299c8274a83d05ac0a0/src/selectize.js#L1106)
In `search` function at line 1059, options will be get from `getSearchOption`

https://github.com/selectize/selectize.js/blob/fc523380c77608383c78e299c8274a83d05ac0a0/src/selectize.js#L1059
In the `getSearchOption` function, the result does not have `filter` property.
But it will pass to `sifter.search` function
https://github.com/selectize/selectize.js/blob/fc523380c77608383c78e299c8274a83d05ac0a0/src/selectize.js#L1072
But in sifter.search, the `options.filter` will be use. Can we pass the filter from settings?

**Comment by risadams** [comment]
This is probably an oversight.  I will need to look at this to understand why it was done this way.
