### ISSUE TITLE
how can i add additional button which toggle dropdown, like arrow in html select?

### ISSUE THREAD

**Issue by russeljo** [selectize/selectize.js#1605]
in examples arrow appear in single mode and it's just a css-pseudo element ::after .... and there is no control of behavier on it.
I need html element like button in selectize-input, to toggle dropdown appearence, because click on input has another callbacks and behaviers.
And it's cause problem that user always need to click out of the selectize to close dropdown. But selectize is look like similar html-select and user need similar behavier - open/close dropdown by clicking on array.
We need separate click on selectize-input and click on arrow.
Hope you'll understand problem.
I found only this closed and dont resolved issue https://github.com/selectize/selectize.js/issues/1289

**Comment by russeljo** [comment]
last release was in 2016 ... there's no hope ,(

**Comment by russeljo** [comment]
i think better use select2 instead of this plugin.

**Comment by russeljo** [comment]
seems like it work:

```
$('.selectize-control .selectize-input').after("<div class='toggle-drop'></div>");
$('.selectize-control').delegate('.toggle-drop','mousedown',function(e){
    e.preventDefault();
    if($selectizeControl.isFocused){
        if($selectizeControl.isOpen) {
            $selectizeControl.close();
            $selectizeControl.blur();
        }else
            $selectizeControl.open();
    }else{
        if($selectizeControl.isOpen) {
            $selectizeControl.close();
            // $selectizeControl.blur();
        }else {
            // $selectizeControl.focus();
            $selectizeControl.open();
        }
    }
});
```

**Comment by anandphulwani** [comment]
> 
> 
> last release was in 2016 ... there's no hope ,(

Avoid making negative comments, you need to understand that we all are working hard, and in our spare time trying to build this library, if you can't contribute the least you can do is make such comments. If you want to contribute, please message for the same.

>
>
> i think better use select2 instead of this plugin.

Try using it ;) , i used select2 and came to this plugin and started helping in the development of this, for me select2 didn't work.

**Comment by russeljo** [comment]
> > last release was in 2016 ... there's no hope ,(
> 
> Avoid making negative comments, you need to understand that we all are working hard, and in our spare time trying to build this library, if you can't contribute the least you can do is make such comments. If you want to contribute, please message for the same.
> 
look up on one comment, i wrote solution, work is done, be happy!
