### ISSUE TITLE
Issue with Wordpress 5.7: Deprecation error - jQuery.isArray is deprecated; use Array.isArray 

### ISSUE THREAD

**Issue by abhij89** [selectize/selectize.js#1610]
With wordpress releasing latest version 5.7 with major jquery changes, I notice following issue with it: 
`selectize.min.js: jQuery.isArray is deprecated; use Array.isArray`

I am using selectize v0.13.3 with WordPress 5.7

Any thoughts on how can I solve this, I don't want to switch to another library?

#1277

**Comment by DenisLabrecque** [comment]
Use jQuery migrate or fix the calls to jQuery.isArray. Also possibly try https://github.com/DenisLabrecque/jQuery-UI-Fixed-for-3.5.1 but it isn't perfect.

**Comment by abhij89** [comment]
I would prefer not to introduce additional jquery to handle this, as I know WordPress already includes all the required js..and would like to avoid creating any conflicts with it.

**Comment by abhij89** [comment]
submitted the fix here: #1611
