### ISSUE TITLE
Tags 13 and up can't be installed with yarn.

### ISSUE THREAD

**Issue by acha5066** [selectize/selectize.js#1618]
Hi there, 

I want to install the latest tag which at the time of writing is 0.13.3 so that I can use the bootstrap 4 css. However, it seems the latest release available in the npm registry is 0.12.6.

I ran the following:

``` bash
yarn add selectize@^v0.13.3
yarn add v1.22.5
[1/4] 🔍  Resolving packages...
Couldn't find any versions for "selectize" that matches "^v0.13.3"
? Please choose a version of "selectize" from this list: (Use arrow keys)
❯ 0.12.6 
  0.12.5 
  0.12.4 
  0.12.3 
  0.12.2 
  0.12.1 
  0.12.0 
```
yarn 1.22.5

**Comment by risadams** [comment]
Yes.  Later versions haven't been officially released yet.

**Comment by chriskoelle** [comment]
any update on this? it's been almost 4 years since v0.13.0 and there are security vulnerabilities related to sifter which was removed in v0.14.0 almost 2 years ago
