### ISSUE TITLE
NPM version (v0.12.6) not updated

### ISSUE THREAD

**Issue by FritzHerbers** [selectize/selectize.js#1619]
On NPM the latest available version is v0.12.6. 
The latest tagged version is v0.13.3.

Can you please update NPM.

**Comment by risadams** [comment]
the v0.13 line is not an official release.  NPM will be updated when it is.

**Comment by subbarao** [comment]
when do you guys planning to publish latest tag to npm?

**Comment by ocarreterom** [comment]
The documentation are showing themes for Bootstrap v4 and v5, but only is available as part of selectize < v0.12.6.
What's the problem with publish NPM?
