### ISSUE TITLE
Selectize.js gets cut off when i placed it in footer area

### ISSUE THREAD

**Issue by kamran-hussen** [selectize/selectize.js#1620]
I am using selectize.js for my project it works fine. but when I put it in the footer area the dropdown menu opens from the bottom but I want it open from the top. how to solve the problem
![selectize-img](https://user-images.githubusercontent.com/48779929/120263511-a3581b80-c2bd-11eb-8778-9635fbf102e4.png)

**Comment by AntonYushkevich** [comment]
You could rewrite default `positionDropdown` method with custom: 
`Selectize.prototype.positionDropdown = function () {
        const $control = this.$control;
        const offset = this.settings.dropdownParent === 'body' ? $control.offset() : $control.position();
        offset.top += $control.outerHeight(true);

        const dropdownHeight = this.$dropdown.prop('scrollHeight') + 5; // 5 - padding value;
        const controlPosTop = this.$control.get(0).getBoundingClientRect().top;
        const wrapperHeight = this.$wrapper.height();

        this.$dropdown.css(
            Object.assign({
                width: $control.outerWidth(),
                left: offset.left
            },
            controlPosTop + dropdownHeight + wrapperHeight  > window.innerHeight
                ? {bottom: offset.top, top: 'unset', margin: '0 0 10px 0'}
                : {top: offset.top, bottom: 'unset', margin: '10px 0 0 0'}
            )
        );
    };`

**Comment by risadams** [comment]
@AntonYushkevich thanks for the suggestion,  would you be willing to add this as a plugin?

**Comment by AntonYushkevich** [comment]
@risadams sure

**Comment by KrunchMuffin** [comment]
@AntonYushkevich was this plugin ever implemented?
