### ISSUE TITLE
Selectize reduces width of dropdown making options illegible

### ISSUE THREAD

**Issue by whitsey** [selectize/selectize.js#1653]
I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [x] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [x] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

When loading selectize select inside a table, the table automatically reduces the cell width to the miminum possible squeezing selectize.  When you open dropdown, the options are illegible - the first 3-4 characters can be read and the rest are hidden.

Steps to reproduce:

1. Create a table with 20 columns
2. Add a select to the header of a few columns with a few values
3. View the dropdown options after selectize applied

Fiddle: https://jsfiddle.net/csjqaf3m/

Expected result:

![image](https://user-images.githubusercontent.com/3803274/129324618-dd0bb42f-27f6-491d-b729-b0261fba60c8.png)

Actual result:

![image](https://user-images.githubusercontent.com/3803274/129324720-b620cf0a-e667-49f3-8c47-0982d2b64f5a.png)

These columns cannot have fixed widths because the data loaded into the varies - Just need the dropdown to be set to the width of its content

**Comment by vanboom** [comment]
My PR #1814 implements a simple `minWidth` option that will allow the dropdown to flow wider than the parent control.  Hoping the maintainers will consider it for a simple easy upgrade to the control.

**Comment by whitsey** [comment]
That doesn't really help because each dropdown is different in width - setting a minWidth is no different than just hardcoding a width on each element.

It is ugly but I ended up using JavaScript to find the length of the longest item in the dropdown.

`optionLength = (cellData.length>optionLength?cellData.length:optionLength);`

and then, created a spacer using dashes with the length each side as a buffer.

`var spacer = "-".repeat(optionLength/1.5);
select.prepend('<option value="">'+spacer+' All '+spacer+'</option>');`

Not the most elegant solution but the best I could come up with for this inflexible framework.
