### ISSUE TITLE
Self-filtering tag-style SELECT

### ISSUE THREAD

**Issue by jasonl99** [selectize/selectize.js#166]
A quick description of what I am trying to do:  I have a tree of categories; for example Countries has Canada and US.  US has States, Canada has Provinces. 

I'm trying to get selectize to self-limit choices based on already-tagged items.  For example, the dropdown initially have everything (Canada, US, States, Provinces, etc).  When I start typing (and then select) "United States" and select it, I get a nice tagged entry exactly as planned. 

Here's where I can't figure out how to get it working.  After having "tagged" United States, I want to add another tag right in the same box, but this time the choices in my selectized-box should be limited to only the states in the US.  

I've verified that my ajax remote code is working properly and returning the new limited subset of data (I send the currently-selected options along with the "q" query), in this case, just a list of states.  However, selectize still shows the entire list of options; it does not seem to limit them based on the  returned data from the server; it seems to use the initially-loaded list.  It seems that the newly-retrieved list of options is not being loaded.

What am I missing?

**Comment by sandstrom** [comment]
This question is better suited for [StackOverflow](http://stackoverflow.com) or similar. I'd suggest closing this issue.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
