### ISSUE TITLE
Input width calculation is wrong, if custom font is used.

### ISSUE THREAD

**Issue by bkonetzny** [selectize/selectize.js#173]
We have a custom font which is loaded via css @font-family. When the input width calculation is done by creating a dummy element in the body DOM containing the text of the input, the font-family for calculation is "serif" as our custom font is not loaded yet by the browser. As the font is different, the initial input is too short to show all the placeholder text to the user as the text is shown in the then loaded font.

We need to find a way to defer calculation of the input until the font is loaded or recalculate when the font on the input is changed. Any ideas about this?

**Comment by mikebronner** [comment]
Just ran into this issue as well.

**Comment by notflip** [comment]
Same issue here

**Comment by Henriquehgb** [comment]
in this code:

/**
- Restores input visibility.
  */

showInput: function() {
 this.$control_input.css({opacity: 1, position: 'relative', left: 0});
 this.isInputHidden = false;
},

I changed to:

/**
- Restores input visibility.
  */

showInput: function () {

  var $control = this.$control;
  var offset = this.settings.dropdownParent === 'body' ? $control.offset() : $control.position();
  offset.top = 0;
  if ($($control).find('div').text().length > 0)
     offset.top -= 20;
  offset.left += ($($control).find('div').width());

  this.$control_input.css({ opacity: 1, position: 'relative', left: offset.left, top:offset.top });
  this.isInputHidden = false;
},

Work for me.

**Comment by marcusmolchany** [comment]
i think this may be a similar issue https://github.com/selectize/selectize.js/issues/851

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
