### ISSUE TITLE
Resume Typing on Focus

### ISSUE THREAD

**Issue by chiplay** [selectize/selectize.js#181]
We're using selectize.js for a search autocomplete menu and it works amazing! (w/ optgroups and 'recent searches'!).  The only problem is when the user want to change the search, the selected 'item' has to be removed to search again.  With the restore_on_backspace option - it works a little better, but the user is expecting backspace to delete a letter on the first press (instead of the second) and if they start typing w/o hitting backspace, it's not responsive.  

Ex. User searches for "Milk" and that is 'created' as a new item in the recent searches optgroup. The "Milk" item stays in the search bar.  User clicks back on the bar to refine the search to "Milk Organic" - but typing doesn't work.

Is there anyway to have the search input stay persistant and add items so that its simple to edit the search query? 

Thanks for the great work!  

(side note - using selectize.js with backbone.stickit and its pretty slick - https://gist.github.com/chiplay/7272109)

**Comment by tjperovich** [comment]
@christopherdupont Thanks a ton! I was just about to write my own handling for this, but this plugin works great.

**Comment by tltowles** [comment]
@christopherdupont This has been on our backlog for a while to fix. Thank you!

**Comment by nkoren** [comment]
Thanks @christopherdupont -- this almost worked for me. For anybody else borrowing this hack: I had to replace '{keyCode: KEY_BACKSPACE}' with '{keyCode: 8}' to make it work properly.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
