### ISSUE TITLE
Selectize should automatically float left to allow buttons next to it

### ISSUE THREAD

**Issue by nesl247** [selectize/selectize.js#197]
A normal select allows buttons to the right of it without having to add a float to it. Using selectize requires this to happen. This becomes annoying when using bootstrap 2's form-inline class.

**Comment by bbalet** [comment]
For the next people who will find this issue (as I did in my search). Here is a cleaner solution to align the control (example with bootstrap) : https://jsfiddle.net/0my82e2f/1/
See http://stackoverflow.com/questions/31922237/how-to-align-a-selectize-control-with-a-boostrap-button-next-to-it/31933644#31933644

No need to manipulate the padding if you use a CSS grid system:

```
.selectize-control {
    display: inline-block;
    vertical-align: middle;
}
```
