### ISSUE TITLE
bootstrap3 css for inputs...

### ISSUE THREAD

**Issue by sanfords** [selectize/selectize.js#203]
Wonderful work on selectize!

```
In the Bootstrap3 CSS for .selectize-input {
}
```

Change:

```
  -webkit-box-shadow: none;
          box-shadow: none;
```

To:

```
  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
          box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
```

To make inputs look a little more consistent with bootstrap3 inputs.  I can't quite get the fade-in to work properly, though.  Any ideas?

**Comment by joallard** [comment]
Thanks for reporting this issue. I am closing it since this issue has been inactive for more than 2 years. If there is still a problem, please re-open.
