### ISSUE TITLE
Right Alt+A issue

### ISSUE THREAD

**Issue by krysros** [selectize/selectize.js#206]
Right Alt+A works like Ctrl+A (select all). This is a big problem in some languages with non-ascii letters. For example: Right Alt+a in Polish should create "ą" character.

Windows 7. Selectize 0.8.5.

**Comment by wojtasskorcz** [comment]
We have the same problem in our project. Brian, please merge the PR if it fixes it. It's quite important for all the people who use languages with diacritics

**Comment by ppawel** [comment]
Yeah it's quite frustrating for the users.

**Comment by FelipeeDev** [comment]
What about this issue. Does the abobe solution from @ppawel can be merge?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
