### ISSUE TITLE
Feature request: Stick to one type of class name separator

### ISSUE THREAD

**Issue by frankie-loves-jesus** [selectize/selectize.js#211]
Noticed some inconsistencies with class name separators, ie.:

```
.selectize-dropdown.plugin-optgroup_columns
.selectize-control.plugin-remove_button
```

should probably be:

```
.selectize-dropdown.plugin-optgroup-columns
.selectize-control.plugin-remove-button
```

**Comment by joallard** [comment]
Agreed, even though it's a breaking change

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
