### ISSUE TITLE
[Remote source] Display selectize dropdown on click on selectize control 

### ISSUE THREAD

**Issue by haovn** [selectize/selectize.js#216]
In the example "Remote Source — Rotten Tomatoes" (http://brianreavis.github.io/selectize.js/). When i click on selectize control, i want to load 10 latest movies from remote server and show the dropdown.

I need this feature but i don't know where to start. Please give me some advice so that i can complete and contribute this feature.

**Comment by joallard** [comment]
Thanks for reporting this issue. I am closing it since this issue has been inactive for more than 2 years. If there is still a problem, please re-open.
