### ISSUE TITLE
Disable automatic sort

### ISSUE THREAD

**Issue by eliashdezr** [selectize/selectize.js#218]
Hi, I'm receiving a pre-ordered list (JSON) but when I loaded into the selectize control, it re-orders the list by the Id and I don't want this. How I can let selectize use the order of my JSON?

This is the JSFiddle example:
http://jsfiddle.net/LYYab/

Thanks.

**Comment by brianreavis** [comment]
A fix for this is coming soon (in the next release, in a couple days). See https://github.com/brianreavis/selectize.js/issues/640#issuecomment-71788203

**Comment by althaus** [comment]
So what is the final solution to this issue? I've tried all kinds of settings and only the following seems to preserve the order from our ajax call:

```
var options = {
    other: settings,
    score: function() {
       return function(search) {
            return 1;
       }
    }
}
```

**Comment by dannyblv** [comment]
Has this issue been resolved? I can't get the correct behavior no matter what I try. @israelidanny

**Comment by hidegh** [comment]
@Danny-weebo if not, just create an additional sort-column with numbers asc/desc and use it as def. sort (see my prev. comment)

**Comment by developer239** [comment]
This worked for me:

```
$("your-selector").selectize({ score: function() { return function() { return 1 }; },
```

**Comment by diofeher** [comment]
Changing the score function will lose the power to search in the input. Still looking for a solution...

**Comment by pnpetroff** [comment]
Still no way to disable auto sort?

When I reorder with the `drag_drop` plugin it resets on update in my application.

**Comment by Pulsar-Mind** [comment]
Still nothing here? Im facing the same problem.

**Comment by thomascjohnson** [comment]
Ping!

**Comment by Skintillion** [comment]
When exporting from database, make a column with a count and use that?

**Comment by saxodel** [comment]
Same here.

**Comment by genechuah** [comment]
+1
I need the original input sequence to be honored when pre-populating the selected options.

**Comment by FlyingTigra** [comment]
Still have this bug! Help!

**Comment by dtenenba** [comment]
Despite this issue being closed, I'm still having it 5 years after it was opened, as are others it seems. (with version 0.12.4). I'm about to ditch selectize altogether because of this. The `score` solutions posted by others don't work for me; they correct the sorting problem but disable selection.

**Comment by mezga0153** [comment]
This works for me:
```
"score": function(search_string) {
	return function(element) {
		return new Sifter([element]).search(search_string, {
			fields : ["same as searchField"]
		}).items.length;
	};
},
```

It disables the default sorting and the search function keeps working as expected

**Comment by LjyYano** [comment]
Still have this bug

**Comment by urmamb** [comment]
Use `sortField` and you should see the sort `sortField: [{field: 'name', direction: 'asc'}]` forexample

```
var select = $('.js_client_search').selectize({
			maxItems	: 1,
			valueField	: 'name',
			labelField	: 'name',
			searchField	: ['name', 'message'],
			options		: [],
			maxOptions	: 30,
			loadThrottle: 0,
			sortField	: [{field: 'name', direction: 'asc'}],
```

**Comment by Riz-waan** [comment]
Is this fixed?

**Comment by xhafan** [comment]
This works for me for `select` tag with options:
```
$("select").selectize({
        score: function (search) {
            // @ts-ignore
            var score = this.getScoreFunction(search);
            return function (item) {
                return score(item) ? 1 : 0;
            };
        }
    });
```
When typing to search, it respects the original order of options.
Taken from https://github.com/selectize/selectize.js/issues/196#issuecomment-69476446 and simplified for my case.

**Comment by Godsmith** [comment]
@xhafan This works for me as well, excellent workaround.
