### ISSUE TITLE
Bug: Firefox and OptGroups. Must press additional [backspace] key.

### ISSUE THREAD

**Issue by jensJJ** [selectize/selectize.js#220]
Hello, I am using Firefox 25.0.1 on Mac. With the newest version of selectize.js and default.css. When using the first optgroups.html example, without Sortfield:  sortField: 'text'.

$('#select-gear').selectize({
});

Firefox does not recognize, that you want to pick a new element. I have to backspace, before being able to select an item. This works in Google Chrome without having to use backspace.

**Comment by joallard** [comment]
Thanks for reporting this issue. I am closing it since this issue has been inactive for more than 2 years. If there is still a problem, please re-open.
