### ISSUE TITLE
Chrome/IE Auto-Width Misbehaving Justification

### ISSUE THREAD

**Issue by locux** [selectize/selectize.js#221]
When setting the width of the selectbox to auto, under the following circumstance, a wide option will spontaneously change it's justification.

a) Create option box with one or more options that exceed width of select option
b) From drop-down list, select the long option
c) Open the list again, and this time click outside the option box to close it (somewhere else on the screen)
d) Sometimes step c needs to be repeated twice to display the issue.

The contents of the box will change their justification.  It behaves differently than if you close the options by clicking inside the box.  Only affects IE and Chrome.  Firefox seems to work OK.

Demonstration here: http://jsfiddle.net/rdX5R/6/

![image](https://f.cloud.github.com/assets/6041029/1736273/3f7268ae-6362-11e3-8abf-197c15cba066.png)

**Comment by joallard** [comment]
Thanks for reporting this issue. I am closing it since this issue has been inactive for more than 2 years. If there is still a problem, please re-open.
