### ISSUE TITLE
How to make a specific option unselectable programmatically?

### ISSUE THREAD

**Issue by babarizbak** [selectize/selectize.js#222]
Hi,

I have a select with several options and I try to make some of the options unselectable programmatically. For instance, my code is :

``` html
<select>
  <option value="1">Value 1</option>
  <option value="2">Value 2</option>
  <option value="3">Value 3</option>
</select>
<script>
  $('select').selectize();
</script>
```

My question is: how can I make to get option "2" disabled (i.e. not displaying and not selectable) programmatically? -- I tried this code...

``` javascript
$('select')[0].selectize.$dropdown_content.find('[data-value="2"]').removeAttr('data-selectable');
```

... but it does not work (when I inspect the DOM I see that option "2" has no 'data-selectable' attribute, but it still renders and is selectable...).

Am I wrong here? And if so: what is the proper way to make an option unselectable (I can't find it anywhere in the doc or examples)?

Edit: I created a jsFiddle here: http://jsfiddle.net/j8YUA/3/

**Comment by joallard** [comment]
Thanks for reporting this issue. I am closing it since this issue has been inactive for more than 2 years. If there is still a problem, please re-open.
