### ISSUE TITLE
how to make enter key press behaves like a tab

### ISSUE THREAD

**Issue by oytunyuksel** [selectize/selectize.js#223]
i can try this:
$(document).ready( function(){
    $(".vertical").keypress(function(event) {
        if(event.keyCode == 13) { 
        textboxes = $(".vertical");
        debugger;
        currentBoxNumber = textboxes.index(this);
        if (textboxes[currentBoxNumber + 1] != null) {
            nextBox = textboxes[currentBoxNumber + 1]
            nextBox.focus();
            nextBox.select();
            event.preventDefault();
            return false 
            }
        }
    });
});
but it's doesn't work with selectize.js

**Comment by sandstrom** [comment]
This question is better suited for [StackOverflow](http://stackoverflow.com) or similar. I'd suggest closing this issue.
