### ISSUE TITLE
No support for "disabled" options?

### ISSUE THREAD

**Issue by babarizbak** [selectize/selectize.js#224]
When an `<option>` in the original `<select>` has a `disabled` attribute, the option is not disabled after being selectize'd.

It is a very big lack IMO, since `disabled` options are quite common. Is there plan to add support?

See this Fiddle http://jsfiddle.net/76ETp/1/

**Comment by francis-li** [comment]
Disabled select options can also be achieved by overriding the render function.

``` javascript
$('#control').selectize({
  render: {
    option: function(item, escape) {
      if (item.value === '') {
        return '<div style="pointer-events: none; color: #aaa;">' + escape(item.label) + '</div>';
      }

      return '<div>' + escape(item.label) + '</div>';
    }
  }
});

```

**Comment by rob-balfre** [comment]
Thanks @francis-li. Worked for me :+1:

**Comment by thednp** [comment]
@francis-li, me too :)

**Comment by JonathanFerreira** [comment]
Thanks @francis-li.

**Comment by sc0ttman** [comment]
Can still select options with keyboard :( What happened I thought there was support for this?

**Comment by ajaymor** [comment]
How can we disable selection for keyboard events as well? "pointer-events" attribute is only for mouse events. Look forward to hearing from you soon. Thank you in advance.

**Comment by sun-ks** [comment]
I used this plugin for disabling some options https://github.com/mondorobot/selectize-disable-options

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
