### ISSUE TITLE
Unbind Events for "OnChange"

### ISSUE THREAD

**Issue by eliashdezr** [selectize/selectize.js#225]
I'm having a trouble were the events are stacking. How I can implement the "unbind" event and then reasign the event.

Thanks.

**Comment by arnaudbos** [comment]
Just wanted to add my two cents:

$("select").selectize(options).on("change", function(event) {console.log("changed!"); })

Works well when adding an onChange event listener on a bunch of selects, but then subsequent operations need to be done on single items.

$("select")[0].selectize.off()
$("select")[0].selectize.on("change", function(event) {console.log("changed 2!"); })

**Comment by ameshkin** [comment]
having the same type of issues. clicking on a label will trigger on change, blur and focus!

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
