### ISSUE TITLE
Default selected value while using ajax

### ISSUE THREAD

**Issue by wishabhilash** [selectize/selectize.js#226]
I have been trying to provide default value to the selectize and also loading new options using ajax.
Example,
Consider you have 5 friends which you get from an ajax query as you search. In the first instance you select 3 friends and save it.
Refresh the page.

Now it should show the 3 selected friends and you can also typeahead to add new friends to it.

I am not able to achieve this. Any idea???

Note: I am able to do it if "options" parameter is not used.

**Comment by maxi032** [comment]
Can you guys please give more details if you were successful?
