### ISSUE TITLE
Bug with 'addPrecedence'

### ISSUE THREAD

**Issue by alibozorgkhan** [selectize/selectize.js#233]
Hi,

I found a bug with 'addPrecedence' option. In `github` example, turn `create` and `addPrecedence` on and type 'appt'. when the data is loaded, clear the text field and type 'a'. It doesn't focus on 'Add a...' anymore and focuses on one of the options. I would love to fix it myself but I am super busy right now. I will look into it maybe later, but just wanted to let you guys know of the problem.

Cheers,
Ali

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
