### ISSUE TITLE
ID of parent select

### ISSUE THREAD

**Issue by freeyland** [selectize/selectize.js#234]
Dear,

I have a lot of selectize elements on my page. Each of them are populated via ajax. 
Is there a way to send the original id or data attribute to the ajax call? I would like to to do, so that I don't need to repeat my code. (type 2600, type 3800,...)
I would like to replicate " type: '2600' " with: $(this).attr('id') or $(this).data('type')
load: function(query, callback) {
            if (!query.length) return callback();
            $.ajax({
                url: 'scripts/current_planned/ajax/field_list.php',
                type: 'GET',
                dataType: 'json',
                data: {
                    q: query,
                    field: 'config',
                    type:'2600'
                },
                error: function() {
                    callback();
                },
                success: function(res) {
                    callback(res);
                }
            });
        }

Home it is clear

**Comment by joallard** [comment]
Thanks for reporting this issue. I am closing it since this issue has been inactive for more than 2 years. If there is still a problem, please re-open.
