### ISSUE TITLE
Setting a default value from <select> element itself

### ISSUE THREAD

**Issue by mgibbs189** [selectize/selectize.js#236]
Hi again - based on your "Movies" example, I have a [select] box pulling in remote data. What's the best way to set a default value? Could it happen using the HTML element itself, it would it need to happen from within the selectize options object?

**Comment by temuri416** [comment]
@dule 

The problem with this approach is that onChange event is fired.

I need to load the page, set some initial value inline on a <select /> and then watch for selection changes made by the user.

Something like this:

``` html
<select data-value="10" ></select>.
```

**Comment by dule** [comment]
@temuri416: According to @brianreavis, the newest release supports a data-data field:
https://github.com/brianreavis/selectize.js/issues/155#issuecomment-72153150

But the `setValue` also accepts a `silent` param that should suppress the change event: https://github.com/brianreavis/selectize.js/blob/master/docs/api.md#methods_other

**Comment by brianreavis** [comment]
The best way to set the default value is to set the [`selected` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option#attr-selected) on the option(s) that you want selected. This of course means that the selected options need to exist in the DOM first, which isn't a bad idea regardless (i.e. when you submit a form before javascript loads, you don't want your form data to be invalid).

**Comment by temuri416** [comment]
@brianreavis 

But that is not possible when select options are provided using "options" parameter.

The following trick works for me, but it's kind of ass-backwards:

``` html
<select ...>
    <option value="5" selected="selected"></option>
</select>
```

Select's options are populated from JSON.

**Comment by brianreavis** [comment]
@temuri416 That's not the question though, is it? For that, set `items: ['5']` in your settings. I just updated the usage documentation to cover that.

**Comment by temuri416** [comment]
Thanks... `items` is what I was looking for.
