### ISSUE TITLE
IE9 not firing focus event on input after selectize

### ISSUE THREAD

**Issue by marijo-knez** [selectize/selectize.js#237]
http://jsfiddle.net/aBkgs/13/

So I have a selectize with some options and an input next to it. When I select a value form the selectize (or just focus on the control) and then click on the input the focus event of the input does not fire in IE9. It works in Chrome. If I click one more time on the input then the event fires.

For jsfiddle to work in IE9 follow this link. http://stackoverflow.com/questions/15260947/why-jsfiddle-is-not-rendering-at-all-in-ie8-and-previous-versions

Can anybody help? Am I missing something?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
