### ISSUE TITLE
The selectize-input input field is bound to the length of the placeholder, potentially expanding the selectize input to 2 lines

### ISSUE THREAD

**Issue by stringbeans** [selectize/selectize.js#238]
When using a placeholder, the width of the selectize-input input is initialized to the width of the placeholder text. This creates a UI bug after you select an option as it'll expand the selectize field into 2 lines vertically.

The below screenshot is an example of this happening. The placeholder of this field is "Where do you want to study?" which initializes a selectize-input input to be a width of 190px... but the whole container itself is roughly 300px. After selecting "Vancouver, Canada" the selectize-input input is pushed to a new line when it should fit right after the selected value of "Vancouver, Canada"

![screen shot 2014-01-02 at 6 16 27 pm](https://f.cloud.github.com/assets/1228699/1837105/2393f08c-741d-11e3-860c-0b809480f671.png)

**Comment by WeiB71** [comment]
how did you do that i want that new line
