### ISSUE TITLE
Using arrays in stead of objects?

### ISSUE THREAD

**Issue by notflip** [selectize/selectize.js#240]
I like this plugin very much, but the examples are really hard to understand..

I want to recreate a situation like the State/City selector, But i'm unable to do that, I tried everything to make the output look the same.

Is it so hard to accept arrays as arguments for the addOption?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
