### ISSUE TITLE
Dropdown effects table cell width

### ISSUE THREAD

**Issue by jeroentaal** [selectize/selectize.js#242]
Is there a way to prevent the selectize dropdowns to effect the width of the table cell (column) without giving it a fixed width (so it's fills up the cell completely at all times)? Just like how a normal dropdown functions. When the content of the input is larger (wider) than the table cell the cell expands. Try it in the demo below by selecting values.

http://codepen.io/anon/pen/weHbk

**Comment by joallard** [comment]
Thanks for reporting this issue. I am closing it since this issue has been inactive for more than 2 years. If there is still a problem, please re-open.
