### ISSUE TITLE
Request to play friendlier with custom scrollbars

### ISSUE THREAD

**Issue by estaylorco** [selectize/selectize.js#246]
There appears to be no way to use any of the various custom scrollbars out there to replace the built-in scrollbar used by selectize.

Currently, I'm using mCustomScrollbar, and I'm unable to integrate it into the control.  I have tried the following using the onDropdownOpen event:

NewOpportunity.prototype.attachScrollbar = function($dropdown) {
    $content = $dropdown.find( '.selectize-dropdown-content' );
    $content.mCustomScrollbar( {theme: 'dark-thick'} )
}

The scrollbar flashes for a moment, but then disappears.  So it's trying to work.  But when I inspect the DOM, I can see that the two helper divs that normally follow the div to which an mCustomScrollbar is attached, are removed.  It must be something that selectize is doing to the DOM surrounding the content.

Does anyone have any idea what's going on?  I posed the question on StackOverflow, but no one's responded.  I thought perhaps this would be the better forum.

Thank you.

Eric

**Comment by thanhlcm90** [comment]
var element = $('element');
var config = {};
// set custom dropdown height
// config.dropdownHeight  = 300;

config.onInitialize = function() {
                    var selectize = element[0].selectize;
                    var dropdownContent = selectize.$dropdown_content;
                    var dropdown = selectize.$dropdown;
                    // config dropdown height
                    config.dropdownHeight = config.dropdownHeight || 250;
                    dropdown.css({
                        'max-height': config.dropdownHeight + 'px'
                    });
                    dropdownContent.css({
                        'max-height': '100%'
                    });
                    dropdown.mCustomScrollbar({
                        setHeight: config.dropdownHeight,
                        theme: 'minimal-dark'
                    });
}
// init selectize
element .selectize(config);

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
