### ISSUE TITLE
How to not open the dropdown when an item is removed?

### ISSUE THREAD

**Issue by deiucanta** [selectize/selectize.js#249]
I tried to do it like this but it doesn't work

``` javascript
$('.selectize.custom').selectize({
    plugins: ['remove_button'],
    onItemRemove: function() {
        this.blur();
        this.close();
    }
});
```

Do you have any ideas?

**Comment by wadjei** [comment]
I achieved this a bit more cleanly, without needing to fork selectize by creating the following plugin:

```
Selectize.define('silent_remove', function(options){
    var self = this;

    // defang the internal search method when remove has been clicked
    this.on('item_remove', function(){
        this.plugin_silent_remove_in_remove = true;
    });

    this.search = (function() {
        var original = self.search;
        return function() {
            if (typeof(this.plugin_silent_remove_in_remove) != "undefined") {
                // re-enable normal searching
                delete this.plugin_silent_remove_in_remove;
                return {
                        items: {},
                        query: [],
                        tokens: []
                    };
            }
            else {
                return original.apply(this, arguments);
            }
        };
    })();
});
```

Include that as a .js file or include it inline and enable the plugin in the selectize items where it's needed using 

```
    $('#item').selectize({
...
        plugins: ['silent_remove'],
...
    });
```

see the api docs here https://github.com/brianreavis/selectize.js/blob/master/docs/plugins.md for more about how to use plugins

**Comment by gmmarc** [comment]
Thanks @wadjei ! Exactly what I needed :)

**Comment by jasmedia** [comment]
@wadjei , Nice stuff man!

**Comment by gregblass** [comment]
For some reason this didn't work for me. Just removed my "x" remove buttons altogether... :(

**Comment by seriouslysean** [comment]
@wadjei seriously excellent way of handling that-- thanks so much!

**Comment by Kerumen** [comment]
I also need this! Any update?

**Comment by mlensment** [comment]
+1

**Comment by mlensment** [comment]
```
$('.selectize').selectize
  plugins: ['silent_remove', 'remove_button']
```

Works in Firefox 41.0.2 (Ubuntu), but doesn't work in Android 4.4.4 default browser.
+1 For this feature.

**Comment by rnbwspctrm** [comment]
It would be great to be able to hook into onItemRemove more easily. My multi-select change event does not fire when an item is removed.

**Comment by zwantE** [comment]
> Do you have any ideas?

just add a timeout 

```
onItemRemove: function(value) {
  var input = this;
  setTimeout(function(){
    input.close();
  }, 7);
}
```
