### ISSUE TITLE
UpdateOption doesn't call UpdateOriginalInput

### ISSUE THREAD

**Issue by Ghalleb** [selectize/selectize.js#252]
When calling UpdateOption, UpdateOriginalInput.

If you have a createItem {1, test1 } et then make a updateOption(1, {2, test1}) in the original select there is still <option value="1" ...>

The workaround is to call UpdateOriginalInput after calling UpdateOption

**Comment by joallard** [comment]
Thanks for reporting this issue. I am closing it since this issue has been inactive for more than 2 years. If there is still a problem, please re-open.
