### ISSUE TITLE
Input width changes and jumps

### ISSUE THREAD

**Issue by ssbb** [selectize/selectize.js#254]
Hello!

Firstly thank you for your good work. It's really useful plugin.

But I have problem on Chrome 32 (Mac OS 10.9) with input width. I use selectize for list of e-mail addresses. And when I type `@` input width starts jumping: firstly 11px and then after few moments it's 18px.

I can fix it if remove line 1026 in the file standalone/selectize.js

But I'm not sure that it is correct.

I see this behavior with another symbols: `~`, `+`, etc.

Can anyone help me? Thanks.

**Comment by joallard** [comment]
Closing for #1106

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
