### ISSUE TITLE
Input height jumps.

### ISSUE THREAD

**Issue by notflip** [selectize/selectize.js#255]
In my example the height of the element jumps open. Is this because the input is to long and i'm limiting the width?

![jump](https://f.cloud.github.com/assets/4146384/1950094/7feec64e-8134-11e3-80af-5394b9e43842.jpg)

**Comment by dmastylo** [comment]
Just for anyone else coming through. If you're using Rails and the Foundation gem, throw the code  @jayswain posted in your foundations_and_overrides.css file at the very bottom and comment out

```
@include box-shadow($input-box-shadow);
```

Quick fix and I'm not overly concerned with the box shadow so I didn't try to locate it.

**Comment by wolfgang-demeter** [comment]
Just a small update and maybe a little help for somebody. The last days i tinkered a lot of hours with selectize.js to work flawless with Foundation (v5.5.1). It works basically - my SCSS-code above is still fine - but it has it's kinks. Sometimes the font-sizes don't match. Sometimes the positions are a little misaligned. Sometimes it works on "desktops" but is unuseable on "mobile".

After a bit of frustration i ditched selectize.js and tried to incorporate jQuery-UI. Look at http://jsfiddle.net/vgarcias/WdncE/ for a basic example (not from me). You have to work a little more if you want to use it with Foundation v.5.5.1. And jQuery-UI is "heavy" just for a basic autocomplete-Feature. And as i really only need it for a basic autocomplete - none of the additional fancy features selectize.js (or jQuery UI) offers - i ditched that to. I now use an **HTML5 datalist**! Look at http://jsfiddle.net/r6evd9s1/9/ for a simple example. You can also use AJAX to fill the datalist: http://codepen.io/matt-west/pen/jKnzG

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
