### ISSUE TITLE
Touch events not firing inside ios - includes fix

### ISSUE THREAD

**Issue by voltsonic** [selectize/selectize.js#259]
inside selectize.js (v0.8.5) you use the events mouseenter and mouse down, in which these events do not get fired within ios. So if someone attempts to choose something from the dropdown list it won't update the new one (although you can certainly add new ones all the other events seem to fire properly)

On line 1177 - 1178 you will see 

```
        $dropdown.on('mouseenter', '[data-selectable]', function() { return self.onOptionHover.apply(self, arguments); });
        $dropdown.on('mousedown', '[data-selectable]', function() { return self.onOptionSelect.apply(self, arguments); });
```

add this line right below to enable the click events within iOS devices!

```
        $dropdown.on('click', '[data-selectable]', function() { return self.onOptionSelect.apply(self, arguments); });
```

**Comment by kinergy** [comment]
@brianreavis this is a pretty annoying bug, please accept the PR referenced above. Like others, I'd rather not maintain my own fork just for fixing this. It's been a year! :) Thanks!

**Comment by kinergy** [comment]
Thanks!
