### ISSUE TITLE
Custom values dissapear

### ISSUE THREAD

**Issue by mattlanham** [selectize/selectize.js#261]
It would seem that selectize will only show highlighted values that it knows about, I have two methods for users to choose the values, from the list, or by typing them in.

If they type them in, then save the value is for example hello, 24, 35 - the numbers in this case are the id's from the selected fields, but when the page is refreshed, only the fields from the dropdown are populated, and the custom value hello, is lost.

Is there anyway to tell selectize to allow any value to be highlighted?

**Comment by oytuntez** [comment]
+1.

This is usually a very useful feature, the biggest reasons I am exploring dropdown libraries at the moment.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
