### ISSUE TITLE
multiple selections

### ISSUE THREAD

**Issue by yiorgos78** [selectize/selectize.js#266]
Hi. i have a html select box, which i selectized! i use multiple option, but i can't seem to get the new value that is selected. I want to capture it and use it later on.

I used the onchange event of the html selct box, but this.value command returns only the first selected option.

Could you give me a hand please?

**Comment by joallard** [comment]
Thanks for reporting this issue. I am closing it since this issue has been inactive for more than 2 years. If there is still a problem, please re-open.
