### ISSUE TITLE
Set selected values in initialization 

### ISSUE THREAD

**Issue by andriijas** [selectize/selectize.js#277]
Using the Email Contacts example here: http://brianreavis.github.io/selectize.js/#tabs

```
var REGEX_EMAIL = '([a-z0-9!#$%&\'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&\'*+/=?^_`{|}~-]+)*@' +
                  '(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)';

$('#select-to').selectize({
    persist: false,
    maxItems: null,
    valueField: 'email',
    labelField: 'name',
    searchField: ['name', 'email'],
    options: [
        {email: 'brian@thirdroute.com', name: 'Brian Reavis'},
        {email: 'nikola@tesla.com', name: 'Nikola Tesla'},
        {email: 'someone@gmail.com'}
    ],
    render: {
        item: function(item, escape) {
            return '<div>' +
                (item.name ? '<span class="name">' + escape(item.name) + '</span>' : '') +
                (item.email ? '<span class="email">' + escape(item.email) + '</span>' : '') +
            '</div>';
        },
        option: function(item, escape) {
            var label = item.name || item.email;
            var caption = item.name ? item.email : null;
            return '<div>' +
                '<span class="label">' + escape(label) + '</span>' +
                (caption ? '<span class="caption">' + escape(caption) + '</span>' : '') +
            '</div>';
        }
    },
    create: function(input) {
        if ((new RegExp('^' + REGEX_EMAIL + '$', 'i')).test(input)) {
            return {email: input};
        }
        var match = input.match(new RegExp('^([^<]*)\<' + REGEX_EMAIL + '\>$', 'i'));
        if (match) {
            return {
                email : match[2],
                name  : $.trim(match[1])
            };
        }
        alert('Invalid email address.');
        return false;
    }
});
```

Is there anyway way to pass in whats going to be the selected value? I can set it afterwards but that would trigger the onChange event which is not what I want.

**Comment by felonious** [comment]
Easy...

  $('#p_cliente_id').selectize({
    items: [5],   //------------>>> place between the id keys that you need to initialize the select.
    create: true,
    maxOptions: 10000
  });

**Comment by NotSqrt** [comment]
5ece5f5d86ab617f finally documented that, 15 days ago.

**Comment by sujeshkumaruv** [comment]
Any positive news. Stuck with the same problem. I have a multi select html . The options are shown first . Then I use ajax to change the options in html multi select  but the selectize does not update?
Any suggestions on how to update selectize?

**Comment by nlwillia** [comment]
@sujeshkumaruv What you're probably looking for (which isn't really on topic for this issue) is the [refreshOptions() API method](https://github.com/brianreavis/selectize.js/blob/master/docs/api.md).  `$('#id').data('selectize').refreshOptions()`

**Comment by czmole** [comment]
I can not make the items[] to work. I am trying like this http://laravel.io/bin/GyXQV
The id 11 is in the list that will be loaded, what am I doing wrong?
I am trying to populate the selectize input with some values when editing a record...
Thank you!

**Comment by richardenglish** [comment]
oh, it's working.  cool.

quick example (pre-select items one and three):

the items array:
var theselected = ['one','three'];  

the selectize:
var $select2 = $('#select-tools2').selectize({
 maxItems: 12,
 preload: true,
 items: theselected,
 openOnFocus: 'true',
 valueField: 'id',
 labelField: 'title',
 searchField: 'title',
 options: [ 
  {id: 'one', title: 'Section One'},
  {id: 'two', title: 'Section Two'},
  {id: 'three', title: 'Section Three'},

etc.

**Comment by 0xLuz** [comment]
Thanks @felonious !! That was the easiest solution I found! Using `setValue` and other stuff didn't work for me!
