### ISSUE TITLE
Implement min-items?

### ISSUE THREAD

**Issue by vemv** [selectize/selectize.js#280]
It'd be cool if there was a min-items option, analog to max-items

I reckon a common use case for it would be setting it to `1`, so no empty option is shown - one would _have_ to pick a value (or use the first one).

**Comment by kuus** [comment]
`required` does not work (it's not taken in consideration) in the `remove_button` plugin, I think that an `<input type="text" required>` should disallow removing tags when there is only one. Great plugin anyway.

**Comment by Pictor13** [comment]
Having the possibility to set a `min-items` (supporting more than just `1`) and a `max-items` setting would really improve the flexibility of this nice piece of JS :)

EDIT: ok, I just found the maxItems setting. :+1: 
Still miss a _minItems_ option. I'm working on it but am not sure how could I extend it and if I have to rely on the `self.isInvalid` flag, to keep everything consistent.
