### ISSUE TITLE
How to close dropdown after insert tag?

### ISSUE THREAD

**Issue by trawen** [selectize/selectize.js#284]
I insert the tag. When I press Enter, tag inserts in the field and have a full list of options. It is not very convenient because it requires a separate clique that would close the list. 

How can I close it automatically? 

I tried two ways: 
1. control.close () in create: - it does not work 
2. $ (". selectize-dropdown").hide() in change(function(){ - this works, but when you enter the following tag in the same field, the list does not appear. 

solve this problem?

**Comment by mkimont** [comment]
property = $('.your-class').selectize(); 
property[0].selectize.open(); property[0].selectize.close(); and so on from https://github.com/brianreavis/selectize.js/blob/master/docs/api.md

**Comment by derunva** [comment]
Hi, for me helps this
selectize.$dropdown.hide();

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
