### ISSUE TITLE
Create from ajax response

### ISSUE THREAD

**Issue by jfromell** [selectize/selectize.js#285]
Trying to create new options based on the response from an ajax call is failing for me. Is there a way to do this?

``` javascript
create: function(input) {
    var match = input.match(new RegExp('^([^<]*)\<(.*?)\>$', 'i'));
    var jqxhr = $.ajax({
        type: "POST",
        url: Routes.api_options_path(),
        data: {
            option: (match ? { presentation: match[1], name: match[2] } : { presentation: input })
        }
    });

    jqxhr.then(function (res) {
        return res;
    });
}
```

In other words, i'm adding a new option in the input, pressing enter, it fires an ajax call to create the option on the server and sends back the json for the created option which i want to use to add the option to selectize.

**Comment by nmocruz** [comment]
I think is better to reopen this bug **async: false** is deprecated since version 1.8

**Comment by Splendour-pomxml1** [comment]
> why @JonasFromell' solution doesn't work ?





https://jquerys.space/questions/managing-various-responses-within-an-ajax-success-callback
