### ISSUE TITLE
Inline CSS for div selectize-dropdown

### ISSUE THREAD

**Issue by tkrotoff** [selectize/selectize.js#289]
*\* With the default theme, `selectize-dropdown` div contains inline CSS:

``` HTML
<div class="selectize-dropdown ..." style="width: 520px; top: 36px; left: 0px; ...">
```
- top: 36px;
- width: 520px; => should probably be 100%
- left: 0px; => does not seem to be needed

*\* Similar issue with the bootstrap 3 theme but different values:

``` HTML
<div class="selectize-dropdown ..." style="width: 520px; top: 31px; left: 0px; ...">
```
- top: 31px; => a different value this time (otherwise it would look ugly)

*\* Would be nice to have these CSS rules inside the .css file instead of inline.

~~I could not determine where these inline CSS rules are coming from.~~
This is done inside [selectize.js, function positionDropdown](https://github.com/tkrotoff/selectize.js/blob/master/dist/js/selectize.js#L1960)

**Comment by michaelperrin** [comment]
I totally agree with you @redheadedstep , this would be a great option.
