### ISSUE TITLE
add multiple items at once in multiple mode

### ISSUE THREAD

**Issue by andriijas** [selectize/selectize.js#296]
if i have string 

`1,2,3,4`  in copy buffer and paste it into selectize box with create: true
is it possible to get option to create

items:
1
2
3
4

rather than "1,2,3,4" as one item?

**Comment by joallard** [comment]
Lucky you, I just fixed this today! Cheers @andriijas from the past!

**Comment by saif005** [comment]
@joallard Can we make input box multiline somehow?
like if i paste 
1
2
3
4
it should be pasted as it with line breaks instead of spaces in between the values?
