### ISSUE TITLE
Selectize & AngularJS not playing along with Select box (Multiple options)

### ISSUE THREAD

**Issue by danimt** [selectize/selectize.js#299]
I've been trying to implement Selectize with AngularJS (1.2.4). I'm using this directive (https://github.com/paolodm/angular-selectize) to interface with the plugin and everything is working smoothly until now. When using the ngModel from a normal select box It works fine, and returns the expected object but when I try to use it with the multiple attribute, it won't set the model.

I've inspected the DOM and appears the script removes unselected options from the hidden select and that might be messing with the angular binding.

I've created a Plunkr to demonstrate the behaviour.

http://plnkr.co/It6C2EPFHTMWOifoYEYA

Thanks

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
