### ISSUE TITLE
the onFocus method gets called twice for one focus event

### ISSUE THREAD

**Issue by ctaschereau** [selectize/selectize.js#301]
Hi,
I tried to use the preload = 'focus' feature, but it appears that the onFocus method gets called twice every time I give focus to my selectize control. This selectize control is bound to a server to obtain its data (not stored client-side) and, as such, does 2 calls to the server.

Also in the onFocus method, the line
if (self.settings.preload === 'focus') self.onSearchChange('');
would appear to reset the search value every time the control receives focus (and twice because of this bug), is this normal ?

**Comment by saeed-parsaee** [comment]
@brianreavis I have the same issue but i cant reproduce it but you can see the issue on beta version of this site:
1- go to [this url](http://bahook.com/shelf?cat=461)
2-hover the first filter to open box.
![image](https://cloud.githubusercontent.com/assets/3070844/21631705/d466f016-d253-11e6-8197-b0dce909d194.png)
3-check for console log.
by focusing in the first 3 filter you will notice that focus in each box will load data twice.
here are my selectize options:
       
        valueField: 'id',
        labelField: 'text',
        searchField: 'text',
        autoselect: 'first',
        closeAfterSelect: true,
        disableDelete: true,
        openOnFocus: true,
        preload: 'focus',
        addPrecedence : false,
        maxOptions: 25,
        loadThrottle: 1200,
        filter: false,
        clearCache: true,
        plugins: ['remove_button', 'preserve_on_blur' ],
