### ISSUE TITLE
Semantic UI theme request

### ISSUE THREAD

**Issue by iband** [selectize/selectize.js#311]
Looks like Semantic UI is becoming more popular. Personally I prefer it over bootstrap. So it would be really nice to see Semantic UI theme for Selectize.

**Comment by jimmybaker** [comment]
:+1:

**Comment by abernix** [comment]
:+1:

**Comment by parhelium** [comment]
:+1:

**Comment by dt1973** [comment]
I'd prefer we focus on Selectize itself rather than getting carried away by yet another UI framework. Personally, the more I use these UI frameworks, the more I wish I just made my own UI from scratch in the first place.

**Comment by proft** [comment]
+1

**Comment by joallard** [comment]
Unfortunately, that is out of scope for now. You're free to make a repo with such a theme. Though if you need the Selectize markup to be more semantic or provide some things in the API, the issues here are a good place to discuss/propose that. Cheers!

**Comment by joallard** [comment]
(You can also still use this thread to discuss organizing that, I'm just going to mark it "closed" as it's not something urgent)

**Comment by topjor** [comment]
I might give it a go to port the less version to semantic-ui, it might take some time but I definitely wanna give it a try as I would like to include this module in my own CMS (theme)
