### ISSUE TITLE
Remove text input by click

### ISSUE THREAD

**Issue by hrumhrumble** [selectize/selectize.js#313]
Hello!
How i can remove text in input field by click?
I try remove this text 
![remove](https://f.cloud.github.com/assets/1830224/2309699/641c82ba-a2d8-11e3-8b08-1b8becc504e5.jpg)

with jquery code

```
  $('.selectize-control').on 'click', ->
    $(this).find('.item').remove().siblings('input').css({
      'position': 'relative'
      'left': '0'
      })
```

, but nothing to achieve (

Help me please

**Comment by mppfiles** [comment]
...four years later, but better than never!

````javascript
$("#mySelect").selectize({
            onDropdownOpen: function($dropdown) {
                    this.$input.get(0).selectize.clear(true);
            }
});
