### ISSUE TITLE
Typing in the "input" of the selectized dropdown doesn't do anything

### ISSUE THREAD

**Issue by jadewelsh** [selectize/selectize.js#314]
I have a form that gets loaded in a modal pop up. When the form is in the popup, typing in the input doesn't do anything. The characters you are typing don't show up, the options don't change. It's almost as if you aren't typing at all. The selectize is still there and functioning and the key down and up events are firing, just nothing happens.

However if I load the page on its own (not in a modal popup) it works perfectly.

The form really needs to be in the modal window so  taking it out of that really isn't an option. Has anyone else had a similar issue?

My thought is that the script for the modal might be interfering with the script for the selectize but I've tried removing things and nothing changes. Also I feel like if the modal was interfering with the selectize script then it wouldn't load at all, not load but not function.

Thanks in advance. :)

**Comment by pnukeid** [comment]
i don't know it's true or not but i think you trying to sending data to the selectize  after selectize is loaded, it should be before selected loaded.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
