### ISSUE TITLE
optgroup_columns: Remove dead space

### ISSUE THREAD

**Issue by frankie-loves-jesus** [selectize/selectize.js#318]
Anybody know how to fix optgroup_columns so that there's no dead space between data groups?

http://jsfiddle.net/D3NAb/1/

![optgroup_columns](https://f.cloud.github.com/assets/4778127/2321673/964b0192-a3a7-11e3-87fc-ec422a145749.png)

**Comment by frankie-loves-jesus** [comment]
@marcel12bell did you manage to get anywhere with this?

@sjhewitt please reconsider releasing this - this plugin is just too cool to be left out like this.

cc @brianreavis

**Comment by marcel12bell** [comment]
@frankie-loves-jesus  No, I put all in one list...
