### ISSUE TITLE
Adding click event to items

### ISSUE THREAD

**Issue by djthread** [selectize/selectize.js#319]
I'm trying to add a click event to the rendered item units, but it seems some other click event -- from jquery? -- is taking precedence. I'm not sure I need the "selecting" functionality that it provides, so is there a way for me to let my click event take affect instead?

In my plnkr, select an element from the selectize dropdown. You will then get the blue box inside the input. My rendered <tag> directive, which I've successfully managed to get rendering properly, DOES appear in the input, but clicking on it does not trigger the ng-click="go()" which should cause an alert().

Any thoughts? Thanks, guys!!

http://plnkr.co/edit/MQqUdym0EU6nUoT5vaE5?p=preview

**Comment by Kitof** [comment]
Do you know why

``` javascript
    $(document).on('click', 'div.selectize-input div.item', function (e) {
               alert("test");
    });
```

works, and

``` javascript
    $('div.selectize-input div.item').on('click', function(e) {
                alert("test");
    });
```

doesn't ?

**Comment by mts88** [comment]
Probably because $(document).on(....) listens the entire DOM, also the elements added dinamically after the DOM is loaded, instead $(..).on(..) listens only the elements the are loaded with the DOM and ignores the elements created dinamically. 
The item in the select are created dinamically and added in the DOM after loading.

**Comment by m4r14n** [comment]
If you want to clear just one item from the selected items, but not from the select, you can use this:
    $(document).on('click', 'div.selectize-input div.item', function(e) {
        var select = $('#services').selectize();
        var selectSizeControl = select[0].selectize;
        // 1. Get the value
        var selectedValue = $(this).attr("data-value");
        // 2. Remove the option 
        select[0].selectize.removeItem(selectedValue);
        // 3. Refresh the select
        select[0].selectize.refreshItems();
        select[0].selectize.refreshOptions();

    });
