### ISSUE TITLE
Delimiter is ignored on input in Chrome Android

### ISSUE THREAD

**Issue by ghost** [selectize/selectize.js#321]
1. Go to http://brianreavis.github.io/selectize.js/
2. Type "test," into the Tags example
3. Notice that the delimiter was ignored and you're still working on the same tag

Happens on Android 4.4, Moto X, Chrome 33. Blink version 537.36, on various keyboards (felt it was worth checking).

Going to look into it further when I have a chance, but if you have any questions let me know.

Edit: https://code.google.com/p/chromium/issues/detail?id=118639 seems to be the root cause, which has been open for over two years. Chrome for Android doesn't fire onKeyPress events.

**Comment by joallard** [comment]
Is this the same thing as #113? Meaning, if #113 is fixed, does it automatically fix this one?

**Comment by ghost** [comment]
Maybe, but it looks like the related Chrome issue is marked WONTFIX, so I think the only solution is going to be a hacky one.

Looking into your investigation on #113  I'm not sure, though. The fact that you were seeing keydown/keyup events at all makes me wonder if they are linked, but I can still repro this unfortunately.

**Comment by joallard** [comment]
Ah, I get it. If we start detecting backspace piecemeal, doesn't mean we detect `$DELIMITER` too. _sigh_ Chrome

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
