### ISSUE TITLE
`tabindex` doesn't fit in the line

### ISSUE THREAD

**Issue by alibozorgkhan** [selectize/selectize.js#322]
Hi,

As you can see in the images, I have more than enough space in front of "ali@bz.com" but `input type="text" autocomplete="off" tabindex` goes to the next line and increases the height of my text field which is not neccesary. I don't have any styles applied to the field.

![1](https://f.cloud.github.com/assets/1771669/2362528/6163a23c-a63f-11e3-9f26-36d4503265c2.png)
![2](https://f.cloud.github.com/assets/1771669/2362529/6176332a-a63f-11e3-9134-6c3264eae8bb.png)

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
