### ISSUE TITLE
IE 9 when attempting to use to drag the scroll indicator selectize closes.

### ISSUE THREAD

**Issue by StephenDKing** [selectize/selectize.js#325]
Using the country example, when attempting to drag the scroll indicator further down to see additional selections, the entire selector closes.

![image](https://f.cloud.github.com/assets/3475465/2374458/4ca809b4-a860-11e3-83aa-da437a263e0f.png)

This seems to only be the case in IE 9

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
