### ISSUE TITLE
maxlength on search input

### ISSUE THREAD

**Issue by danjamin** [selectize/selectize.js#326]
In **v0.8.5**, there does not appear to be a way to set the **maxlength** attribute on the search field input.

The usage documentation does not have this option, and when setting it on the markup itself that selectize binds to, selectize ends up creating a nested input that does not have the **maxlength** attribute.

Any help would be much appreciated.  Thanks.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
