### ISSUE TITLE
Is there a way of hiding existing values on add?

### ISSUE THREAD

**Issue by landwire** [selectize/selectize.js#329]
Hi there,

when letting users add an item, the existing items with the same name show up for selection(see screenshot). Is there a way to only show the add option if the term in the searchbox is actually different to any terms in the loaded options list?
Thanks,
Sascha
![screen shot 2014-03-14 at 09 57 55](https://f.cloud.github.com/assets/1001202/2419139/9c07d058-ab57-11e3-9fb8-e7bd0953b279.png)

**Comment by Pictor13** [comment]
Current behaviour never removes the added *selected* class.

Code should be fixed to:
<pre>
// add "selected" class to selected options
if (!self.settings.hideSelected) {
	$dropdown_content.find('[data-selectable]').each(function() {
		var $option = $(this);
		var selected = self.items.indexOf($option.attr('data-value')) !== -1;
		$option.toggleClass('selected', selected);
	});
}
</pre>

I am gonna put it in my fork and do a pull-request when/if I'll have time.

**EDIT:** just noticed a (onliner) solution was proposed already in #1191 👍
