### ISSUE TITLE
Application event handler for keydown event

### ISSUE THREAD

**Issue by t-nelis** [selectize/selectize.js#334]
Hello,

We'd like to handle the `keydown` event in our application; the use-case is a field navigation system that focuses controls in a certain order.

AFAICT Selectize doesn't expose an API to register handlers for such an event (the [Events](https://github.com/brianreavis/selectize.js/blob/master/docs/events.md) document doesn't list it).

However, after reviewing code here and there (unit tests, plugins, internal code) and analyzing the runtime state of the `selectize` property on the HTML element, I can see some references to properties such as `$input`, `$control`, `$control_input`, `$dropdown`, `$dropdown_content`, `$wrapper` or `$select`. Deducing that these are references to the various jQuery objects that themselves represent the various HTML elements that the Selectize control is composed of, I imagine one of them ought to fit the bill.

Thus, my questions are:
1. Can an application, through the `selectize` property on the extended ("selectized") selector, access these references?
2. If so, are they part of the public contract for applications? (In other words, is their use by applications supported?)
   
   If not, what about the plugin API contract?
3. Considering we want to handle the event to trigger another `focus` event elsewhere (filtering TAB key presses), can we make sure that the currently selected option will actually be selected, or that the dropdown (or whatever else) will be closed/validated first (without us seeing the event) before a second keypress can be handled?
4. In your opinion, which of the mentioned properties would be most appropriate for the use-case we presented?
5. Would you be open to the idea of exposing the event directly through the `selectize` property API, alongside all other events currently defined [here](https://github.com/brianreavis/selectize.js/blob/master/docs/events.md)? I understand the semantics can't easily be generalized ("should the event be fired every time or only when the dropdown is closed?"), but I'm confident a satisfactory solution can be found.

Thank you for your time.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
