### ISSUE TITLE
How to add autocomplete on TAB if I have 1 filtered result or save entered value after press TAB

### ISSUE THREAD

**Issue by pacahon** [selectize/selectize.js#335]
Hello. Thanks for great plugin. I have a questions:
1) I have data [{value:test1}, {value:test2}]
If I type "test2" in input field by hand and press TAB, I loose my value. How can I prevent it? I don't want do mouse click to save entered value.
2) Can I add autocomplete on press TAB or save keydown behavior if I have only 1 filtered result?

**Comment by dandv** [comment]
:+1: Pressing Tab should select into the input box the currently selected value in the dropdown. This is how many systems handle pressing Tab: tag entry in Vanilla Forums, Pinboard.in, [Bootstrap typeahead](http://twitter.github.io/typeahead.js/). Select2 has an open feature request for the [same behavior](https://github.com/select2/select2/issues/2637#issuecomment-53412047).

**Comment by nickgoodliff** [comment]
This exists in settings: selectOnTab

`.selectize({selectOnTab: true})`

**Comment by joallard** [comment]
Thanks @nickgoodliff
