### ISSUE TITLE
bootstrap 3 input-sm box height

### ISSUE THREAD

**Issue by mparthoens** [selectize/selectize.js#336]
with this code:

<div class="col-xs-12 col-md-4">
    <div class="form-group">
        <select id="selectizeCountry"
                class="form-control input-sm"
                data-bind="options: countries,
                           optionsText: 'name',
                           optionsValue: 'code',
                           value: country"></select>
    </div>
</div>

selectize select box has not the same height that regular bootstrap 3 input-sm box.

solved by overwriting selectize css like this:

.selectize-dropdown, .selectize-input, .selectize-input input {
    font-size: 12px;
    line-height: 16px;
}

.selectize-input {
    min-height: 20px;
}

.form-control.selectize-control {
    height: 30px;
}

What is your opinion?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
