### ISSUE TITLE
why valueField and labelField must be same?

### ISSUE THREAD

**Issue by zhangalex** [selectize/selectize.js#346]
If labelField and valueField have different value the selectizeJS will not works well. For example,
<select id="address"></select>

$('#address').selectize({
            persist: false,
            create: false,
            valueField: "item_index",
            labelField: "formatted_address",
            searchField: ["formatted_address"],
            preload: false,
            maxItems: null,
            load: function(query, callback) {
              var _this = this;
              if (!query.length) {
                return callback();
              }
              geocoder = new google.maps.Geocoder();
              return geocoder.geocode({
                address: query
              }, function(results, status) {
                var item, j, _i, _len;
                address_results = [];
                if (status === google.maps.GeocoderStatus.OK) {
                  j = 0;
                  for (_i = 0, _len = results.length; _i < _len; _i++) {
                    item = results[_i];
                    address_results.push({
                      item_index: j + "",
                      formatted_address: item.formatted_address
                    });
                    j = j + 1;
                  }
                  return callback(address_results);
                } else {
                  return console.log("Geocode was not successful for the following reason: " + status);
                }
              });
            }
          });

**Comment by joallard** [comment]
Thanks for reporting this issue. I am closing it since the issue has been inactive for more than 2 years. If there is still a problem with the latest version, please re-open. If you haven't done so, read the [Issue reporting guide](https://github.com/selectize/selectize.js/wiki/Reporting-issues-guide) and make sure your original post follows the guide.
