### ISSUE TITLE
When duplicates are allowed in items, deleting / backspace last item deletes the first one of that item in the list

### ISSUE THREAD

**Issue by artiaggarwal** [selectize/selectize.js#347]
if items in selectize are (test1, test,2, test3, test1) ,  deleting the last item using backspace deletes the first one of that item. result is   (test2, test3, test1)  instead of expected result (test1, test2, test3)  .    the sequence of items  is important as I'm using it to display a rule ... has anyone else seen this behavior ?   please help.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
