### ISSUE TITLE
Strange behavior when reloading a Page label is overwritten by value

### ISSUE THREAD

**Issue by tormedo** [selectize/selectize.js#348]
i have a _selectize.js_ input field:

``` html
<input id="modalinput-old-trainer" type="text" class="form-control" >
```

``` javascript
window.trainer = $('#modalinput-old-trainer').selectize({
    plugins : [ 'remove_button' ],
    valueField : 'id',
    labelField : 'username',
    searchField : [ 'username' ]
});
```

I load the Options via:

``` javascript
window.trainer[0].selectize.clear();
window.trainer[0].selectize.clearOptions();
window.trainer[0].selectize.load(function(callback) {
    $.ajax({
        type : "POST",
        url : "/ajax/admin/gettrainers",
        success : function(data) {
            callback(data.aviableTrainers);
        }
   });
});
```

Then i have a modal, where the selectize.js input is located. By opening the Modal Items are loaded:

``` javascript
$.each(response.trainers, function(index, trainer) {
    window.trainer[0].selectize.addItem(trainer.id);
});
```

This works fine. But if i reload the Page, the Items in the input field are no longer Labeled correctly. Instead the label is replaced by the id means the valueField. But if i delete the Items and then reload, they are back normal.

Any Idea what am i doing wrong.

**Comment by brianreavis** [comment]
Give the input an explicit `value=""` so that it's not autofilled by the browser. Once 0.12 is release, add a `data-data` attribute that has the raw option data you want selected (if that's what you want)
