### ISSUE TITLE
SelectizeJS accessibility (ARIA)

### ISSUE THREAD

**Issue by zirafa** [selectize/selectize.js#349]
Great plugin, just curious if selectize.js is accessible or there are plans to make it so?

There is interest on Drupal.org in adding a library such as yours (Select2, Chosen, TypeaheadJS etc) to core but it seems like none of the existing libraries are accessible. 

Here's the link to the relevant thread on drupal.org regarding adoption:
https://drupal.org/node/1271622

**Comment by SalmenBejaoui** [comment]
I created a plugin to make selectize.js accessibile as Combobox.
https://github.com/SLMNBJ/selectize-plugin-a11y

**Comment by xinspire** [comment]
Hi @SLMNBJ, thank you so much for making a plugin available!  I tested it out and it works well with VoiceOver for the most part.  I am running into a small issue, but I'll post an issue in that repo instead of here.  Thanks again!

**Comment by SalmenBejaoui** [comment]
@xinspire will be appreciated ;)
