### ISSUE TITLE
Using TAB to select an option causes selectize control to lose focus

### ISSUE THREAD

**Issue by cordmata** [selectize/selectize.js#350]
Regarding issue #258, TAB does select the first option in the list, however, it also causes the control to lose focus. This is undesirable especially in the case where creating values is permitted (e.g. the tagging demo on the github.io site). I'm not sure if TAB should act like ENTER in that scenario as tabbing to the next selectable item on the page is desirable when not using TAB to select an option. Thoughts?

**Comment by willjohnson** [comment]
@tclark333 What did you do to fix this?

**Comment by tclark333** [comment]
Sorry, I don't think I ever found a fix for that issue.
