### ISSUE TITLE
Data Attributes in Selectize Options

### ISSUE THREAD

**Issue by geordee** [selectize/selectize.js#353]
I am using Selectize following the State City example. Is it possible to store some additional data from the Ajax request along with every option in City select?

Say, if I want to store the population along with each option, in one of the following ways...

```
<option value="Milwaukee" data-population="598916" selected="selected"></option>

<div data-value="Milwaukee" data-selectable="" data-population="598916" class="option selected">Milwaukee</div>
```

I'd be able to use the option-specific data later without going back to the server.

**Comment by pitashi** [comment]
@artiaggarwal i'm kinda a novice, so sorry for the ask, but I can't seem to figure out how to implement your solution to this issue. I'm basically trying to do the exact same thing @geordee is trying to do by adding data-name="XXX" to the <option> tag, then trying to grab that value on change to insert into another text field.

I'm not totally clear on how the "render" concept works -- sounds like it's re-rendering the <div> that is created in place of the <option> values with the new data elements in there, but I can't figure out how to get it to work. Is there no way of doing it just by adding to the <select> html then somehow telling selectize to include it when rendering the <div>? Any help and further clarification would be appreciated.

**Comment by geordee** [comment]
If I understand correctly by providing render settings, we are overriding default render templates.

See https://github.com/brianreavis/selectize.js/blob/master/src/selectize.js#L298

Also have another look at the code of "Remote Source — Rotten Tomatoes" example in http://brianreavis.github.io/selectize.js/

**Comment by OIlnytskiy** [comment]
@artiaggarwal is it possible to get than data-iso values from all the selected items ?

for example in my case 
![2017-02-18_14h47_05](https://cloud.githubusercontent.com/assets/7911319/23093363/5edbffbc-f5e9-11e6-8106-8d0a84288845.png)
I have multiselect and it successfully render and keep custom attr data-type. 
But how can I access that attribute?

I can gen only selected values
$('#multiple option:selected').each(function(){
       console.log($(this).val());
});
