### ISSUE TITLE
Avoid dropdown opening on deletion

### ISSUE THREAD

**Issue by gwacker** [selectize/selectize.js#356]
Is there a simple way to avoid the select drop-down opening immediately after deleting an item?

Specifically when using the "remove_button" plugin (clicking the x), but also when using backspace. It just seems like an odd behavior.

A config option to suppress this behavior would be nice.

**Comment by elikrief** [comment]
+1

**Comment by mlensment** [comment]
Looks like a duplicate of #249

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
