### ISSUE TITLE
Remote data from the first search are still there after a second search

### ISSUE THREAD

**Issue by Nelrohd** [selectize/selectize.js#357]
How to reproduce:
1. Use the load function and fetch any data from anywhere.
2. Do a search
3. Do a second search. 

Your items from the first search will be still there.

Is it normal? I know about the "persist" option but it is only useful for tags created by user.

Thank you.

**Comment by adarshk7** [comment]
Calling `clearOptions` and the `close` seemed to be a workaround. (`close` because it persists options as long as the dropdown doesn't lose focus). But it would be nice to have a fix for this.

**Comment by voronind** [comment]
How to clear options and keep selected items?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
