### ISSUE TITLE
Select an item with the API without firing the onChange event.

### ISSUE THREAD

**Issue by refringe** [selectize/selectize.js#363]
I'd like a way to dynamically change the value of a selectize element using the API, but not have the onChange event fire.

**Use case:**
I have two selectize elements sharing the same onChange function that update eachother's selected values based on the value the initial selectize element was changed to.

For example, one selectize element holds English country names, and the other holds French country names.
- The user changes the English selectize element value to "Antigua and Barbuda".
- The onChange even fires and changes the French selectize element value to "Antigua et Barbuda" using the API.
- The user can also change the French and expect the English to update automatically.

**Problem:**
When the initial onChange event uses the API (namely, the addItem method), the API fires the onChange event _again_.

**Possible Solution:**
It would be fantastic if we could suppress the onChange event when changing item values through the API. Perhaps by tacking on a method parameter like so:

```
addItem(value, false);
```

Where `false` would suppress the onChange event (default is `true`).

Thoughts? Did I miss a way to do this that's already implemented?

**Comment by brianreavis** [comment]
The next version (v0.12.0, going to be released in the next day or two) has a "silent" argument on: `setValue`,`addItem`,`removeItem`,`clear`.
