### ISSUE TITLE
box-sizing

### ISSUE THREAD

**Issue by marcandre** [selectize/selectize.js#368]
Why do you specify box-sizing in your CSS?

This lib works fine with either box-sizing, there really shouldn't be any default.

Moreover, Bootstrap-3 is already in box-sizing, so that rule is redundant

**Comment by brianreavis** [comment]
While it doesn't make a difference in the out-of-the-box setup, it's there for the cases when people add padding to the dropdown or input (common) and then break the relationship in width between the two. I guess it comes down to the simple reason: prevent an influx of github issues from CSS-unsavvy users
