### ISSUE TITLE
Prevent duplicate tags (some tags already loaded)

### ISSUE THREAD

**Issue by alubeck** [selectize/selectize.js#369]
I used selectize to realize a dropdown list with tags. Additional I use the plugins 'restore_on_backspace' and 'remove_button'. Also I read about the conversation to allow double values, but my case now is:

I have some tags already in my list (right at site load). Now I type in a tag which was already in the input field... AND, i can add it !??? 

Selectize doesnt compare tags which are already in the input ?
Is this a bug? 
How can i prevent this?

Thanks for any help

![what](https://cloud.githubusercontent.com/assets/6048707/2658500/400221fc-c009-11e3-841a-dd301fce94dd.png)

**Comment by brianreavis** [comment]
Closing as inactive.
