### ISSUE TITLE
I think Selectize behavior is not user-friendly ...

### ISSUE THREAD

**Issue by mehrdd** [selectize/selectize.js#379]
Hello,
Like i said; I think Selectize behavior isn't user-friendly.
when we click on a dropdown, it will open all options and highlight the selected one.
in this place, if we want to select another option by keyboard-typing, we 'have to' remove the input field first (by backspace key) and then try to type our desired option.

Isn't there any way to normally click on the select-box and type our destination ? (like a normal <select>)

thank you.

**Comment by qpajrathod09** [comment]
**Change this in selectize.js**

return;
case KEY_BACKSPACE:
case KEY_DELETE:
self.deleteSelection(e);
return;

**to this**

return;
default:
self.deleteSelection(e);
return;

--------------------------------------------------------

this will clear the input field on any key press, try it.
