### ISSUE TITLE
re-ordering my options

### ISSUE THREAD

**Issue by designermonkey** [selectize/selectize.js#381]
Selectize is reordering my provided options, which is undesirable behaviour.

I am providing:

``` html
<select name="fields[places]" placeholder="How many places do you require?" id="places" class=" places">
    <option value=""></option>
    <option value="all">All</option>
    <option value="1">1</option>
    <option value="2">2</option>
</select>
```

The output is ordering by number then alpha, so `1, 2, all`.

**Comment by brianreavis** [comment]
What's your configuration look like?

**Comment by brianreavis** [comment]
Does this not work in your browser?
http://jsfiddle.net/97gvoywx/
