### ISSUE TITLE
Hide search input on specific select

### ISSUE THREAD

**Issue by hmaesta** [selectize/selectize.js#382]
Hello.

Is there a way of hide the search input on specific select?

Some selects in my website are just too short to have a search input, so I want it hidden – [like this one in Chosen plugin](http://harvesthq.github.io/chosen/#hide-search-on-single-select).

Thank you.

**Comment by djchar89** [comment]
You can disable pointer for the "selectize-control" div.

example:
$('.selectize-control').css('pointer-events', 'none');

But this will occur whole selectize select boxes

**Comment by neilmonroe** [comment]
Is it not just as simple as:
1. Add a CSS class of <code>no-search</code> to your HTML select.
2. Add the following rule to your stylesheet.  
   <code>.selectize-control.no-search input { display: none !important; }</code>

You may need to adjust it to fit your situation, but this seemed to work in the code I am working on.

**Comment by adamsoffer** [comment]
+1 to turn it into a built-in feature

**Comment by billybonks** [comment]
+1 but apparently its not part of the scope -.-

**Comment by JustasKuizinas** [comment]
+1 for built-in feature

**Comment by oceangravity** [comment]
+1 for built-in feature

**Comment by joallard** [comment]
Dupe #110

**Comment by eduardo-mior** [comment]
With a little bit of CSS and a little bit of JS we can create this. And it looks perfect.

```javascript
var select = $("#my-select-input");
$(select).next().find("div.selectize-input").addClass("no-searchable"); // Adding style to the div
$(select).next().find("div.selectize-input > input").addClass("no-searchable"); // Adding style to the input
$(select).next().find("div.selectize-input > input").prop("readonly", true); // Setting the input to read-only
$(select).next().find("div.selectize-input > input").prop("inputmode", "none"); // Ensuring that the keyboard will not open on mobile
$(select).next().find("div.selectize-input > input").focus(function () { // Hack for when the search input gets the focus it will automatically blur.
    $(this).blur();
});
```
```css
.no-searchable {
    cursor: pointer !important;
    background-color: #FFFFFF !important;
}
.has-items input.no-searchable {
    width: 1px !important;
}
```
