### ISSUE TITLE
Use standard events on original select element

### ISSUE THREAD

**Issue by t-nelis** [selectize/selectize.js#389]
Related to #102, but for all standard events targeting 'selectized' `<select>` elements.

[List of DOM3 Event Types](http://www.w3.org/TR/DOM-Level-3-Events/#event-types-list) (W3C DOM Level 3)
[Standard Events](https://developer.mozilla.org/en-US/docs/Web/Reference/Events#Standard_events) (MDN Web Technology Reference)

Because selectize sets the `display` style property to `none` to hide the element, the user agent will not trigger certain events on it (e.g. `focus`). As far as I understand, this is the main blocking issue for selectize; even workarounds involving rerouting between standard events and [custom selectize events](https://github.com/brianreavis/selectize.js/blob/master/docs/events.md) do not work because of this.

For my sake, implementing this functionality closes #334, though more explicit (custom) events may still be provided for this case in particular.

You might be interested in [issue 1908 of the Select2 project](https://github.com/ivaynberg/select2/issues/1908), which I filed before our project switched to selectize for unrelated reasons. They're apparently considering to add this functionality and referencing all their related bugs there, though no plan is available yet.

Note that because they don't use `display:none` to hide the `<select>` element, a work-around is possible, though it's incredibly ugly. The same work-around for selectize would be considerably more straightforward, as all sub-components of the control seem to be readily accessible from the `selectize` property on the element. selectize would just need to use another mechanism than `display:none` to hide the element, which is most likely necessary anyway in order to provide built-in functionality for standard events.

**Comment by maplesap** [comment]
Is there a current workaround for listening for keydown events on the input field?

**Comment by piotrpawlik** [comment]
Bumping question.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
