### ISSUE TITLE
Unable to query original select

### ISSUE THREAD

**Issue by marcioaguiar** [selectize/selectize.js#39]
When you select an option with selectize it changes the original select component adding an option with the selected value

``` javascript
for (i = 0, n = this.items.length; i < n; i++) {
                options.push('<option value="' + htmlEntities(this.items[i]) + '" selected="selected"></option>');
            }
```

I think the option component should reflect exactly how the original option was (including the label) so the user can query the select component and get the label and wherever data he wants from it.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
