### ISSUE TITLE
Dropdown Keyboard Navigation: Home / End / Pg-Up / Pg-Down Keys

### ISSUE THREAD

**Issue by nlwillia** [selectize/selectize.js#391]
A normal select control supports Home/End and Page Up/Down to respectively navigate to the beginning/end and page-wise through the list.  While Home/End might be tricky since they also have meaning in the context of the focused text box, Page Up/Down would be useful in longer lists.  The find-as-you-type behavior is often adequate, but sometimes the user will prefer to browse instead.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
