### ISSUE TITLE
Bug: Tab focus behavior in Firefox

### ISSUE THREAD

**Issue by nlwillia** [selectize/selectize.js#396]
When a selectized select control is used in a form, the tab behavior is important.  Currently in Firefox, if the option list is long enough to need to scroll, then tabbing out of the selectize input box does not focus the next control.  The document.activeElement indicates that the body element is active.  Tabbing a second time will either focus the next control or refocus the selectize input box depending on whether there is a selection.  This is inconsistent with other browsers and awkward for keyboard navigation.

Demo: http://jsbin.com/xitom/1/
Affects version: 0.9.1
Broken in: Firefox 28, 29
Works in: Chrome, IE
Workaround: Use explicit tabIndex

**Comment by andreatevoi** [comment]
Hi,
I'd like to add that there is a bigger problem with this in IE10 and IE11. If you try that demo (http://jsbin.com/xitom/1/) in IE it is impossible to focus the third input using tab key. This issue makes the form unusable with tab key.

Regards,
Andrea

**Comment by tranquyetdev** [comment]
Same issue happen in firefox 49.0.1.

**Comment by ryangriggs** [comment]
I can confirm that this is still an issue in Firefox 50 (Windows 10 x64).

**Comment by sietzekeuning** [comment]
I can also confirm this bug on Firefox 50.0.2 on MacOs

**Comment by mmartini-del** [comment]
Same issue in Firefox 51.0.1 on Ubuntu

**Comment by thinkflo** [comment]
Super hacky, but if you set the focus on the next Text Input on blur, then it lets you focus to the next Selectize.  This jQuery call is a bit hacky but it works for now until it's properly fixed:

$('select').selectize({
	onBlur: function() {			
		$('input').eq(parseInt($('input').index($(this.$input[0].nextSibling).find('input')))+1).focus(); 
		}
});

**Comment by AndyThayer** [comment]
Same issue in Firefox 61.0.1 (64-bit).

**Comment by daerogami** [comment]
Still an issue in Firefox 65.0 (64-bit)

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
