### ISSUE TITLE
Windows touch devices closes the drop down on touch scroll

### ISSUE THREAD

**Issue by sreeyashu** [selectize/selectize.js#398]
I have been facing this issue on surface RT/Windows phone as well as it doesn't allow touch scroll. I thought it is more or less same as drag button issue in IE but I see this is a new issue which is very blocking on Windows phone devices and tabs as well. 

I check this when I try to scroll it calls blur function.

**Comment by mauromaniforti** [comment]
Any news about this?
I still have the problem...

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
