### ISSUE TITLE
font-size in selectize.bootstrap3.css

### ISSUE THREAD

**Issue by RomeroMsk** [selectize/selectize.js#400]
Hello.
I think this line must be removed to inherit .form-control font-size: https://github.com/brianreavis/selectize.js/blob/master/dist/css/selectize.bootstrap3.css#L119
If I have .form-control with .input-sm, font-size of items must be 12px.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
