### ISSUE TITLE
Shadows in selectize-input

### ISSUE THREAD

**Issue by RomeroMsk** [selectize/selectize.js#401]
In Bootstrap3 selectize-input there are no shadows, but BS3 text inputs have them:
![image](https://cloud.githubusercontent.com/assets/4639951/2912342/da35adce-d676-11e3-9f77-a04cd951ef8c.png)
Please, add shadows to selectize.bootstrap3.css

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
