### ISSUE TITLE
Persist option does not correctly clear created items when another item is selected

### ISSUE THREAD

**Issue by jamesrom** [selectize/selectize.js#403]
The persist option does not work as described in the [usage documentation](https://github.com/brianreavis/selectize.js/blob/master/docs/usage.md).

> If false, items created by the user will not show up as available options once they are unselected.

To reproduce using the code below:
1. Type `foo` and hit return to add it.
2. Select another item (don't to clear your selection first), notice that the created item has been unselected but is still in the list.
3. Clear your selection, notice that the created item still persists.
4. Type `bar` and hit return to add it.
5. Go to 2.

```
<form>
    <select id="select" placeholder="Select a person...">
        <option value="">Select a person...</option>
        <option value="1">Thomas Edison</option>
        <option value="2">Nikola Tesla</option>
        <option value="3">Arnold Schwarzenegger</option>
    </select>
</form>
<script>
    $(function() {
        $('select').selectize({
            create: true,
            persist: false
        });
    });
</script>
```

**Comment by hankbeasley** [comment]
+1 Anyone going to fix it?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
