### ISSUE TITLE
Preload and select any option requires backspace key to be pressed

### ISSUE THREAD

**Issue by efreibe** [selectize/selectize.js#404]
When I preload and select any option my users gets confused about how to select any new entry, that is because they need to press delete or backspace to erase the current selection.

This is great if you have multiple items, but it doesn't feel very intuitive in a normal select.

The only thing I want to accomplish is that when the popup is shown the user doesn't need to press backspace to start writing.

I've searched the code but couldn't find and easy way to change this behavior.

**Comment by RentecTravis** [comment]
This helped me get started but ultimately I did something quite different. It required using `onFocus`, `onType`, `score`, a custom plugin, and custom styling. The end result is a selectize input where when you focus it, the text is selected, the keyboard can be used as usual, and all options are shown (instead of just the option that matches the current text) until you start typing.

[Codepen example](https://codepen.io/tvanc/pen/ExPjxew)

```js
Selectize.define("anykey", function () {
    const original = this.onKeyDown

    const KEY_A = 65;
    const KEY_RETURN = 13;
    const KEY_ESC = 27;
    const KEY_LEFT = 37;
    const KEY_UP = 38;
    const KEY_P = 80;
    const KEY_RIGHT = 39;
    const KEY_DOWN = 40;
    const KEY_N = 78;
    const KEY_BACKSPACE = 8;
    const KEY_DELETE = 46;
    const KEY_TAB = 9;

    this.onKeyDown = (e) => {
      switch (e.keyCode) {
        case KEY_A:
        case KEY_ESC:
        case KEY_N:
        case KEY_DOWN:
        case KEY_P:
        case KEY_UP:
        case KEY_RETURN:
        case KEY_LEFT:
        case KEY_RIGHT:
        case KEY_TAB:
        case KEY_BACKSPACE:
        case KEY_DELETE:
          original.call(this, e)
      }
    }
});

jQuery("#select").selectize({
  plugins: ["anykey"],
  onFocus() {
    const value = this.getValue();
    const option = this.options[value];
    this.justOpened = true;

    if (option) {
      this.$control_input.val(option.text.trim()).select();
    }
  },

  onType() {
    this.justOpened = false;
  },

  score(search) {
    return this.justOpened ? () => 1 : this.getScoreFunction(search);
  }
});
```

```css
.selectize-input,
.selectize-control.single > .selectize-input.input-active {
  display: flex;
}
.selectize-input.input-active > .item {
  display: none;
}
.selectize-input > input {
  flex-grow: 1;
}
```
