### ISSUE TITLE
Suggestions aren't selecting properly

### ISSUE THREAD

**Issue by jbrooksuk** [selectize/selectize.js#407]
I have a select dropdown full of airports. The `searchField` is the Airport name and the IATA code.

![screen shot 2014-05-13 at 12 49 57](https://cloud.githubusercontent.com/assets/246103/2956714/d50ead56-da94-11e3-9056-69fb53b6747f.png)

If I type `MAN` into the suggestions, then you'd expect it to pick **Manchester Airport / MAN**, but it doesn't. Instead it will select **Man Airport / MJC**.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
