### ISSUE TITLE
Virtual keyboard is still activated on iOS device after "onItemAdd"

### ISSUE THREAD

**Issue by consolelog** [selectize/selectize.js#41]
I compose the item list by using a remote source. However, after I select an item, the virtual keyboard is still on.

I looked at the official demos and I found it not even activate the keyboard at all when the input is focused. 

Tested on iPad mini and iPhone 4s, both iOS 6+.

Hope I did not do something wrong.

**Comment by joallard** [comment]
Thanks for reporting this issue. I am closing this since we have a lot of issues and this issue has been inactive for more than 2 years. If there is still a problem, please re-open.
