### ISSUE TITLE
I want to preselect the selectize with some values in case of editing my form which I submitted earlier. How can I achieve this

### ISSUE THREAD

**Issue by ravis2014** [selectize/selectize.js#411]
$('#textBoxBrowseUsers').selectize({
                        maxItems: null,
                        preload:true,
                        plugins: ['remove_button'],
                        delimiter: ',',
                        valueField: 'UserId',
                        labelField: 'FullName',
                        searchField: 'FullName',
                        options: result,
                        create: false,
                        //addOption: function (data) {
                        //    alert(data);
                        //    debugger;
                        //    console.log(data);

```
                    //},
                    render: {
                        item: function (item, escape) {
                            return '<div>' +
                                (item.FullName ? '<span class="name">' + escape(item.FullName) + '</span>' : '') +
                            '</div>';
                        },
                        option: function (item, escape) {
                            return '<div>' +
                                '<span class="label">' + escape(item.FullName) + '</span>' +
                            '</div>';
                        }

                    },
                    create: function (input) {
                        var match = true;
                        if (match) {
                            return {
                                FullName: match[2],
                                UserId: $.trim(match[1])
                            };
                        }
                        alert('Invalid.');
                        return false;
                    });
```

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
