### ISSUE TITLE
Please add disabled attribute for options

### ISSUE THREAD

**Issue by kosir** [selectize/selectize.js#416]
Hi, I found this project better than select2 in many ways, but one thing is missing: _disabled attribute for options_. It is very convenient to use this attribute, so if option is disabled, it can not be selected (option is grayed out), or if it is selected, it can not be de-selected.
That way I can programatically set default selected options, which can not be de-selected or prevent selecting some options, which is essential for my project.
Please!

Best regards,
Milan

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
