### ISSUE TITLE
Selectize, Node.js environments and Common.js module pattern

### ISSUE THREAD

**Issue by franleplant** [selectize/selectize.js#417]
Hey!

Im using Selectize with Node.js and making it playing along with `browserify-shim`med dependencies such as `jquery` was not easy and required extra effort.

Notes:
## jQuery and Browserify-shim

I have experienced that when trying to use a Shimmed jquery version with Selectize you get `"jquery" module not find`. After digging a lot I found documentation and diagnosis [here](https://github.com/thlorenz/browserify-shim/issues/30) and [here](https://github.com/thlorenz/browserify-ember#fix). 

**Description:** `"jquery"` is being looked up in `node_modules`, but since its shimmed it should be looking in other directory.

**Why?** As the links quoted before say, the problem is that you are including `package.json` in your bower files, and that is causing `Browserify` to never get to the right parent `package.json` that contains the **Browserify-shim** shims.

**Solution:** Ignore your `package.json` ìn your `bower.json` file. 
## Using it with node

`dist/standalone/selectize.js` does not work in Node.js because it calls several times `module.exports` in the same file, overriding the exports value. When trying to use it you will get `"sifter" module not find` and/or `"microplugin module not find"`

**Solution:** Use `dist/selectize.js` and use `Sifter` and `Microplugin` externally (they will be installed automatically when installing Selectize through bower).

**How:**  Add this to your `package.json` in your `browser` attribute:

``` json
    //....
    "browser": {
        "selectize": "./vendor/bower/selectize/dist/js/selectize.js",
        "sifter": "./vendor/bower/sifter/sifter.js",
        "microplugin": "./vendor/bower/microplugin/src/microplugin.js"
    },
    //...
```

The additional "selectize" alias is sugar syntax so you can `require('selectize')`.

In this way you will get Selectize working with Node.js.
## Changes that should be introduced to Selectize

The real deal will be to get Selectize to :
- Ignore your `package.json` ìn it's `bower.json` file. 

and to (choose one):
- Document about the issues with Node.js (Something very similar to what I've just did).
- Create a proper standalone distribution file that avoids doing `module.exports` several time. This mainly includes changing your build process.

Thanks!

Fran

**Comment by YPCrumble** [comment]
@franleplant this pull request solves the first but seems not to fix the second part of your issue, correct?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
