### ISSUE TITLE
still not working with requirejs

### ISSUE THREAD

**Issue by ttback** [selectize/selectize.js#424]
I have spent the morning trying to use selectize in my current code. When I use the standalone version, the selectize() function is not found. When I use the non-standalone version, I get following error:
originalError:
   { [Error: ENOENT, no such file or directory src/sifter.js']
     errno: 34,
     code: 'ENOENT',
     path: 'src/sifter.js',
     syscall: 'open',
     fileName: 'src/sifter.js',
     moduleTree: [ 'js/libs/selectize', 'js/bundle/main' ] } }

i had sifter.js at js/libs/sifter.js, same place as selectize.js, is there a reason why this happens?

**Comment by ahmadassaf** [comment]
@ttback how was it resolved ? can you elaborate please
