### ISSUE TITLE
Re initialize with all options in the select

### ISSUE THREAD

**Issue by andriijas** [selectize/selectize.js#431]
When a select is updated with new options, how can i re initialize the selectize instance to have the selectize updated with all the new options in the select? refreshOptions  doesnt seem to do it and destroying the selectize and instansiating it again seems to remove all options.

Thanks

**Comment by mcavalletto** [comment]
It sounds like @andriijas was asking for the ability to reload the state of the select element from which it was originally initialized in order to pick up new or changed options. That feature is also discussed in issue #991.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
