### ISSUE TITLE
Decouple click event 

### ISSUE THREAD

**Issue by sreeyashu** [selectize/selectize.js#436]
Is there any option that we can decouple the Input box and drop-down, the reason why I am asking, On mobile devices specially on iPhone lets say the drop-down and the keyboard opens at the same time in that case keyboard will overlap on the drop-down and due to the less space we cant see the options properly. 

I hope this can be optimized by decoupling the click events and perform the auto filter on  input focus along with keyboard and just opening drop-down when clicked on arrow portion without keyboard.
![screen shot 2014-05-23 at 6 02 16 pm](https://cloud.githubusercontent.com/assets/4896372/3068877/aee1a8f2-e293-11e3-8ccd-9cff2c1cf10e.png)

I would like to see this optimized feature on Selectize.

**Comment by dkoo761** [comment]
+1

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
