### ISSUE TITLE
Trying to clear options when the input changes

### ISSUE THREAD

**Issue by ttback** [selectize/selectize.js#448]
I need to have multiple tags added to an input field, such as "war", "battle" etc.
And each may have different autocomplete options returned back from server. 
Currently I execute `this.clearOptions();` on every load() call, but this causes the input field to be cleared when i add battle after typing war.  It looks like it is caused by the fact that the new word "battle" wasn't in the options available for "war", and it triggered a load call, so all options and input field are both cleared. 
Is there any way to disable the sync connection between input field and option list?

Current selectize configuration:

``` Javascript
selectize({
               valueField: 'name',
               labelField: 'name',
               searchField: 'name',
               create: true,
               delimiter: ",",
               options: [],
               render: {
                   option: function(item, escape){}
               },
               score: function(search) {
               },
               openOnFocus: false,
               hideSelected: true,
               persist: false,
               load: function(){}
})
```

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
