### ISSUE TITLE
 addPrecedence: true not working as expected

### ISSUE THREAD

**Issue by ttback** [selectize/selectize.js#452]
It only works when first input a random string, but if user selects the created new option (create is also true), then user enters same string, the default selected will be the one next to create item. Steps
1. Enter a string, say, "sand"
2. Press enter, sand is selected. 
3. Enter sand again
4. Press enter, the next item in option is selected.

The expected behavior should be that it is always selecting the create item by default under any conditions, as long as there is a create item in the option dropdown.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
