### ISSUE TITLE
Initializing the selectize control in create mode drops selected items

### ISSUE THREAD

**Issue by Scottmitch** [selectize/selectize.js#454]
##### Bug (or arguably feature request)

If the `options` initializer does not contain all the `items` in the underlying <select> or <input> control, and the `create` initializer is true, then items which are not in the `options` array are dropped.  These items should not be dropped and should be created/selected.
##### Why is this a bug?

The selectize control initialization has no interface to specify the currently selected values. Instead selectize extracts all <option> elements in the <select> element, or extracts delimited items from an <input> element (this is expected/good behavior).  This means that for the user of the selectize API to correctly augment the `options` array and add all the `items` which are missing from the `options` array the selectize control's `item` extraction/initialization code must be duplicated.  Since the selectize control is handling the `item` extraction/initialization internally it should also handle the case where items have been added in the past and the control is now being re-initialized to display these values (if the `create` initializer is `true`).

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
