### ISSUE TITLE
Invoking 'load()' does not reset the $activeOption

### ISSUE THREAD

**Issue by chrisronline** [selectize/selectize.js#460]
Is this intentional? If there are existing options in the list and the user starts typing (assuming the selectize control supports remote loading) and new options are loaded and added into the control, the original match against the existing options remains active even if one of the loaded options is scored higher.

Code flow:
https://github.com/brianreavis/selectize.js/blob/master/dist/js/selectize.js#L1120
https://github.com/brianreavis/selectize.js/blob/master/dist/js/selectize.js#L1128

This line of code will keep the previously $activeOption the newly active option even though new options are present (and could potentially have a higher match score)
https://github.com/brianreavis/selectize.js/blob/master/dist/js/selectize.js#L1446

Along this note, if I go to the demo site (http://brianreavis.github.io/selectize.js/) and use the 'Email Contacts' and:
1) Focus the selectize control so the items dropdown
2) Brian Revis option is "pre-selected" by default (so hitting the Enter key will select that option)
3) Type: 's'
4) The someone option ranks the highest but the Brian Revis option is still "pre-selected" - this seems like incorrect behavior?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
