### ISSUE TITLE
Dynamically change placeholder text

### ISSUE THREAD

**Issue by pmarchezz** [selectize/selectize.js#464]
I'm trying to dynamically change the "placeholder option" in a selectize input based on some external event. Not only I'm unable to do so, but it seems I can't access any of the options values via selectize api (something like `$('myselector').data('selectize').getOption('myvalue')`). Here's a codepen that tries to reproduce the issue: 

http://codepen.io/anon/pen/Dcpmh

As you can see, my attempts to access the options (both the placeholder one and the others) via javascript don't work; while I succeeded in modifying the option with a nonempty value, the other one seems unmodifyable. What am I doing wrong? Is the feature unsupported?

(related: this guy on stackoverflow seems to have a problem similar to mine, and since it's unresolved at the moment I thought it would be a good idea to open an issue, even if it's probably me doing something wrong... http://stackoverflow.com/questions/19143364/how-to-change-placeholder-of-selectize-js-dropdown)

Thanks!

**Comment by PhiLhoSoft** [comment]
It works, but apparently it uses some obscure / non-official or under-documented parts of the API...
I can't find `placeholder` in the options, nor `settings`, nor `updatePlaceholder()`, neither in https://github.com/brianreavis/selectize.js/blob/master/docs/usage.md nor in https://github.com/brianreavis/selectize.js/blob/master/docs/api.md

Perhaps you have closed the issue too soon... :smile: 

[EDIT] Or perhaps I should take a stab at helping to improve the doc... :grin:

**Comment by javamonn** [comment]
This doesn't work if you are attempting to clear the placeholder by settting it to the empty string, ie:

```
var selectize = $('selector').data('selectize');
selectize.settings.placeholder = '';
selectize.updatePlaceholder();
```

This results from the falsey check on settings.placeholder here, which prevents the update:
https://github.com/brianreavis/selectize.js/blob/master/src/selectize.js#L1676

**Comment by PhiLhoSoft** [comment]
Indeed, the check should be more specific, perhaps removing the placeholder attribute if it is an empty string.
Solutions / workaround: either do a monkeypatch of the function, or set the placeholder to a single space.

**Comment by nathanbertram** [comment]
Thanks for the suggestion @PhiLhoSoft -- I ended up using a money patch solution you suggested:

```
$(".selectize-input input[placeholder]").attr('placeholder','Select an Architecture (Optional)'');
$(".selectize-input input[placeholder]").attr("style", "width: 100%;");
```

For my particular scenario it made sense :)
