### ISSUE TITLE
Uncaught TypeError: Cannot read property 'mixin' of undefined 

### ISSUE THREAD

**Issue by montogeek** [selectize/selectize.js#465]
This error appear in the selectize.js and selectize.min.js on the dist folder :S

I just downloaded the selectize.js from the demo page and it works.

**Comment by deronsizemore** [comment]
Not that it matters, but I just got this error too using the selectize.min.js from the dist folder and the selectize.min.js from the standalone folder. When I use selectize.js from standalone, it's fine.

**Comment by karikas** [comment]
This still appears to be an issue when using the dist/standalone/selectize.js file from the latest github commit, but if you use that file from the 0.12.1 "release" it works with no errors.

**Comment by argb** [comment]
how to solve the problem?

**Comment by huogerac** [comment]
I'm using the 'selectize#0.12.1' and got the Cannot read property 'mixin' of undefined error.
I figured out I was using the wrong js file (selectize/dist/js/selectize.min.js) instead of the correct one:
'selectize/dist/js/standalone/selectize.min.js'
It's working now.
