### ISSUE TITLE
getOption(value) not returning the $item even though it exists in this.options

### ISSUE THREAD

**Issue by ttback** [selectize/selectize.js#466]
Not sure if this is expected, but if dropdown is not shown, the getOption doesn't necessarily give you the $item or able to check on the option with given 'value'. But removeOption will work.

Here's a sample from console:

``` shell
this.getOption(value)
[]

value
"wefefwefwefewaf"

this.options
Object {wefefwefwefewaf: Object}

this.getOption(value)
[]

this.removeOption(value);
undefined

this.options
Object {}

```

**Comment by vanboom** [comment]
getOption() was exhibiting this behavior in my application.  Instead of using getOption, access the options directly...

```javascript
var o = this.options[value]
```
