### ISSUE TITLE
Allow focus / backspace delete even when refreshClasses isFull returns true.

### ISSUE THREAD

**Issue by MeoMix** [selectize/selectize.js#468]
Hello,

I'm hoping to convince you that allowing a selectize control to become focused even when it is full should be allowed in some scenarios.

I have a control which allows only one selection to be made. Users have stated that it is confusing to not be able to click the input and hit backspace to remove their selected option. After digging a bit, I found that the following was responsible:

```
    refreshClasses: function () {
        var self = this;
        var isFull = false; //self.isFull();
```

If I set refreshClasses' isFull to false -- I am able to use backspace to clear the provided input. I believe this improves usability and I don't see any incorrect behavior introduced.

Is there a reason why you would like to enforce not using backspace to clear an entry in some scenarios?

Thanks

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
