### ISSUE TITLE
selectize dropdown 'flashes' when using 'nocache' plugin

### ISSUE THREAD

**Issue by PoeHaH** [selectize/selectize.js#469]
I wrote a "nocache" plugin that basically
clears the options when the dropdown is closed.
When the dropdown is opened, ajax fills up the list again.

When using the plugin, the first time eveything is fine, but after the popup closes,
when I want to open it again, the popup flashes (open/closes for a split second).

A simplified code example:

http://jsfiddle.net/cHxcZ/25/

Should I implement the 'nocache' behaviour in a different way?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
