### ISSUE TITLE
No results found message

### ISSUE THREAD

**Issue by mudassir0909** [selectize/selectize.js#470]
When user searches for something I'd like to show some help text "No items found that match your criteria" or something, is it possible by default or should I write my own selectize plugin for that ?

Similar to this
![no_results](https://cloud.githubusercontent.com/assets/1861842/3257564/aea093e0-f22d-11e3-9746-308f5a0ce863.png)

Actually right now I've implemented a plugin to do this, but it seems like a ugly patch. I'd rather have this built in the library instead.

**Comment by feugen24** [comment]
@thiago-negri 
for it to work i changed to

```
if (!self.loadedSearches[str] && !self.hasOptions) { //notice "not" in first expression
```

still the code won't work if source is loaded by remote call, since it will first show "no results" then display them after it gets from server

I used instead

```
$select[0].selectize.$empty_results_container.show();
```

**Comment by KenStipek** [comment]
I changed the `self.on` method to the following to include the query typed in the message. I also removed the text from the options:

```
    self.on('type', function(str) {
        var message = '"' + self.lastQuery + '" is not valid'
        if (!self.hasOptions) {
            self.$empty_results_container.text(message).show();
        } else {
            self.$empty_results_container.hide();
        }
    });
```

**Comment by mininglink** [comment]
@KenStipek  I have implemented your method

I need to show a link to click if there is no results

but changed the line show a link,  but it goes away when click, i assume prevent default, but how do we force a click here

self.$empty_results_container.html(message).show(); 

got this working by using onmousedown for regular browsers with a mouse and touchstart for touch devices

 <a href="#" onmousedown="window.open(\''http://yourlink.com'\'); return false;" touchstart="window.open(\''http://yourlink.com'\'); return false;">click here</a> to go to where ever';

**Comment by KenStipek** [comment]
@mininglink I'm sorry, I don't know :(

**Comment by kalfalasi** [comment]
Hi @KenStipek @mudassir0909 how did you guys make it to work?

**Comment by mudassir0909** [comment]
@alfalasii Make what work? If you are here to display "No results message" then this gist should be fine https://gist.github.com/mudassir0909/2d5c50a411829733d547 (I already pasted it above but adding for the convenience)

**Comment by kalfalasi** [comment]
Thanks @mudassir0909, its working now

**Comment by sdhull** [comment]
I also would appreciate this to be built-in functionality, however for the time being it looks like the plugin by @mudassir0909 will work fine. Thanks @mudassir0909! :+1:

**Comment by morrow95** [comment]
How do we actually 'use' this?  I have added the following in my success : 

```
success: function(data) {
    if(data.total == 0) {
        this.$empty_results_container.show();
    } else {
        callback(data.results);
    }
}
```

and I see the .dropdown-empty-message div created, but with a display:none, but can't get it to show.  Also getting this error in the console : 

```
TypeError: this.$empty_results_container is undefined
```

**Comment by morrow95** [comment]
nevermind - this does not work when allowing create.

**Comment by morrow95** [comment]
Anyone care to take a look at this?  From what I can tell the : 

```
    self.on('type', function(str) {
        if (!self.hasOptions) {
            self.$empty_results_container.show();
        } else {
            self.$empty_results_container.hide();
        }
    });
```

is not being triggered as it shows in the html just not visible.  I am using the create option and ajax though.  Is it possible to manually call `self.$empty_results_container.show();` within my success callback?  That way I could determine if there were any results returned from my script or not and show/hide as needed.  I believe this is what @bkosborne did in an earlier post, but I could never call the function to show it.

Also, when using the plugin I notice my custom addition to always show a default value on empty no longer functions.  If I comment out the plugin then it works like it should.

```
    onDropdownClose:function() {
        if(this.getValue() == '') {
            this.setValue(default_filter);
        }
    }
```

https://jsfiddle.net/Ld5d08pv/1/

**Comment by jfly** [comment]
I find that @mudassir0909's [plugin](https://github.com/brianreavis/selectize.js/issues/470#issuecomment-145775933) doesn't work for me unless I comment out the following code in selectize: https://github.com/brianreavis/selectize.js/blob/043420284064ad998b07e1abd9720f56c86d6614/src/selectize.js#L587-L591.

**Comment by dwickwire** [comment]
Here's a [no_results plugin](https://gist.github.com/dwickwire/3b5c9485467b0d01ef24f7fdfa140d92) that requires no hacks of selectize.js and offers a no results found message only when relevant.

If I were assured a PR would get review, I would happily put it together, given there are 119 open PRs right now I'm less inclined to go through the effort of writing the tests etc.

**Comment by stevro** [comment]
@dwickwire , your plugin does not work properly for results loaded with ajax as it displays the "No results found" message right away, not after the ajax finishes, and if the "create" option is enabled the message never appears as this.hasOptions will return true.

**Comment by jonfer** [comment]
@bkosborne How were you able to call displayEmptyResultsMessage from the ajax call? Thanks

**Comment by RashidShamsi** [comment]
@mudassir0909  with **create:true** option, no-result-found plugin is not working.

**Comment by mudassir0909** [comment]
@RashidShamsi it was created 5 years ago, it worked for the version of library then, maybe things have changed since which I'm not aware of, feel free to fork that plugin & modify it to make it work 🙂

**Comment by vigneshrajarr** [comment]
I had the same issue (While loading the options dynamically from server, "No results found" is shown right away before the request is finished).

Just add an extra condition in a line in the `refreshOptions` method as following.

`this.hasOptions || this.lastQuery == "" || this.loading ? this.$empty_results_container.hide() : this.displayEmptyResultsMessage();`

`loading` attribute will be set before request is made and reset to `false` once the same has been resolved.

Additionally, following checks can also be used to check the loading state.
`this.$wrapper.hasClass('loading')` or 
`this.$wrapper.hasClass(Selectize.defaults.loadingClass)` (in case the `loading` class name is changed upon different versions)

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.

**Comment by eduardo-mior** [comment]
I am using the latest version of selectize and this gist worked perfectly.
https://gist.github.com/dwickwire/3b5c9485467b0d01ef24f7fdfa140d92

I just made an adjustment for no_results to work together with create.
The code is this:

```javascript
           self.displayEmptyResultsMessage = function () {
                this.$empty_results_container.css('top', this.$control.outerHeight());
                this.$empty_results_container.css('width', this.$control.outerWidth());
                this.$empty_results_container.css('box-shadow', 0);
                this.$empty_results_container.show();
                this.$control.addClass("dropdown-active");
                if (this.hasOptions) {
                    this.$dropdown.css('margin-top', '30px');
                    this.$dropdown.css('border-top', '0');
                    this.$dropdown.css('box-shadow', '0px 10px 12px rgb(0 0 0 / 18%)');
                }
            };

            self.refreshOptions = (function () {
                var original = self.refreshOptions;

                return function () {
                    original.apply(self, arguments);
                    if (this.currentResults.items.length > 0 || !this.lastQuery) {
                        this.$dropdown.css('margin-top', '2px');
                        this.$dropdown.css('border-top', '1px solid #B6B6B6');
                        this.$empty_results_container.hide()
                    } else {
                        this.displayEmptyResultsMessage();
                    }
                }
            })();
```

I just made an adjustment in the displayEmptyResultsMessage and in the displayEmptyResultsMessag

**Comment by dave105010** [comment]
Why is this issue closed? Is this available on the current stable version yet?

**Comment by eduardo-mior** [comment]
> Why is this issue closed? Is this available on the current stable version yet?

@dave105010 The problem was closed because the project owner is arrogant. He doesn't want to accept that this function is useful. This was not implemented in selectize. If you want you should manually implement this plugin https://gist.github.com/dwickwire/3b5c9485467b0d01ef24f7fdfa140d92, and if you want to use EmptyResults together with CreateOption you should make the adjustment I made.

**Comment by databyte** [comment]
This is yet another example of why more and more open source developers step back from spending their free time to help developers, like yourself, just to see you talk and criticize while providing no value back to the project themselves.

The group here has provided value to the community out of the goodness of their heart and with their free time.

I'd argue the entire point of plugins is to add functionality that isn't provided. I, personally, don't need this functionality. Why should I bloat my distribution by included unnecessary features? Isn't this the entire point of plugins?

When is a project done and good enough? The rest can be extended as needed! Are you saying you want Node itself to include every single library in npm and that we shouldn't need plugins because everything should just be included?

In the end, if you disagree - open a PR and don't forget to include tests.

**Comment by eduardo-mior** [comment]
> This is yet another example of why more and more open source developers step back from spending their free time to help developers, like yourself, just to see you talk and criticize while providing no value back to the project themselves.
> 
> The group here has provided value to the community out of the goodness of their heart and with their free time.
> 
> I'd argue the entire point of plugins is to add functionality that isn't provided. I, personally, don't need this functionality. Why should I bloat my distribution by included unnecessary features? Isn't this the entire point of plugins?
> 
> When is a project done and good enough? The rest can be extended as needed! Are you saying you want Node itself to include every single library in npm and that we shouldn't need plugins because everything should just be included?
> 
> In the end, if you disagree - open a PR and don't forget to include tests.

@databyte 
There are dozens of useless plugins inside Selectize. Why can't this plugin be added too? All custom Select WEB components have this functionality, Select2, Chosen, PrimeFaces Select etc... Lots of people in many threads both on Stackoverflow and here on github have asked for this.

**Comment by databyte** [comment]
This isn't a custom dev shop that works for free. Open source is based on contributions from the community- not just the author.

Looking forward to the PR. Don't forget the tests.
