### ISSUE TITLE
dropdownlist Postback on Backspace

### ISSUE THREAD

**Issue by imranjanwari** [selectize/selectize.js#471]
Hi
I am using selectize in my asp.net application where i have used normal asp.net dropdownlist binded with datasource.

I have used selectize like:

$('#combo_serviceType').selectize({
                    persist: false,
                    createOnBlur: true,
                    create: true
                });

which works great untill i will enable Postback property of dropdown controll. When i am enabling the Postback for it i am not able to type anything in combobox because on Backspace it is calling Postback itself.

Any sugession please.

Thanks,

Imran

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
