### ISSUE TITLE
Use alternate dependency for drag_drop plugin

### ISSUE THREAD

**Issue by knownasilya** [selectize/selectize.js#474]
jQuery UI's Sortable is 37kb.. as compared to [jquery-sortable](http://johnny.github.io/jquery-sortable) (9kb, 3kb gzipped) or [html5sortable](http://farhadi.ir/projects/html5sortable/) (3kb, 1kb gzipped). 

Would love to submit a PR for this if you're for it.

**Comment by philfreo** [comment]
+1 for using https://github.com/RubaXa/Sortable (the successor to html5sortable, which is no longer maintained) as a dependency instead of jQuery UI.

**Comment by risadams** [comment]
closing this,  
this could be completed with an alternate plugin if you would like to take a stab and create a PR.
