### ISSUE TITLE
FastClick and Selectize.js on iOS 7, can't select from dropdown

### ISSUE THREAD

**Issue by kinergy** [selectize/selectize.js#479]
Just posted [this bug](https://github.com/ftlabs/fastclick/issues/265) on the FastClick repo - 

FastClick is a useful utility that eliminates the 300ms delay when taping to click in iOS. Currently though, a user can't select an option from a Selectize dropdown in iOS when FastClick is enabled.

I just wanted to see if anybody in this group has any ideas about what may be causing the issue.

Thanks!

**Comment by adamgins** [comment]
@biesbjerg thanks for this. 

I am still having issues selecting on a touch device in both Safari & Cordova,

I can select an item / option in the list. I am using the `create=true` option and I can't `add` a new item by clicking on it. If I hit enter it works.. .it's just the click.

I tried overriding the `option_create` too with the following function:

```
function(item, escape) {

     return '<div class="create needsclick">Add <strong>' + escape(item.input) + '</strong>&hellip;</div>';
};

```

But same symptom: nothig happens, it just deselects the dropdown like nothing was clicked. Not sure what I am doing wrong.

**Comment by adamgins** [comment]
Ok, I found a workaround `createOnBlur:true,` . I think when I touch the "add something... " it's closing the dropdown. So the blur event  cateches this.. so I am not sure how good a workaround it is.. but feels like a bug.. that said I am using touchpunch ... which may be part of the issue here.

**Comment by AdamWills** [comment]
I'm having the same issue as @adamgins here.

**Comment by farturi** [comment]
I'm having the same issue as @adamgins ...

**Comment by danielgehr** [comment]
We where able to solve the problem @adamgins describes by adding the touchstart event to the selectize. Check out this PR: https://github.com/selectize/selectize.js/pull/1262

**Comment by adamgins** [comment]
Thanks  will take look.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
