### ISSUE TITLE
Force selectize-control to text align left

### ISSUE THREAD

**Issue by asessa** [selectize/selectize.js#484]
Case: 

```
<div style="text-align:right">
<select></select>
</div>
```

Effect:

text is aligned to right, above the dropdown icon.

![screen shot 2014-06-19 at 11 59 58 am](https://cloud.githubusercontent.com/assets/957555/3326085/8558113c-f798-11e3-88a2-e281ece7207b.png)

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
