### ISSUE TITLE
Can't use Ctrl/Cmd+A to select all text when option is selected

### ISSUE THREAD

**Issue by ragulka** [selectize/selectize.js#486]
Using a simple (single item) select, it seems it's not possible to select all the text in the input by pressing Ctrl+A/Cmd+A. It only seems to work when being in "search mode".

Steps to reproduce:
1. Open select
2. Type something random
3. Press Ctrl+A/Cmd+A - observe that all the text is selected
4. Now, clear the input and select an option from the dropdown
5. Open the select again, press Ctrl+A/Cmd+A
6. Observe that it doesn't select the text in the input

I would expect being able to select the text in input regardless of whether it contains an actual selected option or a search string.

**Comment by joallard** [comment]
Looks similar to #256. Thanks
