### ISSUE TITLE
How to redraw a form with an input control?

### ISSUE THREAD

**Issue by pgee70** [selectize/selectize.js#495]
Hi  i have information request relating to how to manage a form refresh, similar to #366 .  I can get the ajax to read the data remotely, but unlike the example, I am using a text input tag to search for suburbs from postcodes.
e.g.
![screen shot 2014-07-01 at 10 26 39 am](https://cloud.githubusercontent.com/assets/5938974/3437706/69b438da-00b6-11e4-841a-99f631a552c6.png)

i have tried a number of strategies, using <input  data-data="{json}" ...  and also adding an option to the selectize after instantiation.  eg

```
var selectize = $("#input")[0].selectize;
selectize.addOption({'pc_id':pcValue,'pc_post_code':pcValue});
selectize.addItem(pcId);
```

this re-draws the form with the correct value, but the autocomplete afterwards seems broken -- the autocomplete does not refresh.
![screen shot 2014-07-01 at 9 55 13 am](https://cloud.githubusercontent.com/assets/5938974/3437623/881fef32-00b4-11e4-9e79-4a6e771d4a71.png)

Semantically i think it would be best to give the input tag a value="7000" on refresh.  On focus (after redraw), the autocomplete would fire again.  How can i do that?

**Comment by posgarou** [comment]
@pgee70 Thank you so much for mentioning that the searchField is required and saving me those hours!  

@brianreavis If you could clarify in the documentation that searchField is required for ajax that would be very helpful.

**Comment by pgee70** [comment]
Hi Brian
Sorry but i have moved to select2.  I just had too many problems integrating selectize into my project, and I have since wiped the selectize code.

What I wanted to do in this instance was to enter in the numeric postal code, and select the suburb/state, store  the unique id, and display the suburb and state after selection in the disabled fields.

regards

Pete
