### ISSUE TITLE
persist added options

### ISSUE THREAD

**Issue by mikemliu** [selectize/selectize.js#496]
When using `persist: false` as an option, even options that are loaded programmatically through `load` or `addOption` are not persisted after an item removal.

From code, it looks like selectize classifies options that are programmatically inserted also as an `userOption`. Is this intended behavior? If so, documentation should be updated.

My use case involves loading options dynamically, but I would still like to persist these but not user created options.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
