### ISSUE TITLE
Saved values and remote load

### ISSUE THREAD

**Issue by unsafecode** [selectize/selectize.js#497]
I know it has been asked before, but I still have to see a complete solution.

We have a Selectize-enabled component, done with KnockoutJS. The component hooks to an observable (either single-valued or array) and accepts a configuration to fetch data from a remote URL.

We managed to sync the observable with Selectize events (worth noting we need to save the whole object, not just keys), but we have been experiencing serious issues when prefilling the control with previously saved data.

a) Generating a <select> with the initial values as <option>s, all marked with selected='selected', doesn't work: selectize doesn't recognize multiple values, just the first one.
b) Applying the 'data-data' attribute makes no changes
c) Leveraging setValue() doesn't work, UNLESS when coupled with case a)

So, ultimately, we need to generate a fake <select> with the saved choices, initialize Selectize and then call setValue().

Is there an easier way to achieve this?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
