### ISSUE TITLE
optgroup order?

### ISSUE THREAD

**Issue by joshuataylor** [selectize/selectize.js#499]
Is it possible to order multiple optgroups?

Let's say I have fruits and vegetables, would it be possible to put fruits above vegetables?

**Comment by brianreavis** [comment]
This has changed a little in [0.12.0](https://github.com/brianreavis/selectize.js/releases/tag/v0.12.0). Now, set the `$order` property on each item in your `optgroups` array.

**Comment by shurfee** [comment]
@brianreavis, could you please give an example how to implement your advice?

I need to sort optgroups by its labels, is it possible?

In my "options" code for selectize there is a key sortField with a value of "text". But it sorts only options by its inner text.
And I need to sort not only options inside optgroup, but also optgroups themselves.

`<optgroup label="1"> <option>Text ABC</option> </optgroup>`
`<optgroup label="2"> <option>Text BCD</option> </optgroup>`

**Comment by adamgins** [comment]
@brianreavis thanks for the great package. I am using `0.12.1_5`

can't seem to get it to pick up the `$order`, I have `optgroups: [{$order: 1, group:'role',name:'Role'}, {$order: 2,group:'team',name:'Team'}, {$order: 3,group:'people',name: 'Participants'}]`

but it renders in the wrong order. I tried changing the numbering, in reverse... no luck I see items in this order Participants, Team, People regardless of the `$order` param/val

update: I upgraded to `0.12.4 ` , same issue

**Comment by brjadams** [comment]
@adamgins had the same issue. Saw the optgroup examples from selectize, where the added the 'lockOptgroupOrder' flag. Seems to fix it. I'm using 0.12.1.

Just add 'lockOptgroupOrder: true' to your selectize options on initialize.
