### ISSUE TITLE
Stricter input / definition validation

### ISSUE THREAD

**Issue by mallyvai** [selectize/selectize.js#501]
Hello! 

I really like Selectize, but I ran into a pretty annoying bug when trying it for the first time - basically, my valueField: 'thing' value had a small typo in it (valueField: 'thimg'), and as a result, the dropdown didn't display at all.

There was no indication as to why things were breaking -  I didn't see any errors in the console ; the select box simply didn't work. It would be great if the valueField, labelField, and searchField keys/values were more explicit in their failure if they didn't exist on the results object.

**Comment by brianreavis** [comment]
I'm potentially open to pull requests on this
