### ISSUE TITLE
to get Selected text for select box

### ISSUE THREAD

**Issue by satyakishorej** [selectize/selectize.js#504]
Is there any way to get selected text of select when selectize used 

Thank you 
Satyakishore

**Comment by brianreavis** [comment]
Generally speaking:

``` js
var $select = $('#select-type').selectize();
var selectize = $select[0].selectize;

selectize.on('change', function(value) {
    var items = selectize.items; // array of values
    var text = items.map(function(value) {
        return selectize.options[value].text;
    }).join(',');
});
```

**Comment by franklinjoseph** [comment]
How can i change the text of a selected value? Eg: i have a scenario where i have to change the text to "something ...." if the default text is "something something something"(ie - more than 15 chars). How can i achieve this? Thanks
