### ISSUE TITLE
Why can't we focus the selectize input without active items?

### ISSUE THREAD

**Issue by chrisronline** [selectize/selectize.js#505]
I don't understand this line here:

https://github.com/brianreavis/selectize.js/blob/master/src/selectize.js#L550

If I attempt to focus the control outside of selectize, it works unless there are no active items. What's the recommended way around this, besides manually calling showInput after setting focus?

**Comment by mkmms** [comment]
i am unable to type when previously selected option is present..
i would like to type without pressing backspace/delete key to clear.

need suggestion pls.
