### ISSUE TITLE
JSON support?

### ISSUE THREAD

**Issue by samuelschumacher** [selectize/selectize.js#513]
Full disclosure, I may simply be missing something, I'm new to Bootstrap 3.

I see support for remote data as well as JSON support using arrays of JSON-compliant strings, however I can't seem to find any documentation on querying JSON objects already present in the document. It should be fairly direct, but evidently is not. 

My js: 

``` javascript
var soe_data = soeData(),//create object based on JSON wrapped in a function
    facultystuff = soe_data.faculty,//no sifter support for nested JSONs, so
alert(typeof soe_data);//spoiler alert: object
$(function() {
  $('#facultyname').selectize({
    create: false,
    valueField: "fac_name",
    labelField: "fac_name",
    options: [],
    dataAttr: 'facultystuff',//Documentation suggests assigning data to 'dataAttr'
    openOnFocus: 'false',
    maxOptions: '5'
  });
});
```

And the HTML where it gets called:

``` html
<div class="formrow">
    <label for="facultyname">Name: </label>
    <select id="facultyname" class="single" placeholder="Select a person..."></select>
</div>
```

At line 2525 of selectize.js, readData is assigned, and that seemed to be the problem:

``` javascript
var readData = function($el) {
    var data = attr_data && $el.attr(attr_data);
if (/*typeof data === 'object' | */typeof data === 'string' && data.length) {
    return JSON.parse(data);
}
return null;
};
```

The structure of the JSON is as follows:

``` javascript
    "faculty": [{
        "ID": "50005",
        "fac_name": "The Dude",
        "inst_code": "2",
        "dept1": "",
        "dept2": "",
        "url_bio": "https://www.google.com/url?q=something",
        "activity": "Exhibition",
        "proj_desc": "Prints from the Minneapolis Art Institute",
        "year": "1995",
        "instnam(tmp)": "American Embassy",
        "url_two": "",
        "inst_url(tmp)": "https://www.google.com/url?q=somethingaboutfish",
        "sh": "Y",
        "cv": "YES",
        "2nd position": "",
        "other": "",
        "inst_needs_id": ""
    },
{...}...
{...}]
```

The commented edit did nothing, however. Again, I may be missing something very simple here, but it seems silly to stringify my JSON object just to call JSON.parse on it. Any suggestions?

**Comment by joallard** [comment]
Thanks for reporting this issue. I am closing it since the issue has been inactive for more than 2 years. If there is still a problem with the latest version, please re-open. If you haven't done so, read the [Issue reporting guide](https://github.com/selectize/selectize.js/wiki/Reporting-issues-guide) and make sure your original post follows the guide.
