### ISSUE TITLE
Add Option with form

### ISSUE THREAD

**Issue by rgirardRev** [selectize/selectize.js#517]
Is there a way to display a form when adding a new record? Say I am displaying a list of customers to search through and select, but when i dont find one, I might want to add a new one on the fly and attach other data points for a customer record, but then auto select it after its added.

**Comment by msvendsen** [comment]
Did you find a solution/workaround? :)

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
