### ISSUE TITLE
The list under the field doesn't appear when a search result contains unicode chars

### ISSUE THREAD

**Issue by Blackwhitejack** [selectize/selectize.js#518]
When my response has unicode symbols like:

  {"name":"VAQ\u0130F","last_name":"Q\u018fHR\u018fMANOV"}
the list doesn't appear under the input field:

http://stackoverflow.com/questions/24912782/the-list-under-the-field-doesnt-appear-when-a-search-result-contains-unicode-ch

**Comment by yurikuzn** [comment]
I've encountered with the problem with unicode that seems to be the same issue. Could be a problem with a normalization. I have the option `étest` but it get converted to `\u00e9test`.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
