### ISSUE TITLE
Remove item does not work when input is not entirely visible on screen

### ISSUE THREAD

**Issue by ajgarn** [selectize/selectize.js#523]
I am using the `remove_button` plugin. When the bottom of the selectize input field is outside of the screen, clicking the remove button just selects that item as active and scrolls the input into focus (without removing the item). To remove the item I must then click the remove button when it's already selected or when the entire input is visible on my screen.

I think it is the call to `self.setActiveItem($item);` on line 61 of [remove_button/plugin.js](https://github.com/brianreavis/selectize.js/blob/master/src/plugins/remove_button/plugin.js#L61) that is doing this scroll into focus. And the call to `self.deleteSelection()` on the next line does not seem to remove the selected item in this case.

This is causing a problem when using large inputs, like in the example below. Any thoughts?

![image](https://cloud.githubusercontent.com/assets/5390422/3753995/2ea16236-1817-11e4-85cb-ea4cafc35cc3.png)

**Comment by edward93** [comment]
I have the same problem and that code did not help me. I also tried to change the focus code but again same result.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
