### ISSUE TITLE
Multiple selection in dropdown

### ISSUE THREAD

**Issue by kudlajz** [selectize/selectize.js#527]
Hi,

would it be possible to have a `<select multiple="multiple">` behave like single select, except that it would not be a tag input, but rather something like here: http://silviomoreto.github.io/bootstrap-select/, where you can select multiple options in a dropdown and you see a tick or whatever next to them?

I really like your plugin and want to use all the functions, like remote fetching etc., but I do not want to use a tag input, because when I have a lot of options selected, input become really big.

Thank you in advance.

**Comment by brianreavis** [comment]
The single select mode is already somewhat of a divergence from the main idea behind selectize. I think expanding on it support something like this would make selectize less maintainable
