### ISSUE TITLE
Input not selectable on iOS without a placeholder

### ISSUE THREAD

**Issue by AlecRust** [selectize/selectize.js#534]
If a placeholder isn't provided in a Selectize input a mobile user (iOS) can't select the input and trigger the keyboard.

If a placeholder is provided Selectize uses this as the front-most element which is tappable on iOS, triggering the input focus and keyboard.

This should be mentioned somewhere, or ideally this would behave exactly the same with/without a placeholder present.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
