### ISSUE TITLE
selectize suggestions

### ISSUE THREAD

**Issue by 719media** [selectize/selectize.js#535]
I absolutely love this library. I have a few suggestions:

1) Modify the bootstrap3 css as indicated in issue #105  with vertical-align:top; for the .selectize-input class. This fixes some alignment issues.

2) Allow multiple selections of the same value (Several issues recommended a fix, one of them basically suggested this same fix, but I couldn't find the reference). I've found the easiest is to change:

```
var i, active, value_next, wasFull;
value = hash_key(value);

if (self.items.indexOf(value) !== -1) {
```

to

```
var enableDuplicate = self.settings.enableDuplicate;
var i, active, value_next, wasFull;
value = hash_key(value);

if ((! enableDuplicate) && (self.items.indexOf(value) !== -1)) {
```

3) Make bootstrap 3 css work with input-group-addons. RIght now the addon expands in height when the selectize dropdown is opened. I don't have a fix for this one.

Do you have a donation link?

Thanks!

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
