### ISSUE TITLE
Selectize not sorting properly

### ISSUE THREAD

**Issue by shannahutch** [selectize/selectize.js#540]
Selectize is making multiple calls to find answers, but is only returning the first Letter responses.  For example if I type in New York.  Instead of prioritizing responses to eventually display New York as the top choice it shows every option starting with "N".  upon inspecting the Network it is making the call but not updating results.  Ideas?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
