### ISSUE TITLE
How to change $document.on method in plug ?

### ISSUE THREAD

**Issue by magixsource** [selectize/selectize.js#544]
I need click dropdown content but don't call blur method,and i find that i could change it  by below source:
$document.on('mousedown' + eventNS, function(e) {
                if (self.isFocused) {
                    // prevent events on the dropdown scrollbar from causing the control to blur
                    if (e.target === self.$dropdown[0] || e.target.parentNode === self.$dropdown[0]) {
                        return false;
                    }
                    // prevent events on the dropdown custom area(class always-fixed) #NewChange
                    if($(e.target).hasClass('always-fixed') || $(e.target).parents('.always-fixed').length > 0){
                        return false;
                    }
                    // blur on click outside
                    if (!self.$control.has(e.target).length && e.target !== self.$control[0]) {
                        self.blur();
                    }
                }
            });

and i don't wanna code it like above,i wanna code that as a plugin,but when i use "self.onBlur = ..." in plug, the really e.target has change to $input. Could any guy point me ? thanks very much.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
