### ISSUE TITLE
Locale/Diacritics sorting

### ISSUE THREAD

**Issue by miguelcobain** [selectize/selectize.js#559]
This is probably related to sifter, but I'll write it here anyway.

It looks like sorting options is ignoring diacritics.
So, for example, if I have the following options:
- Zebra
- Água

Zebra comes first, which is really strange in my language. Indeed, if you write in your browser console `"Z"<"Á"` it returns `true`.

This is why `localeCompare` was created. See [this SO question](http://stackoverflow.com/questions/3630645/how-to-compare-unicode-strings-in-javascript).
However, since Selectize/Sifter has Diacritics support, why isn't it used to sort the options?

Also, can anyone think of a way to write a `score` function to sort this out?

Edit.

I was able to fix this by changing sifter's `cmp` function to this:

``` javascript
var cmp = function(a, b) {
    if (typeof a === 'number' && typeof b === 'number') {
        return a > b ? 1 : (a < b ? -1 : 0);
    }
    a = String(a || '').toLowerCase();
    b = String(b || '').toLowerCase();
    if (a.localeCompare(b)>0) return 1;
    if (b.localeCompare(a)>0) return -1;
    return 0;
};
```

But instead of `localeCompare` we should just replace the diacritics with the actual letter and the compare.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
