### ISSUE TITLE
Selectize support for multi column dropdown. 

### ISSUE THREAD

**Issue by haovn** [selectize/selectize.js#56]
This is a very helpful feature for production site.

![selectize-multi-column](https://f.cloud.github.com/assets/453964/885034/7c1d2020-f9c5-11e2-96c5-4b241d2c3fa6.jpg)

**Comment by SenerDemiral** [comment]
I'm also interested "dropdown_table" plugin.

**Comment by sameemsalik** [comment]
Hi guys,

This would be an awesome plugin. Is it available now?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
