### ISSUE TITLE
How to modify the posted data

### ISSUE THREAD

**Issue by dvlpp** [selectize/selectize.js#561]
In a tagging context, I'm trying to write a "negate" plugin on the "move_button" model. The idea is that when the user clicks the item's attached button, the style of the tag changes and it's considered as "negated".

My idea was to indicate a negated tag in the underlying hidden select tag by creating an option with a negative value, in order to be able to separate regular tag and negated tags on the server side.

Is this a good way to achieve this? And if so, how can I modify the valuation of the select tag ?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
