### ISSUE TITLE
"Invalid email address." alert appears twice after createOnBlur options is set to TRUE.

### ISSUE THREAD

**Issue by ratheeshnarayanan** [selectize/selectize.js#569]
I am using email contacts selectize plugin. 
After setting the createOnBlur option to true,
        1) On Entering valid email address, its working fine.
        2) On Entering Invalid email address, "Invalid email address." alert appears twice.

Please suggest me how to fix this issue ?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
