### ISSUE TITLE
Getting undefined labelField when using json 

### ISSUE THREAD

**Issue by satyakishorej** [selectize/selectize.js#571]
I am using selectize dropdown 
data is binding to select box  using JSON but in select box i am getting undefined
the following code illustrate the problem

data binding code

$.ajax({
                url : url,
                type : 'get',
                dataType : 'json',
                contentType : 'application/json',
                mimeType : 'application/json',
                success : function(accountMainHeads) {

```
                var selectize = $('#assetaccountId')
                        .selectize({
                            delimiter : ',',
                            persist : false,
                            maxItems : 1,
                            options : accountMainHeads,
                            labelField :"faAccount.accountName",
                            valueField : "assetaccountId"
                        });



            },
            error : function(data, status, er) {

            }

        });
```

Json data is 

accountHead: [{"assetaccountId":1,"faAccount":{"accountId":5,"accountName":"Account value name","accountType":"B"}}]

Please find the attached image

![account](https://cloud.githubusercontent.com/assets/8102128/4316599/ce6589e2-3f08-11e4-994a-e567ef21ab62.png)

Please provide me solution for above problem

Thanks

**Comment by brianreavis** [comment]
Selectize doesn't support dot syntax.
