### ISSUE TITLE
How to prevent selected item from appearing in control

### ISSUE THREAD

**Issue by rstudner** [selectize/selectize.js#572]
Basically I want to have my placeholder text always remain as the user picks various options.

i.e. I have a select that has a placeholder:
Search for Elements...

I'm using the onChange to emit an event to put their selection elsewhere on the page

Therefore, I don't want the select component to show the 'last selected item' I want it to keep the placeholder text (instructions).

Any ideas?

**Comment by gregblass** [comment]
I'm trying to accomplish the same thing - add it somewhere else. This isn't going to remove the selection from the dropdown. And how would you handle the remove?
