### ISSUE TITLE
Can't seem to get 'theme' to work

### ISSUE THREAD

**Issue by rstudner** [selectize/selectize.js#573]
Code excerpt:

``` javascript
        $select.selectize({
            theme: 'mytheme',
            valueField: 'id',
            labelField: 'name',
            searchField: 'name',
            dropdownParent: 'body',
            render: {
                option: function(data, escape) {
                    return '<div class="pointer">' +
                        '<a><span class="icon-20x20-indent icon-20x20-me-' +
                        escape(data.type) + '"><label>' + escape(data.name) + '</label></span></a></div>';
                }
            },
```

In the DOM, nothing has 'mytheme' attached to the classes and thus my css isn't getting picked up.

Basing this off the github example.

![screen shot 2014-09-18 at 9 53 20 pm](https://cloud.githubusercontent.com/assets/209970/4329749/cb7e77c4-3f9f-11e4-9331-b4688e7fdefb.png)

**Comment by Frozenfire92** [comment]
This should be mentioned more clearly in the website/docs/examples. For example https://github.com/brianreavis/selectize.js/blob/master/examples/customization.html
