### ISSUE TITLE
Input drop-down arrow rendered on left side under Bootstrap 3

### ISSUE THREAD

**Issue by amorphic** [selectize/selectize.js#574]
Horizontal alignment of the input drop-down arrow is set by the following in `selectize.less`:

```
.selectize-control.single .selectize-input {
...
&:after {
...
    right: @selectize-arrow-offset;
```

For bootstrap3, the value of `@selectize-arrow-offset` compiles to '`12px + 5px;`', which is invalid. 

This causes the input drop-down arrow to be incorrectly rendered on the left side of the input text box.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
