### ISSUE TITLE
Remove Plug In has an issue in ie 8.

### ISSUE THREAD

**Issue by StephenDKing** [selectize/selectize.js#578]
When using the the multi select and then the remove plug in which puts an (x) on the selected item if there are multiple items selected and you use the (x) to remove the top item, the lower items lose the (x).

![image](https://cloud.githubusercontent.com/assets/3475465/4361579/61132c98-4285-11e4-8ea6-f7131fb36962.png)

then remove the top item.

![image](https://cloud.githubusercontent.com/assets/3475465/4361623/bfea163c-4285-11e4-8637-930d787ed57d.png)

This seems to be an IE 8 item exclusively

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
