### ISSUE TITLE
Anyway to detect click on an option groups label?

### ISSUE THREAD

**Issue by rstudner** [selectize/selectize.js#582]
I have something like
Name:
   foo
   bar
Group:
   abc
   xyz

I'd like to be able to detect a click on Name: (an option group) so I could possibly filter the list by just that group/do something else

I imagine this isn't possible (which is fair) -- just wondered what might be the best approach for trying to make something like this happen?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
