### ISSUE TITLE
why dataAttr option need json

### ISSUE THREAD

**Issue by cncolder** [selectize/selectize.js#586]
most time we only need some simple type data. e.g. `data-size`, `data-price`, `data-color`.
write json data in html is not a good idea. try to write json in mustache is harder.
parse json will waste many times.

i think the better way is `$('option').data()`. just read all data in an object by jQuery.
then assign it to `item.data`.
this will make render function more powerful.

**Comment by brianreavis** [comment]
Doing this would require a lot of casting of the data, and also require much more verbose code to generate the options.
