### ISSUE TITLE
How to hide arrow icon?

### ISSUE THREAD

**Issue by momsenmeister** [selectize/selectize.js#587]
Hi,

is it possible to hide the arrow icon?
I want the input field to behave like a automplete input, not like a dropdown.
MaxItems is set to 1.

Thanks, Mike

**Comment by edward93** [comment]
@ramonesteban thanks a lot, it helped :+1:

**Comment by enchance** [comment]
Thanks, @ramonesteban!

**Comment by ghooton** [comment]
You can also simply change the visibility to hidden...

.selectize-input::after
{
    visibility:hidden;
}

**Comment by jeremyhalin** [comment]
Is it possible to hide/display carret icon whether or not there is options available ? 
Because for people it's not clear, they try to open the dropdown but there is no options to select from.
I'm using selectize also like an autocomplete input.

**Comment by tsaltena** [comment]
@HJerem I was facing a similar issue, I wanted to hide the caret when the external Load function was not yet completed: The way I solved it was:
Create a CSS style that sets the border-color of the caret to white or transparent
```
.initialSelectize:after {
    border-color:white!important;
}
```
Add that class to the original inputClass Selectize Options
```
inputClass: 'form-control initial selectize-input',
```
Remove the class on the success criterion of the Load function. This selector could be a bit too broad still, but you get the point:
```
success: function() {
    $('.initial').removeClass('initial');
    callback etc... 
}
```

**Comment by jjinkxy** [comment]
If someone needs the caret to be hidden after a single input has been chosen (especially if they are using the remove button plugin), this worked for me:
```
.selectize-control.single .selectize-input.has-items::after {
  display: none;
}
```
