### ISSUE TITLE
Auto width from the longer option ?

### ISSUE THREAD

**Issue by Mushr0000m** [selectize/selectize.js#588]
Hi !
When putting the selectize div with a float:left and no width it takes the width of the current selected element. Is there a way of taking the width of the longest option, like the classic select input does ?
The aim is to transform a simple select into a nice one but having only one line and of a dynamic width.

Thanks

**Comment by airblade** [comment]
I would like to know how to do this too, please.

**Comment by netbka** [comment]
Any news on this issue?

**Comment by fsmeier** [comment]
+1

I think we have the same problem @pobdoq

**Comment by marianomd** [comment]
+1

More than a question this is a feature request at least.

**Comment by rusikf** [comment]
+1 It will be awesome to have this option

**Comment by qpajrathod09** [comment]
I change this ---
$wrapper.css({
        width: $input[0].style.width
});

to this ---
 $wrapper.css({
        width: $($input[0]).width() 
  });

it's work on normal html pages, but get stuck on ajax content loading.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
