### ISSUE TITLE
Change to phrasing content

### ISSUE THREAD

**Issue by coreyworrell** [selectize/selectize.js#589]
`select` elements are classified as phrasing content (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select), `div` elements are classified as flow content (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div).

Normal usage would be to put a `select` element inside a `p` element. Using this plugin will break that because it uses `div` elements.

Simple solution is to make all `div` elements into `span` elements with `display: block` set.

**Comment by atav32** [comment]
Just curious about the practical advantages of this change?

**Comment by joallard** [comment]
I also wonder about what would break if we do that. But in spirit, I mean sure.

**Comment by coreyworrell** [comment]
@atav32, @joallard 

For example, if you have markup such as

``` html
<p>
  Label before:
  <select name="test" class="selectize">
    <option value="">Default value</option>
    <option value="test">Testing</option>
  </select>
  Label/description after
</p>
```

then after selectize runs, it turns the markup into this:

``` html
<p>
  Label before
  <select>...</select>
</p>
<div class="selectize-container">...</div>
<p>
  Label/description after
</p>
```

As you can see the html (`div` inside of `p`) is invalid, and thus the browser splits the `p` in half and causes different markup after selectize has run. This would be unexpected behavior because I would expect that a `select` replacement would behave as a native `select` element. Or at least that this wrong behavior would be documented somewhere.

Simple solution is to change all block content to phrasing content (eg: div -> span, etc) and style it to `display: block` or whatever is needed.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
