### ISSUE TITLE
click on dropdown to redirect to result 

### ISSUE THREAD

**Issue by programming-kid** [selectize/selectize.js#590]
ok this may be stupid question but i couldnt figure out how to do this,

i want to click on results in dropdown and redirect user to the result but whenever i click on the result item it gets added in the input box , i even tried wrapping item in `<a>` tag but still it gets added to input and not redirect to the link .

i want to do something like facebook search , click on user to visit their profile page 

Thanks

**Comment by letunglam** [comment]
Had same issue. My solution is using `onItemAdd` as bellow:

```
onItemAdd: function(value, item){
  window.location.href = value;
},
```

Hope it helps

**Comment by josephpbuarao** [comment]
Hi @letunglam,

I did what you suggested but I got an error (item is not defined). Could you please advise me. 

Many Thanks

**Comment by letunglam** [comment]
@josephpbuarao 

Just remove `item` as we don't need it anyway

```
onItemAdd: function(value){
  window.location.href = value;
},
```

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
