### ISSUE TITLE
Options with same value are not shown

### ISSUE THREAD

**Issue by FezVrasta** [selectize/selectize.js#597]
I'm building a select where the user can choose its country (and it will get the country code).
Vatican and Italy have the same code (39) and selectize shows only Vatican, I think this problem should be solved and you should allow options with the same value.

**Comment by woanversace** [comment]
I think you can edit like here
registerOption: function(data) {
            var key = hash_key(data[this.settings.valueField]);
            // if (!key || this.options.hasOwnProperty(key)) {
            //     console.log(key);
            //     return false;
            // }
            data.$order = ++this.order;
            this.options[data.$order] = data;
            return key;
        },

**Comment by naw** [comment]
Just ran into this. HTML allows multiple options with the same value, so not supporting that in selectize violates the principle of least astonishment/surprise. 

Are there reasons that selectize _shouldn't_ or _can't_ support this behavior, or is it just a matter of needing someone to do the work?

Thanks!

**Comment by jaideepYes** [comment]
Actually Problem seems to be in way selectize use its data object. `selectize.options`
which store value as 

```
{  "input value" :{ 
            $order: " selectize.order incrementer, its incremented every times a new option is created.",
            text: "Input value",
            value: "input value"
            }   
}
```

since value is made property key of an javaScript object and every key must be unique , so Options with same value is failing. Creator of this plugin must use some different approach to store options to allow two options with same value.

**Comment by joallard** [comment]
I didn't understand much, but I'm closing in favor of #129. If this concerns another issue, please open a new one with a minimal example and STR.

**Comment by agungjati** [comment]
Since It doesn't support duplicate value, i replace it with select2, it more customize able
