### ISSUE TITLE
Release on NPM

### ISSUE THREAD

**Issue by andreypopp** [selectize/selectize.js#60]
It would be call to have selectize on npm, especially for those using CommonJS browser bundlers such as browserify.

**Comment by mikemaccana** [comment]
@andreypopp (and others) [StyleSelect](http://mikemaccana.github.io/styleselect/) is available on NPM. Please let me know if you have any problems with the packages and feel free to contribute.

**Comment by mikemaccana** [comment]
Although if you want all the selectize features (and don't feel like adding them to styleselect), here's how to run selectize in browserify:

First `npm install --save jquery sifter microplugin`.

Then in your `package.json`:

```
"browser": {
  "selectize": "./public/js/src/vendor/selectize.js"
},
"browserify": {
  "transform": [
    "brfs",
    "browserify-shim"
  ]
},
"browserify-shim": {
  "selectize": {
    "depends": [
      "jquery:$",
      "sifter:sifter",
      "microplugin:microplugin"
    ]
  }
},
```

**Comment by brianreavis** [comment]
Caved in and published it: https://www.npmjs.com/package/selectize

**Comment by mikemaccana** [comment]
Thanks @brianreavis - installed it, required it, added the CSS files and it's working perfectly 👍

**Comment by tulbox** [comment]
Many thanks @brianreavis!

**Comment by fabricioferreira** [comment]
So, after the package was published to NPM, was it removed from Bower?
I don't want to reopen the discussion, but how is it going to work for those who want to use bower for client-side code dependencies?

**Comment by mikeymckay** [comment]
I'm not sure how to use it with browserify.

I've npm installed it and I've tried:
selectize = require 'selectize'

but: TypeError: $(...).selectize is not a function

Any guidance would be appreciated!
