### ISSUE TITLE
Bootstrap 3 input-group issue

### ISSUE THREAD

**Issue by DanielLavrushin** [selectize/selectize.js#600]
Hi,

selectize does not support form-group bootstrap class. It breaks css formatting.
Please see this example
http://jsfiddle.net/5ewytn3n/

**Comment by kmmbvnr** [comment]
I still have a problem with that

![selectize_problem](https://cloud.githubusercontent.com/assets/282529/5718054/24a7909c-9b2b-11e4-9300-77529fb8d7a1.png)

**Comment by EmeryEx** [comment]
The above fix does make it line up for me, but only until you open the select. Then this:
![screen](https://cloud.githubusercontent.com/assets/3971657/5971497/bae4dd92-a80c-11e4-94e7-501d71935dca.jpg)

**Comment by johnrork** [comment]
@MarshallHouse This was driving me crazy, too, especially when I pasted in @flamber's markup and it worked. I went back and forth trying to spot the difference and it came down to not having the `form-control` class initially on the selectized element.

[Here is a fiddle demonstrating the broken behavior](http://jsfiddle.net/5ewytn3n/10/), if you remove the `form-control` class, it works.

I hope this helps you.

**Comment by rmm5t** [comment]
@MarshallHouse @johnrork I believe the correct way to solve your particular behavior is to add `dropdownParent: "body"` to the options passed to `selectize`:
http://jsfiddle.net/5ewytn3n/13/

**Comment by kematzy** [comment]
Thanks @rmm5t for saving me time & headache!  Your solution works great with BS3 and bootstrap's input-groups form fields.

**Comment by ghiotion** [comment]
@rmm5t  That works if you have a single select, but what if you have a multiple select?  The input area doesn't expand.  Any ideas for a workaround for that?

**Comment by rmm5t** [comment]
@ghiotion Not sure. Might be something else, because I have it working in a page with multiple selects.

**Comment by diegoazh** [comment]
both inputClass: 'form-control selectize-input', dropdownParent: "body" are necesary for obtain the correct visual result.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
