### ISSUE TITLE
Can't get JSON Api to work

### ISSUE THREAD

**Issue by ghost** [selectize/selectize.js#602]
Hey guys,

I am trying to access data for a selectize dropdown with just one maxItem. The user has to choose one of approximately 8500 records so I don't want them to load with the page but via ajax. I looked into the API documentation and the demos but I can't get it to work...

My JSON Api looks like:
[
   {"id":"8434","text":"52531 ?bach-Palenberg","value":"8434"},
   {"id":"9387","text":"66802 ?berherrn","value":"9387"},
   {"id":"11593","text":"88662 ?berlingen","value":"11593"}
]

And I want the "text" to be displayed and searchable but the "value" as the value of the field. Also it would be perfect if the records could be preloaded.

I am sry if I created a duplicate post but I really looked into the issues and everything but I just can't get this to work. So thanks heaps for tips or hints on how to do this. :)

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
