### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by gdibble** [selectize/selectize.js#604]
so ppl can `npm install selectize --save` :+1:

**Comment by brianreavis** [comment]
Caved in and published it: https://www.npmjs.com/package/selectize

**Comment by gdibble** [comment]
:+1: Thank you :)

On Thursday, January 29, 2015, Brian Reavis notifications@github.com
wrote:

> Closed #604 https://github.com/brianreavis/selectize.js/issues/604.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/brianreavis/selectize.js/issues/604#event-227320904.

## 

~ BE*Kind . kn0wledge 1s p0wer ~
