### ISSUE TITLE
Ignored maxlength from input fields

### ISSUE THREAD

**Issue by atheros** [selectize/selectize.js#605]
Selectize is ignoring maxlength attribute from input field with option create: true.

This makes it impossible to limit the length of input on the browser side.

**Comment by HaNdTriX** [comment]
~~https://github.com/brianreavis/selectize.js/issues/326~~ #326

**Comment by HaNdTriX** [comment]
I solved this issue by creating a small plugin:

## Plugin

```
Selectize.define('inputMaxlength', function(options) {
  var self = this;
  this.setup = (function() {
    var original = self.setup;
    return function() {
      original.apply(this, arguments);
      this.$control_input.attr('maxlength', this.settings.inputMaxlength);
    };
  })();
});
```

## Usage

```
$('.my-element-selector').selectize({
  plugins: ['inputMaxlength'],
  inputMaxlength: 20
})
```

https://gist.github.com/HaNdTriX/33c487b475af1b57838d

**Comment by joallard** [comment]
Closing for #326 but we'll keep your proposed code handy.

**Comment by knoxcard** [comment]
@HaNdTriX - omg brilliant! u saved me!  How is this not merged into Selectize???

@joallard

**Comment by HaNdTriX** [comment]
This is a plugin. Just install it manually. 

https://github.com/selectize/selectize.js/blob/master/docs/plugins.md

**Comment by knoxcard** [comment]
@HaNdTriX - yup, that's what I did.  It probably sounds like I am bitching, but I am saying the plugin is so great, it should just be merged into selectize.  No worries though, the plugin architecture is fantastic!
