### ISSUE TITLE
[NFR] UI element to allow clearing current selection

### ISSUE THREAD

**Issue by temuri416** [selectize/selectize.js#606]
Hi, 

Thanks for amazing selectize.js!

Would it be possible to add an icon to selectize.js control clicking which would clear all selected items? Something like fa-times icon, positioned next to the triangle.

Cheers!

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.

**Comment by temuri416** [comment]
hmm is the project back to life?

**Comment by risadams** [comment]
Yep!
