### ISSUE TITLE
Refresh items/state hook

### ISSUE THREAD

**Issue by stevelacey** [selectize/selectize.js#609]
I am looking to add a custom panel to a selectize dropdown that essentially adds some extra visibility to options you can filter by. My options essentially have tags, and whilst you can type them and they match via the regular filtering– I want to list the tags in a panel in the dropdown too. They'd essentially work like facets, as you type/select, filtering and disappearing from the panel. I digress.

I can't find any reference in the source code to an event I can hook into to do this. I think it would be somewhere around `refreshOptions` or `refreshState`– am I looking in the right place? How can I approach this?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
