### ISSUE TITLE
Would it be possible to have multiple colors?

### ISSUE THREAD

**Issue by mikebronner** [selectize/selectize.js#612]
I would like to have the items that are already pre-selected when the page is loaded to be one color, and the items that are added manually be another color. That would visualize changes that have not been saved yet. Is there a good way to do this?

**Comment by abhilashlr** [comment]
Did you try a create filter that returns as
'<div class="newItem">' + text + '</div>
And style newItem class in your CSS with different color?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
