### ISSUE TITLE
Support proper less style import and overwriting

### ISSUE THREAD

**Issue by chengyin** [selectize/selectize.js#618]
It is great that the style files utilize variables. However, since those variables are in the LESS file, the only way I to copy this file and edit it. This divergence the file from the source (ie this repo), and I would much prefer to: 1. Add this repo as a dependency; 2. Import the less file; 3. Incorporate my customization in a separate file.  

I see two solutions:
1. Separate the variable definitions from the actual styles, so we can include our own variable file but do not have to duplicate the actual styles
2. Utilize the "!default" flag

Both solution is going to be super simple to implement. However I am not sure what is the maintainer's view on the issue, and will it a break change or not (my view is it won't be).

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
