### ISSUE TITLE
Error “Object does not support property or method 'selectize'” on selectize initialization

### ISSUE THREAD

**Issue by trashMeNow** [selectize/selectize.js#622]
i'm triyng to use this code

```
$(this.node).find("select").selectize({
valueField: "value",
labelField: "label",
searchField: ["label"],
maxOptions: 10,
create: false,
render: {
    option: function (item, escape) {
        return "<div>" + escape(item.label) + "</div>";
    }
},
load: function (query, callback) {
    if (!query.length) return callback();
    $.ajax({
        url: "../ajaxPage.aspx?functionName=GET_03&fieldValue=" + encodeURIComponent(query),
        type: "POST",
        dataType: "json",
        data: {
            maxresults: 10
        },
        error: function () {
            callback();
        },
        success: function (res) {
            console.log(res);
            callback(res);
        }
    });
}
```

});

$(this.node).find("select") is a simple select:

<select name="tagName" id="tagId"></select>
I include this js in my page:
microplugin.min.js
sifter.min.js
selectize.js
selectize.default.css
but when i use .selectize i get this error at runtime:

"Object does not support this property or method selectize"

Any idea about this error?

**Comment by brianreavis** [comment]
What version of jQuery are you using?

**Comment by joallard** [comment]
As we have many issues and not heard back, I'll close this for the time being. If you still need help, please reopen this and post a Jsfiddle/Codepen, that would help us immensely to debug the issue.
