### ISSUE TITLE
`hideInput` clears horizontal scroll position

### ISSUE THREAD

**Issue by kevinansfield** [selectize/selectize.js#625]
### Issue:

When the selectize component is contained within a horizontally scrolling element, selecting an item causes the container to scroll all the way to the left (likely to the right on an RTL system).
### Workaround:

My quick workaround was to change `hideInput`/`showInput` to move the input element upwards instead of left/right:

``` javascript
/**
 * Hides the input element out of view, while
 * retaining its focus.
 */
hideInput: function() {
  var self = this;

  self.setTextboxValue('');
  self.$control_input.css({opacity: 0, position: 'absolute', top: -$('body').height()-100});
  self.isInputHidden = true;
},

/**
 * Restores input visibility.
 */
showInput: function() {
  this.$control_input.css({opacity: 1, position: 'relative', top: 0});
  this.isInputHidden = false;
},
```

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
