### ISSUE TITLE
Selectize only properly initialises when I use `select.classname` rather than simply `.classname`

### ISSUE THREAD

**Issue by besi** [selectize/selectize.js#627]
I have a multiselection dropdown. Now on DOM Ready I initialise my dropdown:

``` coffeescript
$ ->
  $('.selectize-region-cities').selectize()
```

Please note that there are already pre-selected items in my dropdown. But the textfield looks like this:

![screen shot 2014-11-20 at 19 36 11](https://cloud.githubusercontent.com/assets/160412/5130649/83603378-70ec-11e4-86dd-c39c4bfaad47.png)

Now when I enter `$('.selectize-region-cities').selectize()` in the Safari console then the select is displayed correctly:

![screen shot 2014-11-20 at 19 38 52](https://cloud.githubusercontent.com/assets/160412/5130695/e491657c-70ec-11e4-830d-df2daeab77ce.png)

I figured out, that using the following selector will work:

``` coffeescript
$('select.selectize-region-cities').selectize()
```

**Comment by mikebronner** [comment]
I have been experiencing this same issue with Bootstrap 3.3 Modals, but on inspecting JS, it was not being called twice. For some reason if I just did `$('#mySelect').selectize()` it didn't work, but `$('select#mySelect').selectize()` did. Thanks for the work-around, been pulling my hair out all day trying to figure out what was going on.

**Comment by brianreavis** [comment]
Nothing should happen if you call selectize on the same element more than once. What version of jQuery  are you guys using? Also, how does the result of `$('#mySelect')` vs `$('select#mySelect')` differ?

**Comment by joallard** [comment]
That's quite a headscratcher. Were you able to solve this?

As we have many issues and not heard back, I'll close this for the time being. If you still need help, please reopen the issue.

**Comment by skeet70** [comment]
I was able to reproduce this issue and solution, but unfortunately my DOM is hairy enough that I can't easily provide a reproduction case...

I'm on jquery 1.7 in this project. Leaving off the `select` seems to then find some of the sub-elements created by the first initialization call as well, where leaving `select` on always just returns the one element.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
