### ISSUE TITLE
Display 'option_create' template after load remote successful returned and the response is empty.

### ISSUE THREAD

**Issue by qiutiaoming** [selectize/selectize.js#628]
![tmp152eebd2](https://cloud.githubusercontent.com/assets/5118099/5163759/476cd148-740a-11e4-9f45-70d18198cc9f.png)

User always duplicate create tag that ready exists. So  I want display 'option_create' template after load remote successful returned and the items is empty.

Someone could give me a hand?
Thx.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
