### ISSUE TITLE
"load" event fires "dropdown_close" event

### ISSUE THREAD

**Issue by corescan** [selectize/selectize.js#630]
I am trying to customize the behavior of my selectize ui so that when a user opens the dropdown, the input is immediately free for typing. This is opposed to when an item is selected, and the input is blocked from typing until the user hits 'delete,' clearing the input.

Code goes like:

```
        user_input[0].selectize.on('dropdown_open', function($dropdown)
        {
            this.clear();
        });
        user_input[0].selectize.on('dropdown_close', function(e)
        {
            if (this.getValue() == '')
            {
                var input = user_input.parent().find('input');
                input.val('');
                user_input[0].selectize.setValue(last_select_user);
            }
        });
```

where last_select_user is saved on "item_add"

This is fine except my select makes an ajax call to load more data, and it seems somewhere in this process that a quick "dropdown_close" and "dropdown_open" are fired, though for a user's purposes, we don't intend the dropdown to close and reopen. Needless to say, this causes some very crappy behavior.

If it were guaranteed that "load" is fired before "dropdown_close" I think I could work around it, but that is not the case.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
