### ISSUE TITLE
unnecessary dropdown opening (IE only)

### ISSUE THREAD

**Issue by andreichuk** [selectize/selectize.js#631]
http://jsfiddle.net/ywvgve01/
Internet explorer only
click on 'popup'. select any value. the dropdown will close. click on any place (except the selectize control). the dropdown will open. this strange behavior occurs every second time

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
