### ISSUE TITLE
Copying a Fields Classes to selectize-control Instead of selectize-input

### ISSUE THREAD

**Issue by sshaw** [selectize/selectize.js#632]
Looks like a form field's classes are copied to `selectize-control`. Not sure what the reasoning is, but when using Bootstrap3 this prevents fields with errors from having a red border. Selectize [does apply its Bootstrap3 styles to `selectize-input`](https://github.com/brianreavis/selectize.js/blob/master/dist/css/selectize.bootstrap3.css#L129).

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
