### ISSUE TITLE
Remove button on single selectize

### ISSUE THREAD

**Issue by lelelic** [selectize/selectize.js#633]
I know there is remove button plugin to manage an item's deletion in case of multiple selects. I think this would be usefull also in case of single select, like in google chrome date input. 

![image](https://cloud.githubusercontent.com/assets/8255666/5249763/2884f676-7986-11e4-9a22-c363b9accf63.png)

**Comment by brianreavis** [comment]
See https://github.com/brianreavis/selectize.js/issues/665#issuecomment-71788599
