### ISSUE TITLE
createFilter only works when searchField = valueField no possibility for id-value

### ISSUE THREAD

**Issue by imfpa** [selectize/selectize.js#634]
Whenever `valueField` is either not set, or set to anything other than `searchField`, `createFilter` will assume `true` and allow the item to be added.

In the following example, if `valueField`is set to `text`everything is fine, and the user will not be allowed to add an already existing value - however I'm not able to get the `id` from my form...

if `valueField`is changed to `id`, the user is able to create duplicates, but I can get the id I need from my form...

``` javascript
var REGEX = '[a-zA-ZæøåÆØÅ][a-zA-ZæøåÆØÅ ]*[a-zA-ZæøåÆØÅ]';

$('#item-type').selectize({
    persist: true,
    valueField: 'text',
    labelField: 'text',
    searchField: ['text'],
    options: [
        {id: '1', text: 'Maleri'},
        {id: '2', text: 'Elektronik'},
    ],    

    createFilter: function(input) {
        var match, regex;

        regex = new RegExp('^' + REGEX + '$', 'i');
        match = input.match(regex);
        if (match) {
        console.log(match[0]);
            return !this.options.hasOwnProperty(match[0]);
        }

        return false;
    },
    create: true
});
```

Isn't there any way to actually search and filter on `text`but keep `option value=""`as `ìd``?

**Comment by brianreavis** [comment]
Is `createFilter` not working for you? If you return `false` from there you shouldn't be able to add the option (duplicate). Is the problem that you can't really look up the option by the input for the check?

> Isn't there any way to actually search and filter on textbut keep option value=""as ìd`?

Yes, but it sounds like you've already tried that?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
