### ISSUE TITLE
IE 10&11: Cannot type in input after scrolling the dropdown list of options

### ISSUE THREAD

**Issue by nem25** [selectize/selectize.js#637]
I have only tried this out in IE 10 and 11, if you go to the demos and look at the Max Items example. When you start typing it will give you a list of options. If you scroll through the list of options and then click on the input to continue typing, it does not type. 

This works fine in Chrome.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
