### ISSUE TITLE
possibility to change order if multiple items are selected

### ISSUE THREAD

**Issue by hidegh** [selectize/selectize.js#641]
requirement: see how it works in select2.js

currently the API and documentation of selectize.js is better.

there are only 2 functionalities in select2.js that a programmer could eventually miss and that's:
- changing order
- possibility to lock some selection (avoid it's removing, eventually avoid to change locked item order or avoid adding new items between)

**Comment by brianreavis** [comment]
Order can be changed by using `setValue()` with an ordered array. As for locking a partial selection, that's not something that's planned to be supported.
