### ISSUE TITLE
possibility to search test (with diacritics) as **starts with**

### ISSUE THREAD

**Issue by hidegh** [selectize/selectize.js#642]
https://github.com/brianreavis/sifter.js/issues/15

searching inside text is cool, but if you have to narrow down the possibilities, sometimes it's necessary to match only items, where item _starts with the search text..._

**also it'd be nice, if only that part of the items would be highlighted** inside the combo.

**Comment by sophiedeziel** [comment]
I'd really need that _starts with_ search, so I give :100: :+1:

**Comment by falkenhawk** [comment]
+1 !

**Comment by davidrevoledo** [comment]
+1 !

**Comment by kashpatel** [comment]
+1

**Comment by RagazziMoscow** [comment]
+1 !

**Comment by RudeySH** [comment]
It looks like sifter v0.6.0 has implemented the option `respect_word_boundaries`, see https://github.com/brianreavis/sifter.js/pull/51. This is effectively the same as a "starts with" search. Now all that's left to do is for someone to add an option to selectize that sets `respect_word_boundaries` to true. For now, you could (temporarily) modify the prototype of selectize like so:

```js
var getSearchOptions = Selectize.prototype.getSearchOptions;
Selectize.prototype.getSearchOptions = function () {
	var options = getSearchOptions.apply(this, arguments);
	options.respect_word_boundaries = true;
	return options;
};
```

This sets `respect_word_boundaries` to true every time selectize calls sifter internally. Alternatively, you could modify the prototype of sifter itself to make `respect_word_boundaries` true.
