### ISSUE TITLE
Android - Chrome 39 Bug

### ISSUE THREAD

**Issue by leesalminen** [selectize/selectize.js#646]
Hello-

I've noticed a bug that can only be reproduced in Chrome 39 on Android. Here is a video of the bug, if it's easier to understand: http://leesalminen.com/selectize.js-bug-12092014.mov

Here are the steps to re-produce:
- Selectize.js is instantiated with no (default) options on a `<select multiple></select>` node.
- User begins typing, say with the letter "P". 
- User selects an option
- User then begins typing the same first letter again "P".
- The first selected option becomes de-selected

Full UA string for affected device: Mozilla/5.0 (Linux; Android 4.4.4; SM-G900V Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.59 Mobile

**Comment by brianreavis** [comment]
Hmm, that's interesting – thanks for the video! Does the same behavior happen on the [demos](http://brianreavis.github.io/selectize.js/) too? I unfortunately don't have a way to replicate this on my end. My best course of action would be to add `console.log` everywhere and see what selectize methods are being called and when (with [remote debugging](https://developer.chrome.com/devtools/docs/remote-debugging)).

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
