### ISSUE TITLE
Allow typing mode in selectize single selects

### ISSUE THREAD

**Issue by luanfonceca** [selectize/selectize.js#647]
Hi folks, today i did some improvement in our UX from our selectizes, and the result of that work was a plugin, following i show a gif with the result, if you guys think that this can be merged into the core plugins I am glad to fork e send a pull-request. o/

http://g.recordit.co/hiG2m6gAbF.gif

**Comment by brianreavis** [comment]
@luanfonceca Definitely pull request! This is something I would be interested in making the default behavior actually. Looks great :+1:

**Comment by stevelacey** [comment]
@luanfonceca if you focus the select when it already has a selection, then blur, I assume it retains the selection? If so, this is great, and totally addresses #610

**Comment by jeepey** [comment]
@luanfonceca I'd really appreciate this functionality as well. Could you do the pull request (or share the code)?

**Comment by alejcas** [comment]
This is great but... it is posible to allow the user to go off editting (go back before start typing) when pressing Escape key?

**Comment by luanfonceca** [comment]
Hey @janscas, sorry but i dont have any clue to make that, because i just followed the default behaviour of the _selectize_, I just went to the demo page and press ESC in a `select` to see if there was a bug in my plugin, but my plugin has the same behave of the selectize... 

So i dont have idea to solve that.
Sorry for that o/

**Comment by dcramble** [comment]
I really like this plugin. However, I noticed when the selectize element is setup for an ajax load type configuration, I ave to click on the select field twice to get the data drop down to appear. When I disable this plugin, the issue goes away.

**Comment by christor** [comment]
Is there something preventing this from being merged? This looks like a very nice plugin to include.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
