### ISSUE TITLE
Allow access to DOM element in render::option

### ISSUE THREAD

**Issue by pbowyer** [selectize/selectize.js#648]
When enhancing a select box with Selectize, it would be very helpful to have access to the element in 

```
render: {
    option: function(item, escape) {
        // Here
    }
}
```

In order to access `data-*` attributes set on the HTML `<option>` tag.

**Comment by brianreavis** [comment]
Hmm, the crux is that not all options will have `<option>`s associated with them (e.g. if the options are created dynamically). I would use the `dataAttr` option ([docs](https://github.com/brianreavis/selectize.js/blob/master/docs/usage.md)) to provide the JSON representation of the option.
