### ISSUE TITLE
data-value escape problem

### ISSUE THREAD

**Issue by antonkulaga** [selectize/selectize.js#651]
I noticed that selectize sometimes breaks html on insertion.
When I have options like `"GeneAge"^^"<http://www.w3.org/2001/XMLSchema#string>` and even if I escape them it inserts them to item as following data-value 

``` html
<div class="selectize-control ui fluid input multi plugin-select_binder">
<div class="selectize-input items not-full has-options has-items"><div data-value=""GeneAge"^^"

<http://www.w3.org/2001/XMLSchema#string>" class="name">
><!--and so on-->
```

that no doubtedly breaks my html, as there are two quoutes there

**Comment by brianreavis** [comment]
Can you post your Selectize settings? When I paste `"GeneAge"^^"<http://www.w3.org/2001/XMLSchema#string>` any of the demos it seems to work fine.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
