### ISSUE TITLE
Caret does not move when click

### ISSUE THREAD

**Issue by comerc** [selectize/selectize.js#656]
I type "12345" then move caret between 1-2 and click to right side of input but caret does not move.

**Comment by brianreavis** [comment]
Good catch. We should be able to fix this by watching for clicks on selectize's wrapper div, and then moving the selection to the end. This isn't too high on my priorities, but I'm open to pull requests for it

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
