### ISSUE TITLE
label "for" attr does not work

### ISSUE THREAD

**Issue by comerc** [selectize/selectize.js#658]
~~http://www.w3schools.com/tags/att_label_for.asp~~
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label (edit j.)

**Comment by comerc** [comment]
[workaround](https://github.com/comerc/meteor-autoform-selectize/blob/master/autoform-selectize-input.js#L64):

``` coffee
  "click .selectized": (event) ->
    $(event.toElement).next().children(":first-child").children("input:first").focus()
```

**Comment by joallard** [comment]
PR merged, stay tuned for release

**Comment by Alex-Sokolov** [comment]
But what if I didn't have an `id` attribute? Maybe I will attach selectize.js by `class` for elements without `id`

**Comment by joallard** [comment]
I don't get it, seems to me like your input _needs_ an id to give that to `label[for]`

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

**Comment by Alex-Sokolov** [comment]
Oh, my fault. Sorry
