### ISSUE TITLE
Move "Add..." text to options

### ISSUE THREAD

**Issue by dvisockas** [selectize/selectize.js#660]
Yo, I used selectize on few of my projects and all of the times I had to change "Add.." text. Do you guys think that text should be a in options with "Add" as default?

**Comment by taruvar** [comment]
On adding a new field, before being redirected to a new page, it shows "undefined" in the selectize field. Been trying to remove that.

**Comment by enoshixi** [comment]
I think the render > option_create option covers that https://github.com/brianreavis/selectize.js/blob/master/docs/usage.md#rendering
