### ISSUE TITLE
remove_button for single-option selectize

### ISSUE THREAD

**Issue by TachikomaGT** [selectize/selectize.js#665]
Hello! 
I want to have single-option selectize with ability to clear selected element. It seems remove_button plugin must be fine for it, but in the start of plugin there are next line:

```
if (this.settings.mode === 'single') return;
```

If I comment this line, plugin still not working with maxItems 1, only settings mode multi are supported, so I added  

```
plugins: ['remove_button'],
maxItems: 1,
mode: 'multi'
```

lines in selectize initialization settings and now everything works well.

Which troubles I can get with this code, should mode option be undocumented in usage.md and is this is are the best way to make remove_button plugin work together with maxItems 1?

**Comment by brianreavis** [comment]
Yeah, I think this is mostly a styling task which hasn't been done yet. I'm open to pull requests on this.

**Comment by zoltan-sule** [comment]
@brianreavis 
There is still no remove button for single select fields. I am maybe wrong, but the changes above are not in the current master branch (v0.15.2).
https://github.com/selectize/selectize.js/blob/master/src/plugins/remove_button/plugin.js

Could you reopen this, please?

Here are the changes made by @Pictor13 that worked for me
https://github.com/selectize/selectize.js/pull/1311/commits
