### ISSUE TITLE
removeOptionGroup or clearOptionGroups method?

### ISSUE THREAD

**Issue by DarkMarmot** [selectize/selectize.js#669]
In order to work with a selection whose groups can dynamically change, one or both of these methods would be great to have. Currently, I am destroying and rebuilding the control to clear the groups....

Thanks, this is great utility!

**Comment by brianreavis** [comment]
This is now a part of [0.12.0](https://github.com/brianreavis/selectize.js/releases/tag/v0.12.0) (just released)
