### ISSUE TITLE
ID of select element

### ISSUE THREAD

**Issue by Redani** [selectize/selectize.js#676]
Hi,
First, thanks for your lovely work and plugin ;)

My question is very simple but can't find an answer :/
I'd like to get the ID of the < select > element. Ex. < select id="my-id" class="selectize" >, how can I get "my-id"??

or also how can I get a data-attr of the selected option ?

Thanks for you help

**Comment by atheleron** [comment]
I struggle with that to i want to make dynamic selectize so when i click on select i get id and i get ajax url based on that select id so i can load multiple options from database to random select elements like countries cities etc..

so is there a way to get ID from select input that was replaced by selectize ??

**Comment by farturi** [comment]
Hi, any answer? I'm also looking for the same information... 
thank you very much.

**Comment by hardy2defy** [comment]
looking for this as well :(

**Comment by yancoupro** [comment]
You can access using the jquery object using $input property. 

For example in onChange 
`this.$input.attr('id')`
or if you have a selectize object in variable

```
var slz = $('#initial-select')[0].selectize;
slz.$input.attr('id');
```

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
