### ISSUE TITLE
Do something onFocus

### ISSUE THREAD

**Issue by super-cache-money** [selectize/selectize.js#677]
This is probably a really stupid question but:

How do I do something onFocus?

I've tried:
        `$selectizeInput.on('focus', doSomething)`;
Also, I tried adding an `onfocus` property to the corresponding `<select>` tag:
         `<select onfocus="doSomething">`

None of this worked. How do I get it working?

**Comment by brianreavis** [comment]
This is going to be part of the 0.12 release. See https://github.com/brianreavis/selectize.js/pull/185
