### ISSUE TITLE
"No Options" on iPad

### ISSUE THREAD

**Issue by yankeeinlondon** [selectize/selectize.js#678]
I have an HTML app which uses selectize and it works entirely as expected on the OSX desktop but then I load the same app with my iPad the whole screen greys out slightly and I get the following dialog:

![2015-01-20_13-15-04_03](https://cloud.githubusercontent.com/assets/980757/5817687/5d85c1f6-a0a6-11e4-8da8-779df173eaa9.png)

Clicking outside the message bubble dismisses the dialog and then the selectize box operates as expected. Bizarre. I have no idea why this could be happening but it is definitely selectize which is creating the situation. 

My suspicion is that it has to due with asynchronous binding of the options array. I am using selectize within an Ember environment (I use the ember-cli-selectize addon if you're familiar). Now based on what I just said you might think I should add the issue there and possibly you are right but the reason I have opted to do it here is because of the visual nature of the defect which the ember wrapper has nothing to do with.

**Comment by brianreavis** [comment]
I just pulled up the demos with an iPad simulator and couldn't reproduce this. Does this happen to you on the standard [demos](http://brianreavis.github.io/selectize.js/) too? What version of mobile safari is it? Would it be possible to make a jsfiddle of this?

**Comment by yankeeinlondon** [comment]
I find this to happen on both Safari and Chrome on IOS (latest versions). Let me check on the demos and I'll aim to get something up to demonstrate this later today.

**Comment by yankeeinlondon** [comment]
I'm now pretty certain that my lack of understanding of how you used the `load()` call was creating this problem. I'm going to close this as I think I'll be able to crack this tomorrow now that I see how you're doing it.
