### ISSUE TITLE
Question: select an option when is the only one

### ISSUE THREAD

**Issue by RicardoRamirezR** [selectize/selectize.js#689]
Hi,

Having two related selects, say actors -> movies, when I select one actor that has only one movie, how to set the movie so the user not need to view the list of movies only to discover that there is only one and it needs to be selected.

Sure it need to be done in onChange, but can't figure out how...

Hope this make sense.

**Comment by brianreavis** [comment]
Use `setValue(value)` – https://github.com/brianreavis/selectize.js/blob/master/docs/api.md
