### ISSUE TITLE
Selectize release 0.11.2 does not have latest code

### ISSUE THREAD

**Issue by NielsZeilemaker** [selectize/selectize.js#695]
I wanted to use the silent=true argument while setting the value of a selectize.
But the argument seems to be missing from the 0.11.2 release.

Am I doing something wrong, or did something get messed up during packaging?

**Comment by brianreavis** [comment]
That hasn't been released yet – it's going out in the next day or two

**Comment by NielsZeilemaker** [comment]
Sorry about that, I thought the silent=true was merged in july, but now I see it's only been merged 2 days ago #519.
