### ISSUE TITLE
Remove buttons for the drop-down list options

### ISSUE THREAD

**Issue by andreie** [selectize/selectize.js#696]
How can I bind event handler for the delete buttons?
![selectize](https://cloud.githubusercontent.com/assets/10756168/5956650/ab104dce-a7b8-11e4-9c85-d2d11b6afb9e.png)
(It should be possible to remove option element whihout closing dropdown list.)

Thank you

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
