### ISSUE TITLE
Plz, update dist folder with src folder...

### ISSUE THREAD

**Issue by trashMeNow** [selectize/selectize.js#697]
Like in Object,
plz,
update distr folder, last commit was 4 month ago,
with src folder, last commit 10hours ago.

many thanks for your work!!!

**Comment by cgs** [comment]
+1. I'm getting Grunt errors trying to build the latest.

Edit: got it to build with 

```
rm -rf node_modules/
npm cache clean
```

Edit 2: Getting this after building, with both standalone and non-standalone versions:

```
Uncaught TypeError: Cannot read property 'mixin' of undefined
```

**Comment by brianreavis** [comment]
https://github.com/brianreavis/selectize.js/issues/695
