### ISSUE TITLE
Display text in <option> elements is double escaped.

### ISSUE THREAD

**Issue by danielsokolowski** [selectize/selectize.js#70]
There appears to be a bug where `<option>text</option>;` is double escaped. For example plain `<option value="4">#P000000004: Frozen > Strawberries > Whole</option>` after we apply selective is rendered as `<div data-value="4" data-selectable="" class="option selected">#P000000004: Frozen &amp;gt; Strawberries &amp;gt; Whole</div>`; the `&` is escaped again as `&amp;`. 

![selectize js-html-entities-double-escaped-bug](https://f.cloud.github.com/assets/273413/949358/8ee379dc-037c-11e3-9801-46247ed4ff27.JPG)

**Comment by geoffreyvanwyk** [comment]
This is still a problem in the latest version: v0.12.4.
