### ISSUE TITLE
hideInput make the page scroll horizontally

### ISSUE THREAD

**Issue by cvillemure** [selectize/selectize.js#705]
We're using a selectize control in a scrollable form (a enhanced grid).

The problem is that when a value is selected in selectize and the dropdow opens, the method "hideInput" push the input element at -10000 to the left, which make my grid scroll.

I hotfixed my build by playing with z-index instead.

Any objections?  Any hint of what kind of bug I should look at?  
Why do you need to hide the input in the first place?

**Comment by cvillemure** [comment]
Related to #743

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
