### ISSUE TITLE
value 0 ignored in select

### ISSUE THREAD

**Issue by msvendsen** [selectize/selectize.js#706]
Hi,

I've observed an issue in the new version 0.12.0.
I'm pre-filling some <select> from DB. One field with value 0, but the item with value 0 is ignored. It doesn't show up in the select.

It worked in 0.11.0

Is this a bug or a "feature"? :)

**Comment by sandstrom** [comment]
A wild guess is that something like `if (value) { ... }` is used somewhere (`0` is falsy in JS).

A failing test-case reproducing this issue would be a good start. Perhaps you can put together one?

**Comment by thekrotek** [comment]
I confirm this issue. I have empty value (placeholder) and another option with 0 value. Placeholder is displayed, zero value - not.

**Comment by Aljullu** [comment]
A workaround for that is to convert the '0' to a string.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
