### ISSUE TITLE
Allow option to be selected multiple times and multiple plugins

### ISSUE THREAD

**Issue by c143** [selectize/selectize.js#711]
Hey
After you select an option it disappears in the list. For example in "Tagging". But I want to list display resolutions for multiple screens and a user could have 2 screens with the same resolution. So it shouldn't disappear in the list.

And my second question is: Can you select multiple plugins? I want:

['optgroup_columns']
['remove_button']
['restore_on_backspace']
['drag_drop']

at once. That would be perfect.

Greetings

**Comment by simi** [comment]
@c143 to select multiple plugins use Array like `['optgroup_columns', 'remove_button']`.

**Comment by c143** [comment]
@simi Thanks!

**Comment by romanlex** [comment]
If use plugin dropdown_header with params and another plugins without params?
Made himself

``` javascript
plugins: {
    'restore_on_backspace' : {},
    'dropdown_footer': {
        title: 'Вы можете выбрать уже существущий повод и отредактировать его или добавить новый повод просто указав название'
    }
}
```

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
