### ISSUE TITLE
Installing Selectize via NPM pulls in a cli version of sifter

### ISSUE THREAD

**Issue by lukemcgregor** [selectize/selectize.js#712]
When I install selectize via NPM it grabs the sifter CLI not the browser version. Given selectize is a browser control (uses jQuery ect) this is a bit weird.

It also means that a bunch of node only dependencies such as microtime are also installed.

**Comment by brianreavis** [comment]
If using selectize from NPM it's assumed you're using some commonjs bundler (webpack, browserify, etc) which will omit the CLI script. Also, when installed with `--production` the dev dependencies like `microtime` won't be installed.

**Comment by lukemcgregor** [comment]
I'm using browserify and a grunt task to install npm packages which uses the --production flag. I have also tried manually running `npm install --production`.

It doesn't look like the dependencies such as microtime are devDependancies in sifter (https://github.com/brianreavis/sifter.js/blob/master/package.json).

**Comment by brianreavis** [comment]
Ah, you're right... I spoke too quickly, I thought those were part of the benchmark not the CLI. Regardless, does it matter? browserify is not going to pick them up. If you really don't want them, use bower – there can't be the best of both worlds unless two different versions of sifter are published to NPM, which is going to create even more confusion and be more to maintain without much reward

**Comment by lukemcgregor** [comment]
The issue is more that NPM explodes on windows trying to install microtime so it doesn't even get to the browserify step to be ignored. 

I could install selectize via bower but browserify and bower are not best buddies, you basically need to shim components from bower I think.

**Comment by lukemcgregor** [comment]
microtime was erroring in NPM which meant that it never gets to the browserify step. I eventually got it installing but had to install python on windows which was pretty painful.

**Comment by gionkunz** [comment]
This PR will solve it making microtime an optional dependency in sifter brianreavis/sifter.js#28
