### ISSUE TITLE
Selectize not showing over content within JQuery ui dialog

### ISSUE THREAD

**Issue by andreatevoi** [selectize/selectize.js#716]
Hi,

I'm looking at https://github.com/brianreavis/selectize.js/issues/55 and I have a similar problem with JQuery ui dialog when the drop down list overflows the dialog. In this case the dialog displays a scrollbar but the usability becomes very poor.
I've tried using dropdownParent: 'body' in order to achieve the same result as in https://github.com/brianreavis/selectize.js/issues/55 but with this option the drop down list appears behind the dialog.
Is there any way to make it appear over the dialog?

Regards,
Andrea

**Comment by brianreavis** [comment]
Have you tried setting the `z-index` of `.selectize-dropdown` to something higher?

**Comment by andreatevoi** [comment]
Just tried. Thanks Brian, it's working fine now.
