### ISSUE TITLE
Loading indicator?

### ISSUE THREAD

**Issue by ghost** [selectize/selectize.js#718]
Does selectize.js support a loading indicator when retrieving data from remote sources with .load?

**Comment by dl78git** [comment]
Im also very interested in this indicator, especially if you paste a long list, selectize appears to "freeze" until the paste is processed.

**Comment by sandstrom** [comment]
The example `Remote Source — Rotten Tomatoes` shows a loading indicator.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
