### ISSUE TITLE
The Turkish I Problem

### ISSUE THREAD

**Issue by ecehanece** [selectize/selectize.js#719]
Hello there,

First, this is great work :+1: And I'm using selectize in my project. But when I try to search in select box with the Türkish letter " İ " it's not working.

For example; I have a city named İzmir. And when i try to search with the letters "i", "ı", or "I" it's fine. But with "İ" it's not working.

And I have changed the var DIACRITICS variable in selectize.js to this for İ .  [i, ı, I, İ] : [iÌÍÎÏìíîïIİı]

But that isn't working. Is there a solution?

By the way, for the other letters like ö, ü, ş, ç or ğ it's working. Just for İ it's not working.

**Comment by sandstrom** [comment]
I think it's better to file this in https://github.com/brianreavis/sifter.js, since that's the library that handles this. Also, a test-case reproducing the issue are a good start. That way it's easier for others to help out.

I'd suggest closing this issue and reopening within Sifter along with a failing test.

**Comment by hakdogan** [comment]
Hi.

I have that same problem. Any solution?

**Comment by ceremcem** [comment]
Quick and dirty workaround: Sifter has [`asciifold()`](https://github.com/brianreavis/sifter.js/blob/master/sifter.js#L471) function. This function can be used to replace the search string in the first place, then passed to the `sifter.search`, like "`sifter.search(asciifold(mysearchtext), ...)`". This solves the problem.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
