### ISSUE TITLE
SASS Support?

### ISSUE THREAD

**Issue by liorocks** [selectize/selectize.js#725]
Hi,

it would be nice to have a SASS support too, rather than only LESS. 

I would send a pull request, but there are too much requests sent already and I can't see if you merge any of those.

**Comment by julianxhokaxhiu** [comment]
+1

**Comment by Untit1ed** [comment]
+1

**Comment by Xethron** [comment]
+1

**Comment by kevinglover** [comment]
+1

**Comment by Tocacar** [comment]
+1

**Comment by ronaldsuwandi** [comment]
+1

**Comment by isGabe** [comment]
+1

![](http://stream1.gifsoup.com/view3/4658686/doesn-t-matter-not-sass-o.gif)

**Comment by mikemaccana** [comment]
There's https://github.com/herschel666/selectize-scss which is pretty recent. Also if you want this you should check out https://github.com/brianreavis/selectize.js/issues/752 and volunteer to help maintain.

**Comment by liorocks** [comment]
@mikemaccana 
URL is incorrect, https://github.com/herschel666/selectize-scss .

**Comment by mikemaccana** [comment]
@Landish Yup just fixed it.

**Comment by Untit1ed** [comment]
It's still not the same as an official SASS support. 
@brianreavis can you comment on this please?

**Comment by mikemaccana** [comment]
@Untit1ed Actually it is: you can volunteer to help maintain, then make a PR and merge it.

**Comment by brianreavis** [comment]
What @mikemaccana said, hah. I'd love to see SASS support but don't have time to do it myself. Thankfully SASS/LESS are practically identical (don't shoot) for something like this... I imagine it'd be a relatively straightforward job to translate.

**Comment by liorocks** [comment]
@brianreavis 

> I would send a pull request, but there are too much requests sent already and I can't see if you merge any of those.

**Comment by brianreavis** [comment]
@Landish Sorry for not clarifying earlier – I've been in over my head. PR's are welcome. I merge the ones that are tested, solid, and don't have unforseen consequences. But again, I'm looking for maintainers.

**Comment by joallard** [comment]
I'm a huge Sass fan myself (even the actual Sass syntax), but what would be the advantages of changing the Less that's already there?

**Comment by karolyi** [comment]
+1
