### ISSUE TITLE
optgroup_column: Uncaught TypeError: Cannot read property '$order' of undefined

### ISSUE THREAD

**Issue by gor181** [selectize/selectize.js#729]
Using configuration with enabled optgroup_column plugin and create set to true.
Custom typed option is being added without issues, however when deleting the following error arises:

**Uncaught TypeError: Cannot read property '$order' of undefined**

Affected code:
![screenshot from 2015-03-04 10 33 27](https://cloud.githubusercontent.com/assets/8964589/6481020/ef7d2386-c259-11e4-892c-14c26681cf59.png)

Configuration:

```
{
  "create": true,
  "options": [
    {
      "id": "783006",
      "text": "Pickme1",
      "type": "TEST1",
      "$order": 1
    },
    {
      "id": "911004",
      "text": "Pickme2",
      "type": "TEST2",
      "$order": 2
    },
    {
      "id": "1911005",
      "text": "Pickme3",
      "type": "TEST3",
      "$order": 3
    },
  ],
  "optgroups": [
    {
      "$order": 1,
      "id": "TEST1",
      "name": "TEST1"
    },
    {
      "$order": 2,
      "id": "TEST2",
      "name": "TEST2"
    },
    {
      "$order": 3,
      "id": "TEST3",
      "name": "TEST3"
    }
  ],
  "labelField": "text",
  "valueField": "id",
  "optgroupField": "type",
  "optgroupLabelField": "name",
  "optgroupValueField": "id",
  "lockOptgroupOrder": true,
  "searchField": [
    "text"
  ],
  "plugins": [
    "optgroup_columns"
  ],
  "openOnFocus": true,
  "maxItems": null
}
```

P.S - Error is avoided when setting lockOptgroupOrder to false, but then you may loose the group ordering

**Comment by joallard** [comment]
Thanks for reporting this issue. I am closing it since the issue has been inactive for more than a year. If there is still a problem with the latest version, please re-open. If you haven't done so, read the [Issue reporting guide](https://github.com/selectize/selectize.js/wiki/Reporting-issues-guide) and make sure your original post follows the guide.

**Comment by vppetrov** [comment]
This problem still exists today (version 0.12.6) when an object is added that has no valid group value. The code that fails is:

```
// sort optgroups
if (this.settings.lockOptgroupOrder) {
	groups_order.sort(function(a, b) {
		var a_order = self.optgroups[a].$order || 0;
		var b_order = self.optgroups[b].$order || 0;
		return a_order - b_order;
	});
}
```

And the solution is quite easy:

```
// sort optgroups
if (this.settings.lockOptgroupOrder) {
	groups_order.sort(function(a, b) {
		var a_order = (self.optgroups[a] ? self.optgroups[a].$order : 0) || 0;
		var b_order = (self.optgroups[b] ? self.optgroups[b].$order : 0) || 0;
		return a_order - b_order;
	});
}
```
