### ISSUE TITLE
Enhancement: Multi Select

### ISSUE THREAD

**Issue by landwire** [selectize/selectize.js#736]
It would be nice to have a visual clickable multiselect option with selectize - rather than having to press a keyboard button to select more than one. A bit like those 2 plugins:

http://silviomoreto.github.io/bootstrap-select/     ---> 3rd example down
http://hemantnegi.github.io/jquery.sumoselect/sumoselect_demo.html

 Or does selectize support this functionality already? Maybe it's worth adding a multiselect example to the example page.

**Comment by landwire** [comment]
Ok, I made a fiddle and the above is easy enough to do with a bit of CSS. Well at least the first bit of adding a check or highlighting the items in the dropdown. What does not work though is deselecting items on click of the option in the dropdown.

Could that be built in as an option that can be set? Like "deselectOnClick" or similar? Would actually be nice to enable that on the already chosen items shown above the dropdown too, so that if you click them they get deselected.

**Comment by alexkn** [comment]
I have implemented a similar feature in https://github.com/brianreavis/selectize.js/pull/603

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
