### ISSUE TITLE
Clear and make selectize not focusable

### ISSUE THREAD

**Issue by Linuus** [selectize/selectize.js#738]
Hi!

I have a scenario where I need to clear a few selectize fields and then lock the fields. I implemented this first using `foobar[0].selectize.clear();` followed by `foobar[0].selectize.disable()`.

However I notices that running `disable()` disables the original input as well which means that the cleared fields are not sent when submitting the form, i.e. they are not cleared. So, I changed to using `lock()` instead of `disable()`. The problem I have with this is that the field still looks normal and it is focusable. 

The looks is fixed by some CSS but can I prevent the field from being focusable? It would make the user experience a bit better.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
