### ISSUE TITLE
Pasted text triggers the create function immediately

### ISSUE THREAD

**Issue by jeffblake** [selectize/selectize.js#740]
Expected behavior would be to load the results first and let you click to choose a match before going straight to create.

**Comment by PhiLhoSoft** [comment]
I can reproduce this in Chrome and Firefox.

**Comment by PhiLhoSoft** [comment]
And I found the "problem" while browsing the code...
Actually, this is triggered by the `splitOn` option, which, when defined / non null, is used to split the pasted text. Ie. if you paste a list of tags separated by a given delimiter, it will automatically create all the tags.
Funnily, `splitOn` defaults to null... But looking further in the code, we see that if so, if the `delimiter` property is set, `splitOn` is generated from it...
And `delimiter` defaults to a comma.
So, the solution is to set `delimiter` to `null` or `undefined`.

Now, a possible improvement of current behavior could be to not create a tag if the delimiter isn't found in the pasted string...

**Comment by seawatts** [comment]
I'm also running into this. However, I believe the expected functionality shouldn't be to always create. What happens if you have the item already in the list. It should choose that item first before trying to create it.

**Comment by mtownsen** [comment]
I agree with the above.  It is strange behavior to have a search field trigger a create on paste.

**Comment by gambala** [comment]
Thank you @PhiLhoSoft, your hack with `delimiter: null` helps me :pray:

**Comment by 0asa** [comment]
Thank you @PhiLhoSoft! You made my day!

**Comment by joallard** [comment]
Fixed on STR:
1. Go to basic example
2. Outside of Selectize, copy `foo`
3. Focus input, paste
4. => Item is not created
5. Outside, copy `foo,bar`
6. Focus, paste
7. => Items are created
