### ISSUE TITLE
Problems... selecting, in dropdowns.

### ISSUE THREAD

**Issue by nkoren** [selectize/selectize.js#742]
Generally loving Selectize, but having some subtle-yet-important UX problems with its core functionality. Specifically, the auto-suggestion is too sensitive to some things yet too insensitive to others, and I can't find any way to override its behaviour.

What I want to do is the following:
- When the user types, the top-scoring option is highlighted.
- If they hit tab/enter or click on that option, that option is selected.
- If the top-scoring option is not an exact match to what they've typed, they can click on "Add [what they've typed]..." or arrow down to that and hit tab/enter.
- Simply mousing over the dropdown should have no effect upon its selection-state.

Instead, I'm getting the following:
1. The suggested option is too sticky, and remains suggested even if a higher-scoring option is available. For example, I have a list of options which includes "global trade" and "global warming". If the user starts typing "global", then "global trade" will be the top-scoring item and will be auto-suggested. So far so good. But if the user continues typing "global warming", then "global trade" will remain the suggested option, even though "global warming" is now the top-scoring item. If the user then hits enter/tab, they will select "global trade" despite having just typed an exact match to one of the other options. _This is critically broken functionality!_ How can I fix it?
2. If the user mouses over the dropdown list, then whatever options they've moused over will become the suggested option. This shouldn't happen: I'm seeing users tying something, see that it matches the top option, then accidentally brushing the trackpad before hitting tab/enter. In the process, they mouseover the dropdown and select another item. This leaves them very confused.

Any help will be much appreciated!

**Comment by nkoren** [comment]
The options I'm using, FWIW:

``` text/javascript
{
  plugins: ['continue_editing'], // See selectize issue #181
  openOnFocus: false,
  create: true,
  createOnBlur: true,
  createFilter: canCreate,
  openOnFocus: false,
  maxOptions: 20,
  persist: false,
  highlight: false,
  options: factors,
  valueField: '_id',
  searchField: 'title',
  labelField: 'title',
  sortField: {
    field: '$score',
    direction: 'desc'
  },
  searchConjunction: 'or',
  selectOnTab: true,
  onType: charactersLeft,
  closeAfterSelect: true
}
```

**Comment by nkoren** [comment]
_Bump_. Don't mean to be rude, but problem no. 1, above, is really critically breaking Selectize. It should not be possible for the user to type an exact match to one of your options, hit enter, and have it select _another_ option. Has anybody else encountered this, and can you advise on how to fix it?

**Comment by gabsoftware** [comment]
I'm with nkoren on this. I also think mouse-hovering the list should not influence which option will be selected.

I also would prefer that the first option in the dropdown list is selected by default so that on hitting Enter key, it takes the first option.

**Comment by gabsoftware** [comment]
I managed to fix it.

Here's my fix:

``` javascript
@@ -1079,7 +1079,7 @@
                        isCtrlDown       : false,
                        ignoreFocus      : false,
                        ignoreBlur       : false,
-                       ignoreHover      : false,
+                       ignoreHover      : true,
                        hasOptions       : false,
                        currentResults   : null,
                        lastValue        : '',
@@ -1255,7 +1255,7 @@
                                }
                        });
                        $window.on('mousemove' + eventNS, function() {
-                               self.ignoreHover = false;
+                               //self.ignoreHover = false;
                        });

                        // store original children and tab index so that they can be
@@ -2109,11 +2109,11 @@
                        if (self.hasOptions) {
                                if (results.items.length > 0) {
                                        $active_before = active_before && self.getOption(active_before);
-                                       if ($active_before && $active_before.length) {
-                                               $active = $active_before;
-                                       } else if (self.settings.mode === 'single' && self.items.length) {
+                                       //if ($active_before && $active_before.length) {
+                                       //      $active = $active_before;
+                                       //} else if (self.settings.mode === 'single' && self.items.length) {
                                                $active = self.getOption(self.items[0]);
-                                       }
+                                       //}
                                        if (!$active || !$active.length) {
                                                if ($create && !self.settings.addPrecedence) {
                                                        $active = self.getAdjacentOption($create, 1);
```

**Comment by gabsoftware** [comment]
I should add that this fix is for the standalone version of Selectize.

**Comment by gabsoftware** [comment]
I improved my fix and made two new settings.
The default behavior of Selectize is not modified.
See pull request #770

**Comment by joallard** [comment]
Trying this very quickly on http://selectize.github.io/selectize.js/ Single Item Select:
1. Click the select, type 'c'
2. "Chuck Testa" is now the first ranked option
3. Mouse over "Sage"
4. => Selection is unchanged
5. Type 'a', input now says 'ca'
6. "Sage Ca..." is now the first option
7. Press Enter, Sage is selected

Hence I couldn't quickly reproduce your scenarios. If they're still an issue, would you please: either make a minimal demo on JsFiddle/Codepen, or demonstrate using an online demo like I did; provide steps to reproduce and expected/actual. For more info, please consult the Issue reporting guide on the wiki. Please also keep one issue per issue you're trying to report.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
