### ISSUE TITLE
Bootstrap 3 jumping input height when clicking on items

### ISSUE THREAD

**Issue by lserman** [selectize/selectize.js#743]
Here's a quick gif I made of the behavior

https://gfycat.com/AdorableUnkemptGermanpinscher

When I click on one of the items, it is highlighted blue and the input box height collapses. It doesn't return to it's original height until clicking inside the input again (but not on one of the items). Also, the remove_button plugin acts a little wonky because I have to click the item first, then click again on the X button.

I think this is due to the `.selectize-input input[type=text]` element receiving absolute positioning and left: -10000 whenever an item is clicked. Is there anyway to disable this behavior?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
