### ISSUE TITLE
allowEmptyOption regression in 0.12 ?

### ISSUE THREAD

**Issue by y0hnn** [selectize/selectize.js#749]
Hi,

In the version before 0.12, allowEmptyOption was working this way : the empty option - aka the placeholder - was inserted in the dropdown as an option of the select.
Now, it is inserted as a placeholder on the input. Seems great, but... if we set a display none property on the input to disable it, we can't see the placeholder anymore... It seems to be a big regression !

Any thoughts on this ?

**Comment by thekrotek** [comment]
Yes, a very strange behavior. You set this option to true and placeholder (empty option) simply removed.

**Comment by dext0r** [comment]
Hi,
I've found a fast and dirty hack.
In function registerOption replace 
`if (!key || this.options.hasOwnProperty(key)) return false;`
to
`if ((!key || this.options.hasOwnProperty(key)) && !this.settings.allowEmptyOption) return false;`
It seems working for me.

**Comment by gucki** [comment]
:+1:  for the fix

**Comment by viceversus** [comment]
:+1: for the fix

**Comment by cinic** [comment]
@whather :+1:

**Comment by joallard** [comment]
Duping #739
