### ISSUE TITLE
createItem() has incorrect comments and incorrect documentation

### ISSUE THREAD

**Issue by Sevin777** [selectize/selectize.js#751]
first, the [createItem function](https://github.com/brianreavis/selectize.js/blob/master/src/selectize.js#L1526) has invalid comments which suggest that there is a parameter for `callback`, which there is not: 

``` javascript
    /**
     * Invokes the `create` method provided in the
     * selectize options that should provide the data
     * for the new item, given the user input.
     *
     * Once this completes, it will be added
     * to the item list.
     *
     * @param {string} value
     * @param {boolean} [triggerDropdown]
     * @param {function} [callback]
     * @return {boolean}
     */
    createItem: function(input, triggerDropdown) {
```

second, the [documentation](https://github.com/brianreavis/selectize.js/blob/master/docs/api.md) indicates the second parameter is `callback`, when it should be `triggerDropdown`: 

``` markdown
createItem(value, callback)
```

**Comment by brianreavis** [comment]
https://github.com/brianreavis/selectize.js/blob/master/src/selectize.js#L1534-L1535

valid: `createItem(value, callback)`
also valid: `createItem(value, triggerDropdown, callback)`

If you want to add `triggerDropdown` (rare usage), open a pull request.

**Comment by Sevin777** [comment]
My mistake. Thanks for clarifying
