### ISSUE TITLE
Sortable Plugin Issue

### ISSUE THREAD

**Issue by Sevin777** [selectize/selectize.js#753]
https://github.com/brianreavis/selectize.js/blob/master/src/plugins/drag_drop/plugin.js#l25

This code doesn't work with current jQuery version: `sortable = self.$control.data('sortable');` (line 25 and line 32)

See http://stackoverflow.com/questions/11599758/how-to-check-if-list-is-sortable

**Comment by mabasic** [comment]
Had to use jquery-ui version `1.10.5` to get it working.

**Comment by joallard** [comment]
@mabasic Can you tell whether this confirms or solves the issue?

**Comment by mabasic** [comment]
@joallard This confirms the issue. I don't think that using a lower version of `jquery-ui` should be considered as a solution to this issue, but rather fixing the code to work with the newer version of `jquery-ui`.

**Comment by joallard** [comment]
Got it, I agree. Can someone either provide STR or send a quick PR?

**Comment by dmytro-y-dev** [comment]
It works nicely for me with jquery-ui 1.12.1

**Comment by mabasic** [comment]
This can probably be closed now.
