### ISSUE TITLE
[Question] Deleting current input onType when max option is one

### ISSUE THREAD

**Issue by c143** [selectize/selectize.js#763]
Hey
I edited the email selectesize dropdown to this: http://c143.lima-city.de/essen/scripts/select/
Since the max options are 1 I'd like to delete the current input when typing something. At the moment you'd have to press backspace.

As you can see in my source code i tried it with:

```
onType: function(str){
    alert(str);
}
```

But i don't get any output.

Can anyone help me?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
