### ISSUE TITLE
Silent setValue() not silent

### ISSUE THREAD

**Issue by super-cache-money** [selectize/selectize.js#764]
When calling `setValue` with the silent flag set to `true`, instead of not firing an event at all, the `onChange(param)` listener is called with `''` as `param`. 

For example,

```
selectizeControl.setValue('5', true);
```

fires `onChange('')`.

What's going on here, and how would I fix this?

**Comment by brianreavis** [comment]
Try out [0.12.1](https://github.com/brianreavis/selectize.js/releases/tag/v0.12.1)

**Comment by super-cache-money** [comment]
Nailed it :D
