### ISSUE TITLE
Removing item with create:false and persist :false

### ISSUE THREAD

**Issue by mguimard** [selectize/selectize.js#765]
When removing an item with create = false and persist = false, the item doesn't get back in the option list. The doc is confusing about this point, it talks only about items created by the user.

The test made at https://github.com/brianreavis/selectize.js/blob/master/src/selectize.js#L1500 should integrate the create option IMO. Something like this maybe ?

```
if (self.settings.create && !self.settings.persist && self.userOptions.hasOwnProperty(value)) {
    self.removeOption(value, silent);
} 
```

**Comment by PhiLhoSoft** [comment]
I cannot reproduce the problem in the Plunker http://plnkr.co/edit/S3HjP1?p=preview

Maybe you added the options with `addOption()`? That's a problem I reported on the angular-selectize wrapper, which always uses this API to add the options, even the initial ones.
If you want persistent options not added at config time, use `registerOption()` instead (doesn't accept an array, though). That's what Selectize itself does when adding config's options.

`addOption()` marks the data as userOptions, while `registerOption()` doesn't.

**Comment by ghost** [comment]
Thank you!

Maybe this should go into the docs? I don't see a `registerOption()` method documented at all, much less the fact that options added with `addOption()` are not persistent.

**Comment by Pictor13** [comment]
Yes, good point, it should be added (TODO).
I also didn't know this relevant difference between _options_ and _userOptions_.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
