### ISSUE TITLE
How to close dropdown on input onfocus after selections are made.

### ISSUE THREAD

**Issue by shivika** [selectize/selectize.js#767]
Is it possible to have the dropdown close by clicking in the input after selections are made vs. having to click outside the input. 

Thanks!

**Comment by alexbowers** [comment]
if you use closeAfterSelect: true as an option, it does this.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
