### ISSUE TITLE
How to limit the number of selected options in input field

### ISSUE THREAD

**Issue by shivika** [selectize/selectize.js#768]
Is there a way to specify the number of selected options you want see in the input and after that number is reached show something like  "5 selected". 

Thanks!

**Comment by brianreavis** [comment]
Please check the [documentation](https://github.com/brianreavis/selectize.js/blob/master/docs/usage.md) (particularly `maxItems`).

**Comment by shivika** [comment]
Hi - maxItems and maxOptions only effect the items in the dropdown - I'm looking for a way to limit the number of items in the INPUT itself after selections are made so you don't see 12 items in the input but instead would see "12 items selected"...I don't see any options for this in the documentation but was hoping there was maybe a workaround out there

**Comment by MarkusBerroth** [comment]
Hey, I found this question, because I have the same problem within an R Shiny Dashboard. 
It was closed without giving an answer. However it was closed some time ago. 
Is there a good solution meanwhile? 

Thank you in advance!

**Comment by daniilshevelev** [comment]
Hi. How was this issue/request resolved?
I am looking for the same - to limit the number of selected items in an input box.

**Comment by javierdiegof** [comment]
Same thing here (actually trying to use it also on a Shiny dashboard too). When the number of selected elements becomes too large and the page starts to fill up this feature would certainly be very useful.

**Comment by RyanHopkins7** [comment]
maxItems limits the number of options allowed to be selected [rather than number of options in the dropdown] properly for me. 
[https://selectize.github.io/selectize.js/#demo-max-items](https://selectize.github.io/selectize.js/#demo-max-items)

**Comment by morzechowski99** [comment]
I wrote a simple plugin to limit options in input. 
[https://github.com/morzechowski99/Selectize.js-limit-tags-plugin](url)

**Comment by risadams** [comment]
> I wrote a simple plugin to limit options in input. 
> 
> [https://github.com/morzechowski99/Selectize.js-limit-tags-plugin](url)

Would you be willing to add this as a PR?

**Comment by sagittaracc** [comment]
Is everything okay with this plugin rn? It doesn't seem to work

**Comment by mete89** [comment]
@sagittaracc it doesn't work for me as well. @morzechowski99 is this still working for you?
