### ISSUE TITLE
[Question] Identification of new and existing values

### ISSUE THREAD

**Issue by Avtonom** [selectize/selectize.js#769]
How do I determine the server side that came identifier existing record rather than the user entered a new numeric value?
I have read the answers about Ajax to create records (`create: function(input, callback)`), but I think that you should be able to create value and on the server side, because after entering a new value, the user can quickly submit the form.

**Comment by PhiLhoSoft** [comment]
I fear I haven't fully understood the question. I will try to answer what I think I understood...

Basically, user-created values are items of Selectize, along with the existing values provided by the server. So when the form is submitted, you send selected new and existing values, and server can check itself if it already knows a value or not, and add the latter if they are OK.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
