### ISSUE TITLE
Dropdown is opened even when options is empty

### ISSUE THREAD

**Issue by burgalon** [selectize/selectize.js#771]
When initializing in 'single-mode' with {openOnFocus: false}, and clicking the caret, onMouseDown event kicks in, and calls open(), which doesn't check if options is empty.
Additionally, the refreshOptions() method is called, but since triggerDropdown==false, close() is not being called

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
