### ISSUE TITLE
Is it possible to make selectize require a value?

### ISSUE THREAD

**Issue by mikemaccana** [selectize/selectize.js#774]
My original select box has the `required` attribute set

```
<select name="some-name" value="initialValue" required>
     <option value="initialValue">initial value</option>
     <option value="otherValue">other value</option>
</select>
```

I start selectize:

```
$("select[name='some-name']").selectize()
```

But users can still use the backspace key to remove the selected option, making the select box have a value of `''`.

Since `required` on the real select box doesn't seem to affect Selectize, I've read [the selectize documentation](https://github.com/brianreavis/selectize.js/blob/master/docs/usage.md) but can't find any way to stop users from deleting the option. 

How can I prevent users from setting the value to anything except a valid option?

Also asked at http://stackoverflow.com/questions/29777915/how-do-i-make-a-selectize-js-select-box-require-a-value?noredirect=1#comment47687698_29777915 if you want the SO karma!

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
