### ISSUE TITLE
No source code visible under HTTPS

### ISSUE THREAD

**Issue by kevin-brown** [selectize/selectize.js#777]
Right now if you view the Selectize home page at https://brianreavis.github.io/selectize.js/ (default for [HTTPS Everywhere](https://github.com/EFForg/https-everywhere)), there isn't an option to view the source code.

![image](https://cloud.githubusercontent.com/assets/1991850/7311435/51d1000c-ea0a-11e4-9aa8-5d7de3402748.png)

This appears to be because [highlight.js isn't using a protocol-relative URI](https://github.com/brianreavis/selectize.js/blob/4366f03cf1170f017b72c849f556ed14f5010e8b/index.html#L27). The [HTTPS version works](https://yandex.st/highlightjs/7.3/highlight.min.js) without any issues.

The same [also applies to the font](https://github.com/brianreavis/selectize.js/blob/4366f03cf1170f017b72c849f556ed14f5010e8b/index.html#L17), but that's more of a cosmetic issue.

**Comment by msurguy** [comment]
@kevin-brown could you please create a PR that would use relative URI for those assets?
