### ISSUE TITLE
How can we always show the scrollbar?

### ISSUE THREAD

**Issue by gottfrois** [selectize/selectize.js#778]
Feedbacks from my users tell me that since the scrollbar is not showing until you start scrolling down, they think there are no other options than the one displayed.

Is it possible to display the scrollbar when the selectize contents display?

Thanks

**Comment by PhiLhoSoft** [comment]
I don't understand the issue.
In the main page / demo, I always see the scrollbars when I click on the component (or when I focus on it via the keyboard).
Beside, I don't see how "_the scrollbar is not showing until you start scrolling down_", ie. how you start scrolling without scrollbar. Using mouse wheel? Swipe on a mobile browser?

**Comment by gottfrois** [comment]
It's actually an issue with Mac OS X. It has an option in the system config saying "display scrollbar automatically based on mouse and/or trackpad position". For some reason it was not showing a scrollbar on selectize but it's back again now...

Sorry about that.
