### ISSUE TITLE
How is the options object array expected to formatted?

### ISSUE THREAD

**Issue by micahblu** [selectize/selectize.js#779]
Would be nice to specify in the docs the expected format for the options array. I am currently trying to use:

``` js
[{
   name: "field name",
   value: "field value"
}]
```

So I've just discovered that `name` needs to be `text`. I still think it'd be helpful to specify in the docs :) 

Thanks

**Comment by PhiLhoSoft** [comment]
See #745

**Comment by joallard** [comment]
Closing in favor of #785
