### ISSUE TITLE
Enter key should submit form

### ISSUE THREAD

**Issue by nesl247** [selectize/selectize.js#78]
I'm not sure if I am missing an option, but it would be nice to be able to allow the enter key to submit the form, even when selectize has focus.

**Comment by h0jeZvgoxFepBQ2C** [comment]
+1 delfuego

**Comment by karalabe** [comment]
;)

``` javascript
s = $('#sel').selectize({
    onEnter: function() {
        alert("enter key pressed");
    }
})[0].selectize;

onKeyDown = s.onKeyDown.bind(s)
s.onKeyDown = function(e) {
    var result = onKeyDown(e)
    if (e.keyCode == 13) {
        this.settings.onEnter()
    }
    return result
}.bind(s)
```

http://jsfiddle.net/mxom8xxh/

**Comment by fjsj** [comment]
See: https://github.com/wayneashleyberry/selectize-enter-key-submit

**Comment by h0jeZvgoxFepBQ2C** [comment]
Here is also a solution:

``` javascript
var $select = $("#select").selectize({...});

$sele[0].selectize.on("change", function() {
  $("form").submit();
});
```

**Comment by thehonestcto** [comment]
Thanks a lot @fjsj 
This is a great and necessary feature. It should be included in the main Selectize.js release :)

**Comment by thehonestcto** [comment]
Hey! Here's my improved version, based on @fjsj 's code, which fixes 2 issues:
- triggers submit event if Enter is pressed but no option is selected
- triggers submit event after user presses DOWN (which activates the dropdown options) then Enter in order to select the item he wanted (after pressing some UP/DOWN to navigate to it).

``` javascript
Selectize.define('enter_key_submit', function (options) {
    var self = this;

    this.onKeyDown = (function (e) {
      var original = self.onKeyDown;

      return function (e) {
        // this.items.length MIGHT change after event propagation.
        // We need the initial value as well. See next comment.
        var initialSelection = this.items.length;
        original.apply(this, arguments);

        if (e.keyCode === 13
            // Necessary because we don't want this to be triggered when an option is selected with Enter after pressing DOWN key to trigger the dropdown options
            && initialSelection && initialSelection === this.items.length
            && this.$control_input.val() === '') {
          self.trigger('submit');
        }
      };
    })();
  });

// Include this in $('#yourSelector').selectize({
  plugins: ['enter_key_submit'],
  onInitialize: function () {
    this.on('submit', function () {
      this.$input.closest('form').submit();
    }, this);
  },
```

**Comment by jacquescrocker** [comment]
+1 -- this seems like core functionality for selectize.js

@zmirc thanks for the plugin

**Comment by 304NotModified** [comment]
+1. Any plans for this?

**Comment by wolstat** [comment]
would love to see this also

**Comment by joallard** [comment]
As this is default functionality on a vanilla `<input>` but not `<select>`, but this is contrary to the current default and thus a breaking change, I will schedule this for 1.0.

**Comment by dmytro-y-dev** [comment]
@karalabe Thank you! You saved me a day!

**Comment by karalabe** [comment]
@metamaker Hah, this was in a previous life :)) Cheers

**Comment by h0jeZvgoxFepBQ2C** [comment]
Aaand?

**Comment by petrosmm** [comment]
@zmirc extremely elegant solution needed been searching all day for a way to properly hook events such that enter key opens popup but only when not added value! +1

**Comment by mikeover** [comment]
@joallard Any chance this will be making it into the library soon so I don't have to fork?

**Comment by karalabe** [comment]
This issue is 7 years old ;P you do the math
