### ISSUE TITLE
'Readonly' on original <input /> doesn't maintain the behaviour after "Selectization"

### ISSUE THREAD

**Issue by Pictor13** [selectize/selectize.js#789]
May be my fault in not finding the right way to do it BUT I'm trying to understand how to make my Selectized (as Tags)  `<input type="text">` readonly, when there is a _readonly_ attribute on the original input field.

My goal is to **maintain the behaviour of eventual _disabled_/_readonly_ properties present on the _not-selectized_ input.**

Now the _selectized_ input behave correctly if it is _disabled_, not **POST**ing the value of the input/select.

**But** when I have a _readonly_ property on the input, it is still editable/usable.
I could disable the _selectized_ controller using the _disabled_ property, to emulate that; but then I will not receive any **POST**ed data.

Is there a way to maintain the behaviour coherent with the original _<input />_ field?
(so that enabling or disabling Javascript in the page keep behaving in the same coherent way?)

Thanks! And thanks for the wonderful piece of JS! ;)

**Comment by rodrigoguariento** [comment]
Readonly in selectize is a call to "lock" method. Eg.:

`$('#yourElement')[0].selectize.lock();`

Dynamically is possible to unlock too:

`$('#yourElement')[0].selectize.unlock();`

**Comment by Pictor13** [comment]
Thanks for the hint Rodrigo.
Although I believe this is one of the fundamental attributes/behaviours of a `<select>` or `<input>` element and that this should be natively supported, without having to take care of it manually.
