### ISSUE TITLE
Dropdown menu is not shown on mouse click after some item is selected.

### ISSUE THREAD

**Issue by github-gentleman363** [selectize/selectize.js#790]
I am trying to implement Selectize dropdown on top of AngularJS.
The problem is, without any item selected, I click on dropdown, items appear below it, select some item and the items are hidden. Now, when I mouse-click on the dropdown, items do not appear. However, they appear with up/down Arrow key or manual name typing. 

I've spent some time looking into why it is happening. 

My observation:
The reason why it seems that the dropdown list does not show up is that, assuming user already selected any item in the list before, when user clicks on the dropdown again, actually it shows the list and then hides the list immediately, not giving user a second chance to select items.

Any idea what might be causing this issue?

**Comment by PhiLhoSoft** [comment]
See issue #783 I reported not so long ago. It might be related.

Do you use any existing wrapper for AngularJS? I use angular-selectize, which is good, but has some issues on its own.

**Comment by github-gentleman363** [comment]
@PhiLhoSoft 
I am using ui-select.

**Comment by PhiLhoSoft** [comment]
ui-select is a rewrite of Selectize (and Select2), and has no dependency on Selectize.
So I fear you are in the wrong issue tracker... You should close this issue and open a new one at the ui-select project.
Or take a look at angular-selectize which is really based on Selectize and doesn't have the performance issue of ui-select (issue which can be minor if your combos are small, that said).

**Comment by github-gentleman363** [comment]
@PhiLhoSoft 
Thanks. I will open a new one at the ui-select project.
