### ISSUE TITLE
Adding Plugin Without Custom Build

### ISSUE THREAD

**Issue by mcamer** [selectize/selectize.js#793]
I'm looking into adopting selectize into my project, mainly due to the ease of use, the clean code, and the plugin system (so I can extend it relatively easily)

I've seen the examples for the plugins available with the project. Unfortuantely I haven't seen any third party custom plugin (or documentation on how to create a selectize plugin without creating a custom build)

Can you please provide a quick example on how to create a custom plugin to use with an out of the box selecitze if that's possible in the first place?

Thanks,
Amer

**Comment by PhiLhoSoft** [comment]
Look at https://github.com/brianreavis/selectize.js/blob/master/docs/plugins.md and at the source of a plugin. It should get you started. No need for a custom build.

(Although honestly, I haven't tried yet. But looks very straightforward.)

**Comment by Pictor13** [comment]
Maybe you want to follow or vote-up in the issue #976 ?

However, basically you can define your plugin over the *selectize* object with:
```Selectize.define('your_plugin', function(options) { // your plugin code }```

It has minor drawbacks, but in general you can inherit and customise most of the lib.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
