### ISSUE TITLE
Delimiter not working because of suggestion

### ISSUE THREAD

**Issue by yasirrose** [selectize/selectize.js#794]
If you type an email address that is not in suggestion and press the Delimiter key, it works fine.

But if you manually type an exact email address that is in suggestion, then the delimiter key does not work. The only way to select the email address then is to click on the suggestion.

**Comment by PhiLhoSoft** [comment]
Looks like #800 (which is the duplicate one, then).

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
