### ISSUE TITLE
Filter by only first letter

### ISSUE THREAD

**Issue by mkimont** [selectize/selectize.js#795]
Trying to get any options, method, function and cannot get thru if this is real possible here.
Is there a chance to add regex on filtering for selectize? As it will be useful to have option to filter by 'first letters' ex. writing Ca in input will show only Canada not Oncada.
Trying to filter with RegExp like:

var matcher = new RegExp("^" + values, "i"); 
matcher.test(input.val() ) // check if input value is at the begining of value

but where should i inject that ?

**Comment by PhiLhoSoft** [comment]
Add this to your options:

```
  score: function (search)
  {
    return function (option)
    {
//      console.log(JSON.stringify(option));
      if (option.name.indexOf(search) === 0) // Here, 'name' is the property identified by labelField
      {
        return 1;
      }
      return 0;
    }
```

As you can see, no need for a RE for such a simple check, but of course you can use one for more complex requests. And you can make the name and search lower-case for a case-insensitive search.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
