### ISSUE TITLE
Selectize case sensitive

### ISSUE THREAD

**Issue by mahidras** [selectize/selectize.js#796]
Currently i am using selectize.js in one of our project. I am facing one issue with the duplication of tags. For Ex:  if i type test in the input field it is taking the value as test and if i type the Test in the input field, this is also taking. Here duplication in my tags list like test and Test. 
Please help me how can i avoid duplication with in the tags if i type uppercase or lower case.

**Comment by PhiLhoSoft** [comment]
Make sense...
Possible workaround: add the following option to the config
```
  onOptionAdd: function (value, data)
  {
    for (var optValue in selectizeInstance.options)
    {
      if (optValue.toLowerCase() === value.toLowerCase() && optValue !== value)
      {
        selectizeInstance.removeOption(optValue);
        break;
      }
    }
//    console.log(value + " - " + JSON.stringify(data) + " - " + JSON.stringify(selectizeInstance.options));
  }
```
A caseInsensitive option might be useful, though.

**Comment by PhiLhoSoft** [comment]
Add this to your options:

``` javascript
  createFilter: function (value)
  {
//    console.log(JSON.stringify(selectizeInstance.options));
    for (var optValue in selectizeInstance.options)
    {
      var name = selectizeInstance.options[optValue].name; // Property defined by labelField
      if (name.toLowerCase() === value.toLowerCase() && name !== value)
      {
        return false;
      }
    }
    return true;
  }
```

selectizeInstance is the object returned by the selectize() call.

**Comment by alexbowers** [comment]
This will work as well, but be more dynamic.

``` javascript
createFilter: function (value)
{
    for (var optValue in this.options)
    {
        if (optValue.toLowerCase() === value.toLowerCase() && optValue
!== value)
        {
            return false;
        }
    }
    return true;
}
```

**Comment by PhiLhoSoft** [comment]
@alexbowers Valid remark, I didn't know `this` referred to the current instance of Selectize in these callbacks, thanks for the information.

Note: you answered to my first version of my answer, which was incorrect, and was edited. And the space before the language name broke the syntax highlighting. Here is the fixed version:

``` javascript
  createFilter: function (value)
  {
    for (var optValue in this.options)
    {
      var name = this.options[optValue].name;
      if (name.toLowerCase() === value.toLowerCase() && name !== value)
      {
        return false;
      }
    }
    return true;
  },
```

**Comment by mahidras** [comment]
it is working for single word. But not working for sentence. Like for ex:
topic - it works
TOPIC comm, TOPIC COMM - it doesn't work.
if i give spaces it doesn't work :(

**Comment by PhiLhoSoft** [comment]
"It doesn't work" is the kind of bug report users do. Developers are supposed to be more precise, or even better, to debug their code...

I have a little plunk with Selectize, showing the filter above: http://plnkr.co/edit/v2v9CYfDa0B5TR003s5y
I tried it with tags with spaces, it works for me.
I suggest to do your own plunk showing your issue, perhaps based on mine, stripped down to the simplest form, so we can see the issue and if we can fix it.

**Comment by mahidras** [comment]
Sorry about that it works. May be some other reason it was not working. I din't make any changes though, but it started working. Thanks for your quick reply.

**Comment by PhiLhoSoft** [comment]
Then I suggest to close this issue, to keep the backlog clean (as the owner of the project hasn't time to maintain the list, apparently).
