### ISSUE TITLE
opt group matching

### ISSUE THREAD

**Issue by andriijas** [selectize/selectize.js#80]
Hi

Does selectize.js supports or plan to support opt group matching? So that a search that matches an opt group automatically matches all the options of the opt group?

Thanks

**Comment by maxnowack** [comment]
+1

**Comment by samstickland** [comment]
+1

**Comment by anthony07** [comment]
We need this feature too.

**Comment by yetanotherse** [comment]
+1

**Comment by cholnhial** [comment]
Yep we really need this feature. Please.

**Comment by khkramer** [comment]
+1

**Comment by niranjan94** [comment]
+1

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
