### ISSUE TITLE
selectOnDelimiter

### ISSUE THREAD

**Issue by alexbowers** [selectize/selectize.js#800]
There is currently an option to select on tab, however, if you use the delimiter that is set, it doesn't select, but rather creates a new one (if create is true).

Can there be an option for selectOnDelimiter.

**Comment by dandv** [comment]
:+1: IMO, pressing Tab should select into the input box the currently selected value in the dropdown. This is how many systems handle pressing Tab: tag entry in Vanilla Forums, Pinboard.in, [Bootstrap typeahead](http://twitter.github.io/typeahead.js/). Select2 has an open feature request for the [same behavior](https://github.com/select2/select2/issues/2637#issuecomment-53412047).

**Comment by alexbowers** [comment]
https://github.com/brianreavis/selectize.js/pull/807

**Comment by Maluen** [comment]
The selectOnDelimiter behaviour would be greatly appreciated!

**Comment by alexbowers** [comment]
The PR above does this functionality based on closeOnSelect property

**Comment by Maluen** [comment]
@alexbowers I've tried your PR with the "closeOnSelect" property, but pressing the delimiter key after a suggested item has been typed, does not add it.

Is there some other requirement needed?

**Comment by alexbowers** [comment]
There shouldn't be. Can you produce a fiddle with an example of it not
working?

**Comment by Maluen** [comment]
@alexbowers sure, here you go:

http://maluen.github.io/selectize.js/examples/selectOnDelimiter.html

Try to input "someone@gmail.com" and then enter the semicolon (the deilmiter key), the item is not added; it is added instead by pressing enter or when the inserted item isn't a suggested option.

**Comment by alexbowers** [comment]
I dont see on your demo there where it is set to true. by default it is false (to maintain backwards compatability).

closeOnSelect must be made to be true in the config

**Comment by Maluen** [comment]
@alexbowers The property is actually called "close**After**Select", I've setted that in the selectize settings, but the result is the same:

``` javascript
$('#select-to').selectize({
    closeAfterSelect: true,

    persist: false,
    maxItems: null,
    delimiter: ';',
    /* ... */
```

**Comment by Maluen** [comment]
The demo issue has nothing to do with the closeAfterSelect property, is a silly bug with the filtering function itself: https://github.com/Maluen/selectize.js/commit/eebc789a87f1478aa392c1e818c3580c12b52ceb

> return !this.options.hasOwnProperty(match[2]);

This was skipping the item if it was already in the options. Not sure why it worked instead by pressing enter, probably the filtering isn't executed in this case ;)
