### ISSUE TITLE
Option groups can not be selected using arrow keys with "addPrecedence: true"

### ISSUE THREAD

**Issue by Mia-X** [selectize/selectize.js#804]
I have noticed that it is not possible to use the arrow keys to select options from a option group if the "Add..." option is active.

You can see the issue in this demo: http://jsfiddle.net/b69z0wry/

**Comment by PhiLhoSoft** [comment]
Actually, if I comment out the addPrecedence line, I still see the issue.
It is hard to solve the problem, as arrow keys are used in the edition control where we type the search term.
Now, perhaps the down arrow would give the focus to the drop-down list.
Note that just hovering an item in the drop down enables the keyboard navigation in the list. With a strange side effect: left / right arrows also moves the caret in the edit field.

**Comment by Mia-X** [comment]
How can I automatically select the first item in the first column after the user types something in?

**Comment by PhiLhoSoft** [comment]
No idea, but one problem is to define "_after the user types something in_".
Is it after the first letter? After n letters? After a pause of x ms in the typing? What if he wants to continue typing?
Ideally, the user should be able to switch to the list with a shortcut key, but Tab (can) creates the tag, instead of jumping to the list. Down arrow could be a natural choice for this.

**Comment by Mia-X** [comment]
I think that the `getAdjacentOption` function of the `optgroup_columns` is the problem. `$option.closest('[data-group]')` Does not work for the 'create' option.

```
this.getAdjacentOption = function($option, direction) {
    //var $options = $option.closest('[data-group]').find('[data-selectable]');
    var $options = this.$dropdown.find('[data-selectable]');
    var index    = $options.index($option) + direction;
    return index >= 0 && index < $options.length ? $options.eq(index) : $();
};
```

It works if you replace it with `this.$dropdown`.

**Comment by christophburger** [comment]
This problem still exists if you use the plugin 'optgroup_columns', because the plugin contains the old parts of code

``` javascript
this.getAdjacentOption = function($option, direction) {
        var $options = $option.closest('[data-group]').find('[data-selectable]');
        var index    = $options.index($option) + direction;
        return index >= 0 && index < $options.length ? $options.eq(index) : $();
};
```

You can just replace the code in the plugin with the code above.

**Comment by danuep** [comment]
I ran into this problem trying to use optgroup_columns with the create option enabled, and I was wondering if there's a fix in the works yet. If not, would it be helpful for me to put together a pull request incorporating the fix described above?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
