### ISSUE TITLE
Switch Display Hidden for Visibility Hidden? To load external images icons?

### ISSUE THREAD

**Issue by markudevelop** [selectize/selectize.js#808]
I was wondering if there an easy way to make images load before opening the select dropdown, it will lag loading the images because it's display hidden.

**Comment by PhiLhoSoft** [comment]
See https://perishablepress.com/3-ways-preload-images-css-javascript-ajax/ for example...

**Comment by markudevelop** [comment]
@PhiLhoSoft hey thanks for the link I checked it, But I don't really like those hacks. Switching display hidden to visibility hidden will fix this easily. But I'm not sure if it's safe to do that because the plugin relies on the visibility/display css everywhere

**Comment by brianreavis** [comment]
The problem with `visibility: hidden` is that the user can still interact with it. There's the possibility of positioning it offscreen, but that creates problems with the page scroll jumping around depending on the browser. Preloading images no matter how you skin it is going to be a hack...

**Comment by markudevelop** [comment]
@brianreavis thanks for the explanation! hack it's.
