### ISSUE TITLE
select: text cursor

### ISSUE THREAD

**Issue by andrey-burtnyy** [selectize/selectize.js#81]
if you click on "select", after name appears text cursor.
for example from demo:
https://dl.dropboxusercontent.com/u/26455887/images/0/8-23-2013%205-16-47%20PM.png

**Comment by miketeix** [comment]
+1

**Comment by DarkMerge** [comment]
+1

**Comment by jsheffers** [comment]
I agree, has anyone taken a shot at this?

**Comment by flamber** [comment]
WebKit supports messing around with the caret with a little CSS hack: http://jsfiddle.net/tw3xk9z3/
