### ISSUE TITLE
How can I select from a full table with Selectize.js?

### ISSUE THREAD

**Issue by isaahmdantas** [selectize/selectize.js#810]

**Comment by PhiLhoSoft** [comment]
1. Issue tracker isn't for asking questions, use Stack Overlow for that...
2. The question isn't understandable; you forgot to provide a description...

**Comment by isaahmdantas** [comment]
okay !

**Comment by PhiLhoSoft** [comment]
So either improve this issue or close it. This will keep this issue tracker tidy. Thanks.
