### ISSUE TITLE
add a new option with newline

### ISSUE THREAD

**Issue by iamtennislover** [selectize/selectize.js#811]
Is there a way to allow the selectize to allow newline to be entered into the textfield as option's value and that option be added?

**Comment by PhiLhoSoft** [comment]
I doubt it, and it wouldn't be very practical, IMHO...
Perhaps you can instead define a special character as newline placeholder (eg. # or \n or @, whatever) and substitute it later?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
