### ISSUE TITLE
Key:Value pairs as item, when in selctized <input>

### ISSUE THREAD

**Issue by Pictor13** [selectize/selectize.js#822]
Does _selectize_ support key:value pairs, as items, when initialized over a `<input />` instead of a `<select>`?

I found no way and say that `init_textbox` uses the same value either for the `field_label`and the `field_value`; and also that the `addItem()` function doesn't support arrays as value.

I was wondering if I'm missing something in the code or if currently _selectize_ does **not** support hashes in slectized `<input>`(s).

**EDIT:**

Additionally, I was wondering if (when applied to `<select>`) there is any way to support objects/hashmaps as items.

Thank you

**Comment by PhiLhoSoft** [comment]
AFAIK, items are pure strings, whatever the underlying base component (input or select). You have to use these keys (values) to find back the full objects in the list of options.

See, for example, how I do it in a simple example where I used an input tag: http://jsfiddle.net/m92u852e/1/
In my applications, I would rather use Lodash to find back the objects...

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
