### ISSUE TITLE
Drag_Drop fires item_add event

### ISSUE THREAD

**Issue by c143** [selectize/selectize.js#823]
Hey
I wanted to use the Drag and Drop Plugin, but it fires the item_add event, even tho it just changes the values. Can't use it this way.

Greetings

**Comment by PhiLhoSoft** [comment]
Untested simple fix: in the plugin, at the line `self.setValue(values);`, add a `silent` parameter: `self.setValue(values, true);`. You can make your own plugin out of this one...

I agree it should be in the plugin code itself. And / or it should fire a specific event.

**Comment by c143** [comment]
The silent paramter only works on the change Eventlistener as far as I know. So that wouldn't work.

In addition, I want to get the change Eventlistener, but it isn't a new Item. I need to know, when something gets dragged, but at the moment it fires my other function.

**Comment by PhiLhoSoft** [comment]
OK, I found a hack, but it might have hidden caveats I haven't seen yet... But it seems relatively safe in the context of the plugin.

Replace the last two lines of the plugin (marked "Original" in the code below) with the following:

```
                    var is = self.isSetup;
                    self.isSetup = false;
                    self.setValue(values); // Original
                    self.isSetup = is;
                    self.setActiveItem(active); // Orignal
                    self.updateOriginalInput({silent: false});
```

See http://plnkr.co/edit/v2v9CYfDa0B5TR003s5y for a running example.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
