### ISSUE TITLE
How do i return the selected values for multiple selection

### ISSUE THREAD

**Issue by papakay** [selectize/selectize.js#829]
Hi,i've been trying to retrieve the selected value for a multiple select field but proved abortive.

The number of selected values and not the values itself.

Please how do i fix this?

Thanks

**Comment by PhiLhoSoft** [comment]
I am sorry, but I failed to understand your question (BTW, I tend to think questions belong more to sites like StackOverflow than to issues of a project...).

I suggest you do a fiddle / plunk or similar, to show your problem.

**Comment by papakay** [comment]
Thanks! I eventually figured it out.

Thanks once again.

-- 
Best Regards,
Kehinde Alabi
Software Developer / Experienced UI & UX Designer
MOBILE NO: +234 813 7995 908
EMAIL: kehindealabi21@gmail.com
Don’t focus on being better than anyone else rather focus on being the best you can.

On June 19, 2015 at 9:56:11 AM, Philippe Lhoste (notifications@github.com) wrote:

I am sorry, but I failed to understand your question (BTW, I tend to think questions belong more to sites like StackOverflow than to issues of a project...).

I suggest you do a fiddle / plunk or similar, to show your problem.

**Comment by PhiLhoSoft** [comment]
Then you should close this issue.
