### ISSUE TITLE
Non integer width causes left border to hide on Chrome

### ISSUE THREAD

**Issue by philwig** [selectize/selectize.js#830]
Using a Bootstrap3 form-horizontal with two columns, a label in the left column, and a Selectize control in the right, the left border of the Selectize control is invisible until you click in the control, at which point it comes back again. Functionally it's fine.

I'm getting this on Chrome, can't repeat on IE11.

There's some SO report here on this:
 http://stackoverflow.com/questions/28450688/selectize-js-border-missing-in-an-inline-form
## Work around

Setting an _integer_ width on the left column stops the problem. So 149px works, but 149.5px - which is what Bootstrap gives me in a standard modal - causes this issue.

I don't have time to chase it down but presumably a rounding issue in the browser somewhere (as both Chrome and IE report 149.5, but only Chrome gives the visual glitch

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
