### ISSUE TITLE
maintain data- attributes in selected options

### ISSUE THREAD

**Issue by sosukeinu** [selectize/selectize.js#831]
I'm sure I'm just missing this somewhere in the documentation, but I have two data- attributes that I need to grab from the selected option, how do i make sure that selectize keeps these when an option is selected? Right now it only keeps `value="blah"` and `selected="selected"`. Thank you.

**Comment by ilkovalc** [comment]
- need that too

**Comment by MarcusHallettUAH** [comment]
Agreed

**Comment by trashMeNow** [comment]
same here....
on the standard option i have this option situation:
option value="00002" flnom="N" data-flnom="N">Eredi</option

but where i selectize it, i get:
div data-value="00002" data-selectable="" class="option selected">Eredi</div

i lost FLNOM attribute and data...

how to fix it???

thanx

p.s.: how to post HTML blocks here???

thanx again

**Comment by thomasfw** [comment]
I feel like this should be easier, but...

``` javascript
$select = $('select#select').selectize();

// ...

var selectize = $select[0].selectize;
var data = $.map(selectize.items, function(value) {
    return selectize.options[value];
});

var foo = data[0].foo; // Your original foo data (data-foo)
```

#699

**Comment by maxi032** [comment]
I need this too.
My option looks something like 
{"id":8,"text":"Tomato","type":"Vegetable","color":"Red"} 

and when I submit I get only the value of the id

**Comment by joallard** [comment]
Sounds like #239
