### ISSUE TITLE
clearOptions() silent option

### ISSUE THREAD

**Issue by mrd05d** [selectize/selectize.js#832]
I was just going to suggest adding the silent option to clearOptions(). I know this argument is already used elsewhere and it would benefit in situations where you would like to clear options on a selectbox because a dependency selectbox has changed but you do not want to fire onchange of the second selectbox...

**Comment by PhiLhoSoft** [comment]
+1
`clearOptions` calls `clear` which has a `silent` parameter, so it should have one too, to allow to propagate the choice.
