### ISSUE TITLE
Is there a plugin to create tags outside the text box?

### ISSUE THREAD

**Issue by ishandutta2007** [selectize/selectize.js#833]
I need to
1) Search tag
2) Drag and reorder tsgs
3) Add new tags
4) Delete tags
5) Have tags shown outside the text-box as-list.
I can see the first four being provided by selectize.js or even the former ones like select2
Does anyone knows any plugin or something that achieves the 5th one as well.

**Comment by PhiLhoSoft** [comment]
If it is outside of the component, it is more the responsibility of your application to read the list of tags and to update the list, no?

**Comment by ishandutta2007** [comment]
What I am thinking of is to create another text box below it where user will actually type and have my own javascript to copy it to select2/selectize's text box and also write enogh css to make select2/selectize's text box look like a div. I believe this is a common usecase for many web-developers.So was wondering if anything like this is already there?

**Comment by saeed-parsaee** [comment]
Same issue, 
this would be nice to have an option like RENDER_TAGS_TO which overide the default action(display inside input box).
This could be achived by displaying tags outside input box, below or upside of input box and no needs to be completely rendered outside of component

**Comment by Genkilabs** [comment]
I hacked together something similar in the onItemAdd, putting the items in a different div. The problems with this approach is that then the item list within selectize is clear, so other features like 'maxItems' won't work.
The conclusion I arrived at is that Selectize really needs a render_tags_to option so it can manage the items without external hackery.
my 2c...

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
