### ISSUE TITLE
Disable cache completely

### ISSUE THREAD

**Issue by edu2004eu** [selectize/selectize.js#834]
Is there a way to disable the cache of Selectize? I've tried setting `options.loadedSearches` to `{}` but that didn't seem to work.

Thanks.

**Comment by baptistedonaux** [comment]
+1 I have the same problem. In my case, I change the URL to request (according to other fields) and the result are already in the cache.

Do you have an solution to cancel cache option ?

**Comment by edu2004eu** [comment]
Couldn't figure out anything to invalidate the cache, so I switched to select2, unfortunately. I'm having the exact same use-case.

**Comment by demon101** [comment]
+1

I have fixed it by cleaning query cache before load collback

load: function(query, callback) {
        var self = this;
        $.ajax({
          url: ajaxUrl,
          data: { q: query },
          error: function() { callback(); },
          success: function(res) {
            delete self.loadedSearches[query];
            callback(res.results);
          }
        });
      }

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
