### ISSUE TITLE
Selectize js single select search is not easily understandable ?

### ISSUE THREAD

**Issue by vinothwindows47** [selectize/selectize.js#836]
When I use single select using selectize plugin, after i selected item i want to search some other item.Then I did not search item if some one already selected . We forcely delete already selected one and then search the next item.I think is not easily understandable.

It would be better single select should be like chosen or select2 plugin

**Comment by vinothwindows47** [comment]
It would be better single select like this chosen plugin  or something you give understandable.

![chosen](https://cloud.githubusercontent.com/assets/3929019/8322927/de38e2e6-1a5a-11e5-8702-e1fde79cf3cd.png)

**Comment by PhiLhoSoft** [comment]
I think I got it.
When you select an item, but then want to change to another, and want to search for it, you have to hit Backspace to remove the current selection to start typing the new search, which you find annoying. Right?
So you would want a search field separated from the selection area.

Personally, I find the inconvenience to be minor, it is just a key away. The change you request would be a deep change in the design of Selectize, I am not sure it is doable at all...

**Comment by jasonshaev** [comment]
Can't this be solved by using a multi select with maxItems: 1?

**Comment by gdecris** [comment]
This is exactly the behavior I would have expected. Are there any plans to add this as a feature? 

This plugin in my opinion is much better then select2 or chosen. I just need to find a way around this one issue of searching while an item stays selected. 

You may see it as an inconvenience but the change event is triggered when you 'backspace' the selection causing unnecessary updates to the ui in my case.

**Comment by vvoody-** [comment]
It takes me (as web developer) few moments to realize that i need to hit backspace. Normal user can be completely lost. Other problem is fireing on change event after backspace - user didnt want to change select to empty value, he just want to search for another value.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
