### ISSUE TITLE
setActiveItem do not respond when score of available options change

### ISSUE THREAD

**Issue by stevenay** [selectize/selectize.js#837]
I have four available options "Install Laravel", "Install Composer", "Via Laravel Installer" and "Via Composer Create-Project".

When I type "_Install Composer_" in selectized select control, it correctly show the options and set "_Install Composer_" as **active item** in the options list according to the following picture.

![screen shot 2015-06-24 at 2 08 48 pm](https://cloud.githubusercontent.com/assets/6089226/8324935/1bb3ab2c-1a7b-11e5-9ba4-3ba6259b8db9.png)

Then I type again "_Install Laravel_". It correctly show "_Install Laravel_" option at the top of the list. But it does not set this "_Install Laravel_" option as the **active item**. "_Install Composer_" is the still the **active item**. How should I do to reflect active item change to the most matched option when the user type new search text? (In this case, I would like to change active item to "_Install Laravel_" when I type "Install Laravel".)

![screen shot 2015-06-24 at 2 10 07 pm](https://cloud.githubusercontent.com/assets/6089226/8324937/27645f0c-1a7b-11e5-9e3a-5588374a3060.png)

(P.S. I use searchConjunction as "or" condition.)

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
