### ISSUE TITLE
Reset

### ISSUE THREAD

**Issue by afider** [selectize/selectize.js#839]
Hi!
How can I reset the select to the option by default on button click?
How can it be done in case when the select is not single on form?

**Comment by PhiLhoSoft** [comment]
Maybe the https://github.com/brianreavis/selectize.js/blob/master/docs/api.md page can help?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
