### ISSUE TITLE
How to call function inside onChange 

### ISSUE THREAD

**Issue by oroalej** [selectize/selectize.js#840]
how can i call a function inside a onChange: function(value){}? when i try to call a function, it says that function is not defined

```
onChange: function(value){
  weatherWidget(value)
}

$(document).ready(function() {
  function weatherWidget(location){
    console.log('test');
  }
}
```

**Comment by PhiLhoSoft** [comment]
I suggest to read on the bases of JavaScript, including variable scoping...

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
