### ISSUE TITLE
Don't delete option with empty value

### ISSUE THREAD

**Issue by negoziant** [selectize/selectize.js#841]
When I try use selectize.js, I got a problem.
I need to use option with empty value as default option and I could choose this option, but plugin delete it, and I can't use plugin.

Does anyone have a solution?

**Comment by PhiLhoSoft** [comment]
What plugin are you talking about?
Can you do a simple example showing your issue on a site like JSFiddle or Plunker?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
