### ISSUE TITLE
If there is no result use the traditional search + name=q

### ISSUE THREAD

**Issue by josephpbuarao** [selectize/selectize.js#842]
Hi Guys,

I'm using the selectize for auto suggest search on my website but I would like it have a name q on the input because if there is no suggestion I want to use the traditional search. How to implement that? 

This is what I want to achieve
input type=text
name = q
form method=get

Thank you in advance for you help!

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
