### ISSUE TITLE
add a data attribute for the raw text

### ISSUE THREAD

**Issue by alexbowers** [selectize/selectize.js#844]
We currently have data-value, but geting the raw text in there would be good too.

The line to do this is:

``` javascript
 if (templateName === 'option' || templateName === 'item') {
     html = html.replace(regex_tag, '<$1 data-value="' + escape_replace(escape_html(value || '')) + '"');
 }
```

  Change it to be:

``` javascript
if (templateName === 'option' || templateName === 'item') {
    html = html.replace(regex_tag, '<$1 data-value="' + escape_replace(escape_html(value || '')) + '" data-text="' + escape_replace(escape_html(data.title || '')) + '"');
}
```

**Comment by PhiLhoSoft** [comment]
I think the render object described at the end of the https://github.com/brianreavis/selectize.js/blob/master/docs/usage.md page is exactly made for this usage, to allow custom rendering of HTML depending on your needs.

Your snippet assumes that data has a `title` field, while a strength of Selectize is to be data-agnostic, ie. it doesn't impose field names on the data.
