### ISSUE TITLE
How to disable multiselect?

### ISSUE THREAD

**Issue by josephpbuarao** [selectize/selectize.js#845]
Hi,

I would like to disable the multi select. How to do that?

Thanks!

**Comment by PhiLhoSoft** [comment]
https://github.com/brianreavis/selectize.js/blob/master/docs/usage.md

```
maxItems: 1 // null for no limit, 2 or more for limiting the number of tags
```

**Comment by joseluisq** [comment]
:+1:

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
