### ISSUE TITLE
closeAfterSelect doesn't work when create option is true

### ISSUE THREAD

**Issue by alibozorgkhan** [selectize/selectize.js#847]
On the `performance.html` example file:
- Set `closeAfterSelect:true` and `create:true`
- Now pick an option that doesn't exist in the drop down (using `Add foobar`)
- The drop down goes away and comes back on.

**Comment by petr24** [comment]
This worked for me, found in another issue post here. 
Thanks to @kitof for the answer.
Solved with openOnFocus: false.

**Comment by joallard** [comment]
Thanks @petr24
