### ISSUE TITLE
Change events from the internal inputs escape the widget.

### ISSUE THREAD

**Issue by BudgieInWA** [selectize/selectize.js#849]
When the text input that is used to enter search text is blurred without selecting an option, a change event bubbles up, escaping the widget.

See https://jsfiddle.net/b4c0gbzb/ for an example.

This seems unintentional, as it is undocumented, and a side effect of an implementation detail.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.

**Comment by BudgieInWA** [comment]
I believe this issue is still valid.
