### ISSUE TITLE
There is no indication that maxOptions has been exceeded.

### ISSUE THREAD

**Issue by BudgieInWA** [selectize/selectize.js#850]
When the number of options to display is larger than `maxOptions`, some options are not displayed, but there is no indication of this. It looks like all of the options are being displayed, but they are not, which is misleading.

I would expect an ellipsis or something at the end of the list indicating that options have been omitted.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.

**Comment by BudgieInWA** [comment]
I've heard nothing about any changes to this behaviour (or the similar problem described in #1471). I think these issues are stale for a lack of solution, not for lack of accuracy and should be re-opened.
