### ISSUE TITLE
Do we have pagination enable ?

### ISSUE THREAD

**Issue by benli2023** [selectize/selectize.js#853]
Do we have pagination enable ? 

I want some feature like select2 pagination function

http://embed.plnkr.co/db8SXs/preview

**Comment by Maxooo** [comment]
:+1:

**Comment by jbrodie** [comment]
This would be nice.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
