### ISSUE TITLE
Fuzzy Search Not Building Options

### ISSUE THREAD

**Issue by muaaz007** [selectize/selectize.js#860]
Hi Guys,
     Hope you all are enjoying good health, So i have implemented fuzzy search on server side and wanted to render the options but selectize.js does not build those below is a rough example, when
I type "Gatham" and server returns  private_tickers: [{ticker: "Gotham City"}] but does not add options below it. On typing Gotham it works like a charm. Any help will be appreciated.

Regards,
Muaaz Rafi

**Comment by parterburn** [comment]
@muaaz007 I know this is suuuuuuper old, but did you find any kind of solution for this?
