### ISSUE TITLE
Ignore case for options

### ISSUE THREAD

**Issue by ghost** [selectize/selectize.js#861]
I'm facing a small problem with this amazing control.
I'm loading the options remotely and sometimes it happens that the selected option is written as **"option a"**, but on the next server request, that same element might be a part of the list but now written as **"Option A"**.
Since they're case is different, but in actual value they represent the same, this results in the currently selected option to be removed, since **"option a"** is no longer part of the list, even though **"Option A"** is.
Is there a chance we can have a flag to ignore the options casing, for scenarios like these?

Thank you very much.

**Comment by PhiLhoSoft** [comment]
Can't you force the values to be lowercase before adding them to Selectize?
Since values are used as identifiers, I am not sure that making them case insensitive makes sense, as it changes the ID. It is more a task of pre-processing the data before adding it to the component: after all, one can ask for trimmed values, ignore spaces, etc.

**Comment by ghost** [comment]
I ended up solving this question another way: before populating the component with the new options, I check the currently selected option and compare it all the existing options (both strings in lowercase). If one of them is a match, then the selected value is updated to have the load option value.
This works because the component comparison is based on the exact string values and not an uniformized version of them, for example, 'option a' is different from 'Option A', but if we test them both in their lowercase form they'd be equals. Since they're different, no option would be selected upon the component's options refresh.
Does this explanation makes more sense?

**Comment by Shelagh-Lewins** [comment]
I would like to force all tags to be lowercase for consistency and readability, but I am having a problem.
I can force all tags to be lowercase with MyCollection.addTag(input.toLowerCase(), {_id: that.data._id});
However, if I then type "NewTag" into the selectize input and press return, the text "NewTag" remains in the input and is not recognised as a tag. Only when the page is refreshed is the text "newtag" displayed and the input emptied.
I have tried various of the refresh / update options listed in the documentation but I haven't found anything that works here. Any ideas?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
