### ISSUE TITLE
Clicking left of the input field changes the field to focus on some browsers.

### ISSUE THREAD

**Issue by dvanderfaeillie** [selectize/selectize.js#863]
While using selectize.js I noticed some strange behaviour in some browsers.
If you click left of the input field (the place I marked with a red X) the field activates. Reproduces in Chromium, Opera. Doesn't reproduce in FireFox.

[jsFiddle](http://jsfiddle.net/dietervdf/3kpq4s09/)
![selectize](https://cloud.githubusercontent.com/assets/1950967/9008053/b58c5cce-3797-11e5-8a7f-182323cb7ed2.PNG)

**Comment by PhiLhoSoft** [comment]
Strange... Might be related to Bootstrap, but I am not sure.
I can reproduce this in Chrome (Windows), only when I click on the first half of the left margin (roughly from the cross to the left, not between the cross and the form).

**Comment by mcavalletto** [comment]
Unable to reproduce in Mac Chrome.

**Comment by PhiLhoSoft** [comment]
Well, this issue is five years old, and there have been several releases since then, even if the last one is one year and half old. Maybe it has been fixed, I see a fix related to focus on Chrome.
Not sure if there is still somebody maintaining this library, able to close issues, though.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
