### ISSUE TITLE
not work with server

### ISSUE THREAD

**Issue by hanigamini** [selectize/selectize.js#865]
Hi,
thanks for your good selectize !
it is not work with runat="server" , please help me.

**Comment by PhiLhoSoft** [comment]
"it doesn't work" is vague. Do you have error messages in the console? What is the behavior? What doesn't work?

Note: I don't know what this "runat" option is, and I failed to find it in the source code of Selectize...

**Comment by iainvdw** [comment]
runat="server" implies you use ASP.Net. What's the problem exactly and how does this relate to you using ASP.Net? To what element do you apply runat="server"?

**Comment by hanigamini** [comment]
Hi,
this is my asp .net page and my css & js & dist folder.
change only is runat="server" for fill in code behinde,the picture of result is in below, when i remove  runat="server" every things is ok.

![untitled](https://cloud.githubusercontent.com/assets/12791970/9054179/9736dfb6-3a93-11e5-9fc3-4c98503cad99.jpg)
![untitled2](https://cloud.githubusercontent.com/assets/12791970/9054180/9a34a874-3a93-11e5-8d73-cb22d563d33c.jpg)

when i remove  runat="server" every things is ok.
![untitled2222](https://cloud.githubusercontent.com/assets/12791970/9054203/ecf84ade-3a93-11e5-9b3d-d36efe9f5b18.jpg)

**Comment by abezulski** [comment]
What is the element's ID on the output (once page gets rendered)? When you have runat="server", .NET WebForms will generate new ID unless you change it in web.config (https://msdn.microsoft.com/en-us/library/system.web.ui.control.clientidmode(v=vs.110).aspx) That's why it is working for you when you remove runat="server".

**Comment by hanigamini** [comment]
Thank you very much abezulski :+1: 
It is ok with  $('#<%=SelectTrans.ClientID %>').selectize();
