### ISSUE TITLE
How to get the value of the group, when an aption from that group is selected by the user, in selectize

### ISSUE THREAD

**Issue by rajuponnala** [selectize/selectize.js#866]

**Comment by rajuponnala** [comment]
I am getting the value of the option selected. But, how can i get the value of the option group to which the selected option belongs to?. Can anyone reply.. It is urgent for me.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
