### ISSUE TITLE
Item click Event

### ISSUE THREAD

**Issue by martinslae** [selectize/selectize.js#867]
thats any way to get itemClick event?

**Comment by martinslae** [comment]
I can get using:

$('body').on('click', 'div.item', function () {

```
 console.log($(this).attr('data-value'));
```

});

**Comment by PhiLhoSoft** [comment]
onItemAdd()? See https://github.com/brianreavis/selectize.js/blob/master/docs/usage.md

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
