### ISSUE TITLE
Problem with setValue

### ISSUE THREAD

**Issue by kirillkokhv** [selectize/selectize.js#871]
I have a two selectizes: "countries" and "cities". Create both selectizes. On load "countries" get all variables and i'm use setValue to set need value from DB. On change of cities there is a load of "cities" values and then I try to setValue for "cities" but nothing is happen.
I need:
1. create selectizes
2. countries variables load
3. countries setValue
4. cities variables load
5. cities setValue
if I fire cities.setValue from console - everything is OK.

<js>
$countries = $('#countries').selectize({
            valueField: 'country_id',
            labelField: 'name',
            searchField: ['name'],
            create: true,

```
        dropdownParent: 'body',
        onItemAdd: function(value, item) {

        },
        onChange: function(value) {

        cities.disable();
        hotels.disable();
        cities.clearOptions();
        hotels.clearOptions();

        cities.load(function(callback) {
            xhr && xhr.abort();
            xhr = $.ajax({
            url: 'URL',
            success: function(results) {

                cities.enable();
                callback($.parseJSON(results));
            },
            error: function() {
                callback();
            }
            })
        });

        }
    });
    countries = $countries[0].selectize;
    countries.load(function(callback) {
        xhr && xhr.abort();
        xhr = $.ajax({
        url: 'URL',
        success: function(results) {
            callback($.parseJSON(results));
        },
        error: function() {
            callback();
        }
        })

    });
    if(readonly) countries.disable();
    }

    if ($('#cities').is(":visible")) {
    $cities = $('#cities').selectize({
        create: true,
        valueField: 'city_id',
        labelField: 'name',
        searchField: ['name'],

        onChange: function(value) {
        if (value == 0)
            return;
        hotels.disable();
        hotels.clearOptions();

        hotels.load(function(callback) {
            xhr && xhr.abort();
            xhr = $.ajax({
            url: URL,
            success: function(results) {

                hotels.enable();
                callback($.parseJSON(results));
            },
            error: function() {
                callback();
            }
            })
        });
        }


    });
    cities = $cities[0].selectize;
    if(readonly) cities.disable();
    }
```

 countries.setValue(2);
 cities.setValue(1234);
</js>

**Comment by PhiLhoSoft** [comment]
You call `setValue` before the options are loaded. The value is checked against the existing options, and rejected if it is not there.
You need to set the value after loading the options.

**Comment by kirillkokhv** [comment]
I understand it, but how i can do this? 
set value to countries, then load options to cities and then set value to cities. I try onLoad, when().then(). I now that do something wrong, but can't understnad what, need your help)

**Comment by PhiLhoSoft** [comment]
Why you don't call them in the `success` methods? After the `callback()` call.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
