### ISSUE TITLE
optgroup_columns does not render all the entries if the JSON object is large (around 3000 entries distributed in 3 columns)

### ISSUE THREAD

**Issue by mveeramuthu** [selectize/selectize.js#872]
optgroup_columns does not render all the entries if the JSON object is large (around 3000 entries distributed in 3 columns).
However if we search using some keywords, entries that were not previously displayed, appear.
Please let me know if I have to setup a jsfiddle for the same.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
