### ISSUE TITLE
Suggestion: Define another "Add" text.

### ISSUE THREAD

**Issue by mcmukkel** [selectize/selectize.js#879]
When writing in a "tagging" field, there is shown a dropdown saying "Add xxx...":

<img width="528" alt="skaermbillede 2015-08-16 kl 17 34 09" src="https://cloud.githubusercontent.com/assets/3327220/9293938/12272c0a-443d-11e5-877a-d7c5e4222a31.png">

Is it possible to set an option to define another text instead of "Add"? 
It would give the option to make this work in multiple languages.

**Comment by brianreavis** [comment]
Yes, this is possible. See the "option_create" renderer option in the [usage documentation](https://github.com/brianreavis/selectize.js/blob/master/docs/usage.md). The default is:

``` js
'option_create': function(data, escape) {
    return '<div class="create">Add <strong>' + escape(data.input) + '</strong>&hellip;</div>';
}
```
