### ISSUE TITLE
Pasting text with the mouse doesn't trigger search

### ISSUE THREAD

**Issue by demon101** [selectize/selectize.js#882]
For selectize.js with ajax search inserting text by mouse not cause search

It's can be simle reproduced on http://brianreavis.github.io/selectize.js page. On Remote Source — Github example:
1. focus on field
2. delete selected
3. insert text any text by mouse (not by ctrl+v)
4. no result

How to fix it?

For catching event by jquery bind method. Selectize on method can't catch it (bug?).

$('.selectize').bind('input', function(){
// force selectize to make ajax call and show result  
});

// following code catch nothing
$('.selectize')[0].selectize.on('input', function(){
// force selectize to make ajax call  
});

But can't find solution for force selectize ajax call and show result

**Comment by demon101** [comment]
Bug fix is

```
onPaste: function(e) {
            var self = this;
            if (self.isFull() || self.isInputHidden || self.isLocked) {
                e.preventDefault();
            } else {
                // If a regex or string is included, this will split the pasted
                // input and create Items for each separate value
                 setTimeout(function() {
                     if (self.settings.splitOn) {
                        var splitInput = $.trim(self.$control_input.val() || '').split(self.settings.splitOn);
                        for (var i = 0, n = splitInput.length; i < n; i++) {
                            self.createItem(splitInput[i]);
                        }
                      }
                      self.onKeyUp(e);
                }, 0);
            }
        },
```

**Comment by Jaza** [comment]
The fix from @demon101 works for me, I've put it in a pull request.

**Comment by Syone** [comment]
It seems this issue isn't solved yet

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
