### ISSUE TITLE
Support for [autofocus]

### ISSUE THREAD

**Issue by TuckerWhitehouse** [selectize/selectize.js#883]
Would it be possible to support the html `autofocus` attribute?
I've implemented a workaround currently based on the code found in #339

``` js
$('select[data-selectize]').each(function () {
  var defaults = { hideSelected: true, selectOnTab: true }
  var options = $(this).data('selectize')
  var $input = $(this).selectize( $.extend({}, defaults, options) )
  $input.filter('[autofocus]')[0].selectize.focus()
})
```

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
