### ISSUE TITLE
add option with multple select on edit page is not working ?

### ISSUE THREAD

**Issue by vedsingh-fullstack** [selectize/selectize.js#885]
i am able to select multiple option on new page, i have selected one drop down  with choosing one option and other drop down with two options .when i navigate to edit page for one selected option it works fine but for multiple selected it does not create any option .
I have used on success  of  ajax call ,
that.addOption(item);

and using value settter of jquery query builder to set value by 
 rule.$el.find('.rule-value-container input')[0].selectize.setValue([value]);

**Comment by PhiLhoSoft** [comment]
Your issue is not very clear for me. I suggest to make a Plunker / JSFiddle / similar to illustrate it in an isolated code.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
