### ISSUE TITLE
Pressing backspace to clear and then pressing tab renters the value

### ISSUE THREAD

**Issue by bensinclair** [selectize/selectize.js#893]
I am using the `selectOnTab` option to allow people to tab through the selectize options.

One problem I am facing is when you focus a selctize field, press backspase to clear the value and then press tab to move on, it selects the first option. So the only way to clear is to backspace and click out.

Would it make sense to keep the field clear if you backspace and then tab out of it? 

I guess since the `selectOnTab` has the word 'select' in it so it's doing what it was probably designed to do but it would be great if there is a way to not select anything if you've just cleared the input and then press tab.

Here's an example. Click on the first selctize field, press backspace to clear and then press tab. You'll notice even though you cleared it, it selects the first option, January.

http://jsfiddle.net/61az857n/

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
