### ISSUE TITLE
Different item colors within a single multi-select box

### ISSUE THREAD

**Issue by edoarsla** [selectize/selectize.js#896]
I'm wondering if it is possible to specify a color per-selected-item inside the items box?

Thank you.

**Comment by PhiLhoSoft** [comment]
What do you call "items box"? Can you illustrate your point?

**Comment by edoarsla** [comment]
Sorry, I did not see your response.  So, in this "items box" there are 2 selected elements.  I'm trying to find out if there is a way I could specify a color per item.  For example, "Development" is default color but "Production" is red.

<img width="378" alt="screen shot 2015-09-21 at 9 48 57 am" src="https://cloud.githubusercontent.com/assets/7432844/9995117/0c448b78-6046-11e5-984c-dbdbe3a66cef.png">

Thank you!

**Comment by PhiLhoSoft** [comment]
Programmatically, I don't know, but I think you can specify a CSS targeting a tag holding a given string, IIRC.

**Comment by Alex-Sokolov** [comment]
You can
Use render option for item. You have `item` with all properties and full control about styling.
Example from homepage:

``` js
$('#select-to').selectize({
 ... options ...
 render: {
        item: function(item, escape) {
            return '<div>' +
                (item.name ? '<span class="name">' + escape(item.name) + '</span>' : '') +
                (item.email ? '<span class="email">' + escape(item.email) + '</span>' : '') +
            '</div>';
        }
 ... options ...
```

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
