### ISSUE TITLE
How to get this element on event

### ISSUE THREAD

**Issue by emharis** [selectize/selectize.js#897]
how to get THIS element on event , example: on event "onItemAdd" I want to get this select box object , and from the object I want get data on it.

<select name="cblocation" data-hiddenname="myHiddenName" id="cbselect" >
   <option value="1" >Number 1</option>
   <option value="2" >Number 2</option>
   <option value="3" >Number 3</option>
</select>

//jquery
var eventHandler = function (item) {
        return function () {
              //how can I get the cbselect object and get data hiddenname here

```
    };
};
```

$('#cbselect').selectize({
     create: function (input, callback) {
            return {
                value: input,
                text: input
            };
    onItemAdd : eventHandler('onItemAdd')
});

**Comment by PhiLhoSoft** [comment]
The selectize() function returns the corresponding object, so you can get the list of options from it. How you access this value depends on your code structure, of course.

**Comment by mcavalletto** [comment]
Something like the following should do the trick:

```
var selectize = $('#cbselect').get(0).selectize;
var current = selectize.getValue(); 
var option = selectize.options[ current ];
var mydata = option['hiddenname'];
```

That's assuming a single-select; for a multi-select getValue() will return an array of values which you will need to iterate over.

**Comment by AhmedHdeawy** [comment]
@mcavalletto 
thanks, it works fine

**Comment by pmfederico** [comment]
@mcavalletto I have multiple selectized combo boxes. Is it possible to get the corresponding element in the event and set the selectize value?
