### ISSUE TITLE
Provide minimized version of CSS resources

### ISSUE THREAD

**Issue by php-coder** [selectize/selectize.js#899]
If it's possible I want to have minimized version of CSS resources (like `selectize.bootstrap3.css`).

**Comment by vemv** [comment]
Minimize them yourself with your preferred toolchain?

Opening these issues do nothing but hurt the project.

**Comment by php-coder** [comment]
I'm using it from Java project as a web jar. I've asked web jar's creator (https://github.com/webjars/selectize.js/issues/3) but he said that he just packages upstream projects and doesn't want to modify them, so this is why I've created this issue.

**Comment by vemv** [comment]
Alright, sounds reasonable then.

Looks like there's the possibility of making your own webjar. http://www.webjars.org/contributing

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.

**Comment by php-coder** [comment]
Does the release contain `selectize.bootstrap3.min.css` file now? If no, then the issue is still valid. Previously, there was only `selectize.bootstrap3.css` (non-minified).

**Comment by risadams** [comment]
v0.13.x will have minified resources in the css/ directory.
We Will include the raw unminified LESS/SCSS files for folks who prefer to integrate with their own build systems

**Comment by php-coder** [comment]
`selectize.bootstrap3.min.css` still isn't present in WebJar on 0.13.2 and I'm not sure where where it should be fixed -- here or on WebJar creation side.

**Comment by risadams** [comment]
@php-coder I don't work with Java so have no concept of where or how the WebJar is being created; if you have some guidance I can do some research.
In the 0.13.x+ packages the files are minimized but don't explicitly set the extension to *.min.css.

The only exceptions are the bootstrap 2 and legacy css files, which are not touched, but all others should be.
