### ISSUE TITLE
less file doesn't compile

### ISSUE THREAD

**Issue by riccardolorenzon** [selectize/selectize.js#903]
the file selectize.bootstrap3.less doesn't compile, the error is the following : 

```
NameError: variable @input-border-radius is undefined in {$project_dir}/bower_components/selectize/dist/less/selectize.bootstrap3.less
...
9, column 27:
48 @selectize-border: 1px solid @input-border;
49 @selectize-border-radius: @input-border-radius;
50
```

I can use the css related file, of course, but i'd prefer to use the less one for maintenance reasons

**Comment by ajahongir** [comment]
same issue tried to order loading files no results.

**Comment by Remuwon** [comment]
You could try importing bootstraps variables.less file before importing selectize.bootstrap3.less file

**Comment by amakhrov** [comment]
@Remuwon +1
@riccardolorenzon does it solve the issue?

**Comment by Remuwon** [comment]
This is how I compile the less files.

In my grant file I define the less task like this, I also have an assets folder in which I write less scripts to customize/override some of the things done in the libraries

``` javascript
        less : {
            development : {
                options : {
                    compress : false
                },
                files : {
                    './app/webroot/css/lib/selectize/selectize.css' : './assets/stylesheets/selectize.less',
                    './app/webroot/css/lib/selectize/selectize.bootstrap3.css' : './assets/stylesheets/selectize.bootstrap3.less',
                    './app/webroot/css/lib/bootstrap-switch/bootstrap-switch.css' : './assets/stylesheets/bootstrap-switch.less'
                },
            },
        },
```

In my assets/selectize.bootstrap3.less which is run to compile selectizebootstrap this is what I do

``` less
@import "../../bower_components/bootstrap/less/variables.less";
@import "../../bower_components/bootstrap/less/mixins/nav-divider.less";
@import "../../bower_components/selectize/dist/less/selectize.bootstrap3.less";
```

This solves the issue for me
