### ISSUE TITLE
onDelete callback is not fired when using the Tag Delete Button plugin

### ISSUE THREAD

**Issue by jasondavis** [selectize/selectize.js#904]
onDelete callback is not fired when using the Tag Delete Button plugin

**Comment by PhiLhoSoft** [comment]
I just tested in the following plunk: http://plnkr.co/edit/v2v9CYfDa0B5TR003s5y
And I can see the onDelete (and onChange) event fired when I remove a tag with the button.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
