### ISSUE TITLE
Support for Bootstrap 4

### ISSUE THREAD

**Issue by dtamm** [selectize/selectize.js#905]
A support for Bootstrap 4 would be very nice (i know, it's still in alpha version, but later on, when the beta comes out i would be happy!)

**Comment by joallard** [comment]
Yup, a theme could probably be made

**Comment by mlensment** [comment]
Any progress on this?

**Comment by simmerz** [comment]
Do you know if anyone has started work on this or is it still completely open? Now that v4 is in Beta, the featureset won't be changing (much), so is a much slower moving target than the alphas.

**Comment by papakay** [comment]
Hello folks, I published Bootstrap 4 Theme (SCSS) for Selectize. You can get it here https://github.com/papakay/selectize-bootstrap-4-style

**Comment by qayyumabro** [comment]
@papakay how to compile it man, didn't know anything about scss files?

**Comment by papakay** [comment]
@qayyumabro SCSS is a CSS extension language. Please check it out here, you will find information that can help you get started [http://sass-lang.com/](http://sass-lang.com/)

**Comment by redroses** [comment]
papakay's theme works for bootstrap 4 beta 3. got it to work today.
just build the selectize.scss and selectize.bootstrap4.scss file into css files.
include them from local dirs.
you can still include bootstrap 4 from a cdn.

thanks papakay.

**Comment by russellhoff** [comment]
It would be very useful.

**Comment by Larsene** [comment]
the Bootstrap theme from @papakay is great. Perhaps you could include it in distribution, and docs and in sample site ?

**Comment by const-se** [comment]
[Improved Selectize Theme for Bootstrap 4.1.3](https://github.com/const-se/selectize-bootstrap4-theme)

**Comment by jmartyniak** [comment]
Is there any plan to add Bootstrap 4 support directly into Selectize?
