### ISSUE TITLE
Title attribute CSS

### ISSUE THREAD

**Issue by wviana** [selectize/selectize.js#909]
Hello there, could you [help me with it](http://stackoverflow.com/questions/32379266/how-to-show-title-atribute-when-using-selectize-js) 

I would like to know if it's possible to show the title for a HTML source anyway.
Or if if there is some way to access the title attribute when creating a custom render.

**Comment by Alex-Sokolov** [comment]
What do you mean?
Show for all options title?
You can set render style for any option and in markup add `title` attribute btw

``` js
$('#123').selectize({
    render: {
        option_create: function (data, escape) {
            return '<div class="create">Добавить инженера <strong>' + escape(data.input) + '</strong>&hellip;</div>';
        },
        option: function (item, escape) {
            var label = item.text;
            return '<div title="' + item.value + '">' +
                '<span class="">' + escape(label) + '</span>' +
            '</div>';
        }
    },
...
```
