### ISSUE TITLE
 set multiple values of selectize object with multiple tags

### ISSUE THREAD

**Issue by naintome** [selectize/selectize.js#911]
I have the dilemma that I assign API through a single value, but I require to insert multiple values such as get
I can get the values of selectize object, I get a vector

-> Current Value: ["CA", "WY", "AK"]
keep these values in a database in a varchar field "CA,WY,AK", and then do a query on an empty Selectize want to insert multiple tags

```
var $select_country = $('#id_input_countrys ').selectize({
                   plugins: ['remove_button'],
                   delimiter: ',',
                   persist: false,
                   options: countryresult ,
                   labelField: "label",
                   valueField: "value",
                   sortField: 'label',
                   searchField: 'label'

               });

$select_country[0].selectize.setvalue ("CA", "WY", "AK");
```

but it does not work
I can make it work

```
$select_country[0].selectize.setvalue ("CA");
$select_country[0].selectize.setvalue ("WY");
$select_country[0].selectize.setvalue ("AK");
```

but as the API said, the previous values are overwritten and only remains me "AK" where "WY" and "CA" disappear.

Is there any way I can assign multiple values in the same selectize?

so after consulting my database, I can show my data stored and the user can edit.

**Comment by naintome** [comment]
Solution for me:

```
                      $select_country[0].selectize.clear();
                       var vectordividido_country = event.IDs_countrys.split(",");
                       for (var i = 0; i < vectordividido_country .length; i++) {
                            $select_country[0].selectize.addItem(vectordividido_country[i]);
                       }
```

too works for me create a new similar:

```
    /**
         *insert to the given value.
         *
         * @param {mixed} value
         */
        setValues: function(value, silent) {
            var events = silent ? [] : ['change'];
            debounce_events(this, events, function() {  
                this.addItems(value, silent);
            });
        },
```

in line 1820 standalone dist selectize.js

for similar logic 
for(...............)
$select_country[0].selectize.setValues(vector[i]);

**Comment by ErnestBrandi** [comment]
I know it's old but anyhow you can pass an array to setValue in the latest version (0.12.6).

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
