### ISSUE TITLE
Load event for multiple select input doesn't work

### ISSUE THREAD

**Issue by papakay** [selectize/selectize.js#917]
Hi!

Great job with the plugin.

Please i'm currently experiencing some itch and i cannot figure out the cause of the issue

I have multiple input field as below

I have a select field for selecting question:

"<select name="question" id="question" class="selectquestion">
                                        <option value="">Choose Question</option>
                                    </select>"

and two select fields for holding the answer.

"<select name="exactAnswer" class="selectanswer"><option value="">Choose Correct Answer</option></select>"

" <select name="figureLessAnswer" class="selectanswer">
                                        <option value="">Choose Correct Answer</option>
                                    </select>"

and this is my js

```
       var chooseOwnQuestion = false;
        var xhr;
        var selectquestion, $selectquestion;
        var selectanswer, $selectanswer;

        $selectquestion = $('.selectquestion').selectize({
            valueField: "id",
            labelField: "question",
            searchField: ["question"],
            onChange: function(value) {
                if (!value.length) return;
                selectanswer.disable();
                selectanswer.clearOptions();
                selectanswer.load(function(callback) {
                    xhr && xhr.abort();
                    xhr = $.ajax({
                        url: 'http://localhost/ngvdesign3/application/data/json_answer.json',
                        success: function(results) {
                            chooseOwnQuestion = false;
                            $('.answerTypeContainer').show();
                            selectanswer.enable();
                            callback(results);
                        },
                        error: function() {
                            callback();
                            $('.answerTypeContainer').hide();
                        }
                    });
                });
            }
        });

        selectquestion = $selectquestion[0].selectize;
        selectanswer = $selectanswer[0].selectize;
```

When a question is selected i want the return answers to be loaded into the two select fields but it's not working that way. It only loads the first select input and leave the other blank. Please what can i do to have the returned answers loaded into the two select fields?

Thank you very much.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
