### ISSUE TITLE
Keeping data or other attributes on options

### ISSUE THREAD

**Issue by CedNet** [selectize/selectize.js#918]
Hi! I started using your excellent script and I found that some of my form handler scripts stopped working because the generated <div> elements used for the dropdown does not include all the original data-attributes and their values. You should really copy all existing attributes of the original option.

An example, this:

```
<option value="25" data-title="Alias." data-interval="30" data-price="995.00" data-resourcedata="">Alias. | 995.00 SEK | 30 min</option>
```

Becomes:

```
<div data-value="25" class="item">Alias. | 995.00 SEK | 30 min</div>
```

Should of course be:

```
<div data-value="25" class="item" data-interval="30" data-price="995.00" data-resourcedata="">Alias. | 995.00 SEK | 30 min</div>
```

Could you maybe invent a quick fix for this?

**Comment by CedNet** [comment]
Saw an open feature request for this. Please add a simple way to retain original attributes.

#239

**Comment by maxi032** [comment]
+1

**Comment by cyphix333** [comment]
Came to ask this exact question...

+1
