### ISSUE TITLE
iOS 9.0.1 bluetooth keyboard autocomplete problem

### ISSUE THREAD

**Issue by priestirix** [selectize/selectize.js#919]
iOS: 9.0.1
Keyboard: Logitech
Browser: Safari

how to duplicate
- go to http://brianreavis.github.io/selectize.js/
- find demo for Max Items.
- remove the States [California] and [Wyoming]
- with bluetooth keyboard start to type in any state.  nothing autocompletes
- with software keyboard start to type in any state.  works as expected.

iOS: 8.3
Keyboard: Logitech
Browser: Safari
- no issues the bluetooth keyboard works as expected.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
