### ISSUE TITLE
Is it possible to have custom valueField when use selected a value?

### ISSUE THREAD

**Issue by angelinacc** [selectize/selectize.js#920]
Is it possible to set value to something custom after user has selected a dropdown? Such as, if user select value, then set valueField as something custom?

Currently I'm using load() to get remote data and I want to avoid modifying the response if possible. Thanks in advance.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
