### ISSUE TITLE
onOptionAdd and load

### ISSUE THREAD

**Issue by kirillkokhv** [selectize/selectize.js#922]
Heloo guys!
Have a problew with onOptionAdd.
I need to save new values when people set new value and click "add".
As I think, i should use onOptionAdd. 
 onOptionAdd: function(value, data){  
         $.ajax({
                url: ... ,
                data: {
                                       ...
                },
                success: function(results) {
                    ...
                },
                error: function() {
                ...
                }
            })*/

```
      } ,
```

But on start I load values to this selectize from my DB, and on each value its fired "onOptionAdd" event.  What is true method to use only "add" click?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
