### ISSUE TITLE
onItemSelect, missing event

### ISSUE THREAD

**Issue by Ramblurr** [selectize/selectize.js#926]
Internaly selectize.js has an `onSelectItem` event. To be clear: this event is fired when the user clicks an item in the list that has already been chosen from the dropdown. The default behavior is to change the background color of the actively chosen item.
- Why isn't this event exposed publicly?

**Comment by EasonPai** [comment]
I want this event badly. 
So far my workaround to this is to add onClick listener on every items manually after onInitialize event is catched.

**Comment by hmrazali** [comment]
@EasonPai mind sharing your solution?
Tried solutions [here](https://github.com/selectize/selectize.js/issues/319) but didn't work.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
