### ISSUE TITLE
Email field crashes Chrome Tab after about 50 characters

### ISSUE THREAD

**Issue by deanblacc** [selectize/selectize.js#927]
If you type enough characters (about 50 or so) into the Selectize email input field, your Chrome tab will become unresponsive and Crash. This holds true for even the example on https://brianreavis.github.io/selectize.js/

Safari seems to work ok. I have yet to try other browsers.

**Comment by vemv** [comment]
Yes, can reproduce in Chrome and Firefox!

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
