### ISSUE TITLE
selectize.js with cocoon

### ISSUE THREAD

**Issue by Kaktusiewicz** [selectize/selectize.js#928]
Hi,
I have spent many days trying to find the working way to read stored values when using cocoon gem in my Rails application and fill the form fileds with them but with no results. Everything is described here:
http://stackoverflow.com/questions/33070190/ruby-on-rails-selectize-js-with-cocoon

Plese help.

Best regards,
Michał

**Comment by vemv** [comment]
Learn to debug using Rails' `pry` and `better_errors` gems.

Please close issue, just look at the issue count. A proper issue would present the problem in isolation, not intertwined with your project code.
