### ISSUE TITLE
How to hydrate using data-data

### ISSUE THREAD

**Issue by dottodot** [selectize/selectize.js#929]
I have populated the data-data attr with json data but this has no effect. Is there another step required or does the data need formatting in a particular way?

**Comment by hozza** [comment]
I'm having the same problem,  I think the `data-data` docs need to be more explanatory.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
