### ISSUE TITLE
feature request - bit operator for filters

### ISSUE THREAD

**Issue by iamtennislover** [selectize/selectize.js#930]
Hi, 1st off, this is a great project. I have used it a lot. However, I had a feature request and see if you would be interested in it...

I would like to selectize to be able to create a logical filter UI like: 
(city=denver OR state=CO) AND (name=foo or age=30)

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
