### ISSUE TITLE
Questions - coming from current select2 user

### ISSUE THREAD

**Issue by morrow95** [selectize/selectize.js#932]
I haven't really jumped into everything yet, but testing out selectize for use in our project (currently using select2).  Few things I haven't really figured out yet which will determine if we can use this or not.

No X clear on the select?  I see you can just use backspace to delete, but having a X seems more user friendly.  Not a deal breaker by any means though.

Most of our use cases are going to use ajax to retrieve results.  I was able to do this easily, but have a few concerns : 
- I notice that selectize will store/cache the results on successive searches.  We would need a 'fresh' result list each time.
- Is there a way to show a 'no results found' message when there is nothing to return from the remote call?
- Paging.  For the remote calls we will sometimes have a large result set.  This in particular is a great feature of select2.  You limit the results returned by your call to say 25... if there are more results than that there is a 'load more' option in the results which when clicked will load another 25.  All you do is send the page limit and page # to your remote call to get the correct 'set' of returns, but of course the functionality to do this in the drop down is needed (ability to add to dropdown list while it is open on click of 'load more'.

Default selected value?  In some cases we are preloading a selection in our html which works fine, but we need to give the user the ability to revert back to this default if need be.  So say they delete their current selection, it would automatically go back to the default similar to a placeholder, but with an actual value associated with it so that value is sent with the form if used.

**Comment by morrow95** [comment]
Regarding the default value I came up with a solution... I just store the initial value in js and reset it on dropdown close if it is empty : 

```
var default_value = $("#selectize").val();

$('#selectize').selectize({
    onDropdownClose:function() {
        if(this.getValue() == '') {
            this.setValue(default_value);
        }
    },
...
...
```

If there is another way please chime in.  Also interested to hear regarding the paging in the remote results... that is a necessity for us due to result size which may come back.

**Comment by mcavalletto** [comment]
You can add an "X" to each selected item by specifying `plugins: ['remove_button']` in your selectize setup call.

I think that the other features you describe will require the addition of new code via custom plugins.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
