### ISSUE TITLE
onDropdownClose not being hit every time?

### ISSUE THREAD

**Issue by morrow95** [selectize/selectize.js#935]
I've added a `onDropdownClose` to perform some logic each time the dropdown is closed to check if the value is empty and if so, set it to a default value.

The code works, but I've found that `onDropdownClose` is only being triggered every other time instead of each time.  I have created a fiddle at https://jsfiddle.net/Ld5d08pv/5/ to show this.

By default it will show Stephen... click on it, hit backspace, then click out of the dropdown to close... nothing happens.  Now click on the empty input and click out of it... it will trigger and will correctly revert back to Stephen.  I also noticed if you click, start typing anything, then backspace everything, and click out it will work every time.  It is almost as if you HAVE TO type something for this to be triggered on close.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
