### ISSUE TITLE
Clear the intial options listed in 'selectize-dropdown-content'?

### ISSUE THREAD

**Issue by morrow95** [selectize/selectize.js#937]
I'm using ajax to remotely get results.  I noticed that on initial click of the select and when the current selection is cleared with a backspace it seems that all the previous results/options seem to be cached and shown in this state.  When you start typing they disappear and show correct results depending on the search though.

They are all populated in .selectize-dropdown-content within the html.

Is there a way to prevent this behavior?  I can see this being useful when NOT using ajax, but when you are it doesn't make sense and I can see the users being confused.  I only load one option in my html (everything else is retrieved through ajax) so if anything only that one option should show.

**Comment by armandoxxx** [comment]
on dropdown close event ;) 
//clear options that are not selected
if (!$theDropdown.is(':visible')) {
        var self = this;
        $.each(self.options, function(theIndex, theItem) {
            if ($.inArray(theItem.value, self.items) === -1) {
                self.removeOption(theItem.value);
            }
        });
    }
//on remove item event
call selectize.removeOption(item)

**Comment by ikarynerv** [comment]
$('#myobject').selectize({
...bla.bla.bla...

,onDropdownClose: function() {
        this.clearOptions();
}
});

**Comment by bmmpt** [comment]
With this code, when I select an option it doesn't really get selected, the input box is cleared

**Comment by Riddhi-Vithalani** [comment]
thank you ikarynerv, which i need i get it.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
