### ISSUE TITLE
Any suggestions for removing hierarchical indentations?

### ISSUE THREAD

**Issue by booruguru** [selectize/selectize.js#938]
I am displaying my select list as a hierarchy of terms, child terms are indented according to their level in the hierarchy. 

My site uses hyphens, but Markdown was screwing up my example, so I used periods instead.

For example,
Parent
. child 1
.. grandchild 1
.. grandchild 2
.. grandchild 3
. child 2
. child 2

...
I'm looking for a way to remove the hyphen/indentations through JavaScript (or some other means) when it's displayed as tag within the text field... while preserving the indentation when revealing the dropdown list.

Any suggestions?

**Comment by mcavalletto** [comment]
It sounds like you need to provide a custom `render: { item: function ( data, escape ) { ... } }` routine that converts an option data object into an HTML element, as described in [the Usage docs](https://github.com/selectize/selectize.js/blob/master/docs/usage.md).

The default rendering function is defined in the setupTemplates method:`
'item': function(data, escape) {
                    return '<div class="item">' + escape(data[field_label]) + '</div>';
                }`

Your function should do something similar, after modifying the value from `data['text']` to strip out the unwanted portions.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
