### ISSUE TITLE
Drag&Drop between Inputs

### ISSUE THREAD

**Issue by samuelsolis** [selectize/selectize.js#940]
I have to drag and drop items between differents inputs. Can I do it? The usual darg and drop option is only between items inside the same input.

![selectize_suggest](https://cloud.githubusercontent.com/assets/3817887/10761460/c48c609c-7cc1-11e5-8f2c-feab24b2a951.png)

How can I do this feature? I need to create a new pluggin or something similar?

Thanks in advance

**Comment by aggregatejeff** [comment]
I can't help, but I'm struggling with this too so I'll add my voice.

**Comment by joallard** [comment]
The drag plugin is implemented using jQuery UI Sortable. You'll probably find this SO question relevant:
http://stackoverflow.com/questions/307411/how-do-i-connect-multiple-sortable-lists-to-each-other-in-jquery-ui

I will close this so it's not on the Issue to-do list anymore, but feel free to post updates if it helps others.
