### ISSUE TITLE
Table within a table in the documentation

### ISSUE THREAD

**Issue by davidbgk** [selectize/selectize.js#941]
Not sure if it's a bug but at the end of the page the rendering is not optimal because of a table within a table: https://github.com/brianreavis/selectize.js/blob/master/docs/usage.md#rendering

I can fix it if you confirm that's it's not the right rendering.

**Comment by joallard** [comment]
I changed it today, it's nested but functional. Did you have another idea?

**Comment by davidbgk** [comment]
It's definitely better, thanks!
