### ISSUE TITLE
tab to select exact match

### ISSUE THREAD

**Issue by booruguru** [selectize/selectize.js#945]
When I search a select field, if my text string is an exact match to a field...pressing enter will select the value, but press tab deletes my text and leaves the field empty while moving on to the next form field.

I think this is a big problem. If my text is an exact match to the select/option name, I should have to press enter before I can tab to the next field.

Selectize.js is an otherwise fantastic script. Keep up the good work.

**Comment by TASimpson** [comment]
I am having the same issue...have you found a solution for this yet?

**Comment by vppetrov** [comment]
I have the same issue. Has anyone found a solution?

**Comment by vppetrov** [comment]
I found the solution: add selectOnTab: true in the configuration

**Comment by joallard** [comment]
We should probably change that default

**Comment by rbu** [comment]
please do, it's rather confusing this happens, even on the demo page

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
