### ISSUE TITLE
How to keep the value filled without adding it ? 

### ISSUE THREAD

**Issue by marclou** [selectize/selectize.js#948]
I am working on a form where you can fill your first name, surname, email, etc... for several persons.
When you fill your first name, you  can "add" it with the selectize plugin, thanks to that you can easily auto filled the name for another person.

My problem is that when you don't add it, you go to the next field and the value is deleted. That means the dropdown_close delete the value' field if not added.

Do you have an idea how to solve that ? 

Thanks in advance,

Marc

**Comment by mcavalletto** [comment]
It sounds like you want to set the createOnBlur option to true. 

> If true, when user exits the field (clicks outside of input or presses ESC) new option is created and selected (if `create`-option is enabled).
> -- https://github.com/selectize/selectize.js/blob/master/docs/usage.md

**Comment by joallard** [comment]
thanks @mcavalletto

**Comment by hotcakedev628** [comment]
Hello, @mcavalletto , @joallard .
I have the similar issue, but different.
Is there a way to keep the value without add the value to the list?
