### ISSUE TITLE
Style for FezVrasta/bootstrap-material-design?

### ISSUE THREAD

**Issue by thearabbit** [selectize/selectize.js#950]
Style for FezVrasta/bootstrap-material-design?

**Comment by joallard** [comment]
Sorry, I don't understand your question. If you still need help with this, please reopen and give us a few hints with your issue.

**Comment by chase439** [comment]
I'm looking for the same thing. Could I request a style that could work well with https://github.com/FezVrasta/bootstrap-material-design theme? It's a combination of material design and bootstrap.
