### ISSUE TITLE
Dropdown List width configurable from options object

### ISSUE THREAD

**Issue by ikoichi** [selectize/selectize.js#951]
Hi,

I think it was present in previous versions, but no more in version 0.12.1
Please, allow to set the width of the dropdown list in the options object.
Overriding the `.selectize-dropdown` class is not enough because I need a different width according to the dropdown.
Thank you,

`
.selectize({
    width: 300
})
`

**Comment by pasqualevitiello** [comment]
+1

**Comment by moacir-selinger** [comment]
+1

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
