### ISSUE TITLE
Drowdown with checkbox

### ISSUE THREAD

**Issue by freemiumdev** [selectize/selectize.js#952]
how can I enter the checkbox in the dropdown menu?
I need to be able to select multiple options and then take the values.
like this
![casasa](https://cloud.githubusercontent.com/assets/6906254/11307846/0edfacec-8fbb-11e5-8695-31e5c68ddbd8.PNG)

thanks

**Comment by mcavalletto** [comment]
Selectize.js does not present options as checkboxes; you would have to create a new plugin to add this feature.

**Comment by joallard** [comment]
+1 Thanks @mcavalletto

**Comment by MahmoudNasserGouda** [comment]
I have been searching for a plugin to do just that (add a checkbox beside each option in a multi selection selectize dropdown), but i haven't found any so far. Is something like this available now? do you have any recommendations?
