### ISSUE TITLE
What is the purpose of autoGrow?

### ISSUE THREAD

**Issue by jfly** [selectize/selectize.js#953]
I see that it was added in https://github.com/brianreavis/selectize.js/commit/01522dd13f156c5ddf9a075bab5b8cfab8362761, but there's no explanation why it's needed.

With autoGrow, you can see that the true size of the input is pretty small, and clicking on all that whitespace behaves pretty strangely (I'm used to triple clicking in the whitespace of an input to select all, which doesn't work here):

![2015-11-20_1205x98_kaladin](https://cloud.githubusercontent.com/assets/277474/11317238/e245f7b0-8fdb-11e5-9e1b-195cf78cba9d.png)

With autoGrow disabled, and the input's width set to 100% (see this [commit](https://github.com/jfly/selectize-rails/commit/b77ece51920679fc7cc2e4a886e08150288654d3)), I see a full sized input and normal clicking behavior. I have not noticed anything breaking as a result of this.

![2015-11-20_1191x117_kaladin](https://cloud.githubusercontent.com/assets/277474/11317245/20546ef6-8fdc-11e5-99c1-d75d8303575e.png)

I must be missing something obvious. What have I broken by disabling autoGrow?

**Comment by joallard** [comment]
It has to do with sizing the invisible input properly when there are tags before it. If width was 100% it would overflow.

**Comment by jfly** [comment]
When would there be tags before the invisible input?

**Comment by joallard** [comment]
~~How else would you want to enter multiple tags in the box?~~ I read 'why'

When there are >=1 tag in the box and you're entering another

**Comment by jfly** [comment]
Ah, good point! I had forgotten about tags entirely. Here's another reason why `autoGrow` exists. selectize.js moves the input around as you move your caret position between tagged elements. We don't want this new typing area to take up any more space than it has to, or it would push other tags far out of position:

![image](https://cloud.githubusercontent.com/assets/277474/11583649/e765e220-9a10-11e5-938a-ae33402bec22.png)

What if `autoGrow` sized the `$input` to take up all the space in it's parent div, if and only if the current caret position is at the end?

**Comment by joallard** [comment]
Not sure I understand where you're going with this nor am I sure whether that would work

**Comment by jfly** [comment]
As mentioned in the original post, this is about preserving the triple-click-in-whitespace-to-select-all behavior of inputs, which selectize does not currently have.

**Comment by joallard** [comment]
Can't believe I hadn't read that.

> What if autoGrow sized the $input to take up all the space in it's parent div, if and only if the current caret position is at the end?

If there's a tag/element before the `$input`, wouldn't a width 100% still overflow?

**Comment by jfly** [comment]
Sorry, I meant all the remaining space in it's parent div. I suppose this would be tricky, as we'd have to deal with the parent div potentially resizing.

**Comment by pituki** [comment]
I am needing the full size text box for pasting content, and am looking into maybe making it optional. Please let me know if it is a good idea.
I really appreciate the micro-plugin system, i have created about 5 plugins for different uses. Great work

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.

**Comment by jfly** [comment]
As far as I know, selectize still has this less than ideal behavior when trying to triple click to select all the text in an input. I personally would still like to see something done about this.

**Comment by risadams** [comment]
Thanks for the feedback,  we will re-open and review when possible.  
In the meantime if you would like to take a stab at making the change and submitting a PR it would be welcomed.
