### ISSUE TITLE
The height is increasing when adding item using addItem

### ISSUE THREAD

**Issue by nidheesh1994** [selectize/selectize.js#954]
I use addItem to add items to selectize single select. But after adding the item. The height of the field is increased like it is expecting another field. How to correct this issue?
I am attaching the files. 
![before](https://cloud.githubusercontent.com/assets/16012583/11391020/49e85f42-9375-11e5-9437-1c5bdab8542e.png)
![after](https://cloud.githubusercontent.com/assets/16012583/11391012/3166faa0-9375-11e5-9251-e11c6e654325.png)

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
