### ISSUE TITLE
Inactive API key for Rotten Tomatoes

### ISSUE THREAD

**Issue by philgruneich** [selectize/selectize.js#955]
API call as is in the [example](https://github.com/brianreavis/selectize.js/blob/master/examples/movies.html) returns `{"error":"Account Inactive"}`.

For instructions on how to act, [please check this thread](http://developer.rottentomatoes.com/forum/read/184509).

> If the API key has recently stopped working, a new key was added to an existing account, or a new account was created, send an email to API-admin@flixster-inc.com with the following information.
> - How are you planning on using the data?
> - How are you using the API in your app/website? Is the data being cached?
> - Provide mocks of the app/website with the RT API integration following the Brand Guidelines.
> - What is the estimated number of monthly users?
> - Provide a country of origin for your app/website.
> - Your API Username and Email address
> 
> You can find the Brand Guidelines at the following link: http://developer.rottentomatoes.com/docs/brand_guidelines

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
