### ISSUE TITLE
changing messages lang

### ISSUE THREAD

**Issue by prtome** [selectize/selectize.js#956]
hello
My user community does not speak english. Is there a way to change the messages like Add to the users lang (as given by the browser for example) ? 
I looked at the code and it seems to be hard coded, so I was wondering if I missed something and there is a way to do this ?
Or the simplest way is to go to that line of code and change it ?
Thanks

**Comment by ruinobreferreira** [comment]
To have localization it would be really nice to have.
But you can do this:

```
        $('.selectized-tags').selectize({
            render: {
                option_create: function(data, escape) {
                    return '<div class="create">' + this.$input.data('create-label') + ' <strong>' + escape(data.input) + '</strong>&hellip;</div>';
                }
            }
        });
```

And you have to add the data-create-label on your control:

```
<select class="selectized-tags" name="tag_list[]" data-create-label="My text:" multiple="multiple" >
```

**Comment by prtome** [comment]
Thanks ! it works but I had to change create-label to create_label  - I have seen in other case in my code that it does not like "-" in the data
