### ISSUE TITLE
Set maxItem on input/select data attribute

### ISSUE THREAD

**Issue by ruinobreferreira** [selectize/selectize.js#957]
It would be nice to set the maxItems option with a data attribute like

```
<select name="tag_list[]" data-max-items="3" multiple="multiple">
```

**Comment by emman-ok** [comment]
The multiple attribute works but the maxItems not working. Would be nice if added

**Comment by wajdijurry** [comment]
+1

**Comment by wajdijurry** [comment]
Hi,

you can do it as follow:

1- open 'selectize.js', and search for 
```
if (self.plugins.names.length) {
```
2- add this code after it:
```
if (typeof settings.maxItems === 'function') {
    settings.maxItems = settings.maxItems($input);
}
```
3- anywhere in your project, when you apply selectize to drop down element, and you want to use data attribute to set the maxItems number, do this:
```
$(element).selectize({
    maxItems: function(input){
        return input.data('max-limit');
    }
});
```

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
