### ISSUE TITLE
How to extend options in selectize.js?

### ISSUE THREAD

**Issue by maximusDreddoff** [selectize/selectize.js#958]
I have this callback function, which creates list of categories on my page.

> this.getCategoryAdCount(function (categories) {
>     //added selectize plugin to display multiply choice
>     var values = categories.map(function (cat) {return { item : cat.id, text : cat.name + ' (' +cat.count + ')'}; }); //this is my data from the server
>    this.$filtercat.selectize({
>       plugins: ['remove_button'],
>       delimiter: ',',
>       persist: false,
>       maxItems: 5,
>       options: values,
>       labelField: "text",
>       valueField: "item",
>       sortField: 'text',
>       searchField: 'text',
>       create: function(input) {
>         return {
>           value: input,
>           text: input
>         }
>       }
>     });
>   }.bind(this));

It works good, but I have already existing function, which calls .selectize on every $('select') element on my page

>  $('select').each(function(k, v) {
>     var el = $(v);
>     var options = SJA.Config.selectizeOptions;
>     el.selectize(options);
>   });

In this config I have list of options

> selectizeOptions: {
>   persist: true,
>   maxOptions: 99999,
>   dropdownParent: 'body',
>   sortField: false,
> },

So I don't want to call .selectize once again inside my callback function. Is it possible to extend somehow options only for the this.$filtercat variable without calling .selectize ?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
