### ISSUE TITLE
Why I can't see new value in selectize.js?

### ISSUE THREAD

**Issue by maximusDreddoff** [selectize/selectize.js#959]
Good Day!

I have this method in my project

> getCategoryAdCount: function (callback) {
>     var that = this,
>         dataToSend = {
>           method: 'getCategoryAdCount',
>           params: {
>             productId: this.productId
>           }
>         };
> 
>    SJA.ajax(dataToSend, function (respond) {
>           if (respond) {
>             callback && callback(respond);
>        }
>     });
>   },

Below this text you can see my Callback function. This function creates new values inside select field (using data from the server). I call getCategoryAdCount function with this callback every time I change content on the page.

> ```
>  this.getCategoryAdCount(function (categories) {
>     //add selectize plugin to display multiply choice
>     var values = categories.map(function (cat) {return { item : cat.id, text : cat.name + ' (' +cat.count + ')'}; });
>   //id,name,count- this information I receiving from the server
>     var categorySelect = that.$modal.find('.cat-post')[0].selectize;
>     for (var i in categories) {
>       categorySelect.addOption({value: categories[i].id, text: categories[i].name});
>     }
>     this.$filtercat.selectize({
>       plugins: ['remove_button'],
>       delimiter: ',',
>       persist: false,
>       maxItems: 5,
>       options: values,
>       labelField: "text",
>       valueField: "item",
>       sortField: 'text',
>       searchField: 'text',
>       create: function (input) {
>         return {
>           value: input,
>           text: input
>         }
>       }
>     });
> ```

My main problem is variable values. When I refresh server's data  cat.count stays the same(with the old value of count) until I reload the page. I don't understand how can it be, because I am receiving always refreshed values(I can see it in the console)on page's change.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
