### ISSUE TITLE
How to prevent data rearrangement?

### ISSUE THREAD

**Issue by mikedatsko** [selectize/selectize.js#960]
#### Bug

I have a big list (> 100 items) in dropdown and when I click on the first items (viewed scroll) the Selectize working good. But when I click on the item below and much below of the list my dropdown is going to rearrange and you'll see a new items, always.
#### Reason

I inspected the behavior of the list and I saw that list is going to rebuild. Maybe this is the reason.
#### Selectize options:

``` javascript
$select = $(domObject).selectize({
        labelField: 'value',
        searchField: 'value',
        persist: true,
        ignoreBlur: true,
        score: function(search) {
            return function(item) {
                return parseInt(item.count);
            };
        },
        onBlur: function() {
            console.log('blur');
        },
        onType: function(value) {
            console.log('type', value);
        },
        onChange: function(value) {
            console.log('change', value);
        },
        onItemAdd: function(value, $item) {
            console.log('item add', value, $item);
        },
        onOptionAdd: function(value, data) {
            console.log('option add', value, data);
        },
        onLoad: function(data) {
            console.log('on load', data);
        },
        render: {
            option: function(item, escape) {
                return '<div>' +
                  escape(item.value) +
                  " (" + escape(item.count)) + ")" +
                  "</div>";
            }
        },
        initData: true
    });
```
#### P.S.

Maybe it will be better just remove the selected item from the dropdown list or add some event handler for that (rebuilding the list) in options?

**Comment by joallard** [comment]
I don't understand the issue reported. Can you tell us more about what you expected and what happened instead?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
