### ISSUE TITLE
clear the added items in the select lists

### ISSUE THREAD

**Issue by prtome** [selectize/selectize.js#961]
hello,
I am doing some tests to see how to use in my code, i have very simple needs as seen in 
my jsfiddle  http://jsfiddle.net/w8amtsj9/3/

my problem is that if I add a value, either in the input field (the first one) or in the select, these values are not completely cleared, They are proposed to me when I enter a new value. Even after the call to clear.
For the input field I suppose it is the browser behaviour , but for the select list ? should I do something else to clear those values  in that list ? 
Thanks for any pointer

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
