### ISSUE TITLE
Feature request: Select All?

### ISSUE THREAD

**Issue by zlatevbg** [selectize/selectize.js#962]
Hi,

is it possible to add a "Select All" functionality?

Thanks.

**Comment by mcavalletto** [comment]
Do you want to select all all of the current items, or all of the available options?

Currently, pressing command-a while in a multiple-select control will select all of the active items, at which point you can delete them all.

It looks like selecting all of the available options and adding them to the active items list will require a new plugin.

**Comment by heyaustinwood** [comment]
+1

**Comment by ancabury** [comment]
As a workaround for the "Select All" functionality, you could use a js function for `ctrl+a`.

I created this function which adds all the available options, to the active items array:

```ruby
$('#my-select').keyup(function(e) {
    if (e.ctrlKey == true) {
      if (e.keyCode == 65 || e.keyCode == 97){
        var el = el=$('#my-select')[0].selectize;
        var optKeys = Object.keys(el.options);
        optKeys.forEach(function (key, index) {
          el.addItem(key);
        });
      }
    }
  });
```

**Comment by madhukarhere** [comment]
Thank you @asarbu You work around is very useful and helped to completed the select all functionality.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
