### ISSUE TITLE
Latin accents

### ISSUE THREAD

**Issue by YnievesDotNet** [selectize/selectize.js#963]
I have trouble with latin accents, for examples, my code have the params name like this _Am&eacute;rica_, but the selectize how like as, and not as _América_, HOw i can fix this?

Thanks.

YnievesDotNet

**Comment by YnievesDotNet** [comment]
Fixed:
foreach ($countries as $country) {
            $country->name = html_entity_decode($country->name);
        }
this change the &aacute, for example at \u00e1, and the error disappear at selectize control

**Comment by dacsy** [comment]
What is html_entity_decode doing in this case ?
I am having same problem than you, I cannot search with accent. Could you give me your advise how to solve this problem ?

**Comment by YnievesDotNet** [comment]
In me case I fix that. How is your enviroment?
