### ISSUE TITLE
Dropdown shows irrelevant items

### ISSUE THREAD

**Issue by lazandrei19** [selectize/selectize.js#965]
The dropdown archives previous searches and shows unwanted items. Here is a representation: ![](https://i.imgur.com/xrYEbJW.png)

If it helps with anything, this is my configuration: ![](https://i.imgur.com/3rBmHn5.png)

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
