### ISSUE TITLE
Dropdown does not display after losing focus, clicking on the selected pill, and clicking on the input.

### ISSUE THREAD

**Issue by codewarrior415** [selectize/selectize.js#968]
Steps:
1. use a multi-select.
2. Select one item from the dropdown.
![screen shot 2015-12-09 at 9 30 19 am](https://cloud.githubusercontent.com/assets/960135/11693052/87c982a4-9e57-11e5-906b-b43441c2cd85.png)
3. Click out side of the selectize component so it loses focus.
![screen shot 2015-12-09 at 9 31 27 am](https://cloud.githubusercontent.com/assets/960135/11693069/a8128b32-9e57-11e5-8b2c-e04e9e8b2f45.png)
4. Then click on the selected pill.
![screen shot 2015-12-09 at 9 32 01 am](https://cloud.githubusercontent.com/assets/960135/11693083/bbc8a904-9e57-11e5-9af7-b8531e030c84.png)
5. Then click on the input field. Notice that the dropdown doesn't show.
![screen shot 2015-12-09 at 9 33 21 am](https://cloud.githubusercontent.com/assets/960135/11693109/e9108382-9e57-11e5-9a42-69dedeea78e7.png)

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
