### ISSUE TITLE
Only show "create" option after "load" has called back

### ISSUE THREAD

**Issue by skerit** [selectize/selectize.js#969]
When you type something in selectize, and you have the "create" option enabled, it'll immediately show the "Add ..." option, even though the "load" function is still waiting for response from the server.

Is there a way to make "create" wait on "load" to call back?

**Comment by bytestream** [comment]
+1

I did come across this http://stackoverflow.com/questions/24366365/creating-an-item-if-not-already-exists-in-selectize-js-select-box-and-ajax-updat but the function never seems to run using the below:

``` javascript
$('.assign-tags').selectize({
        plugins: ['remove_button'],
        valueField: 'id',
        labelField: 'name',
        searchField: [ 'name' ],
        create: function(input, callback) {
            $.get(searchRoute, { q: input })
                .success(function(res) {
                    if (typeof res.data !== 'undefined' && typeof res.data[0] !== 'undefined' && res.data[0].name == input) {
                        return callback();
                    } else {
                        return callback({ id: res.data[0].id, text: res.data[0].name });
                    }
                });
        },
        maxItems: null,
        placeholder: 'Type in tags...',
        render: {
            option: function(item, escape) {
                return '<div>' + escape(item.name) + '</div>';
            }
        },
        load: function(query, callback) {
            if (!query.length) return callback();

            $.get(searchRoute, { q: query })
                .done(function(res) { callback(res.data); })
                .fail(function() { callback(); });
        },
});
```

**Comment by joallard** [comment]
It would seem to me like this should be the default. If I'm typing the tag "javascript", given the tag exists on the server, then while the Ajax request is made, why would I get the option to add it, given it's going to show up in 50ms–2s? I wonder if there's a use case for the contrary.

**Comment by NickolayCh** [comment]
Any news on this issue?

**Comment by bytestream** [comment]
Not from me.

@joallard any thoughts several months later?

**Comment by joallard** [comment]
I'd accept a PR for this, changing the default behavior, and ensuring we have some UI feedback about the callback "loading".

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.

**Comment by bytestream** [comment]
@risadams suggest to turn on stale bot, will save you a lot of effort

**Comment by risadams** [comment]
@bytestream yep, we've considered that, but I would prefer to do it manually until the project is in a more stable state
