### ISSUE TITLE
Clear selected item on keypress

### ISSUE THREAD

**Issue by brownbl1** [selectize/selectize.js#971]
Currently, when a selectize receives focus and an item is already selected, the user must hit backspace to clear the existing selection before they can start filtering the options. Keypress does nothing until backspace is hit.

I would like to add an option for alternate behavior, namely that when an item is selected and the user punches a key, it would automatically clear the selection and fill in their keystroke to begin filtering. 

If this is an enhancement that sounds favorable, I can submit a pull request. I simply modified this section at the bottom of `onKeyDown`:

**Current**

``` js
if ((self.isFull() || self.isInputHidden) && !(IS_MAC ? e.metaKey : e.ctrlKey)) {
  e.preventDefault();
  return;
}
```

**Proposed**

``` js
if ((self.isFull() || self.isInputHidden) && !(IS_MAC ? e.metaKey : e.ctrlKey)) {
  if (self.settings.clearOnSearch) {
    self.clear();
  } else {
    e.preventDefault();
  }
  return;
}
```

A fiddle demonstrating the behavior is here: https://jsfiddle.net/itslittlejohn/jodhj939/1/

This is a naive implementation, but if the idea is acceptable, I'll re-work it to be more robust as well as do more testing.

**Comment by brownbl1** [comment]
Alternately, I could try reworking this as a plugin, but I'm not sure what the criteria is for what goes in as a plugin and what gets integrated into the baseline.

**Comment by joallard** [comment]
As a general rule, we try to keep the plugin simple as maintaining such a large codebase is a lot of work. I think a feature should go in only when enough people as a percentage of total users expect such a feature to be in the library. I'm not sure your feature is in high demand enough to add another setting. For now I'd recommend making a plugin, and we can integrate the feature if it gets asked a lot.

**Comment by brownbl1** [comment]
Alright. I'll begin reworking it as a plugin and post a pull request when
it's ready.

**Comment by cristianszwarc** [comment]
@itslittlejohn thanks!, let me know where this change ends, I'm looking for this same behavior but only on some specific places.

**Comment by bogdancss** [comment]
any progress on this?

**Comment by brownbl1** [comment]
Unfortunately I haven't had time. I can post a snippet of the changes that we're using for the time being if that would be helpful for those who would rather not wait or would like to work on it themselves. Just let me know!

**Comment by bogdancss** [comment]
Yep, that would be very helpful, thank you!

**Comment by bogdancss** [comment]
actually, I managed to find a plugin for this. Check @ #748

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
