### ISSUE TITLE
when selectize is disabled on a form, submits do not pick up its value

### ISSUE THREAD

**Issue by sc1478** [selectize/selectize.js#972]
I wish to populate a selectize list with values that are sometimes editable by the user and sometimes not.  In the latter case, though, the form submission does not pick up the value

**Comment by joallard** [comment]
Does the input have the attr `disabled`? If so, it is in the web spec that forms cannot submit the value of a disabled field.

If that is not the issue, please post a Jsfiddle/Codepen demonstrating the issue.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
