### ISSUE TITLE
How to change the selected value's text?

### ISSUE THREAD

**Issue by franklinjoseph** [selectize/selectize.js#973]
How can i change the text of a selected value? Eg: i have a scenario where i have to change the text to "something ...." if the default text is "something something something"(ie - more than 15 chars). How can i achieve this? Thanks

**Comment by joallard** [comment]
You would probably modify the way items are rendered, this is not implemented for now, but could be done with a plugin.

**Comment by franklinjoseph** [comment]
Hi.. Thanks for your time.
What i did is  - "item" is the class that holds the value. So i altered innerHTML value of this class according to my needs. Not the appropriate way. But works fine. Thanks.
