### ISSUE TITLE
Refactor: Break down into components

### ISSUE THREAD

**Issue by joallard** [selectize/selectize.js#974]
As I've realized when wanting to hack around the plugin, is that Selectize could be broken down into different components, that could then be used individually as need be. These components would do one thing and do it well. Then Selectize would simply be the right combination of those, still working out of the box.

Main blocks I've been able to identify:

**ItemInput**&emsp; Behaves like a text input, can contain items (elements, eg inline-blocks, tags) as well as text. Knows how to serialize its contents into a string value for submission.

``` coffee
ItemInput =
  options:
    onType: (char, value) ->

  add: (item) ->
  value:
```

**Select**: behaves like a regular select, has an arrow and displays a Dropdown

**Dropdown**: Displays a box with suggestion DOM elements under an input element. Elements can be focused and selected. Knows how to render items. Can group items.

``` coffee
Dropdown =
  options:
    renderItem: (item) ->
    onSelect: (item) ->
    onFocus: (item) ->

  open: (maybeList) ->
  close: ->

  # private
  _populate: (list) ->
```

**Autocomplete**: Can suggest entities based on partial search, and highlight relevant parts in suggestions

``` coffee
Autocomplete =
  options:
    dataSource:
    onSuggest: (suggestions) ->

  feed: (input) ->
```

Composed into:

``` coffee
SelectizeElement =
  setup: ->
    input.on 'type', autocomplete.feed
    autocomplete.on 'suggest', dropdown.open
    dropdown.on 'select', input.add
```

(Don't mind me, using Coffeescript to pseudocode an API. Arrow means function.)

**Comment by atav32** [comment]
Totally dig this. I feel like it's backwards to have to write a plugin to disable the input component so that I can use selectize as only a fancy select field. (Maybe I'm misunderstanding some options?)

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
