### ISSUE TITLE
Drop up plugin

### ISSUE THREAD

**Issue by Samsinite** [selectize/selectize.js#975]
Wrote a drop_up plugin to make selectize position above the input instead of below. Would you be interested in a PR to add it to the official plugins?

**Comment by joallard** [comment]
That just prompted me to start #976 ;)

**Comment by xwilders** [comment]
Hi Samsinite: I'd love to be able to use that plugin if you still plan on adding it!

**Comment by Samsinite** [comment]
@xwilders Is this still something you are interested in? I can bug a co-worker for the code that her and I paired on.

**Comment by xwilders** [comment]
Still interested, yes :)

**Comment by elynnaie** [comment]
@Samsinite The code for this plugin would be great, if you are still able to get it. Otherwise it looks like I'll be rolling my own for the time being.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
