### ISSUE TITLE
Tabindex to the items' remove button

### ISSUE THREAD

**Issue by Pictor13** [selectize/selectize.js#978]
I am trying to get the best from Selectize regarding accessibility tabbing.
I just incurred in this line on the _remove_button_ plugin:

> https://github.com/selectize/selectize.js/blob/master/src/plugins/remove_button/plugin.js#L28

I was wondering if there is a specific reason/explanation for keeping the remove buttons with `tabindex="-1"`, because currently it prevents the Selectize to be managed exclusively via keyboard.

And maybe it could be changed to have an option for allowing tabindex on single items, improving accessibility.
But I'd like to be sure it is not needed for something I overlooked.

Anyway, really nice and useful piece of code ;)

**EDIT**
Noticed it is possible to remove the items moving with the _left/right-arrow_ keys and pressing _backspace_.
While this is fair/flexible enough I am not sure if this is sufficient for a person with disabilities (that, I guess, usually expects to have a visual feedback directly on the item that _he is working on; and I believe that the item should be able get *:focused_).

**Comment by joallard** [comment]
> Noticed it is possible to remove the items moving with the left/right-arrow keys and pressing backspace.
> While this is fair/flexible enough I am not sure if this is sufficient for a person with disabilities (that, I guess, usually expects to have a visual feedback directly on the item that he is working on; and I believe that the item should be able get *:focused).

That's what I'd intuitively would've gone with. For items to get focus, I think that could be another plugin. Otherwise, I don't think the (x) button should get focus.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
