### ISSUE TITLE
Unnecessary dependencies in package.json

### ISSUE THREAD

**Issue by godza** [selectize/selectize.js#980]
Hi,

I'm trying to use selectize in my project, and i'm trying to get it via npm. I see that you have 2 items in your dependencies list:

`"dependencies": {
    "microplugin": "0.0.3",
    "sifter": "^0.4.0"
  }`

I don't believe that you need to have those dependencies to use selectize in production, so i think they belong in devDependencies.

Am i right or did i made mistake in my reasoning.

Thanks

**Comment by brianreavis** [comment]
They're both needed. Sifter handles option filtering for example.

**Comment by godza** [comment]
That's too bad, i needed only selectize but got additional 15 dependencies for production i don't need at all for my frontend project. Are they optional dependencies?

```
drwxr-xr-x   9 goran  staff  306 Jan  8 03:05 ansicolors
drwxr-xr-x   7 goran  staff  238 Jan  8 03:05 async
drwxr-xr-x   5 goran  staff  170 Jan  8 03:05 bindings
drwxr-xr-x  15 goran  staff  510 Jan  8 03:05 cardinal
drwxr-xr-x   7 goran  staff  238 Jan  8 03:05 esprima
drwxr-xr-x   9 goran  staff  306 Jan  8 03:05 humanize
drwxr-xr-x   9 goran  staff  306 Jan  8 03:05 microplugin
drwxr-xr-x  14 goran  staff  476 Jan  8 03:05 microtime
drwxr-xr-x   9 goran  staff  306 Jan  8 03:05 minimist
drwxr-xr-x  28 goran  staff  952 Jan  8 03:05 nan
drwxr-xr-x   7 goran  staff  238 Jan  8 03:05 node-csv
drwxr-xr-x   9 goran  staff  306 Jan  8 03:05 optimist
drwxr-xr-x  12 goran  staff  408 Jan  8 03:05 redeyed
drwxr-xr-x  17 goran  staff  578 Jan  8 03:05 selectize
drwxr-xr-x  12 goran  staff  408 Jan  8 03:05 sifter
drwxr-xr-x   8 goran  staff  272 Jan  8 03:05 wordwrap
```

**Comment by joallard** [comment]
Those seem to be dependencies from Sifter as Microplugin depends on nothing. I guess we could make the Sifter dependency optional in the future refactor.

**Comment by brianreavis** [comment]
Those are all dev dependencies through... they in no way are included in the clientside code and won't even be downloaded if you run `npm install --production`.

**Comment by joallard** [comment]
Maybe I'm getting this wrong, but in Sifter's `package.json`:

``` js
  "dependencies": {
    "optimist": "0.6.x",
    "cardinal": "0.4.x",
    "async": "0.2.x",
    "humanize": "0.0.x",
    "node-csv": "https://github.com/voodootikigod/node-csv/tarball/master"
  },
```

**Comment by brianreavis** [comment]
Ahh yes, I had forgotten about that. Those are for the sifter CLI. Is this an install time issue? I suppose we could just make a separate `sifter-cli` package.

**Comment by joallard** [comment]
My comprehension is that those get installed on a stock `npm install selectize`

**Comment by godza** [comment]
It happens in both cases, when doing `npm install selectize` and when doing `npm install --production`

**Comment by brianreavis** [comment]
If we make a separate `sifter-cli` package we can strip off those dependencies for regular `sifter`-as-a-library usage. I'll try to get to this in the next few days.

**Comment by godza** [comment]
Thanks Brian.
