### ISSUE TITLE
Make possible to disable the autocomplete dropdown

### ISSUE THREAD

**Issue by mcalello** [selectize/selectize.js#981]
If I do not have options but still want to use selectize for tagging, can I turn off the options dropdown and the option_create altogether?

**Comment by ErwanGuillon** [comment]
I'm looking for this too

**Comment by joallard** [comment]
Have you found a way to disable it? Otherwise sounds like an enhancement

**Comment by mcalello** [comment]
I have not.  Been just living with the dropdown appearing as the user types with the "Add abc ..." showing.

**Comment by gundogcreative** [comment]
Is it possible to disable this "Add..." feature all together?

**Comment by uvarovkv** [comment]
@ErwanGuillon, @mcalello lets try this
`selectize.$control_input.on('keypress', function() {
        selectize.close();
});
    selectize.on('type', function() {
            selectize.close();
    });`
+
openOnFocus: false,

**Comment by joallard** [comment]
Sounds like this would be easy if we refactor Selectize into components, but not quite yet. Meanwhile, let us know how the workaround works!

**Comment by defaria** [comment]
+1 for this option. On mobile the keyboard comes up because of the filter option, which is not needed on small dropdowns.

**Comment by Jeiwan** [comment]
This works fine:

```
onDropdownOpen: function(dropdown) {
  dropdown.remove();
}
```

**Comment by nd-ffx** [comment]
> This works fine:
> 
> ```
> onDropdownOpen: function(dropdown) {
>   dropdown.remove();
> }
> ```

Unfortunately this doesn't prevent selectize to insert an item by autocomplete on Enter-keypress. Isn't there any possibility to disable it at all?

**Comment by awdyer** [comment]
@nd-ffx try this instead:

```
onDropdownOpen: function() {
  this.close();
}
```

**Edit:** Never mind, this seems to cause issues deselecting the input afterwards.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
