### ISSUE TITLE
Converting px to em in selectize css

### ISSUE THREAD

**Issue by creativefctr** [selectize/selectize.js#982]
Hi,
Selectize is using px unit in it's css values which is not a good practice. If all of these units are converted to em then we will have the ability to scale the control anyway we want without loosing the proportions by changing the font size in the parent container; That's very useful in creating responsive and/or scalable user interfaces.
Thanks for the great plugin

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
