### ISSUE TITLE
Use text from <option> with no value attribute or document this requirement

### ISSUE THREAD

**Issue by ACReeser** [selectize/selectize.js#985]
According to [MDN's documentation of the `value` attribute of the `<option>` tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option):
value
If this attribute is omitted, the value is taken from the text content of the option element.

Currently it seems that selectize() requires a non-empty value attribute in order to fill the items array. This means that setups like this:

```
<select>
    <option>You</option>
    <option>Will not</option>
    <option>See</option>
    <option>These</option>
</select>
<script>
    (function(){
        $('select').selectize();
    })();
</script>
```

Initialize a selectize component with an empty items array.

To me, either selectize.js should use the text content of the option tag if the value attribute is not set, or the documentation should explicitly note that `<option>` tags with no value will not appear in the items list.

Apologies if this is documented, but I could not find anything, and it took looking at the HTML code of the demos to recognize the requirement.

**Comment by joallard** [comment]
I'd have no problem with a PR implementing that behavior, seeing it's in the HTML spec.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
