### ISSUE TITLE
Is it possible to show certain options on text entry only?

### ISSUE THREAD

**Issue by JamieBradders** [selectize/selectize.js#986]
Okay, so I know this is a strange one but I am using Selectize for a site I'm working on at the moment and have found it very beneficial. But today I was asked about a rather unusual request and haven't been able to find anything online as to whether selectize could do this or not.

Let's say, for example, I have a selectize instance which renders a selectize unit that contains static data which I've assigned to the 'options' property in my selectize config. I split this data into two option groups using optgroups. One group is called areas and the second group is called hotels. The hotels group is populated with say 30 hotels and all works well. But as you can imagine the list is rather long and takes up more than enough space (height wise) in the view when a user opens the selectize box.

So, what I am being asked to do is to only display 10 of the 30 hotels from my hotels option group in the UI, when the user initially opens the selectize dropdown. But if a user starts to type the name of one of the other 20 "hidden" hotels contained within my static data, then can the hotel be displayed for the user to select from the selectize box?

I can't seem to find a way that would make this possible with Selectize, as every hotel that will be added to the hotel group is automatically rendered in the view. I appreciate that this is an odd question but any help or suggestions would be appreciated as I'm a bit stumped.

**Comment by joallard** [comment]
I have not checked, but looks like this entails serious hacking/refactoring. I'm afraid that with a 365 issue backlog, I can't help you more than that. Maybe if there are things in the API you'd like to be added, you can open a "Wishlist:" issue.

**Comment by JamieBradders** [comment]
Cheers for that. I agree that it is something that could only be achieved by a nasty hack! Managed to find an alternative solution with no hacking required but will consider the wish list as you have suggested. Thanks again!
