### ISSUE TITLE
remove_button Plugin doesn't work when there is no focus in huge lists

### ISSUE THREAD

**Issue by bb1** [selectize/selectize.js#987]
How to reproduce:

Step 1: Have a huge list with the remove plugin and search enabled
![1](https://cloud.githubusercontent.com/assets/3842623/12455611/ac43fbda-bf9c-11e5-84ba-666712331a1a.png)
Step 2: Try to remove an element at the top of the list (the input filed must be out of the viewpoint)
![2](https://cloud.githubusercontent.com/assets/3842623/12455656/c9aa0084-bf9c-11e5-9a6d-7adb8f262c2d.png)
Step 3: You automatically jump to the input field, nothing is removed. 
![3](https://cloud.githubusercontent.com/assets/3842623/12455685/df3f54f8-bf9c-11e5-95d1-7580fb99cf6c.png)
Step 4: Now with the focus inside the input you can actually remove elements

I've implemented a work-a-round with setting the focus to the input and then scroll up. But it's a ugly one and I'm sure the fix can't be that hard for someone familiar with the code.

**Comment by joallard** [comment]
The problem is, nobody deeply familiar with the code has time to help right now. PR welcome!

**Comment by DarthSonic** [comment]
I encountered the same problem. Do not have any workaround.

**Comment by bb1** [comment]
My workaround is to set the focus manually and scroll down to the end of
the list. It looks like it's working for the user.

**Comment by bb1** [comment]
I meant to write scroll up inside the div not down.

**Comment by sdk2000** [comment]
I faced a similar issue while trying to implement the same without the plugin. I made changes in the onItemSelect method of selectize.js to check the class of the triggered element.
if (e.toElement.className === 'removeItem') {
    var item_name = e.toElement.getAttribute('item-name');
    if (item_name) {
        self.removeItem(item_name);
    }
} else if (self.settings.mode === 'multi') {
    e.preventDefault();
    self.setActiveItem(e.currentTarget, e);
}
And in my js code,in render for item, I generated &lt;div&gt;ABC&lt;span id="removeItem" item_name="ABC"&gt;x&lt;/span&gt;&lt;/div&gt;

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
