### ISSUE TITLE
1) Auto-select typed tags and 2) Searching without clearing first

### ISSUE THREAD

**Issue by johnnyoshika** [selectize/selectize.js#988]
We've been getting a lot of feedback on an app that uses selectize extensively, and I wanted to get the community's thoughts on whether the enhancements that I'm going propose below makes sense or not.  I'd be even willing to submit a pull request if it does.
### Auto-select typed tags

Using the _Tagging_ example from [here](http://selectize.github.io/selectize.js/), our users tend to type something but then click away with their mouse instead of hitting <kbd>Enter</kbd> or <kbd>Tab</kbd> or selecting the `Add {value}` option that appears below the textbox after they've typed their value.  They're then surprised that what they typed disappeared.  We've received numerous reports that our input control is broken because of this.  I think it would be better to auto-select the value on `blur` like the _tags-input_ plugin does:
https://github.com/xoxco/jQuery-Tags-Input
http://xoxco.com/projects/code/tagsinput/example.html
### Searching without clearing first

Using the _Single Item Select_ example from [here](http://selectize.github.io/selectize.js/), our users are confused why they can't start typing and search for an item if one is already selected.  We keep getting reports that this is broken.  It turns out that if an item is already selected, then the user has to hit <kbd>Backspace</kbd> first to clear the selected item before they can type and search for an item.  It would be more intuitive if they could just start typing and search for an item, even if an item was previously selected, just like how [select2](https://select2.github.io/examples.html) works.

Thoughts?

**Comment by mcavalletto** [comment]
The first item sounds like you want to set the createOnBlur option to true.

The second item appears to be covered by [Issue 647](https://github.com/selectize/selectize.js/issues/647), which includes a plugin that changes this behavior.

**Comment by johnnyoshika** [comment]
@mcavalletto: `createOnBlur` works well and thank you for the link to the plugin.

**Comment by joallard** [comment]
Really interesting stuff, thanks for the UX perspective!
